/*
 * GENERATED by scripts/make-index.mjs — do not edit.
 *
 * The roadmap, without the reading. Everything here is needed to draw the
 * course before anyone has opened a lesson; the prose, the questions and the
 * definitions load on demand from ./full.
 */
import type { Level } from './types';

export type LightLesson = { id: string; title: string; oneLine: string; mins: number };

export type LightStage = {
  number: string;
  title: string;
  subtitle: string;
  level: Level;
  tags: string[];
  weeks: number;
  hours: number;
  hue: number;
  plain: string;
  outcome: string;
  project: string;
  checkpoint: string;
  resources: { label: string; href: string }[];
  lessons: LightLesson[];
};

export const stages: LightStage[] = [
  {
    "number": "00",
    "title": "Start here, stay legal",
    "subtitle": "What security actually is, and how to practise without hurting anyone",
    "level": "BEGINNER",
    "tags": [
      "FOUNDATIONS"
    ],
    "weeks": 1,
    "hours": 20,
    "hue": 210,
    "plain": "Before touching a single tool, you learn what the job really is: protecting things people care about, and doing it with permission.",
    "outcome": "You can describe any security situation using five words — asset, threat, weakness, control, evidence — and you know exactly where the legal line is.",
    "project": "Write your own rules of engagement, draw your first threat model on paper, and build a practice lab that cannot touch anything real.",
    "checkpoint": "You can explain to a non-technical friend what you are allowed to do, what you are not, and why your lab is safe.",
    "resources": [
      {
        "label": "NIST Cybersecurity Framework 2.0",
        "href": "https://www.nist.gov/cyberframework"
      },
      {
        "label": "CISA Cyber Career Pathways",
        "href": "https://niccs.cisa.gov/tools/cyber-career-pathways-tool"
      },
      {
        "label": "TryHackMe (free beginner rooms)",
        "href": "https://tryhackme.com/"
      }
    ],
    "lessons": [
      {
        "id": "00-1",
        "title": "What cybersecurity actually is",
        "oneLine": "Cybersecurity is the job of keeping valuable things safe when those things live on computers.",
        "mins": 6
      },
      {
        "id": "00-2",
        "title": "The three promises: CIA",
        "oneLine": "Every security control on earth exists to protect one of three promises: keep it secret, keep it correct, keep it available.",
        "mins": 6
      },
      {
        "id": "00-3",
        "title": "The five words that explain everything",
        "oneLine": "Asset, threat, vulnerability, control, evidence — string these together and you can describe any security problem in the world.",
        "mins": 7
      },
      {
        "id": "00-4",
        "title": "Permission, law and the line you never cross",
        "oneLine": "The only thing separating a security professional from a criminal is written permission.",
        "mins": 8
      },
      {
        "id": "00-5",
        "title": "Build a lab that cannot hurt anyone",
        "oneLine": "A lab is a set of fake computers living inside your real computer, sealed in a box so mistakes stay inside.",
        "mins": 8
      },
      {
        "id": "00-6",
        "title": "How to learn this without drowning",
        "oneLine": "Cybersecurity is too big to finish, so you learn in loops: small topic, hands on it, write it down, come back later.",
        "mins": 7
      },
      {
        "id": "00-7",
        "title": "The jobs: what the roles actually do",
        "oneLine": "Security is not one job — it is roughly seven families of job, and they want very different personalities.",
        "mins": 7
      },
      {
        "id": "00-8",
        "title": "Frameworks: the shared maps",
        "oneLine": "Frameworks are agreed maps of the field, so thousands of people can describe the same problem the same way.",
        "mins": 7
      }
    ]
  },
  {
    "number": "01",
    "title": "How computers really work",
    "subtitle": "Files, processes, memory, Linux and Windows — the ground everything stands on",
    "level": "BEGINNER",
    "tags": [
      "FOUNDATIONS",
      "BUILD"
    ],
    "weeks": 4,
    "hours": 55,
    "hue": 195,
    "plain": "You cannot defend or attack a machine you do not understand. This stage opens the box and shows you what is inside.",
    "outcome": "You can follow a program from a file on disk, to a running process, to the memory it uses — and inspect all three from a command line.",
    "project": "Build a Linux and a Windows lab machine, lock down their user accounts, and write a baseline report describing what \"normal\" looks like on each.",
    "checkpoint": "You can find out what is running, who started it, what it is touching, and where it wrote a log about doing so.",
    "resources": [
      {
        "label": "OverTheWire Bandit (free shell practice)",
        "href": "https://overthewire.org/wargames/bandit/"
      },
      {
        "label": "Linux Journey",
        "href": "https://linuxjourney.com/"
      },
      {
        "label": "Microsoft PowerShell training",
        "href": "https://learn.microsoft.com/en-us/training/powershell/"
      }
    ],
    "lessons": [
      {
        "id": "01-1",
        "title": "Everything is numbers",
        "oneLine": "Every photo, password and program on your computer is, underneath, just a very long list of numbers.",
        "mins": 6
      },
      {
        "id": "01-2",
        "title": "The CPU, memory and processes",
        "oneLine": "A program is a file that does nothing; a process is that file loaded into memory and actually running.",
        "mins": 8
      },
      {
        "id": "01-3",
        "title": "Files, filesystems and permissions",
        "oneLine": "A filesystem is a filing cabinet with labels saying who is allowed to open each drawer.",
        "mins": 8
      },
      {
        "id": "01-4",
        "title": "The Linux command line",
        "oneLine": "The shell is a text conversation with your computer, and it is faster and more precise than any clicking.",
        "mins": 9
      },
      {
        "id": "01-5",
        "title": "Windows internals and PowerShell",
        "oneLine": "Most companies run Windows, so most real attacks happen on Windows — and it works very differently to Linux.",
        "mins": 9
      },
      {
        "id": "01-6",
        "title": "Virtual machines and containers",
        "oneLine": "Both give you isolated environments — a VM fakes a whole computer, a container only fakes a private room in one.",
        "mins": 7
      },
      {
        "id": "01-7",
        "title": "From source code to running program",
        "oneLine": "Code you write is text; the machine needs numbers, and the journey between the two is where many bugs are born.",
        "mins": 8
      },
      {
        "id": "01-8",
        "title": "Baselines, logs and hardening",
        "oneLine": "You cannot spot abnormal until you have written down what normal looks like.",
        "mins": 8
      }
    ]
  },
  {
    "number": "02",
    "title": "How the internet moves data",
    "subtitle": "Packets, addresses, DNS, TLS — following a message from your finger to a server",
    "level": "EASY",
    "tags": [
      "FOUNDATIONS",
      "DEFENSE",
      "OFFENSE"
    ],
    "weeks": 5,
    "hours": 65,
    "hue": 185,
    "plain": "Every attack and every defence eventually travels over a network. This stage teaches you to read that traffic like a sentence.",
    "outcome": "Given a connection that is failing or a flow that looks suspicious, you can say which layer is responsible and prove it with a packet capture.",
    "project": "Design a segmented home lab network, then capture and annotate real traffic for DNS, TCP, HTTP and TLS, explaining every field you highlight.",
    "checkpoint": "You can narrate exactly what happens between typing a web address and the page appearing, in order, without hand-waving.",
    "resources": [
      {
        "label": "Wireshark User Guide",
        "href": "https://www.wireshark.org/docs/wsug_html_chunked/"
      },
      {
        "label": "Cloudflare Learning Center",
        "href": "https://www.cloudflare.com/learning/"
      },
      {
        "label": "Let’s Encrypt: how certificates work",
        "href": "https://letsencrypt.org/how-it-works/"
      }
    ],
    "lessons": [
      {
        "id": "02-1",
        "title": "Layers: the postal system model",
        "oneLine": "Networking is built in layers, where each layer does one job and hands the result to the next without caring how it works.",
        "mins": 7
      },
      {
        "id": "02-2",
        "title": "Local networks, MAC addresses and ARP",
        "oneLine": "Inside your own network, machines find each other by hardware address, and the system that does it politely trusts everyone.",
        "mins": 7
      },
      {
        "id": "02-3",
        "title": "IP addresses, subnets and NAT",
        "oneLine": "An IP address is where a machine lives; a subnet mask says which part of that address is the street and which is the house.",
        "mins": 8
      },
      {
        "id": "02-4",
        "title": "Routing, firewalls and ports",
        "oneLine": "Routers decide where a packet goes next; firewalls decide whether it should be allowed to go there at all.",
        "mins": 8
      },
      {
        "id": "02-5",
        "title": "DNS: the internet’s phone book",
        "oneLine": "DNS turns names people can remember into addresses machines can use — and almost everything trusts it completely.",
        "mins": 8
      },
      {
        "id": "02-6",
        "title": "TCP, UDP and the handshake",
        "oneLine": "TCP is a careful phone call that confirms every word; UDP is shouting a postcard and hoping.",
        "mins": 7
      },
      {
        "id": "02-7",
        "title": "HTTP, TLS and certificates",
        "oneLine": "HTTP is how browsers ask for things; TLS is the envelope that stops anyone else reading or changing the request.",
        "mins": 9
      },
      {
        "id": "02-8",
        "title": "Wi-Fi, VPNs and reading captures",
        "oneLine": "Wireless and VPNs change who can see your traffic, and packet capture is how you check what is really happening.",
        "mins": 8
      }
    ]
  },
  {
    "number": "03",
    "title": "Code enough to be dangerous",
    "subtitle": "Python, Bash, PowerShell, SQL and a little C — automate the boring, understand the rest",
    "level": "EASY",
    "tags": [
      "BUILD",
      "FOUNDATIONS"
    ],
    "weeks": 5,
    "hours": 65,
    "hue": 265,
    "plain": "You do not need to be a software engineer. You need to read code without fear and write small programs that do your repetitive work for you.",
    "outcome": "You can write scripts that parse logs, call APIs, test inputs and produce reports — and read unfamiliar code well enough to spot its assumptions.",
    "project": "Build a command-line tool that reads security logs, pulls out indicators, enriches them, and exports a clean report with tests.",
    "checkpoint": "Given a script you did not write, you can explain what it does, what could go wrong, and what it trusts that it should not.",
    "resources": [
      {
        "label": "Official Python tutorial",
        "href": "https://docs.python.org/3/tutorial/"
      },
      {
        "label": "Automate the Boring Stuff (free online)",
        "href": "https://automatetheboringstuff.com/"
      },
      {
        "label": "SQL practice — SQLBolt",
        "href": "https://sqlbolt.com/"
      }
    ],
    "lessons": [
      {
        "id": "03-1",
        "title": "Python: your everyday tool",
        "oneLine": "Python is the language most security work is written in, because it is readable and gets out of your way.",
        "mins": 9
      },
      {
        "id": "03-2",
        "title": "Bash: gluing tools together",
        "oneLine": "Bash is not for building software; it is for chaining existing tools into an answer in one line.",
        "mins": 7
      },
      {
        "id": "03-3",
        "title": "PowerShell and Windows automation",
        "oneLine": "PowerShell is how you ask thousands of Windows machines a question and get a structured answer back.",
        "mins": 8
      },
      {
        "id": "03-4",
        "title": "JavaScript and how browsers run code",
        "oneLine": "JavaScript runs inside every visitor’s browser, which makes it both the web’s engine and its biggest security surface.",
        "mins": 8
      },
      {
        "id": "03-5",
        "title": "SQL and how databases get broken",
        "oneLine": "SQL is the language for asking databases questions, and mixing it with user input is one of the oldest disasters in computing.",
        "mins": 8
      },
      {
        "id": "03-6",
        "title": "A little C, and why memory bugs exist",
        "oneLine": "C gives you direct control of memory, which is why it is fast, and why forgetting a boundary check becomes a security hole.",
        "mins": 8
      },
      {
        "id": "03-7",
        "title": "Regex, parsing and encoding traps",
        "oneLine": "Regular expressions find patterns in text, and the mistakes people make with them cause both missed detections and outages.",
        "mins": 7
      },
      {
        "id": "03-8",
        "title": "APIs, Git and not shipping secrets",
        "oneLine": "Tools talk to each other over APIs, your work lives in Git, and both are places credentials leak constantly.",
        "mins": 8
      }
    ]
  },
  {
    "number": "04",
    "title": "Security thinking",
    "subtitle": "Risk, identity, cryptography, zero trust and threat modelling",
    "level": "MEDIUM",
    "tags": [
      "FOUNDATIONS",
      "BUILD",
      "LEADERSHIP"
    ],
    "weeks": 4,
    "hours": 55,
    "hue": 230,
    "plain": "This is where you stop collecting facts and start making decisions: what to protect, how much, and how you would know it worked.",
    "outcome": "You can turn a principle into a layered set of controls that fits real risk, instead of copying a checklist you found online.",
    "project": "Threat-model a small online product end to end, then propose a risk-ranked security design with a test for every control you recommend.",
    "checkpoint": "You can justify any control by naming its threat, its cost, its evidence, and the risk you are choosing to accept anyway.",
    "resources": [
      {
        "label": "NIST CSF 2.0",
        "href": "https://www.nist.gov/cyberframework"
      },
      {
        "label": "OWASP Threat Modeling Cheat Sheet",
        "href": "https://cheatsheetseries.owasp.org/cheatsheets/Threat_Modeling_Cheat_Sheet.html"
      },
      {
        "label": "CVSS v4.0 specification",
        "href": "https://www.first.org/cvss/v4.0/"
      }
    ],
    "lessons": [
      {
        "id": "04-1",
        "title": "Risk: the only honest measure",
        "oneLine": "Risk is how likely something bad is, multiplied by how bad it would be — and it is the only sane way to decide what to fix first.",
        "mins": 8
      },
      {
        "id": "04-2",
        "title": "Identity: who are you, and what may you do",
        "oneLine": "Authentication proves who you are; authorisation decides what you are allowed to touch — and confusing them causes breaches.",
        "mins": 9
      },
      {
        "id": "04-3",
        "title": "Cryptography without the maths",
        "oneLine": "Cryptography gives you four powers: hide data, prove it was not changed, prove who sent it, and agree a secret over an open line.",
        "mins": 10
      },
      {
        "id": "04-4",
        "title": "Defence in depth and zero trust",
        "oneLine": "Assume every single control will fail, and design so that failure is survivable.",
        "mins": 8
      },
      {
        "id": "04-5",
        "title": "Threat modelling: thinking like the attacker, on paper",
        "oneLine": "Threat modelling is asking four questions about a design before you build it, and it is the cheapest security you will ever do.",
        "mins": 9
      },
      {
        "id": "04-6",
        "title": "Vulnerability management: CVE, CVSS and reality",
        "oneLine": "Knowing about a vulnerability is easy; deciding which of the ten thousand you found actually matters is the job.",
        "mins": 8
      },
      {
        "id": "04-7",
        "title": "Resilience: backups, patching and recovery",
        "oneLine": "Since prevention eventually fails, the ability to recover quickly is itself a security control — often the most valuable one.",
        "mins": 8
      },
      {
        "id": "04-8",
        "title": "Governance, privacy and the law",
        "oneLine": "Policies, standards and regulations are how security scales beyond the people who care about it personally.",
        "mins": 8
      }
    ]
  },
  {
    "number": "05",
    "title": "Breaking and fixing web apps",
    "subtitle": "The OWASP Top 10 (2025), APIs, and finding the root cause instead of the symptom",
    "level": "MEDIUM",
    "tags": [
      "BUILD",
      "OFFENSE",
      "RESEARCH"
    ],
    "weeks": 5,
    "hours": 55,
    "hue": 25,
    "plain": "Most of the world runs on web applications, so most real vulnerabilities are web vulnerabilities. This stage teaches you to find them and fix them properly.",
    "outcome": "You can trace trust boundaries through a web or API stack, reproduce a flaw safely in a lab, and design a fix that closes the whole class of abuse.",
    "project": "Work through a curated set of legal web labs, then write a developer-ready report with evidence, root cause, and a test that proves the fix holds.",
    "checkpoint": "You can tell the difference between a symptom and a root cause, and prove that your fix actually closes the path.",
    "resources": [
      {
        "label": "PortSwigger Web Security Academy (free)",
        "href": "https://portswigger.net/web-security"
      },
      {
        "label": "OWASP Top 10: 2025",
        "href": "https://owasp.org/Top10/"
      },
      {
        "label": "OWASP Cheat Sheet Series",
        "href": "https://cheatsheetseries.owasp.org/"
      }
    ],
    "lessons": [
      {
        "id": "05-1",
        "title": "The OWASP Top 10, 2025 edition",
        "oneLine": "A ranked awareness list of the ten risk categories that break web applications most often, refreshed for 2025.",
        "mins": 9
      },
      {
        "id": "05-2",
        "title": "Broken access control",
        "oneLine": "The application knows who you are but forgets to check whether you should be allowed to do this particular thing.",
        "mins": 9
      },
      {
        "id": "05-3",
        "title": "Injection: when data becomes instruction",
        "oneLine": "Injection happens whenever untrusted input is glued into something that gets interpreted — SQL, a shell, a template, an LDAP query.",
        "mins": 9
      },
      {
        "id": "05-4",
        "title": "XSS, CSRF and browser trust",
        "oneLine": "Cross-site scripting runs the attacker’s code in your user’s browser; cross-site request forgery makes the browser act on its own credentials.",
        "mins": 9
      },
      {
        "id": "05-5",
        "title": "SSRF, XXE, deserialisation and file handling",
        "oneLine": "Four ways to make a server fetch, parse or reconstruct something it should never have touched.",
        "mins": 9
      },
      {
        "id": "05-6",
        "title": "API security: REST, GraphQL and the new perimeter",
        "oneLine": "APIs expose business logic directly, without a user interface to hide behind, and they are now the majority of web traffic.",
        "mins": 9
      },
      {
        "id": "05-7",
        "title": "Supply chain and integrity failures",
        "oneLine": "Your application is mostly other people’s code, and attacking the code you trust is easier than attacking the code you wrote.",
        "mins": 9
      },
      {
        "id": "05-8",
        "title": "Secure design, testing and shipping the fix",
        "oneLine": "Finding a bug is a quarter of the work; the rest is fixing the cause, proving the fix, and stopping it coming back.",
        "mins": 9
      }
    ]
  },
  {
    "number": "06",
    "title": "Attacking, with permission",
    "subtitle": "Penetration testing from scope to report — recon, exploitation, Active Directory, cleanup",
    "level": "HARD",
    "tags": [
      "OFFENSE",
      "RESEARCH"
    ],
    "weeks": 6,
    "hours": 80,
    "hue": 350,
    "plain": "Testing like an attacker, inside legal boundaries, so defenders find out what is broken before a criminal does.",
    "outcome": "You can run a controlled assessment from rules of engagement to an evidence-backed report, without breaking what you were hired to protect.",
    "project": "Assess an intentionally vulnerable lab environment, chain at least two weaknesses into real impact, clean up after yourself, and deliver both an executive and a technical report.",
    "checkpoint": "You can state scope, prove impact safely, preserve evidence, stop at boundaries, and recommend fixes a developer can act on.",
    "resources": [
      {
        "label": "PTES technical guidelines",
        "href": "http://www.pentest-standard.org/"
      },
      {
        "label": "HackTricks methodology notes",
        "href": "https://book.hacktricks.wiki/"
      },
      {
        "label": "Hack The Box Academy",
        "href": "https://academy.hackthebox.com/"
      }
    ],
    "lessons": [
      {
        "id": "06-1",
        "title": "Scope, method and not causing harm",
        "oneLine": "A professional test is defined by its paperwork before it is defined by its tools.",
        "mins": 8
      },
      {
        "id": "06-2",
        "title": "Reconnaissance and OSINT",
        "oneLine": "Before touching anything, you learn everything about the target that is already public.",
        "mins": 8
      },
      {
        "id": "06-3",
        "title": "Scanning and enumeration",
        "oneLine": "Find what is listening, work out exactly what it is, and turn a list of ports into a list of possibilities.",
        "mins": 9
      },
      {
        "id": "06-4",
        "title": "Exploitation and validating impact",
        "oneLine": "Exploitation is proving a weakness is real; the discipline is proving it without causing damage.",
        "mins": 9
      },
      {
        "id": "06-5",
        "title": "Privilege escalation on Linux",
        "oneLine": "You landed as a low-privilege user; now you look for the one misconfiguration that makes you root.",
        "mins": 9
      },
      {
        "id": "06-6",
        "title": "Windows and Active Directory",
        "oneLine": "Corporate networks run on Active Directory, and attacking identity relationships beats attacking machines.",
        "mins": 10
      },
      {
        "id": "06-7",
        "title": "Pivoting and chaining weaknesses",
        "oneLine": "Real impact usually comes from several medium problems connected together, not from one critical bug.",
        "mins": 9
      },
      {
        "id": "06-8",
        "title": "Cleanup, reporting and purple teaming",
        "oneLine": "The report is the product; everything before it was research.",
        "mins": 9
      }
    ]
  },
  {
    "number": "07",
    "title": "Defending and detecting",
    "subtitle": "Logs, SIEM, MITRE ATT&CK, detection engineering and SOC triage",
    "level": "HARD",
    "tags": [
      "DEFENSE",
      "BUILD"
    ],
    "weeks": 6,
    "hours": 75,
    "hue": 155,
    "plain": "Attacks will get through. This stage is about seeing them happen, deciding fast whether it is real, and stopping it spreading.",
    "outcome": "You can turn endpoint, identity, network and cloud telemetry into detections that fire on real behaviour instead of on noise.",
    "project": "Build a small detection lab with normalised logs, write five detections mapped to ATT&CK techniques, and document your triage and tuning decisions.",
    "checkpoint": "For any alert you write, you can state the hypothesis, the data source, the blind spots, the triage path and the response.",
    "resources": [
      {
        "label": "MITRE ATT&CK",
        "href": "https://attack.mitre.org/"
      },
      {
        "label": "Sigma detection rules",
        "href": "https://github.com/SigmaHQ/sigma"
      },
      {
        "label": "Atomic Red Team (safe technique tests)",
        "href": "https://atomicredteam.io/"
      }
    ],
    "lessons": [
      {
        "id": "07-1",
        "title": "Telemetry: you can only detect what you collect",
        "oneLine": "Detection begins with a decision about what to record, and most detection failures are really collection failures.",
        "mins": 8
      },
      {
        "id": "07-2",
        "title": "SIEM: making a million logs answer a question",
        "oneLine": "A SIEM collects logs centrally, normalises them, and lets you search and correlate across everything at once.",
        "mins": 8
      },
      {
        "id": "07-3",
        "title": "MITRE ATT&CK as a working tool",
        "oneLine": "A catalogue of what attackers actually do, which lets you measure your detection coverage instead of guessing at it.",
        "mins": 8
      },
      {
        "id": "07-4",
        "title": "Writing detections that survive contact",
        "oneLine": "Good detections describe attacker behaviour, not one specific tool — because tools change and behaviour is harder to avoid.",
        "mins": 9
      },
      {
        "id": "07-5",
        "title": "Endpoint and identity signals",
        "oneLine": "Most attacks touch an endpoint and almost all of them touch identity, which makes these the two richest places to watch.",
        "mins": 8
      },
      {
        "id": "07-6",
        "title": "Network monitoring and its blind spots",
        "oneLine": "Network data shows you what talked to what, which endpoint tooling cannot tell you when the endpoint is not covered.",
        "mins": 8
      },
      {
        "id": "07-7",
        "title": "Threat intelligence, used properly",
        "oneLine": "Intelligence is knowing which threats actually apply to you, so you can prepare for those rather than for everything.",
        "mins": 8
      },
      {
        "id": "07-8",
        "title": "Triage, hunting and closing the loop",
        "oneLine": "Triage decides fast whether an alert is real; hunting looks for what never alerted at all.",
        "mins": 9
      }
    ]
  },
  {
    "number": "08",
    "title": "When it goes wrong",
    "subtitle": "Incident response, digital forensics, memory analysis and malware triage",
    "level": "HARD",
    "tags": [
      "DEFENSE",
      "RESEARCH"
    ],
    "weeks": 6,
    "hours": 70,
    "hue": 275,
    "plain": "Something bad happened. Now you work out exactly what, stop it spreading, prove it with evidence, and make sure it cannot happen the same way twice.",
    "outcome": "You can preserve evidence properly, build a defensible timeline, analyse malicious behaviour safely, contain an incident and improve the system afterwards.",
    "project": "Investigate a simulated compromise end to end and produce a timeline, a scope statement, a containment plan and a lessons-learned brief.",
    "checkpoint": "Another analyst can reproduce your findings from your notes, and can tell your confirmed facts from your hypotheses.",
    "resources": [
      {
        "label": "NIST SP 800-61r3 incident response",
        "href": "https://csrc.nist.gov/pubs/sp/800/61/r3/final"
      },
      {
        "label": "Volatility Foundation",
        "href": "https://volatilityfoundation.org/"
      },
      {
        "label": "DFIR training and free labs",
        "href": "https://www.13cubed.com/"
      }
    ],
    "lessons": [
      {
        "id": "08-1",
        "title": "The incident response lifecycle",
        "oneLine": "Response follows a repeatable cycle — prepare, detect and analyse, contain, eradicate, recover, learn — and preparation does most of the work.",
        "mins": 8
      },
      {
        "id": "08-2",
        "title": "Evidence: order of volatility and chain of custody",
        "oneLine": "Evidence disappears in a predictable order, so you collect the most fragile things first and prove nothing changed afterwards.",
        "mins": 8
      },
      {
        "id": "08-3",
        "title": "Disk forensics and the artefacts that talk",
        "oneLine": "Operating systems record far more about user and program activity than users realise, and most of it survives deletion.",
        "mins": 9
      },
      {
        "id": "08-4",
        "title": "Memory forensics",
        "oneLine": "Memory holds what disk never sees — running processes, injected code, keys, passwords and network connections in flight.",
        "mins": 9
      },
      {
        "id": "08-5",
        "title": "Email, identity and cloud investigations",
        "oneLine": "Many modern incidents involve no malware at all — just a stolen identity used through legitimate services.",
        "mins": 8
      },
      {
        "id": "08-6",
        "title": "Malware triage, safely",
        "oneLine": "Work out what a hostile file does — first without running it, then by running it somewhere it cannot escape.",
        "mins": 9
      },
      {
        "id": "08-7",
        "title": "Reverse engineering: reading what the machine reads",
        "oneLine": "When you need to know exactly what code does and you have no source, you read the assembly.",
        "mins": 9
      },
      {
        "id": "08-8",
        "title": "Ransomware, recovery and learning",
        "oneLine": "Ransomware is a business, the encryption is the last step, and recovery is decided long before the ransom note appears.",
        "mins": 9
      }
    ]
  },
  {
    "number": "09",
    "title": "Cloud and DevSecOps",
    "subtitle": "Shared responsibility, cloud identity, containers, Kubernetes and securing the pipeline",
    "level": "HARD",
    "tags": [
      "CLOUD",
      "BUILD",
      "DEFENSE"
    ],
    "weeks": 5,
    "hours": 65,
    "hue": 200,
    "plain": "Almost everything now runs in the cloud and ships through an automated pipeline. Both are new places to be attacked, and both are securable.",
    "outcome": "You can secure identity, data, workloads, deployment pipelines and software provenance across cloud-native systems.",
    "project": "Ship a hardened containerised service through a scanned CI pipeline with least privilege, signed artefacts, an SBOM and working alerts.",
    "checkpoint": "You can say exactly who owns which control in your cloud provider’s model, and prove security from commit through to runtime.",
    "resources": [
      {
        "label": "Kubernetes security checklist",
        "href": "https://kubernetes.io/docs/concepts/security/security-checklist/"
      },
      {
        "label": "NIST Secure Software Development Framework",
        "href": "https://csrc.nist.gov/pubs/sp/800/218/final"
      },
      {
        "label": "CIS Benchmarks",
        "href": "https://www.cisecurity.org/cis-benchmarks"
      }
    ],
    "lessons": [
      {
        "id": "09-1",
        "title": "Shared responsibility, and who owns what",
        "oneLine": "The cloud provider secures the platform; you secure what you put on it — and the boundary moves depending on the service.",
        "mins": 8
      },
      {
        "id": "09-2",
        "title": "Cloud identity and least privilege",
        "oneLine": "In cloud, identity is the perimeter, and over-permissive roles are the most common serious weakness.",
        "mins": 9
      },
      {
        "id": "09-3",
        "title": "Cloud networking, data and keys",
        "oneLine": "Same networking principles as before, different names — plus a key management service you should let do the hard part.",
        "mins": 8
      },
      {
        "id": "09-4",
        "title": "Cloud posture, monitoring and response",
        "oneLine": "Cloud environments change constantly, so security has to be checked continuously rather than reviewed annually.",
        "mins": 8
      },
      {
        "id": "09-5",
        "title": "Container security in practice",
        "oneLine": "Containers are convenient and their defaults are not secure — most of the risk comes from the image and the permissions.",
        "mins": 8
      },
      {
        "id": "09-6",
        "title": "Kubernetes: the parts that bite",
        "oneLine": "Kubernetes is powerful, complicated, and insecure by default in ways that are not obvious until you look.",
        "mins": 9
      },
      {
        "id": "09-7",
        "title": "Securing the pipeline itself",
        "oneLine": "Your CI/CD system can deploy anything to production, which makes it one of the most powerful and least protected systems you own.",
        "mins": 9
      },
      {
        "id": "09-8",
        "title": "Provenance: proving what you shipped",
        "oneLine": "Supply chain security ends with being able to prove that what is running is what you built, from source you reviewed.",
        "mins": 8
      }
    ]
  },
  {
    "number": "10",
    "title": "The deep end",
    "subtitle": "Exploit development, mobile, wireless, hardware, OT, cryptography and AI security",
    "level": "EXPERT",
    "tags": [
      "RESEARCH",
      "OFFENSE",
      "DEFENSE"
    ],
    "weeks": 5,
    "hours": 55,
    "hue": 300,
    "plain": "Eight frontier fields, sampled honestly. You pick one to go deep on — nobody masters all of them, and pretending otherwise is how people stay shallow.",
    "outcome": "You can sample advanced specialities, judge which suits you, and go genuinely deep in one rather than superficially wide across all.",
    "project": "Complete one specialisation capstone with a reproducible lab, original analysis, and a write-up safe to publish.",
    "checkpoint": "You can read primary technical material, reproduce someone else’s result, question its assumptions, and say clearly what remains unknown.",
    "resources": [
      {
        "label": "pwn.college (free systems security curriculum)",
        "href": "https://pwn.college/"
      },
      {
        "label": "MITRE ATLAS — adversarial AI",
        "href": "https://atlas.mitre.org/"
      },
      {
        "label": "OWASP GenAI Security Project",
        "href": "https://genai.owasp.org/"
      }
    ],
    "lessons": [
      {
        "id": "10-1",
        "title": "Exploit development and modern mitigations",
        "oneLine": "Turning a crash into reliable control of a program, against defences specifically designed to stop you.",
        "mins": 10
      },
      {
        "id": "10-2",
        "title": "Mobile application security",
        "oneLine": "Phones hold everything, run apps from thousands of publishers, and put a copy of the client in the attacker’s hands.",
        "mins": 9
      },
      {
        "id": "10-3",
        "title": "Wireless and radio",
        "oneLine": "Anything transmitting through the air can be received by anyone nearby, which changes the threat model completely.",
        "mins": 9
      },
      {
        "id": "10-4",
        "title": "Hardware, firmware and IoT",
        "oneLine": "Physical access changes everything, and most connected devices were built to a price rather than to a threat model.",
        "mins": 9
      },
      {
        "id": "10-5",
        "title": "Operational technology and industrial control",
        "oneLine": "In OT, the priorities invert: availability and safety come first, and a wrong action can hurt people.",
        "mins": 9
      },
      {
        "id": "10-6",
        "title": "Cryptographic engineering and post-quantum",
        "oneLine": "Real cryptographic failures come from implementation and key management, not from broken mathematics.",
        "mins": 9
      },
      {
        "id": "10-7",
        "title": "AI and LLM security",
        "oneLine": "AI systems fail in ways traditional software does not, because their instructions and their data arrive through the same channel.",
        "mins": 10
      },
      {
        "id": "10-8",
        "title": "Choosing your depth",
        "oneLine": "Sampling is over; now pick one field and go deeper than is comfortable, because depth is what makes you valuable.",
        "mins": 7
      }
    ]
  },
  {
    "number": "11",
    "title": "Becoming a professional",
    "subtitle": "Research, disclosure, writing, portfolio, influence and the long game",
    "level": "EXPERT",
    "tags": [
      "RESEARCH",
      "LEADERSHIP"
    ],
    "weeks": 4,
    "hours": 40,
    "hue": 45,
    "plain": "The final stage is about becoming someone the field trusts: doing original work, disclosing it responsibly, explaining it clearly, and helping others.",
    "outcome": "You can turn curiosity into reproducible research, disclose it responsibly, write about it convincingly, and be trusted with judgement calls.",
    "project": "Publish a sanitised capstone portfolio: the problem, your method, your evidence, its limitations, the fix, a talk, and an honest retrospective.",
    "checkpoint": "Your work survives peer review, helps a real audience, and clearly labels what is evidence, what is inference, and what is still unknown.",
    "resources": [
      {
        "label": "CVE Program",
        "href": "https://www.cve.org/"
      },
      {
        "label": "NICE Framework work roles",
        "href": "https://niccs.cisa.gov/workforce-development/nice-framework"
      },
      {
        "label": "disclose.io — disclosure policy templates",
        "href": "https://disclose.io/"
      }
    ],
    "lessons": [
      {
        "id": "11-1",
        "title": "Doing research that holds up",
        "oneLine": "Research is a question narrow enough to answer, a method someone else could repeat, and honesty about what you did not prove.",
        "mins": 8
      },
      {
        "id": "11-2",
        "title": "Fuzzing and finding new bugs",
        "oneLine": "Fuzzing throws enormous quantities of malformed input at software and watches for the crashes that reveal real bugs.",
        "mins": 9
      },
      {
        "id": "11-3",
        "title": "Coordinated disclosure",
        "oneLine": "You found a real flaw in someone else’s software; now you have an ethical obligation and a process to follow.",
        "mins": 8
      },
      {
        "id": "11-4",
        "title": "Writing that people act on",
        "oneLine": "Technical work that nobody understands changes nothing, so writing clearly is a security skill, not a soft one.",
        "mins": 8
      },
      {
        "id": "11-5",
        "title": "Portfolio, interviews and proof",
        "oneLine": "Nobody can see what you know, so you have to build things that show it.",
        "mins": 8
      },
      {
        "id": "11-6",
        "title": "Risk communication and influence",
        "oneLine": "Being right is not enough; security only happens when other people, who do not report to you, choose to act.",
        "mins": 8
      },
      {
        "id": "11-7",
        "title": "Staying current without burning out",
        "oneLine": "The field changes constantly, and the goal is a sustainable system for keeping up rather than heroic attention.",
        "mins": 8
      },
      {
        "id": "11-8",
        "title": "Teaching, mentoring and what comes next",
        "oneLine": "Explaining what you know makes you better at it, and it is how the field replaces itself.",
        "mins": 8
      }
    ]
  },
  {
    "number": "12",
    "title": "Internship ready",
    "subtitle": "The tools and the audit work real junior adverts ask for — Burp, ZAP, Nmap, VAPT, control testing",
    "level": "MEDIUM",
    "tags": [
      "CAREER",
      "OFFENSE",
      "DEFENSE",
      "LEADERSHIP"
    ],
    "weeks": 3,
    "hours": 72,
    "hue": 95,
    "plain": "Everything else teaches you how security works. This stage teaches you to do the specific tasks junior job adverts list, so the requirements stop looking like a foreign language.",
    "outcome": "You can drive Burp Suite, ZAP and Nmap on a legal target, write a finding a developer will act on, and take part in a security audit and a risk assessment.",
    "project": "Run a full mini-assessment of a deliberately vulnerable app: scope it, scan it, verify by hand, and deliver a findings report plus a small control-testing worksheet.",
    "checkpoint": "You can read a junior job advert line by line and say, honestly, which parts you have actually done and where the evidence is.",
    "resources": [
      {
        "label": "PortSwigger Web Security Academy (free, includes Burp)",
        "href": "https://portswigger.net/web-security"
      },
      {
        "label": "OWASP ZAP",
        "href": "https://www.zaproxy.org/"
      },
      {
        "label": "Nmap reference guide",
        "href": "https://nmap.org/book/man.html"
      },
      {
        "label": "ISO/IEC 27001 Annex A control overview",
        "href": "https://www.iso.org/standard/27001"
      },
      {
        "label": "GOAD — a free vulnerable Active Directory lab",
        "href": "https://github.com/Orange-Cyberdefense/GOAD"
      }
    ],
    "lessons": [
      {
        "id": "12-1",
        "title": "VAPT: the job those adverts describe",
        "oneLine": "VAPT means finding weaknesses with tools and then proving by hand which of them are actually real.",
        "mins": 8
      },
      {
        "id": "12-2",
        "title": "Burp Suite, properly",
        "oneLine": "Burp sits between your browser and the site so you can read, change and replay every request.",
        "mins": 10
      },
      {
        "id": "12-3",
        "title": "OWASP ZAP and automated scanning",
        "oneLine": "ZAP is the free, scriptable scanner you reach for when you need coverage rather than precision.",
        "mins": 8
      },
      {
        "id": "12-4",
        "title": "Nmap for real work",
        "oneLine": "Nmap answers one question thoroughly: what is listening on these machines, and what exactly is it.",
        "mins": 9
      },
      {
        "id": "12-5",
        "title": "Writing a finding somebody fixes",
        "oneLine": "A finding is a small persuasive document: here is the problem, here is the proof, here is what it costs, here is the fix.",
        "mins": 9
      },
      {
        "id": "12-6",
        "title": "How a security audit actually runs",
        "oneLine": "An audit checks whether the controls a company claims to have are real, working, and evidenced.",
        "mins": 9
      },
      {
        "id": "12-7",
        "title": "Risk assessment and the risk register",
        "oneLine": "A risk assessment turns vague worry into a ranked, owned, tracked list that somebody has to decide about.",
        "mins": 8
      },
      {
        "id": "12-8",
        "title": "Applying when you have no experience",
        "oneLine": "Junior adverts describe an ideal candidate who does not exist; what they actually screen for is evidence that you can do the work.",
        "mins": 9
      },
      {
        "id": "12-9",
        "title": "The CV and the portfolio",
        "oneLine": "A CV gets you past the filter; the portfolio is what convinces the person who reads it.",
        "mins": 9
      },
      {
        "id": "12-10",
        "title": "The interview",
        "oneLine": "Interviews test how you think, not what you memorised, and the honest answer beats the confident one every time.",
        "mins": 9
      },
      {
        "id": "12-11",
        "title": "Talking about money",
        "oneLine": "The offer is the one moment in the whole process where you have leverage, and most people give it away by answering the first question honestly.",
        "mins": 9
      },
      {
        "id": "12-12",
        "title": "Your first certification",
        "oneLine": "A certification is a receipt for knowledge you already have, so earn it in that order and pick the one a job you want actually names.",
        "mins": 9
      },
      {
        "id": "12-13",
        "title": "A home lab worth showing",
        "oneLine": "Lesson 00-5 built one safe machine; this builds the small network that actually teaches you something, and documents it so it counts as evidence.",
        "mins": 10
      },
      {
        "id": "12-14",
        "title": "Getting found",
        "oneLine": "Most junior roles are filled from somebody the team already knows about, so the work is becoming somebody they know about.",
        "mins": 9
      }
    ]
  }
];

/** Review card ids per lesson, so unlocking does not need the cards themselves. */
export const cardIdsByLesson: Record<string, string[]> = {
  "00-1": [
    "q:00-1-a",
    "q:00-1-b",
    "w:Risk",
    "w:Threat",
    "w:Control",
    "w:Breach"
  ],
  "00-2": [
    "q:00-2-a",
    "q:00-2-b",
    "w:Confidentiality",
    "w:Integrity",
    "w:Availability",
    "w:Non-repudiation"
  ],
  "00-3": [
    "q:00-3-a",
    "q:00-3-b",
    "w:Asset",
    "w:Vulnerability",
    "w:Exploit",
    "w:Attack surface"
  ],
  "00-4": [
    "q:00-4-a",
    "q:00-4-b",
    "w:Rules of engagement (RoE)",
    "w:Scope",
    "w:Authorised",
    "w:Responsible disclosure"
  ],
  "00-5": [
    "q:00-5-a",
    "q:00-5-b",
    "w:Virtual machine (VM)",
    "w:Hypervisor",
    "w:Snapshot",
    "w:Host-only network"
  ],
  "00-6": [
    "q:00-6-a",
    "q:00-6-b",
    "w:T-shaped skills",
    "w:Spaced repetition",
    "w:Active recall"
  ],
  "00-7": [
    "q:00-7-a",
    "q:00-7-b",
    "w:Blue team",
    "w:Red team",
    "w:Purple team",
    "w:SOC"
  ],
  "00-8": [
    "q:00-8-a",
    "q:00-8-b",
    "w:NIST CSF 2.0",
    "w:MITRE ATT&CK",
    "w:CVE",
    "w:CVSS"
  ],
  "01-1": [
    "q:01-1-a",
    "q:01-1-b",
    "w:Bit",
    "w:Byte",
    "w:Hex",
    "w:Encoding"
  ],
  "01-2": [
    "q:01-2-a",
    "q:01-2-b",
    "w:Process",
    "w:Thread",
    "w:Kernel",
    "w:User mode / kernel mode"
  ],
  "01-3": [
    "q:01-3-a",
    "q:01-3-b",
    "w:Permissions",
    "w:SetUID",
    "w:ACL",
    "w:Root / Administrator"
  ],
  "01-4": [
    "q:01-4-a",
    "q:01-4-b",
    "w:Shell",
    "w:Pipe (|)",
    "w:sudo",
    "w:Daemon / service"
  ],
  "01-5": [
    "q:01-5-a",
    "q:01-5-b",
    "w:Registry",
    "w:SID",
    "w:Access token",
    "w:Active Directory (AD)"
  ],
  "01-6": [
    "q:01-6-a",
    "q:01-6-b",
    "w:Container",
    "w:Image",
    "w:Container escape"
  ],
  "01-7": [
    "q:01-7-a",
    "q:01-7-b",
    "w:Compiler",
    "w:Binary",
    "w:Debugger",
    "w:Reverse engineering"
  ],
  "01-8": [
    "q:01-8-a",
    "q:01-8-b",
    "w:Baseline",
    "w:Hardening",
    "w:Least privilege",
    "w:Log forwarding"
  ],
  "02-1": [
    "q:02-1-a",
    "q:02-1-b",
    "w:Packet",
    "w:Header",
    "w:Encapsulation",
    "w:Protocol"
  ],
  "02-2": [
    "q:02-2-a",
    "q:02-2-b",
    "w:MAC address",
    "w:ARP",
    "w:On-path attack",
    "w:VLAN"
  ],
  "02-3": [
    "q:02-3-a",
    "q:02-3-b",
    "w:IP address",
    "w:Subnet mask / CIDR",
    "w:NAT",
    "w:Private address range"
  ],
  "02-4": [
    "q:02-4-a",
    "q:02-4-b",
    "w:Port",
    "w:Default gateway",
    "w:Stateful firewall",
    "w:Egress filtering"
  ],
  "02-5": [
    "q:02-5-a",
    "q:02-5-b",
    "w:DNS",
    "w:Resolver",
    "w:TTL",
    "w:DNS tunnelling"
  ],
  "02-6": [
    "q:02-6-a",
    "q:02-6-b",
    "w:TCP",
    "w:UDP",
    "w:Three-way handshake",
    "w:Amplification attack"
  ],
  "02-7": [
    "q:02-7-a",
    "q:02-7-b",
    "w:HTTP method",
    "w:Cookie",
    "w:TLS",
    "w:Certificate authority"
  ],
  "02-8": [
    "q:02-8-a",
    "q:02-8-b",
    "w:WPA2 / WPA3",
    "w:Rogue access point",
    "w:VPN",
    "w:pcap"
  ],
  "03-1": [
    "q:03-1-a",
    "q:03-1-b",
    "w:Dictionary",
    "w:Library / module",
    "w:JSON",
    "w:Virtual environment"
  ],
  "03-2": [
    "q:03-2-a",
    "q:03-2-b",
    "w:awk",
    "w:jq",
    "w:Command injection",
    "w:Exit code"
  ],
  "03-3": [
    "q:03-3-a",
    "q:03-3-b",
    "w:Cmdlet",
    "w:Pipeline object",
    "w:Script block logging",
    "w:Living off the land"
  ],
  "03-4": [
    "q:03-4-a",
    "q:03-4-b",
    "w:DOM",
    "w:Same-origin policy",
    "w:CORS",
    "w:Sink"
  ],
  "03-5": [
    "q:03-5-a",
    "q:03-5-b",
    "w:Query",
    "w:SQL injection",
    "w:Parameterised query",
    "w:ORM"
  ],
  "03-6": [
    "q:03-6-a",
    "q:03-6-b",
    "w:Buffer overflow",
    "w:Use-after-free",
    "w:ASLR",
    "w:Memory-safe language"
  ],
  "03-7": [
    "q:03-7-a",
    "q:03-7-b",
    "w:Regex",
    "w:Anchor",
    "w:ReDoS",
    "w:Canonicalisation"
  ],
  "03-8": [
    "q:03-8-a",
    "q:03-8-b",
    "w:REST API",
    "w:API token",
    "w:Commit history",
    "w:Secret scanning"
  ],
  "04-1": [
    "q:04-1-a",
    "q:04-1-b",
    "w:Likelihood",
    "w:Impact",
    "w:Risk appetite",
    "w:Residual risk"
  ],
  "04-2": [
    "q:04-2-a",
    "q:04-2-b",
    "w:Authentication",
    "w:Authorisation",
    "w:MFA",
    "w:Passkey"
  ],
  "04-3": [
    "q:04-3-a",
    "q:04-3-b",
    "w:Symmetric encryption",
    "w:Asymmetric encryption",
    "w:Hash",
    "w:Salt",
    "w:ML-KEM"
  ],
  "04-4": [
    "q:04-4-a",
    "q:04-4-b",
    "w:Defence in depth",
    "w:Zero trust",
    "w:Micro-segmentation",
    "w:Lateral movement"
  ],
  "04-5": [
    "q:04-5-a",
    "q:04-5-b",
    "w:Threat model",
    "w:Trust boundary",
    "w:STRIDE",
    "w:Abuse case"
  ],
  "04-6": [
    "q:04-6-a",
    "q:04-6-b",
    "w:EPSS",
    "w:KEV"
  ],
  "04-7": [
    "q:04-7-a",
    "q:04-7-b",
    "w:RPO",
    "w:RTO",
    "w:Immutable backup",
    "w:Configuration drift"
  ],
  "04-8": [
    "q:04-8-a",
    "q:04-8-b",
    "w:Policy",
    "w:GDPR",
    "w:ISO 27001",
    "w:Audit evidence"
  ],
  "05-1": [
    "q:05-1-a",
    "q:05-1-b",
    "w:OWASP",
    "w:CWE",
    "w:Awareness document",
    "w:ASVS"
  ],
  "05-2": [
    "q:05-2-a",
    "q:05-2-b",
    "w:IDOR",
    "w:Privilege escalation",
    "w:Force browsing",
    "w:Deny by default"
  ],
  "05-3": [
    "q:05-3-a",
    "q:05-3-b",
    "w:Injection",
    "w:Blind injection",
    "w:Allow-list",
    "w:RCE"
  ],
  "05-4": [
    "q:05-4-a",
    "q:05-4-b",
    "w:XSS",
    "w:Stored XSS",
    "w:CSRF",
    "w:CSP"
  ],
  "05-5": [
    "q:05-5-a",
    "q:05-5-b",
    "w:SSRF",
    "w:IMDS",
    "w:Deserialisation",
    "w:Path traversal"
  ],
  "05-6": [
    "q:05-6-a",
    "q:05-6-b",
    "w:BOLA",
    "w:Mass assignment",
    "w:Introspection",
    "w:Shadow API"
  ],
  "05-7": [
    "q:05-7-a",
    "q:05-7-b",
    "w:Transitive dependency",
    "w:SBOM",
    "w:Dependency confusion",
    "w:SLSA"
  ],
  "05-8": [
    "q:05-8-a",
    "q:05-8-b",
    "w:SAST / DAST",
    "w:Fail open / fail closed",
    "w:Regression test",
    "w:Root cause"
  ],
  "06-1": [
    "q:06-1-a",
    "q:06-1-b",
    "w:Rules of engagement",
    "w:Scope creep",
    "w:PTES",
    "w:Proof of concept"
  ],
  "06-2": [
    "q:06-2-a",
    "q:06-2-b",
    "w:OSINT",
    "w:Certificate transparency",
    "w:Passive vs active"
  ],
  "06-3": [
    "q:06-3-a",
    "q:06-3-b",
    "w:Port scan",
    "w:Service enumeration",
    "w:Banner grabbing",
    "w:Null session"
  ],
  "06-4": [
    "q:06-4-a",
    "q:06-4-b",
    "w:Payload",
    "w:Password spraying",
    "w:Proof of exploitation"
  ],
  "06-5": [
    "q:06-5-a",
    "q:06-5-b",
    "w:GTFOBins",
    "w:Cron job",
    "w:PATH hijacking"
  ],
  "06-6": [
    "q:06-6-a",
    "q:06-6-b",
    "w:Kerberos ticket",
    "w:Kerberoasting",
    "w:Pass-the-hash",
    "w:BloodHound"
  ],
  "06-7": [
    "q:06-7-a",
    "q:06-7-b",
    "w:Pivot",
    "w:Attack chain",
    "w:Persistence",
    "w:Detection gap"
  ],
  "06-8": [
    "q:06-8-a",
    "q:06-8-b",
    "w:Executive summary",
    "w:Reproduction steps",
    "w:Retest"
  ],
  "07-1": [
    "q:07-1-a",
    "q:07-1-b",
    "w:Telemetry",
    "w:Sysmon",
    "w:Normalisation",
    "w:Retention"
  ],
  "07-2": [
    "q:07-2-a",
    "q:07-2-b",
    "w:SIEM",
    "w:Correlation rule",
    "w:Enrichment",
    "w:Alert fatigue"
  ],
  "07-3": [
    "q:07-3-a",
    "q:07-3-b",
    "w:Tactic",
    "w:Technique",
    "w:Coverage map",
    "w:Atomic test"
  ],
  "07-4": [
    "q:07-4-a",
    "q:07-4-b",
    "w:Pyramid of Pain",
    "w:Sigma",
    "w:False positive",
    "w:Detection as code"
  ],
  "07-5": [
    "q:07-5-a",
    "q:07-5-b",
    "w:EDR",
    "w:Process lineage",
    "w:LOLBin",
    "w:Impossible travel"
  ],
  "07-6": [
    "q:07-6-a",
    "q:07-6-b",
    "w:NetFlow",
    "w:Beaconing",
    "w:Zeek",
    "w:JA3 / JA4"
  ],
  "07-7": [
    "q:07-7-a",
    "q:07-7-b",
    "w:IOC",
    "w:TTP",
    "w:STIX / TAXII",
    "w:Attribution"
  ],
  "07-8": [
    "q:07-8-a",
    "q:07-8-b",
    "w:Triage",
    "w:Threat hunting",
    "w:Hypothesis-driven",
    "w:Feedback loop"
  ],
  "08-1": [
    "q:08-1-a",
    "q:08-1-b",
    "w:Incident",
    "w:Containment",
    "w:Eradication",
    "w:Post-incident review"
  ],
  "08-2": [
    "q:08-2-a",
    "q:08-2-b",
    "w:Order of volatility",
    "w:Chain of custody",
    "w:Forensic image",
    "w:Write blocker"
  ],
  "08-3": [
    "q:08-3-a",
    "q:08-3-b",
    "w:File carving",
    "w:Prefetch",
    "w:Timestomping",
    "w:Super timeline"
  ],
  "08-4": [
    "q:08-4-a",
    "q:08-4-b",
    "w:Memory image",
    "w:Volatility",
    "w:Fileless malware",
    "w:Process injection"
  ],
  "08-5": [
    "q:08-5-a",
    "q:08-5-b",
    "w:BEC",
    "w:Mail rule abuse",
    "w:OAuth consent phishing",
    "w:Control plane log"
  ],
  "08-6": [
    "q:08-6-a",
    "q:08-6-b",
    "w:Static analysis",
    "w:Dynamic analysis",
    "w:Packer",
    "w:Sandbox evasion"
  ],
  "08-7": [
    "q:08-7-a",
    "q:08-7-b",
    "w:Assembly",
    "w:Decompiler",
    "w:Breakpoint",
    "w:Obfuscation"
  ],
  "08-8": [
    "q:08-8-a",
    "q:08-8-b",
    "w:Double extortion",
    "w:Tabletop exercise",
    "w:Blameless review"
  ],
  "09-1": [
    "q:09-1-a",
    "q:09-1-b",
    "w:IaaS / PaaS / SaaS",
    "w:Shared responsibility model",
    "w:Control plane",
    "w:Data plane"
  ],
  "09-2": [
    "q:09-2-a",
    "q:09-2-b",
    "w:Role",
    "w:Workload identity",
    "w:Privilege escalation path"
  ],
  "09-3": [
    "q:09-3-a",
    "q:09-3-b",
    "w:VPC",
    "w:Security group",
    "w:KMS",
    "w:Envelope encryption"
  ],
  "09-4": [
    "q:09-4-a",
    "q:09-4-b",
    "w:CSPM",
    "w:Audit log",
    "w:Guardrail",
    "w:Cryptojacking"
  ],
  "09-5": [
    "q:09-5-a",
    "q:09-5-b",
    "w:Base image",
    "w:Distroless",
    "w:Capabilities",
    "w:Image scanning"
  ],
  "09-6": [
    "q:09-6-a",
    "q:09-6-b",
    "w:API server",
    "w:RBAC",
    "w:Admission controller",
    "w:Network policy"
  ],
  "09-7": [
    "q:09-7-a",
    "q:09-7-b",
    "w:CI/CD",
    "w:Ephemeral runner",
    "w:OIDC federation",
    "w:Infrastructure as code"
  ],
  "09-8": [
    "q:09-8-a",
    "q:09-8-b",
    "w:Sigstore / cosign",
    "w:Provenance"
  ],
  "10-1": [
    "q:10-1-a",
    "q:10-1-b",
    "w:ROP",
    "w:Info leak",
    "w:Heap grooming",
    "w:CFI"
  ],
  "10-2": [
    "q:10-2-a",
    "q:10-2-b",
    "w:Sandbox",
    "w:Certificate pinning",
    "w:Frida",
    "w:Exported component"
  ],
  "10-3": [
    "q:10-3-a",
    "q:10-3-b",
    "w:Handshake capture",
    "w:Evil twin",
    "w:SDR",
    "w:Replay attack"
  ],
  "10-4": [
    "q:10-4-a",
    "q:10-4-b",
    "w:UART",
    "w:JTAG",
    "w:Secure boot",
    "w:Side-channel"
  ],
  "10-5": [
    "q:10-5-a",
    "q:10-5-b",
    "w:PLC",
    "w:SCADA",
    "w:Purdue model",
    "w:Safety instrumented system"
  ],
  "10-6": [
    "q:10-6-a",
    "q:10-6-b",
    "w:Nonce",
    "w:Hybrid key exchange",
    "w:Crypto agility"
  ],
  "10-7": [
    "q:10-7-a",
    "q:10-7-b",
    "w:Prompt injection",
    "w:Indirect prompt injection",
    "w:Excessive agency",
    "w:MITRE ATLAS"
  ],
  "10-8": [
    "q:10-8-a",
    "q:10-8-b",
    "w:Primary source",
    "w:Reproduction",
    "w:Specialisation",
    "w:Capstone"
  ],
  "11-1": [
    "q:11-1-a",
    "q:11-1-b",
    "w:Reproducible",
    "w:Prior work",
    "w:Threat to validity",
    "w:Negative result"
  ],
  "11-2": [
    "q:11-2-a",
    "q:11-2-b",
    "w:Fuzzing",
    "w:Harness",
    "w:Sanitizer",
    "w:Variant analysis"
  ],
  "11-3": [
    "q:11-3-a",
    "q:11-3-b",
    "w:Coordinated disclosure",
    "w:security.txt",
    "w:CNA",
    "w:Embargo"
  ],
  "11-4": [
    "q:11-4-a",
    "q:11-4-b",
    "w:BLUF",
    "w:Confidence level",
    "w:Actionable"
  ],
  "11-5": [
    "q:11-5-a",
    "q:11-5-b",
    "w:Portfolio",
    "w:Write-up",
    "w:Home lab",
    "w:Behavioural interview"
  ],
  "11-6": [
    "q:11-6-a",
    "q:11-6-b",
    "w:Compensating control",
    "w:Risk acceptance",
    "w:Credibility"
  ],
  "11-7": [
    "q:11-7-a",
    "q:11-7-b",
    "w:Information diet",
    "w:On-call",
    "w:Sustainable pace"
  ],
  "11-8": [
    "q:11-8-a",
    "q:11-8-b",
    "w:Mentoring",
    "w:Blameless culture",
    "w:Gatekeeping",
    "w:Community contribution"
  ],
  "12-1": [
    "q:12-1-a",
    "q:12-1-b",
    "w:VAPT",
    "w:Verification"
  ],
  "12-2": [
    "q:12-2-a",
    "q:12-2-b",
    "w:Intercepting proxy",
    "w:Repeater",
    "w:Intruder"
  ],
  "12-3": [
    "q:12-3-a",
    "q:12-3-b",
    "w:Passive scan",
    "w:Active scan",
    "w:Spider / crawler",
    "w:Baseline scan"
  ],
  "12-4": [
    "q:12-4-a",
    "q:12-4-b",
    "w:Host discovery",
    "w:Service and version detection",
    "w:Filtered port",
    "w:NSE"
  ],
  "12-5": [
    "q:12-5-a",
    "q:12-5-b",
    "w:Remediation",
    "w:Redaction"
  ],
  "12-6": [
    "q:12-6-a",
    "q:12-6-b",
    "w:Design vs operating effectiveness",
    "w:Sampling",
    "w:Exception"
  ],
  "12-7": [
    "q:12-7-a",
    "q:12-7-b",
    "w:Inherent risk",
    "w:Risk register",
    "w:Risk owner"
  ],
  "12-8": [
    "q:12-8-a",
    "q:12-8-b",
    "w:Evidence of skill",
    "w:Transferable requirement",
    "w:Screening"
  ],
  "12-9": [
    "q:12-9-a",
    "q:12-9-b",
    "w:ATS",
    "w:Pinned repository"
  ],
  "12-10": [
    "q:12-10-a",
    "q:12-10-b",
    "w:Scenario question",
    "w:STAR",
    "w:Clarifying question",
    "w:Technical screen"
  ],
  "12-11": [
    "q:12-11-a",
    "q:12-11-b",
    "w:Anchoring",
    "w:Range",
    "w:Total compensation",
    "w:Counter"
  ],
  "12-12": [
    "q:12-12-a",
    "q:12-12-b",
    "w:Exam objectives",
    "w:Voucher",
    "w:Braindump",
    "w:Recertification"
  ],
  "12-13": [
    "q:12-13-a",
    "q:12-13-b",
    "w:GOAD",
    "w:Evaluation ISO"
  ],
  "12-14": [
    "q:12-14-a",
    "q:12-14-b",
    "w:Referral",
    "w:Chapter",
    "w:Informational interview",
    "w:Capture the flag (CTF)",
    "w:Hidden market"
  ]
};

/** Lessons carrying a hands-on exercise, so the roadmap can say which. */
export const practiceLessons: string[] = ["03-2","05-3","04-6","12-4","05-2","00-4","01-3","02-7","06-1","07-4","08-2","09-2","10-7","11-3","08-5"];

export const glossaryCount = 414;
export const totalQuestions = 220;
