import type { Question } from './types';

/** Questions for stages 08–11. */
export const quizC: Question[] = [
  // ---------- 08 When it goes wrong ----------
  {
    id: '08-1-a', lesson: '08-1',
    ask: 'Why can containing an incident too early make the outcome worse?',
    options: [
      'You alert the attacker before you know the full scope, and they may turn destructive',
      'Containment permanently destroys forensic evidence',
      'Regulators require notification before any containment action',
      'Early containment voids most cyber insurance policies',
    ],
    answer: 0,
    why: 'The most common failure is declaring scope too early — announcing containment while the attacker still holds access somewhere nobody looked.',
  },
  {
    id: '08-1-b', lesson: '08-1',
    ask: 'Which incident response phase does the most to determine the outcome?',
    options: ['Preparation', 'Detection and analysis', 'Containment', 'Recovery'],
    answer: 0,
    why: 'A plan, defined roles, an out-of-band comms channel, retained tooling and logging already switched on. None of these can be added during an incident.',
  },
  {
    id: '08-2-a', lesson: '08-2',
    ask: 'Why is immediately powering off a suspected compromised machine usually wrong?',
    options: [
      'It destroys memory, running processes and network state — the most volatile evidence',
      'It triggers the attacker\'s dead-man switch',
      'It invalidates the chain of custody',
      'It prevents the disk from being imaged afterwards',
    ],
    answer: 0,
    why: 'Order of volatility: registers, memory, connections and processes, temporary files, then disk. Pulling power destroys everything above disk.',
  },
  {
    id: '08-2-b', lesson: '08-2',
    ask: 'Why hash a forensic image before and after your analysis?',
    options: [
      'Matching hashes prove the copy is identical and nothing changed while you worked',
      'It compresses the image for long-term storage',
      'It is required before the image can be mounted read-only',
      'It identifies which files were deleted from the original',
    ],
    answer: 0,
    why: 'Work from copies, never originals, and use a write blocker for physical media.',
  },
  {
    id: '08-3-a', lesson: '08-3',
    ask: 'Why does a mismatch between two sets of NTFS timestamps suggest tampering?',
    options: [
      'Attackers who timestomp often change only one of the two sets',
      'NTFS keeps timestamps synchronised, so any difference is a filesystem error',
      'The second set is written only when a file is deleted',
      'Mismatches indicate the disk was imaged incorrectly',
    ],
    answer: 0,
    why: 'NTFS keeps standard information and file name attribute timestamps. Forgetting the second is a detectable anomaly.',
  },
  {
    id: '08-3-b', lesson: '08-3',
    ask: 'Which Windows artefact records that a program was executed?',
    options: ['Prefetch', 'ShellBags', 'Jump lists', 'The SAM hive'],
    answer: 0,
    why: 'Prefetch records execution and frequency; Shimcache and Amcache record presence; ShellBags record folder browsing.',
  },
  {
    id: '08-4-a', lesson: '08-4',
    ask: 'Why is an executable memory region with no backing file suspicious?',
    options: [
      'It is the strongest signal for code injection, and hard for an attacker to avoid',
      'It always indicates a kernel-mode rootkit',
      'Legitimate programs never allocate executable memory',
      'It means the process was started without a parent',
    ],
    answer: 0,
    why: 'It is why memory analysis frequently finds what disk-only investigation missed entirely.',
  },
  {
    id: '08-4-b', lesson: '08-4',
    ask: 'Why capture memory as early as possible?',
    options: [
      'Every minute of runtime overwrites more of what you wanted to capture',
      'Memory contents are wiped after a fixed timeout',
      'Capture tools stop working once the system is under load',
      'The chain of custody expires after one hour',
    ],
    answer: 0,
    why: 'Fileless malware and in-memory command and control leave nothing on disk to find later.',
  },
  {
    id: '08-5-a', lesson: '08-5',
    ask: 'Why does resetting a password fail to remove access granted through a malicious OAuth application?',
    options: [
      'The app holds its own durable token, independent of the user\'s password',
      'Password resets do not apply to federated accounts',
      'The attacker will simply phish the new password',
      'OAuth consent is stored on the endpoint, not in the directory',
    ],
    answer: 0,
    why: 'Consent phishing grants access that survives credential rotation. The consent grant itself has to be revoked.',
  },
  {
    id: '08-5-b', lesson: '08-5',
    ask: 'You find a gap in the audit trail during an investigation. What is that?',
    options: [
      'Evidence — attackers frequently disable or reconfigure logging early',
      'A collection error that should be excluded from the timeline',
      'Proof that the system was not compromised during that window',
      'A normal consequence of log rotation',
    ],
    answer: 0,
    why: 'The absence of logs where logs should exist is itself a finding, not the absence of evidence.',
  },
  {
    id: '08-6-a', lesson: '08-6',
    ask: 'Why can uploading a sample to a public sandbox damage an active investigation?',
    options: [
      'It can alert the attacker that they have been discovered, and may expose confidential data',
      'Public sandboxes cannot analyse targeted malware',
      'It transfers ownership of the evidence to the sandbox provider',
      'It invalidates the sample\'s hash for later comparison',
    ],
    answer: 0,
    why: 'Attackers monitor public submissions for their own samples. This has genuinely compromised real investigations.',
  },
  {
    id: '08-6-b', lesson: '08-6',
    ask: 'What is the practical output of malware triage during an incident?',
    options: [
      'Indicators to hunt, techniques observed, persistence to remove, destinations to block',
      'A complete reverse-engineered specification of the sample',
      'Attribution to a named threat group',
      'A signature submitted to antivirus vendors',
    ],
    answer: 0,
    why: 'Deep reverse engineering is a specialisation. Triage is what every responder needs, and it is behavioural.',
  },
  {
    id: '08-7-a', lesson: '08-7',
    ask: 'Why is running a packed sample and dumping memory often better than statically unpacking it?',
    options: [
      'The program unpacks itself, doing the hard work for you',
      'Static unpacking is illegal without the vendor\'s permission',
      'Memory dumps include the original source code',
      'Packed samples cannot be opened in a disassembler at all',
    ],
    answer: 0,
    why: 'Packing, anti-debugging and encrypted strings exist to waste your time. Letting it run past that point is usually the efficient move.',
  },
  {
    id: '08-7-b', lesson: '08-7',
    ask: 'What should you do before starting a reverse engineering session?',
    options: [
      'Set a specific answerable goal, because the work expands to fill infinite time',
      'Fully decompile the binary to readable source',
      'Identify the compiler and its exact version',
      'Disable all anti-debugging checks in advance',
    ],
    answer: 0,
    why: '"What is the command and control protocol?" is answerable. "Understand this binary" is not.',
  },
  {
    id: '08-8-a', lesson: '08-8',
    ask: 'Why is restoring from backup insufficient after ransomware?',
    options: [
      'Restoring a compromised system restores the compromise — you must rebuild and rotate credentials',
      'Backups are always encrypted by the same attacker',
      'Restored systems lose their security patches',
      'Insurance requires a full rebuild regardless',
    ],
    answer: 0,
    why: 'Rebuild from known-good images, restore data after scanning, rotate every credential, and monitor intensively — return visits are common.',
  },
  {
    id: '08-8-b', lesson: '08-8',
    ask: 'What does double extortion mean?',
    options: [
      'Data is stolen before encryption, so paying cannot un-steal it',
      'Two separate groups demand payment for the same intrusion',
      'The ransom doubles if not paid within a deadline',
      'Both the organisation and its customers are extorted',
    ],
    answer: 0,
    why: 'This is why "we have backups" is only half an answer to a ransomware question.',
  },

  // ---------- 09 Cloud and DevSecOps ----------
  {
    id: '09-1-a', lesson: '09-1',
    ask: 'Which responsibility never moves to the cloud provider, at any service level?',
    options: [
      'Identity, access management and data classification',
      'Operating system patching',
      'Physical security of the data centre',
      'Hypervisor maintenance',
    ],
    answer: 0,
    why: 'No provider will stop you giving an intern administrative rights or making a storage bucket public.',
  },
  {
    id: '09-1-b', lesson: '09-1',
    ask: 'Why is a stolen cloud credential often more dangerous than a compromised virtual machine?',
    options: [
      'The attacker uses the provider\'s own API — no malware, just administrative-looking calls',
      'Credentials cannot be revoked once issued',
      'Cloud APIs are not logged by default',
      'A credential grants access to every account in the organisation',
    ],
    answer: 0,
    why: 'This is why the control plane audit log is your primary evidence source in cloud investigations.',
  },
  {
    id: '09-2-a', lesson: '09-2',
    ask: 'Why can the permission to pass a role to a service be equivalent to administrator access?',
    options: [
      'You can attach a highly privileged role to something you control and inherit its power',
      'It grants direct read access to all IAM policies',
      'It bypasses multi-factor authentication requirements',
      'It allows the creation of new root accounts',
    ],
    answer: 0,
    why: 'Escalation paths hidden inside the permission model are exactly what an attacker enumerates first.',
  },
  {
    id: '09-2-b', lesson: '09-2',
    ask: 'What should machines use instead of embedded long-lived access keys?',
    options: [
      'Workload identity issuing short-lived credentials automatically',
      'Keys stored in an encrypted configuration file',
      'A shared key rotated quarterly by an automation script',
      'Keys passed as command line arguments at startup',
    ],
    answer: 0,
    why: 'Long-lived keys get committed to repositories and never expire. Also enforce IMDSv2 so an SSRF bug cannot simply read them.',
  },
  {
    id: '09-3-a', lesson: '09-3',
    ask: 'Why does envelope encryption scale better than encrypting everything with a master key?',
    options: [
      'A data key encrypts the data and the master key encrypts only the data key',
      'It allows encryption to happen on the client instead of the server',
      'It removes the need for key rotation entirely',
      'It permits the same key to be reused across regions',
    ],
    answer: 0,
    why: 'The master key never has to travel or handle bulk data, which is what makes key management tractable.',
  },
  {
    id: '09-3-b', lesson: '09-3',
    ask: 'Where should application secrets live, in order of preference?',
    options: [
      'Secrets manager, then environment variables, then config files, and never in source',
      'Source code, since it is access-controlled by the repository',
      'Config files, because they are excluded from builds',
      'Environment variables only, since they are never persisted',
    ],
    answer: 0,
    why: 'Every step up that list removes a whole class of leak.',
  },
  {
    id: '09-4-a', lesson: '09-4',
    ask: 'Why write cloud audit logs to a separate account?',
    options: [
      'So an attacker who compromises the monitored account cannot delete the evidence',
      'To reduce storage costs through consolidated billing',
      'Because providers do not allow logging within the same account',
      'To satisfy data residency requirements',
    ],
    answer: 0,
    why: 'Attackers disable logging early. A separate logging account with restricted access is the standard defence.',
  },
  {
    id: '09-4-b', lesson: '09-4',
    ask: 'An unexplained increase in cloud spend should be treated as what?',
    options: [
      'A security alert — often cryptojacking, and the first sign a credential leaked',
      'A billing anomaly for the finance team to investigate',
      'Normal variance in autoscaling behaviour',
      'A sign of misconfigured reserved instance pricing',
    ],
    answer: 0,
    why: 'Resource hijacking for mining is common and fast, and the bill is frequently the detection nobody planned for.',
  },
  {
    id: '09-5-a', lesson: '09-5',
    ask: 'Why is mounting the Docker socket into a container equivalent to giving it root on the host?',
    options: [
      'It can create new privileged containers that mount the host filesystem',
      'The socket contains the host\'s root password hash',
      'It disables all namespace isolation for that container',
      'It grants the container direct kernel module loading',
    ],
    answer: 0,
    why: 'Along with --privileged and host filesystem mounts, this is one of the three configurations that effectively hand over the host.',
  },
  {
    id: '09-5-b', lesson: '09-5',
    ask: 'Why rebuild container images regularly even when your code has not changed?',
    options: [
      'The base image and its packages fall behind on patches',
      'Image layers degrade in the registry over time',
      'Registries delete images that are not rebuilt',
      'Rebuilding regenerates the image signature, which expires',
    ],
    answer: 0,
    why: 'An image built six months ago is six months behind on every dependency it contains.',
  },
  {
    id: '09-6-a', lesson: '09-6',
    ask: 'What is true about Kubernetes network policies by default?',
    options: [
      'Without any policy, every pod can reach every other pod',
      'They default to deny-all until explicitly opened',
      'They only apply to traffic leaving the cluster',
      'They are enforced by the API server, not the network plugin',
    ],
    answer: 0,
    why: 'A default-deny policy per namespace is the single highest-value Kubernetes control, and it surprises people every time.',
  },
  {
    id: '09-6-b', lesson: '09-6',
    ask: 'Why is the ability to read secrets in a Kubernetes namespace effectively a privileged permission?',
    options: [
      'Secrets are only Base64-encoded, so reading them yields plain text credentials',
      'It grants the ability to modify the pods that use them',
      'It reveals the cluster\'s certificate authority key',
      'It allows escalation to cluster-admin automatically',
    ],
    answer: 0,
    why: 'Base64 is encoding, not encryption. Enable encryption at rest or use an external secrets store.',
  },
  {
    id: '09-7-a', lesson: '09-7',
    ask: 'Why pin a third-party CI action to a commit hash rather than a version tag?',
    options: [
      'Tags can be moved to point at different, possibly malicious code',
      'Hashes download faster than tags',
      'Tags expire after a fixed period',
      'Hashes are required for the action to access secrets',
    ],
    answer: 0,
    why: 'Treat CI as production. It holds deployment credentials, signing keys and source, which is exactly why attackers target it.',
  },
  {
    id: '09-7-b', lesson: '09-7',
    ask: 'What is the classic weakness in pull request triggers from forks?',
    options: [
      'A workflow may run untrusted code with access to repository secrets',
      'Fork branches bypass required reviews',
      'Fork builds run on unpatched runners',
      'Forks inherit the parent repository\'s deploy keys',
    ],
    answer: 0,
    why: 'Understand which trigger types expose secrets and which do not. It is a straightforward path to credential theft.',
  },
  {
    id: '09-8-a', lesson: '09-8',
    ask: 'When does signing an artefact become a real security control?',
    options: [
      'Once something verifies the signature at deployment and refuses unsigned artefacts',
      'As soon as the signature is published to a transparency log',
      'When the signing key is stored in a hardware module',
      'When every developer signs their own commits',
    ],
    answer: 0,
    why: 'Admission-time verification converts a signature from documentation into enforcement.',
  },
  {
    id: '09-8-b', lesson: '09-8',
    ask: 'What is an SBOM most valuable for?',
    options: [
      'Answering "are we affected?" in minutes when a new critical vulnerability lands',
      'Proving licence compliance to auditors',
      'Reducing the size of container images',
      'Detecting malware inside dependencies',
    ],
    answer: 0,
    why: 'It is the structural answer to Log4Shell: you cannot patch what you cannot inventory.',
  },

  // ---------- 10 The deep end ----------
  {
    id: '10-1-a', lesson: '10-1',
    ask: 'Why do most modern exploits require two vulnerabilities rather than one?',
    options: [
      'ASLR randomises addresses, so an information leak is needed before control can be used',
      'Operating systems require two failures before a crash occurs',
      'One bug is needed for entry and another for persistence',
      'Memory-safe languages block single-bug exploitation',
    ],
    answer: 0,
    why: 'Canaries, DEP/NX and ASLR each have to be defeated. That is what turned exploitation into a craft rather than a technique.',
  },
  {
    id: '10-1-b', lesson: '10-1',
    ask: 'What is return-oriented programming for?',
    options: [
      'Executing logic by chaining existing code fragments when the stack is non-executable',
      'Returning execution to the original program after a payload runs',
      'Restoring the stack canary after an overflow',
      'Reordering functions to defeat static analysis',
    ],
    answer: 0,
    why: 'DEP/NX makes injected data non-executable, so attackers reuse code that is already marked executable.',
  },
  {
    id: '10-2-a', lesson: '10-2',
    ask: 'Why is root detection in a mobile app a cost-raising measure rather than a boundary?',
    options: [
      'The app runs on a device the attacker controls, so any client-side check can be removed',
      'Root detection only works on Android, not iOS',
      'It can be disabled through the operating system settings',
      'App stores require it to be optional',
    ],
    answer: 0,
    why: 'The server must enforce everything that matters. Pinning and obfuscation raise cost; they do not create a boundary.',
  },
  {
    id: '10-2-b', lesson: '10-2',
    ask: 'In mobile testing, where do most real vulnerabilities actually live?',
    options: [
      'The backend API the app talks to',
      'The app\'s local database encryption',
      'The operating system sandbox',
      'The app store distribution process',
    ],
    answer: 0,
    why: 'Bypassing certificate pinning to see the API traffic is usually the first practical step, precisely because that is where the findings are.',
  },
  {
    id: '10-3-a', lesson: '10-3',
    ask: 'Why does a client failing to validate the RADIUS server certificate undermine enterprise Wi-Fi?',
    options: [
      'An attacker can stand up a fake authentication server and harvest credentials',
      'It disables WPA3 and falls back to WPA2',
      'It exposes the pre-shared key to anyone in range',
      'It allows deauthentication frames to be forged',
    ],
    answer: 0,
    why: 'It is a configuration problem across thousands of managed devices, which is why it persists in real networks.',
  },
  {
    id: '10-3-b', lesson: '10-3',
    ask: 'What is the legal reality of software-defined radio research?',
    options: [
      'Receiving is usually permitted; transmitting on licensed bands generally is not',
      'Both receiving and transmitting require a licence everywhere',
      'Both are unrestricted for research purposes',
      'Only transmitting above 1 GHz is restricted',
    ],
    answer: 0,
    why: 'Interfering with aviation, emergency or medical systems carries serious consequences. Research in a shielded environment or on permitted bands.',
  },
  {
    id: '10-4-a', lesson: '10-4',
    ask: 'Why is a hard-coded key shared across an entire product line especially bad?',
    options: [
      'Extracting it from one cheap device compromises every device ever sold',
      'It cannot be stored in secure hardware',
      'It prevents firmware updates from being signed',
      'It makes each device individually easier to clone',
    ],
    answer: 0,
    why: 'Combined with no update mechanism and a lifespan exceeding vendor support, this is the structural IoT problem Mirai demonstrated.',
  },
  {
    id: '10-4-b', lesson: '10-4',
    ask: 'What is a side-channel attack?',
    options: [
      'Extracting secrets from physical behaviour such as power draw or timing',
      'Attacking a secondary network interface on the device',
      'Bypassing authentication through a debug port',
      'Intercepting traffic on an unencrypted management channel',
    ],
    answer: 0,
    why: 'This is why constant-time cryptographic implementations exist — the logic is correct, but the physics leaks.',
  },
  {
    id: '10-5-a', lesson: '10-5',
    ask: 'How do security priorities differ in operational technology?',
    options: [
      'Safety and availability come first, ahead of confidentiality',
      'Confidentiality comes first because process data is proprietary',
      'The priorities are identical to enterprise IT',
      'Integrity is the only priority that matters',
    ],
    answer: 0,
    why: 'A controller taken offline can stop a production line or endanger people. This is why scanning is dangerous and patching is slow.',
  },
  {
    id: '10-5-b', lesson: '10-5',
    ask: 'What made the Triton incident particularly serious?',
    options: [
      'It targeted the safety instrumented system whose purpose is preventing harm',
      'It was the first malware to use a zero-day in an industrial protocol',
      'It spread automatically between unrelated facilities',
      'It encrypted process historian data for ransom',
    ],
    answer: 0,
    why: 'Attacking the layer that exists to stop dangerous conditions is a categorically different intent from attacking production.',
  },
  {
    id: '10-6-a', lesson: '10-6',
    ask: 'Which NIST standard covers post-quantum key establishment?',
    options: [
      'FIPS 203 (ML-KEM)',
      'FIPS 204 (ML-DSA)',
      'FIPS 205 (SLH-DSA)',
      'FIPS 140-3',
    ],
    answer: 0,
    why: 'FIPS 203 is key encapsulation, 204 and 205 are signatures. All three were finalised in August 2024.',
  },
  {
    id: '10-6-b', lesson: '10-6',
    ask: 'Why is post-quantum migration urgent before quantum computers exist?',
    options: [
      'Harvest-now-decrypt-later — traffic captured today can be decrypted once machines arrive',
      'Current algorithms are already broken by classical computers',
      'Certificate authorities have stopped issuing classical certificates',
      'Regulators have banned RSA for new deployments',
    ],
    answer: 0,
    why: 'Anything needing secrecy for a decade should already be moving to hybrid key exchange — and you need a cryptographic inventory before you can migrate anything.',
  },
  {
    id: '10-7-a', lesson: '10-7',
    ask: 'Why is prompt injection so difficult to fix?',
    options: [
      'A model has no structural boundary between instructions and the data it reads',
      'Models cannot be updated once trained',
      'Input filtering is computationally impossible at scale',
      'The vulnerability lives in the transformer architecture itself',
    ],
    answer: 0,
    why: 'There is no complete fix today. Mitigation is architectural: minimal permissions, human confirmation for consequential actions, untrusted output.',
  },
  {
    id: '10-7-b', lesson: '10-7',
    ask: 'Why does limiting an AI agent\'s permissions matter more than filtering prompts?',
    options: [
      'The damage from injection is bounded by what the model is allowed to do',
      'Filtering degrades model accuracy unacceptably',
      'Permissions are easier to audit than prompts',
      'Prompt filters cannot be applied to retrieved documents',
    ],
    answer: 0,
    why: 'Excessive agency is what converts a text vulnerability into a real-world one. Least privilege matters more for AI systems, not less.',
  },
  {
    id: '10-8-a', lesson: '10-8',
    ask: 'What does going deep in a speciality actually require?',
    options: [
      'Reading primary sources, reproducing known results, then pushing slightly past them',
      'Completing the certification associated with that field',
      'Reading every published summary of the area',
      'Building a lab covering all eight frontier fields',
    ],
    answer: 0,
    why: 'The gap between "I understand this" and "I found something" is smaller than beginners assume and larger than experts remember.',
  },
  {
    id: '10-8-b', lesson: '10-8',
    ask: 'What is the risk of specialising without maintaining breadth?',
    options: [
      'You produce technically impressive work that solves the wrong problem',
      'Your certification lapses without broad continuing education',
      'You become unemployable outside that speciality',
      'You lose the ability to read code outside your domain',
    ],
    answer: 0,
    why: 'The T-shape is a shape, not a spike. Keep the fundamentals alive.',
  },

  // ---------- 11 Becoming a professional ----------
  {
    id: '11-1-a', lesson: '11-1',
    ask: 'What makes a research question answerable?',
    options: [
      'It is narrow and specific enough to test — "does this implementation validate the hostname?"',
      'It has not been published on before',
      'It concerns a widely deployed product',
      'It can be answered without building a lab',
    ],
    answer: 0,
    why: 'Broad questions produce essays. "Is this protocol secure?" is unanswerable; the narrow version can be tested this afternoon.',
  },
  {
    id: '11-1-b', lesson: '11-1',
    ask: 'Why are negative results worth publishing?',
    options: [
      '"This does not work against this configuration, and here is why" saves others weeks',
      'They are easier to peer review than positive results',
      'They demonstrate rigour to potential employers',
      'Journals require a balance of positive and negative findings',
    ],
    answer: 0,
    why: 'The field under-publishes them because they feel like failures, which is precisely why they are valuable.',
  },
  {
    id: '11-2-a', lesson: '11-2',
    ask: 'Why is coverage guidance so much more effective than random fuzzing?',
    options: [
      'It mutates inputs that reach new code paths, turning blind search into guided search',
      'It runs many more executions per second',
      'It automatically minimises crashing inputs',
      'It avoids generating inputs the parser would reject',
    ],
    answer: 0,
    why: 'AFL++ and libFuzzer instrument the target and follow coverage. It finds bugs humans consistently miss.',
  },
  {
    id: '11-2-b', lesson: '11-2',
    ask: 'Why run a fuzzer with a sanitizer such as AddressSanitizer?',
    options: [
      'Most memory bugs do not crash on their own, so the fuzzer would report nothing',
      'Sanitizers make the target run faster under instrumentation',
      'Sanitizers deduplicate crashes automatically',
      'They are required to generate a coverage map',
    ],
    answer: 0,
    why: 'Without them, memory errors quietly corrupt state instead of crashing, and your fuzzer looks unproductive while finding plenty.',
  },
  {
    id: '11-3-a', lesson: '11-3',
    ask: 'Why do coordinated disclosure deadlines exist?',
    options: [
      'Without them, indefinite vendor silence protects the vendor and leaves users exposed',
      'Because researchers lose the right to a CVE after a fixed period',
      'Because most vulnerabilities become public within ninety days regardless',
      'Because exploit code becomes unreliable over time',
    ],
    answer: 0,
    why: 'Ninety days is the widely accepted norm, with flexibility for genuinely complex fixes and urgency for actively exploited issues.',
  },
  {
    id: '11-3-b', lesson: '11-3',
    ask: 'Which of these crosses the line into extortion?',
    options: [
      'Requesting payment outside a bounty programme in exchange for not disclosing',
      'Accepting a reward through a published bug bounty programme',
      'Setting a disclosure deadline the vendor did not agree to',
      'Publishing an advisory once the fix has shipped',
    ],
    answer: 0,
    why: 'Bug bounties are a legitimate framework with rules agreed in advance. Demanding money for silence is not, regardless of phrasing.',
  },
  {
    id: '11-4-a', lesson: '11-4',
    ask: 'Why does stating impact in business terms change a report\'s outcome?',
    options: [
      '"An unauthenticated attacker can read all customer payment records in under a minute" is a decision, not a fact',
      'Executives are not permitted to read technical detail',
      'It shortens the report, which increases the chance it is read',
      'Compliance frameworks require business language',
    ],
    answer: 0,
    why: 'Findings that get fixed and findings that get ignored differ mostly in how the impact was expressed.',
  },
  {
    id: '11-4-b', lesson: '11-4',
    ask: 'Where should the conclusion go in a security report?',
    options: [
      'First — executives may read the opening paragraph and nothing else',
      'Last, after the evidence has been presented',
      'In a separate appendix for decision-makers',
      'Distributed through the document alongside each finding',
    ],
    answer: 0,
    why: 'Bottom line up front. Building suspense is for fiction.',
  },
  {
    id: '11-5-a', lesson: '11-5',
    ask: 'Why does a write-up about a failed investigation impress an interviewer?',
    options: [
      'It shows how you think, which is what they are actually assessing',
      'It demonstrates humility, which is a cultural fit signal',
      'Failures are rarer in portfolios, so they stand out',
      'It proves you worked on something difficult',
    ],
    answer: 0,
    why: 'Interviews test reasoning more than recall. "I do not know, and here is how I would find out" beats a confident guess every time.',
  },
  {
    id: '11-5-b', lesson: '11-5',
    ask: 'What is the correct role of certifications?',
    options: [
      'They validate knowledge; they do not create it, and they do not replace building things',
      'They are the primary hiring signal in security',
      'They should be collected early to compensate for lack of experience',
      'They are only useful for government and defence roles',
    ],
    answer: 0,
    why: 'Choose one because a job you want requires it, not as a substitute for a portfolio.',
  },
  {
    id: '11-6-a', lesson: '11-6',
    ask: 'Why does calling too many findings critical make an organisation less safe?',
    options: [
      'Credibility is spent once — people stop believing you when it genuinely matters',
      'Critical findings must be reported to regulators',
      'It overloads the patching pipeline and delays real fixes',
      'It triggers unnecessary incident response activity',
    ],
    answer: 0,
    why: 'The loss is asymmetric. Reserve your strongest language for situations that warrant it.',
  },
  {
    id: '11-6-b', lesson: '11-6',
    ask: 'What is the best way to present a risk you cannot fully mitigate?',
    options: [
      'Offer options with trade-offs, and document the decision whichever way it goes',
      'Insist on the correct fix until it is approved',
      'Escalate immediately to the board',
      'Implement the fix and inform stakeholders afterwards',
    ],
    answer: 0,
    why: 'The decision belongs to the business. Documenting it protects everyone, including you.',
  },
  {
    id: '11-7-a', lesson: '11-7',
    ask: 'What is the healthiest way to filter security news?',
    options: [
      'Ask "does this affect what I am responsible for?" and let the rest go',
      'Read everything published and triage weekly',
      'Follow only vendor advisories for products you own',
      'Rely on a colleague to summarise the important items',
    ],
    answer: 0,
    why: 'The compulsion to read everything is the beginning of burnout. Most published research will never touch your systems.',
  },
  {
    id: '11-7-b', lesson: '11-7',
    ask: 'What is a realistic view of your responsibility as a defender?',
    options: [
      'Reduce likelihood, limit impact and respond well — not guarantee no incidents',
      'Prevent every incident within your area of control',
      'Ensure the organisation passes every audit',
      'Detect every intrusion within a defined time window',
    ],
    answer: 0,
    why: 'Nobody can guarantee an outcome that depends on an adversary. Believing otherwise is a direct route to burnout.',
  },
  {
    id: '11-8-a', lesson: '11-8',
    ask: 'Why is teaching one of the fastest ways to learn?',
    options: [
      'Explaining something simply exposes the parts you had only memorised',
      'It forces you to read more source material',
      'Students ask questions that reveal new vulnerabilities',
      'It builds a professional network that shares knowledge',
    ],
    answer: 0,
    why: 'You do not need to be an expert to help someone one step behind you — you are better placed, because you still remember what was confusing.',
  },
  {
    id: '11-8-b', lesson: '11-8',
    ask: 'What is the correct expectation about finishing this course?',
    options: [
      'You will not finish — security is a practice, not a body of knowledge to complete',
      'Completion takes roughly two years of consistent study',
      'You finish when you can pass the associated certifications',
      'You finish when you have completed one specialisation capstone',
    ],
    answer: 0,
    why: 'Keep a lab, keep a notebook, keep asking how things work, and keep teaching what you learn. That is the whole job.',
  },
];
