import type { Question } from './types';

/** Questions for stage 12. */
export const quizD: Question[] = [
  {
    id: '12-1-a', lesson: '12-1',
    ask: 'What does the two halves of VAPT actually mean in practice?',
    options: [
      'Scan broadly with tools, then verify by hand which findings are genuinely exploitable',
      'Test the vulnerability first, then assess how much it would cost to fix',
      'Two separate engagements, run by two separate teams',
      'Automated testing for web apps and manual testing for infrastructure',
    ],
    answer: 0,
    why: 'The assessment half is broad and mostly automated; the testing half is narrow and manual. Junior work is weighted towards the first, which is why it is learnable quickly.',
  },
  {
    id: '12-1-b', lesson: '12-1',
    ask: 'A scanner flags a critical vulnerability in a library. What comes before it reaches a report?',
    options: [
      'Check whether the vulnerable code path is actually reachable in this application',
      'Raise it immediately, since critical findings are time-sensitive',
      'Confirm the CVSS score matches the vendor advisory',
      'Search for public exploit code to attach as evidence',
    ],
    answer: 0,
    why: 'False-positive triage is the single skill separating a useful junior from a noisy one. Raw scanner output is not a report.',
  },
  {
    id: '12-2-a', lesson: '12-2',
    ask: 'Which Burp tool do you use to re-send one request with modifications?',
    options: ['Repeater', 'Intruder', 'Decoder', 'Comparer'],
    answer: 0,
    why: 'Repeater is where you confirm an injection or an access control flaw. Intruder is for sending many automated variations.',
  },
  {
    id: '12-2-b', lesson: '12-2',
    ask: 'Why set the Target scope in Burp before you start?',
    options: [
      'So Burp only records the targets you are permitted to touch',
      'Because Burp will not intercept traffic without it',
      'To speed up the automated scanner',
      'Because scope is required to install the CA certificate',
    ],
    answer: 0,
    why: 'Without scope you end up logging your own bank traffic in the same project file as a client engagement. Scope is a discipline, not a convenience.',
  },
  {
    id: '12-3-a', lesson: '12-3',
    ask: 'What is the practical difference between a passive and an active ZAP scan?',
    options: [
      'Passive only observes traffic; active sends attack payloads and needs permission',
      'Passive runs in the background; active runs on demand',
      'Passive covers the public site; active covers authenticated pages',
      'Passive uses the spider; active uses the AJAX spider',
    ],
    answer: 0,
    why: 'Active scans can create records, trigger emails, lock accounts, and in badly built applications delete data. Never point one at something you lack written permission to attack.',
  },
  {
    id: '12-3-b', lesson: '12-3',
    ask: 'Your ZAP scan of a modern single-page app finds almost nothing. What is the most likely reason?',
    options: [
      'The standard spider missed content that only appears after JavaScript runs',
      'The application is genuinely secure',
      'Passive scanning was disabled',
      'The target blocked the scanner at the firewall',
    ],
    answer: 0,
    why: 'Modern apps need the AJAX spider, which drives a real browser. Forgetting it, and forgetting to stay authenticated: is why beginner scans come back empty.',
  },
  {
    id: '12-4-a', lesson: '12-4',
    ask: 'What does a "filtered" result in Nmap mean?',
    options: [
      'No response came back, which usually means a firewall dropped the packet',
      'The port is open but the service could not be identified',
      'The host answered but nothing is listening on that port',
      'The scan was rate-limited and the result is unreliable',
    ],
    answer: 0,
    why: 'Open means something accepted the connection, closed means the host answered but nothing is listening, filtered means silence, and silence is information too.',
  },
  {
    id: '12-4-b', lesson: '12-4',
    ask: 'Why does -oA matter on a real engagement?',
    options: [
      'It saves the output, which is both reusable and evidence of what you found and when',
      'It enables all scan types at once',
      'It suppresses noisy output for fragile targets',
      'It is required for the scripting engine to run',
    ],
    answer: 0,
    why: 'An unsaved scan is work you will repeat. The file is also the record of what the network looked like at that moment.',
  },
  {
    id: '12-5-a', lesson: '12-5',
    ask: 'Which of these is an acceptable remediation line in a finding?',
    options: [
      'Use parameterised queries in the getUserById function in orders.js',
      'Improve input validation on user-supplied data',
      'Follow secure coding best practice',
      'Consider adding a web application firewall',
    ],
    answer: 0,
    why: 'A fix must be specific enough to implement. Vague remediation tells the developer you did not fully understand the bug.',
  },
  {
    id: '12-5-b', lesson: '12-5',
    ask: 'You need a screenshot proving you could read customer records. What do you include?',
    options: [
      'One record with the sensitive fields redacted, timestamped',
      'A full export of the table, to remove any doubt',
      'A description in prose, with no screenshot at all',
      'The raw database credentials you used',
    ],
    answer: 0,
    why: 'Prove it exists without exhausting it. Evidence sufficient to convince, and nothing beyond that.',
  },
  {
    id: '12-6-a', lesson: '12-6',
    ask: 'What is the difference between design and operating effectiveness?',
    options: [
      'Whether the control would work as written, versus whether it is actually happening',
      'Whether it is documented, versus whether it is automated',
      'Whether it was approved, versus whether it was budgeted',
      'Whether it covers the risk, versus whether it covers the framework requirement',
    ],
    answer: 0,
    why: 'A well-designed quarterly review last performed fourteen months ago is designed effectively and operating ineffectively.',
  },
  {
    id: '12-6-b', lesson: '12-6',
    ask: 'Which form of audit testing gives the strongest evidence?',
    options: ['Re-performance', 'Inspection', 'Observation', 'Inquiry'],
    answer: 0,
    why: 'Inquiry: asking someone: proves almost nothing on its own. Re-performance means doing it yourself and getting the same result.',
  },
  {
    id: '12-7-a', lesson: '12-7',
    ask: 'Which two risk register fields do juniors most often leave blank, and why does it matter?',
    options: [
      'Owner and review date: without them nobody is actually handling the risk',
      'Likelihood and impact: without them the score is meaningless',
      'Inherent and residual risk: without them controls cannot be justified',
      'Asset and description: without them the row cannot be understood',
    ],
    answer: 0,
    why: 'A risk with no name against it is a risk nobody is handling. The register exists to assign accountability, not to list worries.',
  },
  {
    id: '12-7-b', lesson: '12-7',
    ask: 'Which of these is a properly written risk statement?',
    options: [
      'An employee enters credentials on a phishing page, letting an attacker redirect a supplier payment',
      'Phishing',
      'Email security is insufficient',
      'Staff awareness training is overdue',
    ],
    answer: 0,
    why: 'Cause and consequence. A topic cannot be scored, controlled or tested; a cause-and-consequence statement can.',
  },
  {
    id: '12-8-a', lesson: '12-8',
    ask: 'You meet about sixty percent of a junior advert\'s requirements. What is the right move?',
    options: [
      'Apply, and attach evidence for the parts you can actually do',
      'Wait until you meet all of them before applying',
      'Apply but claim familiarity with the rest',
      'Apply only if you hold a matching certification',
    ],
    answer: 0,
    why: 'Junior adverts describe an ideal candidate who does not exist. Waiting means applying a year late, against people who applied a year early.',
  },
  {
    id: '12-8-b', lesson: '12-8',
    ask: 'What differentiates an application more than anything on the CV?',
    options: [
      'A link to something you made: a write-up, a report, a small tool',
      'A longer list of tools under a skills heading',
      'A certification in progress',
      'A cover letter tailored to the company',
    ],
    answer: 0,
    why: 'Evidence a stranger can look at beats any wording. Most of the other applicants will attach nothing at all.',
  },
  {
    id: '12-9-a', lesson: '12-9',
    ask: 'What belongs on a junior security CV instead of a long skills list?',
    options: [
      'A projects section where each entry says what you built and links to it',
      'Skill bars showing your proficiency percentage in each tool',
      'Every tool and framework you have ever opened',
      'A personal statement describing your passion for cybersecurity',
    ],
    answer: 0,
    why: 'Nobody can act on "Networking ▓▓▓▓░". Three real projects a stranger can click beat any list, because they are evidence rather than a claim.',
  },
  {
    id: '12-9-b', lesson: '12-9',
    ask: 'Why include the failures and dead ends in a project write-up?',
    options: [
      'They show judgement and how you think, which is what an interviewer is assessing',
      'They make the project look harder than it was',
      'They pad the write-up to a respectable length',
      'They prove the work is original rather than copied',
    ],
    answer: 0,
    why: 'Anyone can copy a tutorial to a working result. "This did not work, here is why" is the part that cannot be copied, and it is the natural opening for the interview conversation.',
  },
  {
    id: '12-10-a', lesson: '12-10',
    ask: 'You are asked about a tool you have never used. What is the strongest answer?',
    options: [
      'Say you have not used it, then reason aloud about what category it is in and how you would approach it',
      'Describe what you have read about it as though you have used it',
      'Change the subject to a tool you do know well',
      'Say you would look it up and move on',
    ],
    answer: 0,
    why: 'Bluffing is the only reliably fatal move: the interviewer has done the job. Reasoning from the category outwards shows exactly the thinking the role needs.',
  },
  {
    id: '12-10-b', lesson: '12-10',
    ask: 'An interviewer describes an alert and asks what you would do. What should come first?',
    options: [
      'Clarifying questions: what the asset is, who the user is, what normal looks like',
      'The name of the tool you would open',
      'A description of the most likely attack',
      'An estimate of the severity',
    ],
    answer: 0,
    why: 'Scenario questions test your process. Two good clarifying questions demonstrate the habit the job actually requires; jumping to a tool name is weaker even when the tool is right.',
  },
  {
    id: '12-11-a', lesson: '12-11',
    ask: 'You are asked your expected salary before you know the role well. What is the strongest move?',
    options: [
      'Ask what range they have budgeted, and give a number only if they insist',
      'Give your ideal figure so they know you value yourself',
      'State what you earned previously so the offer is fair',
      'Say you are flexible and will accept whatever is standard',
    ],
    answer: 0,
    why: 'Whoever names a number first sets the frame. About half the time they will answer, and then you are negotiating inside their range instead of against your own guess.',
  },
  {
    id: '12-11-b', lesson: '12-11',
    ask: 'For an internship with a fixed stipend and no room on pay, what is worth negotiating instead?',
    options: [
      'Conversion terms, study leave, exam fees, remote days and what you get to work on',
      'Nothing: accept the terms as offered',
      'A signing bonus to make up the difference',
      'A shorter notice period',
    ],
    answer: 0,
    why: 'Pushing hard on money can cost you an internship place. Everything around it is usually flexible, and a paid certification or a written conversion path is worth more than a small stipend increase.',
  },
  {
    id: '12-12-a', lesson: '12-12',
    ask: 'How should you choose your first certification?',
    options: [
      'Read ten adverts for the role you want and buy whichever one they name most',
      'Pick the most respected certification in the industry overall',
      'Start with the cheapest and work upwards',
      'Choose whichever has the highest pass rate',
    ],
    answer: 0,
    why: 'A certification is only worth what a specific employer weighs it at. In Sri Lanka that is usually Security+ or CEH at entry level, plus a cloud certification where the employer runs on Azure or AWS.',
  },
  {
    id: '12-12-b', lesson: '12-12',
    ask: 'Why are braindumps a career-ending shortcut rather than a study aid?',
    options: [
      'They mean revocation and a ban, and the industry reads it as an integrity failure',
      'They are usually out of date and contain wrong answers',
      'They cost more than official practice material',
      'They only cover a fraction of the exam objectives',
    ],
    answer: 0,
    why: 'Leaked real questions are cheating, and in a field whose entire product is trustworthiness that is not a small thing. Provider-written practice questions are fine; actual exam questions are not.',
  },
  {
    id: '12-13-a', lesson: '12-13',
    ask: 'What actually limits how large a home lab you can run?',
    options: [
      'Memory: a domain controller, a client and a logging stack are roughly 4GB each',
      'Processor cores, since each virtual machine needs a dedicated one',
      'Disk space, because every machine needs a full operating system image',
      'Network bandwidth between the virtual machines',
    ],
    answer: 0,
    why: 'On 16GB you can comfortably run three machines at once, which covers every exercise here: provided you stop treating "all machines on" as the normal state.',
  },
  {
    id: '12-13-b', lesson: '12-13',
    ask: 'What turns a home lab from a hobby into a portfolio piece?',
    options: [
      'A repository with the diagram, build steps, configs and what broke along the way',
      'Running more virtual machines than anyone else',
      'Using exactly the same tools a real company uses',
      'Building all of it without following any guide',
    ],
    answer: 0,
    why: 'Adverts ask for test labs and personal projects by name, but only a documented lab is something a stranger can look at. An undocumented one is invisible.',
  },
  {
    id: '12-14-a', lesson: '12-14',
    ask: 'Why does asking a stranger to refer you almost never work?',
    options: [
      'A referral spends their credibility, so they need to have seen your work first',
      'Companies forbid employees from referring people they met online',
      'Referrals are only allowed for senior roles',
      'Recruiters ignore referred candidates to keep the process fair',
    ],
    answer: 0,
    why: 'The person forwarding your CV wears part of the blame if you turn out badly. That is why the order runs: do the work publicly, be around the people who do it, and let the referral become the obvious thing rather than the favour.',
  },
  {
    id: '12-14-b', lesson: '12-14',
    ask: 'You get fifteen minutes with somebody working in a security team you admire. What is the best use of it?',
    options: [
      'Ask how they got there, say what you are learning, and show the one thing you built',
      'Ask directly whether they have an opening and can refer you',
      'Ask them to review your CV line by line',
      'Explain everything you have studied so far in as much detail as fits',
    ],
    answer: 0,
    why: 'Asking a near-stranger for a job puts them in an awkward position and is the fastest way to be remembered badly. Most people happily give fifteen minutes about their own path, and some of those conversations end with them forwarding you something.',
  },
];
