import type { Question } from './types';

/** Questions for stages 00-03. Distractors are plausible on purpose: a quiz you can pass by elimination teaches nothing. */
export const quizA: Question[] = [
  // ---------- 00 Start here, stay legal ----------
  {
    id: '00-1-a', lesson: '00-1',
    ask: 'Which statement best describes what security work actually is?',
    options: [
      'Managing risk: making harm harder, noticing it, and recovering from it',
      'Making systems impossible to break into',
      'Finding and exploiting vulnerabilities in software',
      'Installing and configuring security products',
    ],
    answer: 0,
    why: 'Security is risk management. Prevention always eventually fails, which is why noticing and recovering matter just as much as making it hard.',
  },
  {
    id: '00-1-b', lesson: '00-1',
    ask: 'Why is "is this secure?" the wrong question to ask?',
    options: [
      'Because security is always relative to a threat, a timeframe and a consequence',
      'Because only auditors are allowed to answer it',
      'Because nothing connected to the internet can ever be secure',
      'Because it should be "is this compliant?" instead',
    ],
    answer: 0,
    why: 'The useful version is "secure enough against who, for how long, and what happens when it fails?" Everything in the field is a trade-off.',
  },
  {
    id: '00-2-a', lesson: '00-2',
    ask: 'Ransomware encrypts a hospital\'s files. Which promise breaks first?',
    options: ['Availability', 'Confidentiality', 'Integrity', 'Non-repudiation'],
    answer: 0,
    why: 'The files are still secret and still correct: you just cannot reach them. Ransomware is primarily an availability attack, though modern strains steal data too, which then breaks confidentiality.',
  },
  {
    id: '00-2-b', lesson: '00-2',
    ask: 'An attacker quietly changes a payment amount in a database. Which promise broke?',
    options: ['Integrity', 'Availability', 'Confidentiality', 'Authenticity'],
    answer: 0,
    why: 'Integrity means nobody changed the data behind your back. These attacks are often worse than theft because you may never notice they happened.',
  },
  {
    id: '00-3-a', lesson: '00-3',
    ask: 'A vulnerability exists but no threat actor has any reason to use it. What does that tell you?',
    options: [
      'It is often not urgent: risk needs both a weakness and someone motivated to use it',
      'It must still be fixed immediately, before anything else',
      'It is not a vulnerability at all',
      'It automatically becomes a critical finding',
    ],
    answer: 0,
    why: 'A vulnerability with no matching threat is usually low priority, and a threat with no matching vulnerability cannot land. Both halves are needed.',
  },
  {
    id: '00-3-b', lesson: '00-3',
    ask: 'A control that notices an attack in progress is which type?',
    options: ['Detective', 'Preventive', 'Corrective', 'Compensating'],
    answer: 0,
    why: 'Preventive stops it, detective notices it, corrective fixes it afterwards. Good designs have all three, because prevention always eventually fails.',
  },
  {
    id: '00-4-a', lesson: '00-4',
    ask: 'A company\'s website is publicly reachable. What does that permit you to do?',
    options: [
      'Nothing beyond using it normally: public reachability is not permission to test',
      'Run a port scan, since scanning causes no damage',
      'Test it as long as you report anything you find',
      'Anything non-destructive',
    ],
    answer: 0,
    why: 'Unauthorised access is a crime in most countries regardless of intent or damage. "It was publicly reachable" has never been a legal defence.',
  },
  {
    id: '00-4-b', lesson: '00-4',
    ask: 'You accidentally find a real flaw in a live service you were not testing. What is the correct first move?',
    options: [
      'Stop, then report privately via security.txt or a bug bounty page',
      'Verify how far it goes so your report is complete',
      'Publish it so users can protect themselves',
      'Contact the company asking for a reward before disclosing',
    ],
    answer: 0,
    why: 'Do not exploit it further, do not go public, and never ask for money in exchange for silence: that is extortion regardless of phrasing.',
  },
  {
    id: '00-5-a', lesson: '00-5',
    ask: 'Why set a lab virtual machine to host-only networking?',
    options: [
      'So the lab machines can reach each other but not your real network or the internet',
      'Because it makes the virtual machines run noticeably faster',
      'So the host can share its own IP address with the guests',
      'Because bridged networking does not work with snapshots',
    ],
    answer: 0,
    why: 'This one setting is the difference between a lab and an accident. Switch internet on briefly when you need packages, then switch it back off.',
  },
  {
    id: '00-5-b', lesson: '00-5',
    ask: 'What is the practical value of taking a snapshot before you break something?',
    options: [
      'It turns "I destroyed my machine" into a five-second undo',
      'It encrypts the virtual disk against tampering',
      'It stops malware escaping the virtual machine',
      'It makes the virtual machine boot faster next time',
    ],
    answer: 0,
    why: 'Snapshots remove the cost of failure, which is a large part of why people stick with learning instead of giving up.',
  },
  {
    id: '00-6-a', lesson: '00-6',
    ask: 'Which study habit actually makes information stick?',
    options: [
      'Retrieving it from memory and using it, at growing intervals',
      'Re-reading the material until it feels familiar',
      'Highlighting the important passages carefully',
      'Watching a complete video course start to finish',
    ],
    answer: 0,
    why: 'Active recall and spaced repetition build durable memory. Re-reading and highlighting feel productive and teach very little, which is exactly what the Review tab in this app is for.',
  },
  {
    id: '00-6-b', lesson: '00-6',
    ask: 'What does a "T-shaped" skill profile mean in security?',
    options: [
      'Broad foundations across the field plus deep expertise in one part',
      'Equal expertise across every speciality',
      'Technical skills paired with management skills',
      'Two years of theory followed by two years of practice',
    ],
    answer: 0,
    why: 'Nobody knows all of cybersecurity. Broad knowledge gets you hired; depth in one area makes you hard to replace.',
  },
  {
    id: '00-7-a', lesson: '00-7',
    ask: 'What does a purple team do?',
    options: [
      'Attackers and defenders work together so detection measurably improves',
      'It is another name for a red team engagement',
      'It audits both technical controls and compliance paperwork',
      'It manages the security budget across red and blue teams',
    ],
    answer: 0,
    why: 'Run a technique, check whether it was detected, tune the detection, run it again. It produces improvement rather than an annual report that gets filed.',
  },
  {
    id: '00-7-b', lesson: '00-7',
    ask: 'Which role reconstructs what happened after a compromise?',
    options: ['DFIR', 'GRC', 'AppSec', 'Detection engineering'],
    answer: 0,
    why: 'Digital forensics and incident response is the detective work: timelines, evidence, and working out how far the intruder reached.',
  },
  {
    id: '00-8-a', lesson: '00-8',
    ask: 'What are the six functions of NIST CSF 2.0, in order?',
    options: [
      'Govern, Identify, Protect, Detect, Respond, Recover',
      'Identify, Protect, Detect, Respond, Recover, Review',
      'Plan, Do, Check, Act, Report, Improve',
      'Prevent, Detect, Contain, Eradicate, Recover, Learn',
    ],
    answer: 0,
    why: 'Govern was added in version 2.0 and wraps around the other five. It is the lifecycle behind almost every security programme.',
  },
  {
    id: '00-8-b', lesson: '00-8',
    ask: 'What is MITRE ATT&CK for?',
    options: [
      'Cataloguing observed adversary behaviour so you can check detection coverage',
      'Scoring how severe a given vulnerability is',
      'Listing the ten most common web application risks',
      'Mapping job roles to required skills',
    ],
    answer: 0,
    why: 'It turns the unanswerable "are we secure?" into the measurable "which of these specific behaviours would we catch?"',
  },

  // ---------- 01 How computers really work ----------
  {
    id: '01-1-a', lesson: '01-1',
    ask: 'Why is Base64 not a way to protect a password?',
    options: [
      'It is encoding, not encryption: anyone can reverse it instantly',
      'It uses a key that is published publicly',
      'It only works on text, not on binary data',
      'It was broken by researchers in the 2010s',
    ],
    answer: 0,
    why: 'Encoding changes format, not secrecy. Attackers use Base64 constantly to slip past naive filters, and beginners constantly mistake it for a secret.',
  },
  {
    id: '01-1-b', lesson: '01-1',
    ask: 'How many hexadecimal characters represent one byte?',
    options: ['Two', 'One', 'Four', 'Eight'],
    answer: 0,
    why: 'One hex digit covers four bits, so a byte: eight bits: is always exactly two hex characters.',
  },
  {
    id: '01-2-a', lesson: '01-2',
    ask: 'What does "privilege escalation" mean at the operating system level?',
    options: [
      'Moving from code that must ask permission to code that does not',
      'Increasing a process\'s CPU scheduling priority',
      'Adding a user to more groups than they need',
      'Running a program with a larger memory allocation',
    ],
    answer: 0,
    why: 'Your programs run in user mode and must ask the kernel. Escalation means reaching a position where you no longer have to ask.',
  },
  {
    id: '01-2-b', lesson: '01-2',
    ask: 'Why does the operating system give each process its own memory space?',
    options: [
      'So one process cannot read or corrupt another\'s data: it is a security boundary',
      'To let each process use the full amount of physical RAM',
      'To make context switching between processes faster',
      'Because the CPU can only address one process at a time',
    ],
    answer: 0,
    why: 'It is an isolation boundary, and a large share of serious attacks are fundamentally about crossing it.',
  },
  {
    id: '01-3-a', lesson: '01-3',
    ask: 'What does the SetUID bit do?',
    options: [
      'Makes a program run with its owner\'s privileges rather than yours',
      'Marks a file as readable by every user on the system',
      'Locks a file so only root can modify it',
      'Sets the default user for a new login session',
    ],
    answer: 0,
    why: 'It is how a normal user can change their own password. Any SetUID program owned by root is a potential path to full control if it can be tricked.',
  },
  {
    id: '01-3-b', lesson: '01-3',
    ask: 'On a directory, what does the execute permission actually grant?',
    options: [
      'Permission to enter the directory',
      'Permission to run the files inside it',
      'Permission to list the directory contents',
      'Permission to delete the directory',
    ],
    answer: 0,
    why: 'On directories, execute means traverse. Misunderstanding this causes a great many of the misconfigurations you will later find as a tester.',
  },
  {
    id: '01-4-a', lesson: '01-4',
    ask: 'What does the pipe character do in a shell command?',
    options: [
      'Feeds one command\'s output into the next command\'s input',
      'Runs two commands at the same time in parallel',
      'Writes the output to a file instead of the screen',
      'Runs the second command only if the first succeeds',
    ],
    answer: 0,
    why: 'Chaining small sharp tools with pipes is how you answer investigative questions in one line using only what is already installed.',
  },
  {
    id: '01-4-b', lesson: '01-4',
    ask: 'On a Linux machine, where do you look first for records of logins and sudo use?',
    options: [
      '/var/log (auth.log or secure)',
      '/etc/passwd',
      '/proc/self/status',
      '/tmp/session.log',
    ],
    answer: 0,
    why: 'auth.log or secure records authentication events, syslog records general system events, and journalctl reads the systemd journal.',
  },
  {
    id: '01-5-a', lesson: '01-5',
    ask: 'Which Windows event ID records a successful logon?',
    options: ['4624', '4625', '4688', '1102'],
    answer: 0,
    why: '4624 is a successful logon, 4625 a failed one, and 4688 a new process. Those three alone carry you through your first hundred investigations.',
  },
  {
    id: '01-5-b', lesson: '01-5',
    ask: 'Why do attackers steal Windows access tokens?',
    options: [
      'A token lets them act as another user without ever knowing the password',
      'Tokens contain the user\'s password in encrypted form',
      'Tokens bypass the need for the machine to be domain-joined',
      'Tokens grant kernel mode execution directly',
    ],
    answer: 0,
    why: 'The token is the badge Windows checks. Stealing or duplicating one sidesteps authentication entirely, which is why password policy alone is not the control people assume.',
  },
  {
    id: '01-6-a', lesson: '01-6',
    ask: 'You need to analyse a suspicious file. Why choose a VM over a container?',
    options: [
      'A VM has its own kernel, so isolation is far stronger',
      'Containers cannot run untrusted binaries at all',
      'VMs prevent the sample from making network connections',
      'Containers do not support snapshots',
    ],
    answer: 0,
    why: 'A container shares the host kernel. If you escape it, the host kernel is right there. For untrusted code, use the stronger boundary.',
  },
  {
    id: '01-6-b', lesson: '01-6',
    ask: 'A secret was added to a Docker image in one layer and deleted in a later one. What is true?',
    options: [
      'It is still recoverable from the earlier layer',
      'It is gone, because the final image reflects the deletion',
      'It is encrypted automatically by the container runtime',
      'It is only recoverable if the image was pushed to a registry',
    ],
    answer: 0,
    why: 'Image layers are permanent. This is one of the most common ways credentials leak from container builds.',
  },
  {
    id: '01-7-a', lesson: '01-7',
    ask: 'Why do memory-safety bugs appear in C but rarely in Python?',
    options: [
      'C makes you manage memory yourself with no automatic bounds checking',
      'Python programs are compiled, so the compiler catches the errors',
      'C does not support arrays, only raw pointers',
      'Python encrypts memory regions at runtime',
    ],
    answer: 0,
    why: 'C refuses to spend the time on checking, which is why it is fast, and why forgetting a boundary check becomes a security hole.',
  },
  {
    id: '01-7-b', lesson: '01-7',
    ask: 'What is reverse engineering?',
    options: [
      'Working out how something behaves without having its source code',
      'Recompiling a binary back into its original source file',
      'Undoing an attacker\'s changes to a compromised system',
      'Testing software by working backwards from its output',
    ],
    answer: 0,
    why: 'A binary is not a black box. strings, file, objdump and a debugger let you read what is inside: it just takes patience.',
  },
  {
    id: '01-8-a', lesson: '01-8',
    ask: 'Why forward logs off a machine rather than keeping them locally?',
    options: [
      'Because one of the first things a competent attacker does is edit or wipe local logs',
      'Because local disks are too small to retain them',
      'Because local logs are not timestamped accurately',
      'Because compliance frameworks forbid local storage',
    ],
    answer: 0,
    why: 'A local log after a compromise is evidence the attacker had write access to. Forwarded logs survive them.',
  },
  {
    id: '01-8-b', lesson: '01-8',
    ask: 'What is the point of taking a system baseline?',
    options: [
      'You cannot recognise abnormal until normal is written down',
      'It creates a restore point for recovery after an incident',
      'It satisfies the asset inventory requirement in most frameworks',
      'It measures how much performance headroom the system has',
    ],
    answer: 0,
    why: 'Every detection you will ever write is a statement about the difference between this and normal. Without a baseline you are guessing.',
  },

  // ---------- 02 How the internet moves data ----------
  {
    id: '02-1-a', lesson: '02-1',
    ask: 'A page loads but shows the wrong data. Which layer should you suspect first?',
    options: ['Layer 7, the application', 'Layer 3, IP', 'Layer 4, TCP', 'Layer 2, the link layer'],
    answer: 0,
    why: 'Cannot reach the host at all is layer 3. Connection opens then dies is layer 4. Content is wrong is layer 7.',
  },
  {
    id: '02-1-b', lesson: '02-1',
    ask: 'What is encapsulation in networking?',
    options: [
      'Each layer wrapping the layer above it in its own header',
      'Encrypting a packet before it leaves the host',
      'Splitting a large message into equally sized fragments',
      'Hiding internal addresses behind a public one',
    ],
    answer: 0,
    why: 'Envelopes inside envelopes. Opening a packet in Wireshark is unwrapping them one at a time, which is exactly why the tool looks the way it does.',
  },
  {
    id: '02-2-a', lesson: '02-2',
    ask: 'Why is ARP spoofing possible?',
    options: [
      'ARP has no authentication: any machine can answer, and the asker believes it',
      'ARP packets are encrypted with a key shared across the subnet',
      'Switches forward ARP replies to every port by design',
      'ARP relies on DNS, which can be poisoned',
    ],
    answer: 0,
    why: 'It is the classic on-path attack, and it is why "we are on the same Wi-Fi" is a meaningful risk statement.',
  },
  {
    id: '02-2-b', lesson: '02-2',
    ask: 'What does putting IoT devices on their own VLAN achieve?',
    options: [
      'A compromise of one device cannot reach the rest of the network directly',
      'It encrypts traffic between the devices and the router',
      'It prevents the devices from being scanned from the internet',
      'It stops the devices receiving malicious firmware updates',
    ],
    answer: 0,
    why: 'Segmentation limits blast radius. It is the cheapest genuinely effective piece of network security available.',
  },
  {
    id: '02-3-a', lesson: '02-3',
    ask: 'Which of these is a private address range that is never routed on the internet?',
    options: ['10.0.0.0/8', '11.0.0.0/8', '100.0.0.0/8', '1.1.1.0/24'],
    answer: 0,
    why: 'The private ranges are 10.x.x.x, 172.16-31.x.x and 192.168.x.x. Recognising them instantly tells you whether an address is internal or external.',
  },
  {
    id: '02-3-b', lesson: '02-3',
    ask: 'Why can a firewall policy that only filters IPv4 leave a network exposed?',
    options: [
      'Many networks run IPv6 in parallel, and it is unfiltered and has no NAT to hide behind',
      'IPv4 rules are automatically disabled when IPv6 is present',
      'IPv6 traffic cannot be logged by most firewalls',
      'IPv6 encrypts payloads, so rules cannot inspect them',
    ],
    answer: 0,
    why: 'IPv6 removes NAT\'s accidental protection and defenders routinely forget the IPv6 side. Attackers do not.',
  },
  {
    id: '02-4-a', lesson: '02-4',
    ask: 'Which firewall default is the correct one?',
    options: [
      'Default-deny: block everything unless a rule explicitly allows it',
      'Default-allow: pass everything unless a rule blocks it',
      'Default-log: permit everything but record it for review',
      'It depends entirely on the vendor\'s recommendation',
    ],
    answer: 0,
    why: 'Default-allow eventually lets something through that nobody thought to name. You cannot enumerate all bad, but you can enumerate all needed.',
  },
  {
    id: '02-4-b', lesson: '02-4',
    ask: 'Why does egress filtering frustrate an attacker who is already inside?',
    options: [
      'Their command channel and their stolen data both have to travel outward',
      'It prevents them from escalating privileges locally',
      'It blocks the initial exploit from reaching the host',
      'It stops them moving laterally between internal machines',
    ],
    answer: 0,
    why: 'Most organisations control inbound traffic and ignore outbound. Attackers rely on exactly that.',
  },
  {
    id: '02-5-a', lesson: '02-5',
    ask: 'A host makes a burst of DNS queries to long random subdomains of one domain. What does this suggest?',
    options: [
      'DNS tunnelling: data being smuggled out inside lookups',
      'A misconfigured DNS resolver retrying failed queries',
      'Normal behaviour for a content delivery network',
      'The host\'s DNS cache has expired',
    ],
    answer: 0,
    why: 'DNS is allowed almost everywhere, so it makes a convenient covert channel. This pattern is one of the highest-value things to alert on.',
  },
  {
    id: '02-5-b', lesson: '02-5',
    ask: 'Which DNS record type holds SPF, DKIM and DMARC information?',
    options: ['TXT', 'MX', 'CNAME', 'A'],
    answer: 0,
    why: 'They live in TXT records, and together they decide whether someone can convincingly forge email from your domain.',
  },
  {
    id: '02-6-a', lesson: '02-6',
    ask: 'What are the three steps of the TCP handshake, in order?',
    options: ['SYN, SYN-ACK, ACK', 'SYN, ACK, FIN', 'ACK, SYN, SYN-ACK', 'SYN, RST, ACK'],
    answer: 0,
    why: 'After the handshake, TCP numbers every byte, acknowledges what arrived and retransmits what did not. That reliability is why the web uses it.',
  },
  {
    id: '02-6-b', lesson: '02-6',
    ask: 'In a port scan, what does an RST response usually mean?',
    options: ['The port is closed', 'The port is open', 'The port is filtered', 'The host is offline'],
    answer: 0,
    why: 'SYN-ACK means open, RST means closed, and silence usually means filtered by a firewall.',
  },
  {
    id: '02-7-a', lesson: '02-7',
    ask: 'What does the padlock in a browser actually promise?',
    options: [
      'The connection is encrypted and you reached the domain the certificate names',
      'The website is trustworthy and safe to use',
      'The site has passed a security audit',
      'The site does not collect personal data',
    ],
    answer: 0,
    why: 'It says nothing about whether the site is legitimate. Phishing sites have valid certificates too. They are phishing sites with encryption.',
  },
  {
    id: '02-7-b', lesson: '02-7',
    ask: 'Why does the HttpOnly flag on a cookie matter?',
    options: [
      'It stops JavaScript reading the cookie, limiting what stolen XSS can take',
      'It forces the cookie to be sent only over HTTPS',
      'It prevents the cookie being sent on cross-site requests',
      'It encrypts the cookie value in the browser store',
    ],
    answer: 0,
    why: 'Secure forces HTTPS, SameSite restricts cross-site sending, and HttpOnly hides it from scripts. Three different flags, three different jobs.',
  },
  {
    id: '02-8-a', lesson: '02-8',
    ask: 'Which statement about VPNs is accurate?',
    options: [
      'It moves your trust to the VPN provider rather than removing the need for trust',
      'It makes you anonymous online',
      'It protects you from malware and phishing',
      'It prevents websites from tracking you',
    ],
    answer: 0,
    why: 'A VPN protects you from the local network and hides your address from destinations. It does not make you anonymous, and the provider can see what your ISP used to.',
  },
  {
    id: '02-8-b', lesson: '02-8',
    ask: 'Why capture packets first and filter afterwards?',
    options: [
      'Filtering while capturing throws away context you did not know you needed',
      'Capture filters are slower than display filters',
      'Wireshark cannot apply filters during a live capture',
      'Filtered captures cannot be saved to a pcap file',
    ],
    answer: 0,
    why: 'You rarely get the same five minutes of traffic back. Capture broadly, then narrow in analysis.',
  },

  // ---------- 03 Code enough to be dangerous ----------
  {
    id: '03-1-a', lesson: '03-1',
    ask: 'Why should a log-parsing tool keep going when it meets one malformed line?',
    options: [
      'A tool that dies on line one of a million-line log is a tool you cannot trust',
      'Malformed lines are always benign and can be ignored safely',
      'Stopping on error loses the data already parsed',
      'Python cannot catch exceptions inside a loop',
    ],
    answer: 0,
    why: 'Decide deliberately what should stop everything and what should be logged and skipped. Silent crashing is the worst of both.',
  },
  {
    id: '03-1-b', lesson: '03-1',
    ask: 'Which data structure does most security data arrive as?',
    options: [
      'Nested dictionaries and lists',
      'Fixed-width text records',
      'Binary structs',
      'Relational tables',
    ],
    answer: 0,
    why: 'JSON from APIs, parsed log lines, configuration files: being comfortable walking nested structures is most of the practical skill.',
  },
  {
    id: '03-2-a', lesson: '03-2',
    ask: 'Why is an unquoted shell variable a security problem, not just a bug?',
    options: [
      'Its contents get word-split and can become extra arguments or commands',
      'It causes the script to leak the variable into the environment',
      'It makes the variable readable by other users',
      'It disables the script\'s exit codes',
    ],
    answer: 0,
    why: 'If untrusted input ends up somewhere the shell evaluates, whoever controls that input controls your machine. Same root cause as command injection.',
  },
  {
    id: '03-2-b', lesson: '03-2',
    ask: 'What does "set -euo pipefail" do at the top of a script?',
    options: [
      'Makes the script stop on errors instead of continuing with wrong assumptions',
      'Enables verbose logging of every command run',
      'Runs the script with elevated privileges',
      'Forces the script to use bash rather than sh',
    ],
    answer: 0,
    why: 'Exit on error, error on undefined variables, and fail a pipeline if any stage fails. Almost always what you actually wanted.',
  },
  {
    id: '03-3-a', lesson: '03-3',
    ask: 'What is the practical difference between PowerShell and Bash pipelines?',
    options: [
      'PowerShell passes structured objects; Bash passes text that must be parsed',
      'PowerShell runs commands in parallel; Bash runs them sequentially',
      'PowerShell pipelines are encrypted in transit',
      'Bash pipelines cannot be used for filtering',
    ],
    answer: 0,
    why: 'Filtering on a real property beats fragile string matching, which is why PowerShell scales to thousands of machines cleanly.',
  },
  {
    id: '03-3-b', lesson: '03-3',
    ask: 'Why is PowerShell execution policy not a security boundary?',
    options: [
      'Anyone who can run PowerShell at all can bypass it',
      'It only applies to signed scripts',
      'It is disabled by default on all Windows versions',
      'It can only be set by domain policy',
    ],
    answer: 0,
    why: 'It stops accidents, not attackers. Script block logging is the control that actually helps, because it records what ran.',
  },
  {
    id: '03-4-a', lesson: '03-4',
    ask: 'What does the same-origin policy prevent?',
    options: [
      'Code from one site reading another site\'s data',
      'A site loading images from another domain',
      'A user visiting two sites at the same time',
      'A server accepting requests from other servers',
    ],
    answer: 0,
    why: 'Origin means scheme, host and port all matching. Nearly every browser security feature is either enforcing this rule or carefully making an exception to it.',
  },
  {
    id: '03-4-b', lesson: '03-4',
    ask: 'Which of these is a dangerous sink where data can become executable code?',
    options: ['innerHTML', 'textContent', 'getAttribute', 'querySelector'],
    answer: 0,
    why: 'innerHTML, eval and document.write turn strings into markup or code. textContent treats input strictly as text, which is why it is safe.',
  },
  {
    id: '03-5-a', lesson: '03-5',
    ask: 'Why does escaping quotes fail as an SQL injection defence where parameterisation succeeds?',
    options: [
      'Parameterisation sends structure and values separately, so input can never become code',
      'Escaping is too slow to run on every query',
      'Databases ignore escape characters in WHERE clauses',
      'Escaping only works on string columns, not numeric ones',
    ],
    answer: 0,
    why: 'Escaping tries to enumerate every dangerous input, which is impossible across encodings and contexts. Parameterisation removes the ambiguity entirely.',
  },
  {
    id: '03-5-b', lesson: '03-5',
    ask: 'Are NoSQL databases immune to injection?',
    options: [
      'No: raw input in a query object can inject operators that always match',
      'Yes, because they do not use SQL syntax',
      'Yes, provided the driver is up to date',
      'Only document stores are vulnerable, not key-value stores',
    ],
    answer: 0,
    why: 'Different syntax, identical root cause: data becoming instruction.',
  },
  {
    id: '03-6-a', lesson: '03-6',
    ask: 'Why does an attacker care about overwriting a function\'s return address?',
    options: [
      'It controls where the CPU goes next, and therefore what code runs',
      'It corrupts the stack so the program crashes reliably',
      'It reveals the contents of adjacent memory',
      'It disables the program\'s error handling',
    ],
    answer: 0,
    why: 'Control of the instruction pointer is control of execution. That is the whole goal of memory-corruption exploitation.',
  },
  {
    id: '03-6-b', lesson: '03-6',
    ask: 'What does ASLR do?',
    options: [
      'Randomises memory layout so attackers cannot predict addresses',
      'Marks the stack as non-executable',
      'Detects overwritten return addresses before a function returns',
      'Encrypts pointers stored in memory',
    ],
    answer: 0,
    why: 'Canaries detect overwrites, DEP/NX makes data non-executable, and ASLR randomises addresses. Modern exploitation is defeating these one at a time.',
  },
  {
    id: '03-7-a', lesson: '03-7',
    ask: 'Why decode input before validating it rather than after?',
    options: [
      'Otherwise an attacker encodes the payload to slip past the check, and it decodes later',
      'Decoding is faster than validating, so it should come first',
      'Validation libraries cannot handle encoded input at all',
      'Because encoding after validation corrupts the data',
    ],
    answer: 0,
    why: 'Check-then-decode is how filters get bypassed. Normalise to one canonical form first, then decide.',
  },
  {
    id: '03-7-b', lesson: '03-7',
    ask: 'What is ReDoS?',
    options: [
      'A denial of service caused by a regex that takes exponential time on crafted input',
      'A flood of requests aimed at a regular expression service',
      'A regex that matches too broadly and blocks legitimate users',
      'A technique for evading regex-based detections',
    ],
    answer: 0,
    why: 'One short crafted string can pin a CPU at 100%. It hides in innocuous-looking validation code.',
  },
  {
    id: '03-8-a', lesson: '03-8',
    ask: 'You pushed an API key to a repository and deleted it in the next commit. What must you do?',
    options: [
      'Rotate the key: it is still in history and scanners find leaked keys within minutes',
      'Nothing, since the current code no longer contains it',
      'Force-push to rewrite history, which fully resolves it',
      'Make the repository private, which prevents any exposure',
    ],
    answer: 0,
    why: 'Deleting the line is cosmetic. Assume the credential was collected the moment it was pushed.',
  },
  {
    id: '03-8-b', lesson: '03-8',
    ask: 'Which two realities most often break a first API enrichment script?',
    options: [
      'Rate limits and pagination',
      'Certificate validation and DNS resolution',
      'Character encoding and line endings',
      'Timezones and daylight saving',
    ],
    answer: 0,
    why: 'Ask too fast and you get blocked; assume one response holds everything and you silently miss results.',
  },
];
