import type { Question } from './types';

/** Questions for stage 12. */
export const quizD: Question[] = [
  {
    id: '12-1-a', lesson: '12-1',
    ask: 'What does the two halves of VAPT actually mean in practice?',
    options: [
      'Scan broadly with tools, then verify by hand which findings are genuinely exploitable',
      'Test the vulnerability first, then assess how much it would cost to fix',
      'Two separate engagements, run by two separate teams',
      'Automated testing for web apps and manual testing for infrastructure',
    ],
    answer: 0,
    why: 'The assessment half is broad and mostly automated; the testing half is narrow and manual. Junior work is weighted towards the first, which is why it is learnable quickly.',
  },
  {
    id: '12-1-b', lesson: '12-1',
    ask: 'A scanner flags a critical vulnerability in a library. What comes before it reaches a report?',
    options: [
      'Check whether the vulnerable code path is actually reachable in this application',
      'Raise it immediately, since critical findings are time-sensitive',
      'Confirm the CVSS score matches the vendor advisory',
      'Search for public exploit code to attach as evidence',
    ],
    answer: 0,
    why: 'False-positive triage is the single skill separating a useful junior from a noisy one. Raw scanner output is not a report.',
  },
  {
    id: '12-2-a', lesson: '12-2',
    ask: 'Which Burp tool do you use to re-send one request with modifications?',
    options: ['Repeater', 'Intruder', 'Decoder', 'Comparer'],
    answer: 0,
    why: 'Repeater is where you confirm an injection or an access control flaw. Intruder is for sending many automated variations.',
  },
  {
    id: '12-2-b', lesson: '12-2',
    ask: 'Why set the Target scope in Burp before you start?',
    options: [
      'So Burp only records the targets you are permitted to touch',
      'Because Burp will not intercept traffic without it',
      'To speed up the automated scanner',
      'Because scope is required to install the CA certificate',
    ],
    answer: 0,
    why: 'Without scope you end up logging your own bank traffic in the same project file as a client engagement. Scope is a discipline, not a convenience.',
  },
  {
    id: '12-3-a', lesson: '12-3',
    ask: 'What is the practical difference between a passive and an active ZAP scan?',
    options: [
      'Passive only observes traffic; active sends attack payloads and needs permission',
      'Passive runs in the background; active runs on demand',
      'Passive covers the public site; active covers authenticated pages',
      'Passive uses the spider; active uses the AJAX spider',
    ],
    answer: 0,
    why: 'Active scans can create records, trigger emails, lock accounts, and in badly built applications delete data. Never point one at something you lack written permission to attack.',
  },
  {
    id: '12-3-b', lesson: '12-3',
    ask: 'Your ZAP scan of a modern single-page app finds almost nothing. What is the most likely reason?',
    options: [
      'The standard spider missed content that only appears after JavaScript runs',
      'The application is genuinely secure',
      'Passive scanning was disabled',
      'The target blocked the scanner at the firewall',
    ],
    answer: 0,
    why: 'Modern apps need the AJAX spider, which drives a real browser. Forgetting it — and forgetting to stay authenticated — is why beginner scans come back empty.',
  },
  {
    id: '12-4-a', lesson: '12-4',
    ask: 'What does a "filtered" result in Nmap mean?',
    options: [
      'No response came back, which usually means a firewall dropped the packet',
      'The port is open but the service could not be identified',
      'The host answered but nothing is listening on that port',
      'The scan was rate-limited and the result is unreliable',
    ],
    answer: 0,
    why: 'Open means something accepted the connection, closed means the host answered but nothing is listening, filtered means silence — and silence is information too.',
  },
  {
    id: '12-4-b', lesson: '12-4',
    ask: 'Why does -oA matter on a real engagement?',
    options: [
      'It saves the output, which is both reusable and evidence of what you found and when',
      'It enables all scan types at once',
      'It suppresses noisy output for fragile targets',
      'It is required for the scripting engine to run',
    ],
    answer: 0,
    why: 'An unsaved scan is work you will repeat. The file is also the record of what the network looked like at that moment.',
  },
  {
    id: '12-5-a', lesson: '12-5',
    ask: 'Which of these is an acceptable remediation line in a finding?',
    options: [
      'Use parameterised queries in the getUserById function in orders.js',
      'Improve input validation on user-supplied data',
      'Follow secure coding best practice',
      'Consider adding a web application firewall',
    ],
    answer: 0,
    why: 'A fix must be specific enough to implement. Vague remediation tells the developer you did not fully understand the bug.',
  },
  {
    id: '12-5-b', lesson: '12-5',
    ask: 'You need a screenshot proving you could read customer records. What do you include?',
    options: [
      'One record with the sensitive fields redacted, timestamped',
      'A full export of the table, to remove any doubt',
      'A description in prose, with no screenshot at all',
      'The raw database credentials you used',
    ],
    answer: 0,
    why: 'Prove it exists without exhausting it. Evidence sufficient to convince, and nothing beyond that.',
  },
  {
    id: '12-6-a', lesson: '12-6',
    ask: 'What is the difference between design and operating effectiveness?',
    options: [
      'Whether the control would work as written, versus whether it is actually happening',
      'Whether it is documented, versus whether it is automated',
      'Whether it was approved, versus whether it was budgeted',
      'Whether it covers the risk, versus whether it covers the framework requirement',
    ],
    answer: 0,
    why: 'A well-designed quarterly review last performed fourteen months ago is designed effectively and operating ineffectively.',
  },
  {
    id: '12-6-b', lesson: '12-6',
    ask: 'Which form of audit testing gives the strongest evidence?',
    options: ['Re-performance', 'Inspection', 'Observation', 'Inquiry'],
    answer: 0,
    why: 'Inquiry — asking someone — proves almost nothing on its own. Re-performance means doing it yourself and getting the same result.',
  },
  {
    id: '12-7-a', lesson: '12-7',
    ask: 'Which two risk register fields do juniors most often leave blank, and why does it matter?',
    options: [
      'Owner and review date — without them nobody is actually handling the risk',
      'Likelihood and impact — without them the score is meaningless',
      'Inherent and residual risk — without them controls cannot be justified',
      'Asset and description — without them the row cannot be understood',
    ],
    answer: 0,
    why: 'A risk with no name against it is a risk nobody is handling. The register exists to assign accountability, not to list worries.',
  },
  {
    id: '12-7-b', lesson: '12-7',
    ask: 'Which of these is a properly written risk statement?',
    options: [
      'An employee enters credentials on a phishing page, letting an attacker redirect a supplier payment',
      'Phishing',
      'Email security is insufficient',
      'Staff awareness training is overdue',
    ],
    answer: 0,
    why: 'Cause and consequence. A topic cannot be scored, controlled or tested; a cause-and-consequence statement can.',
  },
  {
    id: '12-8-a', lesson: '12-8',
    ask: 'You meet about sixty percent of a junior advert\'s requirements. What is the right move?',
    options: [
      'Apply, and attach evidence for the parts you can actually do',
      'Wait until you meet all of them before applying',
      'Apply but claim familiarity with the rest',
      'Apply only if you hold a matching certification',
    ],
    answer: 0,
    why: 'Junior adverts describe an ideal candidate who does not exist. Waiting means applying a year late, against people who applied a year early.',
  },
  {
    id: '12-8-b', lesson: '12-8',
    ask: 'What differentiates an application more than anything on the CV?',
    options: [
      'A link to something you made — a write-up, a report, a small tool',
      'A longer list of tools under a skills heading',
      'A certification in progress',
      'A cover letter tailored to the company',
    ],
    answer: 0,
    why: 'Evidence a stranger can look at beats any wording. Most of the other applicants will attach nothing at all.',
  },
];
