import type { Question } from './types';

/** Questions for stages 04–07. */
export const quizB: Question[] = [
  // ---------- 04 Security thinking ----------
  {
    id: '04-1-a', lesson: '04-1',
    ask: 'What separates accepting a risk from ignoring it?',
    options: [
      'Documentation — a deliberate, recorded decision by someone with the authority to make it',
      'Whether the risk later turns out to cause an incident',
      'Whether a compensating control was also applied',
      'Whether the risk scored below a defined threshold',
    ],
    answer: 0,
    why: 'Accepting risk is legitimate and professional. Ignoring it is neither, and the only difference is that the acceptance was written down.',
  },
  {
    id: '04-1-b', lesson: '04-1',
    ask: 'What is residual risk?',
    options: [
      'What remains after your controls are in place',
      'Risk carried by third parties in your supply chain',
      'Risk that was accepted rather than mitigated',
      'The gap between your risk appetite and your budget',
    ],
    answer: 0,
    why: 'It is never zero. Being able to state it clearly is what separates a professional from someone promising safety they cannot deliver.',
  },
  {
    id: '04-2-a', lesson: '04-2',
    ask: 'Why is a hardware security key phishing-resistant when an authenticator app code is not?',
    options: [
      'The key verifies the real domain before responding, so a fake site gets nothing usable',
      'The key generates codes that expire in under one second',
      'The key requires a fingerprint as well as possession',
      'The code is transmitted over an encrypted channel',
    ],
    answer: 0,
    why: 'A convincing fake site can ask for a typed code and replay it immediately. FIDO2 and passkeys bind the credential to the origin, which breaks that structurally.',
  },
  {
    id: '04-2-b', lesson: '04-2',
    ask: 'What is the difference between OAuth 2.0 and OpenID Connect?',
    options: [
      'OAuth handles delegated permission; OIDC adds identity on top of it',
      'OAuth is for web apps; OIDC is for mobile apps',
      'OAuth is the newer replacement for OIDC',
      'OAuth encrypts tokens; OIDC signs them',
    ],
    answer: 0,
    why: 'OAuth answers "may this app act on my behalf?" OIDC answers "who is this user?" People mix these up constantly.',
  },
  {
    id: '04-3-a', lesson: '04-3',
    ask: 'Why is a fast hash wrong for storing passwords but right for verifying a download?',
    options: [
      'Speed helps integrity checks but helps attackers guess billions of passwords per second',
      'Fast hashes produce shorter outputs, which is fine for files but not passwords',
      'Fast hashes are not collision resistant, which only matters for passwords',
      'Password hashes must be reversible, and fast hashes are not',
    ],
    answer: 0,
    why: 'For passwords use a deliberately slow hash — Argon2, bcrypt or scrypt — with a unique salt per user.',
  },
  {
    id: '04-3-b', lesson: '04-3',
    ask: 'What is the single most important rule about cryptography in production?',
    options: [
      'Never write your own — use vetted libraries at a high level',
      'Always use the largest key size available',
      'Rotate every key at least once per month',
      'Prefer symmetric encryption over asymmetric wherever possible',
    ],
    answer: 0,
    why: 'Almost every catastrophic crypto failure came from someone assembling primitives themselves — reusing a nonce, choosing ECB, comparing secrets in non-constant time.',
  },
  {
    id: '04-4-a', lesson: '04-4',
    ask: 'What does zero trust actually replace?',
    options: [
      'Trust based on network location, with continuous per-request verification',
      'Passwords, with biometric authentication',
      'Firewalls, with endpoint detection',
      'On-premises infrastructure, with cloud services',
    ],
    answer: 0,
    why: 'Remote work, cloud and mobile destroyed the idea of an inside. Zero trust is an architecture and a discipline, not a product you can buy.',
  },
  {
    id: '04-4-b', lesson: '04-4',
    ask: 'What is the point of defence in depth?',
    options: [
      'Every control will eventually fail, so failure must be survivable',
      'Multiple products from different vendors reduce supplier risk',
      'It satisfies most compliance frameworks\' control requirements',
      'It spreads the security budget across more categories',
    ],
    answer: 0,
    why: 'Each independent layer buys time and generates evidence. The attacker has to beat all of them, not one.',
  },
  {
    id: '04-5-a', lesson: '04-5',
    ask: 'What do the letters in STRIDE stand for?',
    options: [
      'Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege',
      'Scope, Threat, Risk, Impact, Detection, Evidence',
      'Survey, Test, Report,Isolate, Defend, Escalate',
      'Static, Traffic, Runtime, Interface, Data, Endpoint',
    ],
    answer: 0,
    why: 'Six prompts to walk each element of a data flow diagram against, so you find threats systematically rather than by inspiration.',
  },
  {
    id: '04-5-b', lesson: '04-5',
    ask: 'Why can a scanner find a missing security header but never a flawed permission design?',
    options: [
      'Scanners find implementation bugs; design flaws require understanding intent',
      'Scanners only inspect HTTP responses, not application logic',
      'Permission designs are stored in databases scanners cannot read',
      'Scanners are only run after deployment, when the design is fixed',
    ],
    answer: 0,
    why: 'This is exactly why threat modelling exists, and why an hour at a whiteboard before any code is written is the cheapest security you will ever do.',
  },
  {
    id: '04-6-a', lesson: '04-6',
    ask: 'Why might a CVSS 6.5 deserve attention before a CVSS 9.8?',
    options: [
      'If the 6.5 is on the KEV list and internet-facing while the 9.8 is not reachable',
      'Because CVSS scores above 9 are usually inflated by vendors',
      'Because medium findings are cheaper to fix, so they clear the backlog faster',
      'Because CVSS v4 rescored most critical vulnerabilities downward',
    ],
    answer: 0,
    why: 'A base score is a generic measurement by someone who does not know your environment. Severity times exposure times value is the real queue.',
  },
  {
    id: '04-6-b', lesson: '04-6',
    ask: 'What does EPSS tell you that CVSS does not?',
    options: [
      'The probability that a vulnerability will actually be exploited soon',
      'How difficult the vulnerability is to patch',
      'Which vendors have released a fix',
      'How many systems in your estate are affected',
    ],
    answer: 0,
    why: 'CVSS says how bad it would be. EPSS says how likely it is to happen. KEV says it is already happening.',
  },
  {
    id: '04-7-a', lesson: '04-7',
    ask: 'Why does ransomware specifically require an immutable or offline backup copy?',
    options: [
      'Attackers deliberately destroy or encrypt reachable backups before triggering encryption',
      'Online backups are always stored unencrypted',
      'Immutable copies restore faster than ordinary ones',
      'Regulators require one offline copy for all personal data',
    ],
    answer: 0,
    why: 'Three online copies an administrator can delete are three copies the attacker can delete. That is what the extra 1 in 3-2-1-1-0 is for.',
  },
  {
    id: '04-7-b', lesson: '04-7',
    ask: 'What do RPO and RTO describe?',
    options: [
      'How much data you can afford to lose, and how long you can afford to be down',
      'Recovery priority order and recovery team ownership',
      'The retention period and the rotation schedule for backups',
      'Required patch outage and required testing outage windows',
    ],
    answer: 0,
    why: 'Both are business decisions, not technical ones, and they determine what you build and what it costs.',
  },
  {
    id: '04-8-a', lesson: '04-8',
    ask: 'How can an organisation be compliant but not secure?',
    options: [
      'Compliance is a floor written by committee that always lags the current threat',
      'Compliance only applies to documentation, never to technical controls',
      'Auditors are not permitted to test systems, only to read policies',
      'Compliance frameworks deliberately exclude technical requirements',
    ],
    answer: 0,
    why: 'The reverse also happens: a genuinely secure organisation can fail an audit for lacking evidence. You need both, and you should be honest about which you are doing.',
  },
  {
    id: '04-8-b', lesson: '04-8',
    ask: 'What makes security awareness training actually work?',
    options: [
      'Short, frequent, specific and blame-free, so people report mistakes early',
      'An annual video with a mandatory completion quiz',
      'Punitive consequences for failing simulated phishing tests',
      'Detailed technical explanations of each attack technique',
    ],
    answer: 0,
    why: 'Early reporting is worth more than any amount of quiz completion. Punishment teaches people to hide mistakes.',
  },

  // ---------- 05 Breaking and fixing web apps ----------
  {
    id: '05-1-a', lesson: '05-1',
    ask: 'Which category entered the OWASP Top 10 2025 at number three?',
    options: [
      'Software Supply Chain Failures',
      'Broken Access Control',
      'Server-Side Request Forgery',
      'Insecure Design',
    ],
    answer: 0,
    why: 'It replaced the narrower "vulnerable components" category, recognising that attacks moved to build systems, dependencies and the tools everyone trusts.',
  },
  {
    id: '05-1-b', lesson: '05-1',
    ask: 'What sits at A01 in the OWASP Top 10 2025?',
    options: ['Broken Access Control', 'Injection', 'Cryptographic Failures', 'Security Misconfiguration'],
    answer: 0,
    why: 'It stayed at number one. The most common serious web vulnerability is not clever — it is a page that forgets to check whether this user may see this thing.',
  },
  {
    id: '05-2-a', lesson: '05-2',
    ask: 'How do you test for broken access control most directly?',
    options: [
      'Do an action as user A, capture the request, and replay it with user B\'s session',
      'Scan the application with an automated vulnerability scanner',
      'Review the source code for missing input validation',
      'Check whether admin pages are linked from the navigation menu',
    ],
    answer: 0,
    why: 'Two accounts and a replayed request finds the most common serious web vulnerability there is.',
  },
  {
    id: '05-2-b', lesson: '05-2',
    ask: 'Why is hiding an admin link from the menu not access control?',
    options: [
      'The endpoint still exists and can be requested directly',
      'Menus are cached, so the link may reappear',
      'Search engines will index the admin page anyway',
      'Screen readers still announce hidden links',
    ],
    answer: 0,
    why: 'If security depends on the user not knowing a URL exists, there is no security. The fix is deny by default, enforced centrally.',
  },
  {
    id: '05-3-a', lesson: '05-3',
    ask: 'What single design principle prevents SQL, command and template injection at once?',
    options: [
      'Never mix instruction and data in the same string',
      'Always escape special characters before use',
      'Validate all input against a maximum length',
      'Run every interpreter with reduced privileges',
    ],
    answer: 0,
    why: 'Parameterised queries, argument arrays instead of shell strings, and templates that treat input strictly as values are all the same idea applied in three places.',
  },
  {
    id: '05-3-b', lesson: '05-3',
    ask: 'Why are allow-lists better than deny-lists for input validation?',
    options: [
      'You cannot enumerate every dangerous input, but you can enumerate every acceptable one',
      'Allow-lists are faster to evaluate at runtime',
      'Deny-lists cannot be expressed as regular expressions',
      'Allow-lists are required by the OWASP standard',
    ],
    answer: 0,
    why: 'That asymmetry is the whole design lesson. Encoding and context give attackers effectively unlimited variations of "bad".',
  },
  {
    id: '05-4-a', lesson: '05-4',
    ask: 'Why does an XSS vulnerability make your CSRF token protection irrelevant?',
    options: [
      'The injected script runs in your origin and can simply read the token',
      'CSRF tokens are stored in cookies that XSS deletes',
      'XSS disables the SameSite attribute on all cookies',
      'The browser stops sending tokens once a script error occurs',
    ],
    answer: 0,
    why: 'Fix XSS first. Anti-CSRF tokens assume the attacker cannot read the page, which XSS breaks completely.',
  },
  {
    id: '05-4-b', lesson: '05-4',
    ask: 'Which XSS variant is the most damaging and why?',
    options: [
      'Stored, because it is saved server-side and served to every later visitor',
      'Reflected, because it appears in the URL and is easy to distribute',
      'DOM-based, because the server never sees the payload',
      'They are equally severe in all circumstances',
    ],
    answer: 0,
    why: 'Reflected and DOM-based need a victim to follow a crafted link. Stored just waits for people to arrive.',
  },
  {
    id: '05-5-a', lesson: '05-5',
    ask: 'Why is SSRF far more dangerous in cloud than on a standalone server?',
    options: [
      'It can reach the instance metadata service, which hands out credentials',
      'Cloud networks have no internal firewalls',
      'Cloud providers disable outbound request filtering by default',
      'Cloud services always resolve internal hostnames publicly',
    ],
    answer: 0,
    why: 'Several very large cloud breaches happened exactly this way. Enforcing IMDSv2 is the specific mitigation.',
  },
  {
    id: '05-5-b', lesson: '05-5',
    ask: 'What is the correct fix for insecure deserialisation of untrusted data?',
    options: [
      'Do not deserialise untrusted data with a format that can carry code — use JSON with a schema',
      'Sign the serialised payload and verify the signature',
      'Deserialise inside a try/catch and discard malformed objects',
      'Limit the size of the serialised payload',
    ],
    answer: 0,
    why: 'Code can run during reconstruction, before any validation you wrote gets a chance. Signing helps only if the key never leaks; changing format removes the class.',
  },
  {
    id: '05-6-a', lesson: '05-6',
    ask: 'What is BOLA in API security?',
    options: [
      'Broken Object Level Authorisation — the API version of IDOR, and number one on the API Top 10',
      'A denial of service caused by deeply nested queries',
      'Binary object leakage in API responses',
      'A GraphQL-specific batching vulnerability',
    ],
    answer: 0,
    why: 'APIs expose object identifiers directly and at scale, which makes this both easier to find and easier to automate than in a web interface.',
  },
  {
    id: '05-6-b', lesson: '05-6',
    ask: 'Why does testing through the web interface miss most API vulnerabilities?',
    options: [
      'The interface only exercises the paths the developers intended',
      'Interfaces use a different authentication system than APIs',
      'Browsers block requests that would reveal API flaws',
      'API responses are encrypted separately from page traffic',
    ],
    answer: 0,
    why: 'Read the OpenAPI or GraphQL schema, enumerate endpoints, and try each with a low-privilege token. The interface is not a security control.',
  },
  {
    id: '05-7-a', lesson: '05-7',
    ask: 'What was the real lesson of Log4Shell?',
    options: [
      'You cannot patch what you cannot inventory',
      'Logging libraries should never be third-party',
      'Java is fundamentally unsuited to production use',
      'Critical vulnerabilities should be embargoed for longer',
    ],
    answer: 0,
    why: 'A library used almost everywhere, a feature nobody knew was there, and organisations unable to answer "are we affected?" — which is what SBOMs exist to fix.',
  },
  {
    id: '05-7-b', lesson: '05-7',
    ask: 'What is dependency confusion?',
    options: [
      'A public package shadowing a private internal package name',
      'Two libraries requiring incompatible versions of a third',
      'A lockfile that disagrees with the manifest',
      'Transitive dependencies pulled in more than once',
    ],
    answer: 0,
    why: 'The build resolves the public one because it looks newer or is checked first, and the attacker\'s code runs inside your pipeline.',
  },
  {
    id: '05-8-a', lesson: '05-8',
    ask: 'Why is an authorisation check that fails open worse than no check at all?',
    options: [
      'It grants access on error while looking correct to everyone reviewing it',
      'It logs errors that fill the disk and cause an outage',
      'It only fails during peak load, when attacks are most likely',
      'It cannot be detected by static analysis tools',
    ],
    answer: 0,
    why: 'This is the new A10, Mishandling of Exceptional Conditions. Ask what happens when the token service times out or the value is null.',
  },
  {
    id: '05-8-b', lesson: '05-8',
    ask: 'Which testing method finds business logic flaws that the others cannot?',
    options: [
      'Manual testing, because tools do not understand business rules',
      'SAST, because it reads the whole codebase',
      'DAST, because it attacks the running application',
      'SCA, because it inspects every dependency',
    ],
    answer: 0,
    why: 'Each method has a defined blind spot. Logic — "should this user be able to do this?" — needs a human who knows what the application is for.',
  },

  // ---------- 06 Attacking, with permission ----------
  {
    id: '06-1-a', lesson: '06-1',
    ask: 'During a test you find a serious vulnerability on a system that is not in scope. What do you do?',
    options: [
      'Stop, do not test it further, and report it to the client through the agreed channel',
      'Verify the impact quietly so the report is accurate',
      'Add it to the report without mentioning how you confirmed it',
      'Test it, since you are already authorised on the network',
    ],
    answer: 0,
    why: 'Scope is the boundary of your legal authorisation. Discovering something is not permission to test it.',
  },
  {
    id: '06-1-b', lesson: '06-1',
    ask: 'What does minimising impact look like when proving a vulnerability?',
    options: [
      'Read one record, not the whole table — evidence sufficient to convince and nothing more',
      'Test outside business hours regardless of the agreement',
      'Take a full database copy so the finding cannot be disputed',
      'Disable monitoring so the client\'s alerts are not flooded',
    ],
    answer: 0,
    why: 'The goal is proof, not exhaustion. Every step beyond proof adds risk with no additional value to the client.',
  },
  {
    id: '06-2-a', lesson: '06-2',
    ask: 'How can certificate transparency logs reveal internal-sounding hostnames?',
    options: [
      'Every issued certificate is published, including ones for internal-facing subdomains',
      'They record every DNS query made for a domain',
      'They index web server configuration files',
      'They mirror the contents of public WHOIS databases',
    ],
    answer: 0,
    why: 'Organisations issue certificates for staging, admin and internal services and forget that the act of issuing publishes the name.',
  },
  {
    id: '06-2-b', lesson: '06-2',
    ask: 'What is the difference between passive and active reconnaissance?',
    options: [
      'Passive never touches the target; active interacts with it and generates logs',
      'Passive is automated; active is done manually',
      'Passive is legal everywhere; active requires a licence',
      'Passive covers infrastructure; active covers people',
    ],
    answer: 0,
    why: 'Do passive work first and only go active once you are certain you are inside scope. Confusing them is how testers accidentally scan someone else\'s network.',
  },
  {
    id: '06-3-a', lesson: '06-3',
    ask: 'Why is a service version number often more valuable than knowing the port is open?',
    options: [
      'It maps directly to known vulnerabilities and specific abuse paths',
      'It reveals the operating system of the host',
      'It confirms the service is reachable from the internet',
      'It shows how long the service has been running',
    ],
    answer: 0,
    why: 'An open port is a starting point, not a finding. Ninety percent of successful tests come from thorough enumeration, not clever exploitation.',
  },
  {
    id: '06-3-b', lesson: '06-3',
    ask: 'Why can a routine scan be genuinely dangerous in some environments?',
    options: [
      'Fragile industrial and medical devices have been knocked offline by ordinary scans',
      'Scanning always triggers automatic legal action',
      'Scans corrupt the target\'s log files',
      'Modern firewalls retaliate by blocking the scanner permanently',
    ],
    answer: 0,
    why: 'Know your target, control your rate, and never assume a scan is harmless.',
  },
  {
    id: '06-4-a', lesson: '06-4',
    ask: 'Why is password spraying effective against a lockout policy?',
    options: [
      'It tries one password across many accounts, so no single account hits the threshold',
      'It resets the lockout counter between attempts',
      'It uses valid session tokens rather than passwords',
      'Lockout policies do not apply to authentication over Kerberos',
    ],
    answer: 0,
    why: 'It is a favourite in real intrusions precisely because naive lockout policies do not see it.',
  },
  {
    id: '06-4-b', lesson: '06-4',
    ask: 'Why read public exploit code before running it?',
    options: [
      'Plenty of published "exploits" are backdoored or destructive',
      'Exploit code must be recompiled for each target',
      'Reading it is required to obtain a CVE reference',
      'Most exploits do not work without modification',
    ],
    answer: 0,
    why: 'Running unread code from the internet against a client\'s network is how engagements become incidents.',
  },
  {
    id: '06-5-a', lesson: '06-5',
    ask: 'Why is a root-owned cron script that you can write to a critical finding?',
    options: [
      'The scheduler will execute your content as root at the next run',
      'Cron scripts are readable by every user on the system',
      'It reveals the root account\'s password hash',
      'It allows you to disable system logging',
    ],
    answer: 0,
    why: 'Configuration paths like this are faster, quieter and far more reliable than any kernel exploit.',
  },
  {
    id: '06-5-b', lesson: '06-5',
    ask: 'Why are kernel exploits a last resort in an authorised test?',
    options: [
      'They are version-specific and unstable, and a crash is an outage you caused',
      'They are explicitly illegal in most jurisdictions',
      'They leave permanent changes that cannot be reversed',
      'They only work on systems with no security patches at all',
    ],
    answer: 0,
    why: 'Prefer configuration paths, and if you must use a kernel exploit, get explicit agreement first.',
  },
  {
    id: '06-6-a', lesson: '06-6',
    ask: 'What is Kerberoasting?',
    options: [
      'Requesting service tickets as any authenticated user, then cracking them offline',
      'Forging a Kerberos ticket using the domain controller\'s key',
      'Replaying a captured ticket against a different service',
      'Downgrading Kerberos to NTLM to capture hashes',
    ],
    answer: 0,
    why: 'Service accounts frequently have weak, never-rotated passwords and excessive privileges, which makes this remarkably reliable.',
  },
  {
    id: '06-6-b', lesson: '06-6',
    ask: 'Why does pass-the-hash mean a strong password policy alone does not protect an account?',
    options: [
      'The hash authenticates without the password ever being known or cracked',
      'Strong passwords produce hashes that are easier to collide',
      'Password policies do not apply to service accounts',
      'The hash can be reversed to the original password',
    ],
    answer: 0,
    why: 'This is why credential hygiene, tiered administration and LAPS matter more than password complexity rules.',
  },
  {
    id: '06-7-a', lesson: '06-7',
    ask: 'Why can three medium-severity findings justify a critical rating together?',
    options: [
      'Chained, they produce impact none of them has alone — which is what an attacker will do',
      'Because severity scores are additive by definition',
      'Because three findings indicate systemic process failure',
      'Because CVSS requires escalation when findings share an asset',
    ],
    answer: 0,
    why: 'A good report shows the chain and rates the chain. Clients frequently deprioritise mediums that were three steps from catastrophe.',
  },
  {
    id: '06-7-b', lesson: '06-7',
    ask: 'What must you do with every persistence mechanism you set up during a test?',
    options: [
      'Document each one and remove them all, verifiably',
      'Leave them until the retest so you can re-enter quickly',
      'Remove them only if the client asks',
      'Transfer them to the client\'s administrators',
    ],
    answer: 0,
    why: 'Leftover access is a genuine liability for both sides. Keep a checklist as you go, because you will not remember at the end of a two-week engagement.',
  },
  {
    id: '06-8-a', lesson: '06-8',
    ask: 'Why is a purple team exercise often more valuable to a mature organisation than a traditional test?',
    options: [
      'It produces measurable detection improvement rather than a document that gets filed',
      'It costs less because both teams are internal',
      'It removes the need for scope agreements',
      'It covers more systems in the same amount of time',
    ],
    answer: 0,
    why: 'Run a technique, check detection, tune, run it again. The output is a better defence, not a better report.',
  },
  {
    id: '06-8-b', lesson: '06-8',
    ask: 'What makes a remediation recommendation actually useful?',
    options: [
      'It is specific enough for a developer to implement without further research',
      'It cites the relevant compliance requirement',
      'It lists every possible mitigating option',
      'It includes the CVSS vector string',
    ],
    answer: 0,
    why: '"Improve input validation" is not a fix. Reports that get acted on reduce the reader\'s work rather than adding to it.',
  },

  // ---------- 07 Defending and detecting ----------
  {
    id: '07-1-a', lesson: '07-1',
    ask: 'Why is a thirty-day log retention policy a serious problem?',
    options: [
      'Intrusions are often discovered months later, so you cannot investigate your own breach',
      'Most compliance frameworks require ninety days minimum',
      'Detection rules need historical data to run correctly',
      'Logs older than thirty days compress poorly',
    ],
    answer: 0,
    why: 'Balance cost against the practical minimum, and keep the highest-value sources — endpoint and identity — longest.',
  },
  {
    id: '07-1-b', lesson: '07-1',
    ask: 'Which two telemetry sources would catch the largest share of real intrusions?',
    options: [
      'Endpoint process creation and identity/authentication events',
      'Netflow and firewall deny logs',
      'Antivirus alerts and email gateway logs',
      'Web server access logs and DHCP leases',
    ],
    answer: 0,
    why: 'Together they cover the intrusion lifecycle from first foothold to final theft — which is why Sysmon and audit logging are such high-value settings.',
  },
  {
    id: '07-2-a', lesson: '07-2',
    ask: 'How can reducing the number of alerts improve security?',
    options: [
      'Alert fatigue trains analysts to close alerts without reading them',
      'Fewer alerts reduce SIEM licensing costs, freeing budget',
      'Fewer rules means less chance of a rule being misconfigured',
      'It shortens the time each alert spends in the queue',
    ],
    answer: 0,
    why: 'Fewer, better alerts genuinely beat more coverage on paper. Tuning is not a sign of weakness.',
  },
  {
    id: '07-2-b', lesson: '07-2',
    ask: 'What does enrichment add to a raw log event?',
    options: [
      'Context such as asset criticality, owner, geolocation and threat intel matches',
      'Cryptographic signatures proving the log was not altered',
      'Compression to reduce storage costs',
      'Translation into a vendor-neutral query language',
    ],
    answer: 0,
    why: 'An analyst who must open four other tools to understand an alert triages far fewer per hour, and quality drops with fatigue.',
  },
  {
    id: '07-3-a', lesson: '07-3',
    ask: 'What did MITRE ATT&CK v18 introduce?',
    options: [
      'Detection Strategies and Analytics, replacing the deprecated data source objects',
      'A merged matrix covering enterprise, mobile and ICS in one view',
      'Confidence scores for each documented technique',
      'Automatic mapping from CVEs to techniques',
    ],
    answer: 0,
    why: 'Released October 2025, it substantially restructured detection guidance — which means older coverage mappings need revisiting.',
  },
  {
    id: '07-3-b', lesson: '07-3',
    ask: 'Why is an untested detection rule not the same as detection coverage?',
    options: [
      'Until the technique is actually executed against it, you do not know it fires',
      'Untested rules are disabled by default in most SIEMs',
      'Rules expire if they have not matched anything recently',
      'Coverage requires two independent rules per technique',
    ],
    answer: 0,
    why: 'This is exactly why Atomic Red Team exists: run the technique safely and check whether the alert appears.',
  },
  {
    id: '07-4-a', lesson: '07-4',
    ask: 'According to the Pyramid of Pain, which indicator costs an attacker the most to change?',
    options: ['Their tactics and behaviours', 'A file hash', 'A domain name', 'An IP address'],
    answer: 0,
    why: 'Hashes are trivial to alter and addresses are cheap. Detections aimed at behaviour last across campaigns and tools.',
  },
  {
    id: '07-4-b', lesson: '07-4',
    ask: 'Which detection would survive an attacker recompiling their malware?',
    options: [
      'Office spawning a scripting engine that then makes an outbound connection',
      'A rule matching the sample\'s SHA-256 hash',
      'A rule matching the sample\'s filename',
      'A rule matching the command and control IP address',
    ],
    answer: 0,
    why: 'Behaviour-based logic catches an entire family of phishing chains regardless of the specific payload.',
  },
  {
    id: '07-5-a', lesson: '07-5',
    ask: 'Why is business email compromise often invisible to endpoint tooling?',
    options: [
      'Nothing is installed — the attacker uses stolen credentials through legitimate services',
      'Email clients do not generate endpoint telemetry',
      'EDR agents exclude mail processes by default',
      'The activity happens entirely inside encrypted TLS sessions',
    ],
    answer: 0,
    why: 'The evidence lives in identity and audit logs: impossible travel, new OAuth consent, mail forwarding rules, delegation changes.',
  },
  {
    id: '07-5-b', lesson: '07-5',
    ask: 'What does "living off the land" mean?',
    options: [
      'Attacking using legitimate tools already installed on the system',
      'Operating without any command and control infrastructure',
      'Persisting only in memory, never writing to disk',
      'Using only credentials harvested from the target environment',
    ],
    answer: 0,
    why: 'PowerShell, WMI, certutil, rundll32. The answer is to look at how legitimate tools are being used, not whether they are present.',
  },
  {
    id: '07-6-a', lesson: '07-6',
    ask: 'How can you detect command and control inside encrypted traffic without decrypting it?',
    options: [
      'Beaconing patterns — regular intervals and consistent payload sizes remain visible',
      'By reading the TLS certificate\'s subject field',
      'By inspecting the HTTP host header',
      'Encrypted traffic cannot be analysed without decryption',
    ],
    answer: 0,
    why: 'JA3 and JA4 fingerprints also identify the client software from the handshake alone, without touching the content.',
  },
  {
    id: '07-6-b', lesson: '07-6',
    ask: 'Which is a genuine blind spot of network monitoring?',
    options: [
      'Remote workers connecting directly to SaaS never cross your sensors',
      'It cannot see which hosts talked to each other',
      'It cannot record connection durations',
      'It only works on IPv4 traffic',
    ],
    answer: 0,
    why: 'Do not claim coverage you do not have. Cloud-to-cloud traffic is similarly invisible.',
  },
  {
    id: '07-7-a', lesson: '07-7',
    ask: 'Why do behavioural TTPs stay useful far longer than indicator lists?',
    options: [
      'Addresses and hashes are abandoned within days; changing how you operate is expensive',
      'TTPs are published under stricter quality control',
      'Indicator feeds are usually out of date when published',
      'SIEMs cannot store large indicator lists efficiently',
    ],
    answer: 0,
    why: 'Feeding enormous indicator lists into a SIEM produces noise and a false sense of coverage.',
  },
  {
    id: '07-7-b', lesson: '07-7',
    ask: 'What is the honest position on attribution?',
    options: [
      'It is difficult, politically loaded, and frequently wrong in early reporting',
      'It is reliable once malware samples are matched to a known family',
      'It should always be included in an incident report',
      'It is a solved problem given sufficient telemetry',
    ],
    answer: 0,
    why: 'Separate what was observed from what was inferred, and label your own confidence honestly.',
  },
  {
    id: '07-8-a', lesson: '07-8',
    ask: 'What should every threat hunt end with?',
    options: [
      'Either a finding or a new detection rule',
      'A report circulated to leadership',
      'An updated asset inventory',
      'A tuned version of an existing alert',
    ],
    answer: 0,
    why: 'Otherwise the same hunt gets repeated forever. Closing the loop is what separates a maturing SOC from a treadmill.',
  },
  {
    id: '07-8-b', lesson: '07-8',
    ask: 'What is the key discipline in alert triage?',
    options: [
      'Deliberately looking for evidence that would disconfirm your first conclusion',
      'Closing low-severity alerts quickly to protect queue time',
      'Escalating anything you cannot resolve within ten minutes',
      'Starting with the newest alerts, since they are most actionable',
    ],
    answer: 0,
    why: 'Analysts under time pressure find the story that fits and stop. Asking "what would I see if this were benign?" catches both false positives and near-missed intrusions.',
  },
];
