import type { Stage } from './types';

export const s00: Stage = {
  number: '00',
  title: 'Start here, stay legal',
  subtitle: 'What security actually is, and how to practise without hurting anyone',
  level: 'BEGINNER',
  tags: ['FOUNDATIONS'],
  weeks: 1,
  hours: 20,
  hue: 210,
  plain: 'Before touching a single tool, you learn what the job really is: protecting things people care about, and doing it with permission.',
  outcome: 'You can describe any security situation using five words — asset, threat, weakness, control, evidence — and you know exactly where the legal line is.',
  project: 'Write your own rules of engagement, draw your first threat model on paper, and build a practice lab that cannot touch anything real.',
  checkpoint: 'You can explain to a non-technical friend what you are allowed to do, what you are not, and why your lab is safe.',
  resources: [
    { label: 'NIST Cybersecurity Framework 2.0', href: 'https://www.nist.gov/cyberframework' },
    { label: 'CISA Cyber Career Pathways', href: 'https://niccs.cisa.gov/tools/cyber-career-pathways-tool' },
    { label: 'TryHackMe (free beginner rooms)', href: 'https://tryhackme.com/' },
  ],
  lessons: [
    {
      id: '00-1',
      title: 'What cybersecurity actually is',
      mins: 6,
      oneLine: 'Cybersecurity is the job of keeping valuable things safe when those things live on computers.',
      like: 'It is like being the person responsible for a building: you think about the doors, the locks, the guards, the cameras, the fire exits — and the people who might walk in pretending they belong.',
      body: [
        'Most people think security means hacking. It does not. Security is risk management. You have things that matter — money, private messages, medical records, the ability to turn the lights on — and there are people who want to steal them, break them, or lock them away from you. Your job is to make that hard, notice when it happens, and recover fast when it does.',
        'Notice the three parts: make it hard, notice it, recover. Beginners obsess over the first one. Professionals know all three matter, and that the second is where most organisations fail. Attackers are often inside a network for weeks before anyone spots them.',
        'You will never make anything perfectly safe. That is not a failure, it is the actual nature of the work. A bank vault can be drilled. A password can be guessed. The real question is never "is this secure?" — it is "secure enough against who, for how long, and what happens when it fails?"',
        'So every decision in this field is a trade. More security usually means more cost, more friction, more annoyed users. Someone who bolts on every control they read about is not good at security. Someone who can explain which risks they chose to accept, and why, is.',
      ],
      words: [
        { term: 'Risk', means: 'How bad it would be if something went wrong, multiplied by how likely it is.' },
        { term: 'Threat', means: 'Someone or something that could cause harm — a criminal, a careless employee, a flood.' },
        { term: 'Control', means: 'Anything you put in place to reduce risk. A password rule is a control. So is a locked door.' },
        { term: 'Breach', means: 'When someone reaches data they were never supposed to reach.' },
      ],
      why: 'If you skip this idea you will spend years collecting tools without ever being able to answer the only question that matters in a job interview or a boardroom: "why this, and not something else?"',
      doThis: 'Pick one thing you own that lives on a computer — your email account. Write down: what would someone gain by taking it? Who might want it? What is currently stopping them? What would you do in the first hour if it happened?',
      check: 'Can you name something in your own life that is deliberately less secure than it could be, and explain why that is a reasonable choice?',
    },
    {
      id: '00-2',
      title: 'The three promises: CIA',
      mins: 6,
      oneLine: 'Every security control on earth exists to protect one of three promises: keep it secret, keep it correct, keep it available.',
      like: 'Think of your bank balance. Nobody else should see it (secret). The number must be right (correct). And you must be able to check it when you need to (available).',
      body: [
        'The industry calls these Confidentiality, Integrity and Availability — the CIA triad. Ignore the fancy words for a second and just remember: secret, correct, reachable.',
        'Confidentiality means only the right people can see it. Encryption, passwords and permissions all serve this promise. When someone leaks a customer database, confidentiality broke.',
        'Integrity means the data is what it should be and nobody changed it behind your back. Digital signatures and checksums serve this. When an attacker quietly edits a payment amount, integrity broke — and this is often worse than theft, because you may never notice.',
        'Availability means you can actually use the thing. Backups, redundancy and capacity planning serve this. Ransomware is mostly an availability attack: your files are still there, still secret, but you cannot open them.',
        'Two more get added in serious work: authenticity (are you really who you claim to be?) and non-repudiation (can you later deny you did it?). These matter enormously the moment money or law is involved.',
      ],
      words: [
        { term: 'Confidentiality', means: 'Only the right eyes see it.' },
        { term: 'Integrity', means: 'Nobody changed it without permission or without leaving a trace.' },
        { term: 'Availability', means: 'You can get to it when you need it.' },
        { term: 'Non-repudiation', means: 'Proof strong enough that the person cannot credibly say "that was not me".' },
      ],
      why: 'When you investigate an incident, the first useful question is "which promise broke?" It instantly narrows down what happened and what to do next.',
      doThis: 'Take three recent news stories about hacks. For each one, write down which of the three promises broke first. You will find integrity attacks are the least reported and the most dangerous.',
      check: 'Ransomware encrypts a hospital’s files. Which promises broke, and in what order?',
    },
    {
      id: '00-3',
      title: 'The five words that explain everything',
      mins: 7,
      oneLine: 'Asset, threat, vulnerability, control, evidence — string these together and you can describe any security problem in the world.',
      like: 'A house (asset), a burglar (threat), an unlocked window (vulnerability), a lock (control), and the CCTV footage (evidence).',
      body: [
        'An asset is the thing worth protecting. It might be data, a machine, a service, a reputation, or the ability to keep a factory running. If you cannot name the asset, you are not doing security — you are fiddling with settings.',
        'A threat is who or what could harm it. Be specific. "Hackers" is useless. "A financially motivated group who encrypt files and demand payment" is something you can plan against.',
        'A vulnerability is the weakness they would use. Old software, a reused password, an employee who has never been shown what a phishing email looks like. Note: a vulnerability with no matching threat is often not urgent, and a threat with no matching vulnerability cannot land.',
        'A control is what you do about it. Controls come in three flavours worth knowing: preventive (stop it happening), detective (notice it happening), corrective (fix it afterwards). A good design has all three, because prevention always eventually fails.',
        'Evidence is proof — logs, alerts, records — that the control works and that you can reconstruct what happened. Security without evidence is just belief. In a real investigation, or an audit, or a court case, belief is worthless.',
      ],
      words: [
        { term: 'Asset', means: 'The thing you care about protecting.' },
        { term: 'Vulnerability', means: 'A weakness that could be used against you.' },
        { term: 'Exploit', means: 'The actual technique or code that takes advantage of a vulnerability.' },
        { term: 'Attack surface', means: 'Every possible way in. Fewer doors means less to defend.' },
      ],
      why: 'Every framework you will ever meet — NIST, ISO, ATT&CK — is a more detailed version of these five words. Learn the skeleton now and the frameworks become easy.',
      doThis: 'Write these five words down the side of a page. Fill them in for your phone. Then fill them in for your home Wi-Fi router. Notice how the answers differ.',
      check: 'Give an example of a vulnerability you would reasonably choose not to fix. What makes that a defensible decision?',
    },
    {
      id: '00-4',
      title: 'Permission, law and the line you never cross',
      mins: 8,
      oneLine: 'The only thing separating a security professional from a criminal is written permission.',
      like: 'A locksmith and a burglar use the same skills and the same tools. One of them was invited.',
      body: [
        'This is the most important lesson in the entire course, and it is the one people skip. In most countries, accessing a computer system without authorisation is a crime, even if you cause no damage, even if you were only curious, even if you meant to help. Good intent is often not a defence.',
        'The rule is simple: you may only test systems you own, systems you have explicit written permission to test, or systems deliberately built for practice. There is no fourth category. "It was publicly reachable" is not permission. "I only ran a scan" is not harmless. Scanning a stranger’s server has ended careers before they started.',
        'Written permission has a name: rules of engagement, or scope. A real one says exactly which systems, which techniques, which hours, who to call when something breaks, and what you must never touch. If you cannot point to that document, stop.',
        'Legal practice grounds exist and they are excellent. TryHackMe and Hack The Box for guided labs. PortSwigger Web Security Academy for web flaws. OverTheWire and pwn.college for systems. Your own virtual machines for anything else. That is more practice than you can finish in a decade.',
        'One more: responsible disclosure. If you accidentally find a real flaw in a real system, do not exploit it, do not post it publicly, and do not demand money. Look for a security.txt file or a bug bounty page, report it quietly, and give them time to fix it.',
      ],
      words: [
        { term: 'Rules of engagement (RoE)', means: 'The written agreement saying exactly what you are allowed to do.' },
        { term: 'Scope', means: 'The list of systems you may touch. Everything else is off-limits, full stop.' },
        { term: 'Authorised', means: 'Someone with actual authority said yes, in writing, before you started.' },
        { term: 'Responsible disclosure', means: 'Telling the owner privately and giving them time to fix it before anyone else knows.' },
      ],
      why: 'Nothing else you learn matters if you get arrested, expelled, or permanently unemployable in your first year. This industry runs on trust, and trust is a one-time asset.',
      doThis: 'Write a one-page rules-of-engagement document for your own home lab. List the machines in scope, the ones out of scope (your router, your family’s devices, anything cloud), and one line: "I will not test anything I do not own."',
      check: 'A friend asks you to check whether their company website is vulnerable. What do you need before you touch it, and who actually has the authority to give it?',
    },
    {
      id: '00-5',
      title: 'Build a lab that cannot hurt anyone',
      mins: 8,
      oneLine: 'A lab is a set of fake computers living inside your real computer, sealed in a box so mistakes stay inside.',
      like: 'A flight simulator. You can crash it as many times as you like and nobody dies.',
      body: [
        'A virtual machine (VM) is a whole computer pretending to exist inside your computer. It has its own disk, its own memory, its own network card — all software. If you break it, you delete it and make another one in ten minutes.',
        'Install a hypervisor first: VirtualBox is free everywhere, VMware Workstation is free for personal use, and on Windows, Hyper-V is already built in. On an Apple Silicon Mac, UTM works well. Any of them is fine. Do not spend a week choosing.',
        'Now the safety part. Set your lab network to "host-only" or "internal" — the fake machines can then talk to each other but not to your real network or the internet. This one setting is the difference between a lab and an accident. When you need internet to install packages, switch it on briefly, then switch it back.',
        'Take a snapshot before you break anything. A snapshot is a saved moment you can jump back to. This turns "I destroyed my machine" from a lost evening into a five-second undo, and it is the single biggest reason beginners give up less often.',
        'A good starter lab: one Kali or Ubuntu machine to work from, one deliberately vulnerable target such as Metasploitable or a DVWA container, and later a small Windows machine to learn the other half of the world. Two or three VMs is genuinely enough for your first year.',
      ],
      words: [
        { term: 'Virtual machine (VM)', means: 'A software computer running inside your real one.' },
        { term: 'Hypervisor', means: 'The program that runs virtual machines.' },
        { term: 'Snapshot', means: 'A saved state you can instantly return to.' },
        { term: 'Host-only network', means: 'A sealed network where lab machines talk only to each other.' },
      ],
      why: 'You cannot learn this field by reading. You learn it by breaking things — and you need somewhere breaking things is free.',
      doThis: 'Install VirtualBox. Create one Ubuntu VM. Set its network adapter to host-only. Take a snapshot and name it "clean". You now have a lab.',
      check: 'Why is host-only networking safer than bridged networking for a machine you are about to attack?',
    },
    {
      id: '00-6',
      title: 'How to learn this without drowning',
      mins: 7,
      oneLine: 'Cybersecurity is too big to finish, so you learn in loops: small topic, hands on it, write it down, come back later.',
      like: 'Learning a language. Nobody memorises the dictionary. You learn a few words, use them badly, get corrected, and repeat until you are fluent.',
      body: [
        'The field has hundreds of specialities. Nobody knows all of it. Anyone who claims to is selling something. Your goal is broad foundations plus one deep speciality — a T-shape. This course is built that way: stages 00 to 04 are the broad bar, and everything after is where you choose depth.',
        'Use spaced repetition. Read a thing today, try it tomorrow, explain it to someone in a week, use it in a project in a month. Information you retrieve from memory sticks; information you re-read does not. Highlighting a textbook feels productive and teaches you almost nothing.',
        'Write everything down in your own words. Not copy-paste — your own words, including the bits you did not understand. A notes system becomes your real qualification. In five years you will search your own notes more often than the internet.',
        'Learn by teaching. When you can explain DNS to someone who has never heard of it, without using the word "DNS", you understand DNS. Until then you have memorised a description.',
        'Finally: stop measuring progress in courses watched. Measure it in things built and things broken. One working home lab beats twenty finished video series.',
      ],
      words: [
        { term: 'T-shaped skills', means: 'Broad knowledge across the field, deep expertise in one part.' },
        { term: 'Spaced repetition', means: 'Reviewing something at growing intervals so it sticks permanently.' },
        { term: 'Active recall', means: 'Testing yourself from memory instead of re-reading.' },
      ],
      why: 'Burnout and tutorial-hell are the two biggest reasons people leave this field before their first job. Both are learning-method problems, not intelligence problems.',
      doThis: 'Start a notes folder today. Make one note per lesson in this app, in your own words, maximum ten lines. Never copy a definition without rewriting it.',
      check: 'Explain what a vulnerability is to an imaginary ten-year-old, without using the words vulnerability, exploit, or hacker.',
    },
    {
      id: '00-7',
      title: 'The jobs: what the roles actually do',
      mins: 7,
      oneLine: 'Security is not one job — it is roughly seven families of job, and they want very different personalities.',
      like: 'Medicine is not one job either. Surgeons, epidemiologists, paramedics and hospital administrators all work on health, and would be miserable in each other’s roles.',
      body: [
        'Blue team defends. SOC analysts triage alerts and decide what is real; detection engineers write the rules that generate those alerts. Good fit if you like patterns, evidence and fast decisions under pressure.',
        'Red team attacks with permission. Penetration testers find and prove weaknesses; red teamers simulate a full adversary over weeks. Good fit if you like creative problem-solving and writing clearly, because the report is the actual deliverable.',
        'Application security sits with developers, finds flaws in code and design, and helps fix them at the source. Cloud security does the same for cloud platforms and pipelines. Both suit people who like building as much as breaking.',
        'DFIR — digital forensics and incident response — reconstructs what happened after a compromise. Malware analysts take hostile software apart. This is the detective work. It suits patient, methodical people who like puzzles with real stakes.',
        'GRC — governance, risk and compliance — connects technical reality to business and legal decisions. It is unfairly dismissed as paperwork; done well it is the role with the most actual influence. And vulnerability research is the frontier: finding brand-new flaws nobody knew existed.',
        'You do not have to choose today. You should, however, notice which of those paragraphs made you sit up.',
      ],
      words: [
        { term: 'Blue team', means: 'The defenders.' },
        { term: 'Red team', means: 'The authorised attackers.' },
        { term: 'Purple team', means: 'Both working together so defence actually improves.' },
        { term: 'SOC', means: 'Security Operations Centre — the team watching the alerts.' },
      ],
      why: 'Studying with a role in mind turns a vague pile of topics into a path, and makes it obvious which stages you need first.',
      doThis: 'Read three real job adverts for the role that interested you most. Write down every requirement you do not understand. That list is your personal syllabus.',
      check: 'Which two roles in this list would suit you worst, and honestly why?',
    },
    {
      id: '00-8',
      title: 'Frameworks: the shared maps',
      mins: 7,
      oneLine: 'Frameworks are agreed maps of the field, so thousands of people can describe the same problem the same way.',
      like: 'Road signs. They do not tell you where to go, but everyone reading them means the same thing, which is the entire point.',
      body: [
        'NIST Cybersecurity Framework 2.0 is the big one for organising a whole programme. It has six functions: Govern, Identify, Protect, Detect, Respond, Recover. Learn those six words. They are the lifecycle of everything: decide what matters, know what you have, defend it, notice trouble, act, get back up.',
        'MITRE ATT&CK is a catalogue of what attackers actually do, observed in the real world, organised into tactics (their goal) and techniques (how they achieve it). Defenders use it to find blind spots: can we detect this technique? And this one? Version 18, released in late 2025, added explicit detection strategies and analytics.',
        'OWASP Top 10 is the awareness list for web application risks. The 2025 edition put Broken Access Control first again, promoted Security Misconfiguration to second, and added Software Supply Chain Failures as a brand-new number three — a direct reflection of attacks moving to the tools and dependencies everyone trusts.',
        'The NICE Framework maps careers to the actual tasks, knowledge and skills each role needs, which makes it a surprisingly good study planner. And CVSS gives every known vulnerability a severity score, so teams can argue about priority with numbers rather than volume.',
        'Do not memorise frameworks. Learn what each one is for, and know where to look it up. That is exactly how professionals use them.',
      ],
      words: [
        { term: 'NIST CSF 2.0', means: 'Six-function model for running security: Govern, Identify, Protect, Detect, Respond, Recover.' },
        { term: 'MITRE ATT&CK', means: 'A public catalogue of real attacker behaviour.' },
        { term: 'CVE', means: 'A unique ID for one specific publicly known vulnerability.' },
        { term: 'CVSS', means: 'A 0–10 score describing how severe a vulnerability is.' },
      ],
      why: 'Frameworks are the shared vocabulary of the industry. Using them makes you instantly legible to other professionals; ignoring them makes your work hard to trust.',
      doThis: 'Open MITRE ATT&CK and pick any one technique. Read it fully: what it is, who used it, how to detect it. Ten minutes with one technique teaches more than an hour scrolling the whole matrix.',
      check: 'Name the six functions of NIST CSF 2.0 from memory, in order, and say what each one means in one sentence.',
    },
  ],
};
