import type { Stage } from './types';

export const s01: Stage = {
  number: '01',
  title: 'How computers really work',
  subtitle: 'Files, processes, memory, Linux and Windows: the ground everything stands on',
  level: 'BEGINNER',
  tags: ['FOUNDATIONS', 'BUILD'],
  weeks: 4,
  hours: 55,
  hue: 195,
  plain: 'You cannot defend or attack a machine you do not understand. This stage opens the box and shows you what is inside.',
  outcome: 'You can follow a program from a file on disk, to a running process, to the memory it uses, and inspect all three from a command line.',
  project: 'Build a Linux and a Windows lab machine, lock down their user accounts, and write a baseline report describing what "normal" looks like on each.',
  checkpoint: 'You can find out what is running, who started it, what it is touching, and where it wrote a log about doing so.',
  resources: [
    { label: 'OverTheWire Bandit (free shell practice)', href: 'https://overthewire.org/wargames/bandit/' },
    { label: 'Linux Journey', href: 'https://linuxjourney.com/' },
    { label: 'Microsoft PowerShell training', href: 'https://learn.microsoft.com/en-us/training/powershell/' },
  ],
  lessons: [
    {
      id: '01-1',
      title: 'Everything is numbers',
      mins: 6,
      oneLine: 'Every photo, password and program on your computer is, underneath, just a very long list of numbers.',
      like: 'Like Morse code. Dots and dashes carry any message you want, as long as everyone agrees what the pattern means.',
      body: [
        'Computers only store two states: on and off, written as 1 and 0. One of those is a bit. Eight bits together make a byte, which can hold 256 different values. That is the entire alphabet the machine has.',
        'Meaning comes from agreement. The number 65 means the letter "A" only because a standard called ASCII says so. Change the agreement: read those same bytes as a picture instead of text, and you get nonsense, or sometimes something interesting. A huge amount of security work is exactly this: making a program read bytes as the wrong kind of thing.',
        'Hexadecimal (hex) is just a shorter way to write those numbers, using 0-9 and then a-f. One hex digit covers four bits, so one byte is always exactly two hex characters. You will see hex everywhere: in memory dumps, file signatures, and hashes, so it is worth ten minutes of practice.',
        'Encoding is not encryption. Base64 turns binary into safe-to-send text; anyone can reverse it instantly. It hides nothing. Attackers use it constantly to slip past naive filters, and beginners constantly mistake it for a secret.',
      ],
      words: [
        { term: 'Bit', means: 'A single 1 or 0.' },
        { term: 'Byte', means: 'Eight bits: one small unit of data.' },
        { term: 'Hex', means: 'Base-16 shorthand for writing bytes, using 0-9 and a-f.' },
        { term: 'Encoding', means: 'Rewriting data in another format. Reversible by anyone. Not security.' },
      ],
      why: 'File formats, network packets, memory bugs and malware analysis all come down to reading bytes and knowing what they were supposed to mean.',
      doThis: 'Take the word "hello", find its bytes in hex, then its Base64 form. Then decode a Base64 string someone else made. Notice how effortless the reversal is.',
      check: 'Why is Base64 not a way to protect a password?',
    },
    {
      id: '01-2',
      title: 'The CPU, memory and processes',
      mins: 8,
      oneLine: 'A program is a file that does nothing; a process is that file loaded into memory and actually running.',
      like: 'A recipe versus a chef actually cooking. Same instructions, but only one of them is using the kitchen, the ingredients and the heat.',
      body: [
        'The CPU does one thing: fetch an instruction, do it, repeat, billions of times a second. RAM (memory) is the fast workspace where the current work lives. Disk is the slow, permanent shelf. When you run a program, the operating system copies it from the shelf into the workspace and points the CPU at it.',
        'Each running program gets its own private memory space, so one process cannot casually read another’s data. This isolation is a security boundary, and a huge share of serious attacks are about crossing it.',
        'Inside that space, memory is organised into regions. The stack holds function calls and local variables and grows in a strict order. The heap holds bigger, longer-lived data the program asks for as it goes. Knowing which is which is the entire foundation of memory-corruption bugs later in the course.',
        'A thread is a single line of execution; a process can have many, sharing the same memory. This is why threading bugs cause security problems: two threads touching the same data at the wrong moment produces states the developer never imagined.',
        'The operating system kernel is the referee. It owns the hardware and decides who gets what. Code running in kernel mode can do anything; your programs run in user mode and must politely ask. "Privilege escalation" means an attacker moving from asking politely to not having to ask.',
      ],
      words: [
        { term: 'Process', means: 'A running program, with its own memory.' },
        { term: 'Thread', means: 'One line of execution inside a process.' },
        { term: 'Kernel', means: 'The core of the operating system that controls the hardware.' },
        { term: 'User mode / kernel mode', means: 'Restricted mode for normal programs, unrestricted mode for the kernel.' },
      ],
      why: 'Detection, forensics and exploitation all happen at the process level. "Which process did this, started by whom, touching what?" is the core question of the job.',
      doThis: 'Open your task manager or run "ps aux" on Linux. Pick a process you do not recognise, look up what it is, and find out which program started it.',
      check: 'Why does the operating system keep processes in separate memory spaces, and what would go wrong if it did not?',
    },
    {
      id: '01-3',
      title: 'Files, filesystems and permissions',
      mins: 8,
      oneLine: 'A filesystem is a filing cabinet with labels saying who is allowed to open each drawer.',
      like: 'An office. Everyone has a key that opens some doors and not others, and the cleaner has a master key that should be used carefully.',
      body: [
        'On Linux, everything is a file: documents, devices, even some network connections. Each file has an owner, a group, and permission bits: read, write, execute, for owner, group and everyone else. That is what "chmod 755" means; it is three digits for three audiences.',
        'The execute bit on a directory does something surprising: it means "you may enter", not "you may run". Misunderstanding this causes a great many misconfigurations you will later find as a tester.',
        'Two special bits matter enormously in security. SetUID makes a program run as its owner rather than as you, which is how a normal user can change their own password. Any SetUID program owned by root is a potential path to full control if it can be tricked, so finding them is a standard step in privilege escalation.',
        'Windows uses a different model: access control lists (ACLs). Instead of three audiences, each file has a list of entries saying which users and groups get which specific rights. It is more flexible and much easier to get subtly wrong.',
        'Files also leave traces. Timestamps record when a file was created, modified and last accessed. Deleted files often still exist on disk until overwritten. Both facts are the foundation of digital forensics.',
      ],
      words: [
        { term: 'Permissions', means: 'Rules saying who may read, change or run a file.' },
        { term: 'SetUID', means: 'A flag that makes a program run with its owner’s power, not yours.' },
        { term: 'ACL', means: 'Access Control List: a detailed per-user list of rights on Windows.' },
        { term: 'Root / Administrator', means: 'The all-powerful account. Treat it like a loaded tool.' },
      ],
      why: 'Wrong permissions are one of the most common ways attackers move from a small foothold to complete control of a machine.',
      doThis: 'In your Linux VM, run "find / -perm -4000 -type f 2>/dev/null" to list SetUID programs. Pick one and read what it is for.',
      check: 'Why is a writable file owned by root more dangerous than a readable one?',
    },
    {
      id: '01-4',
      title: 'The Linux command line',
      mins: 9,
      oneLine: 'The shell is a text conversation with your computer, and it is faster and more precise than any clicking.',
      like: 'Ordering at a counter instead of pointing at pictures. Slower to learn, dramatically faster once you know the words.',
      body: [
        'Start with ten commands and you can survive anywhere: ls (list), cd (move), pwd (where am I), cat (show a file), less (page through), grep (search inside), find (search for), cp, mv, rm (copy, move, delete). Everything else is built on these.',
        'The real power is the pipe: the "|" character takes the output of one command and feeds it into the next. "cat auth.log | grep Failed | wc -l" reads a log, keeps only failed logins, and counts them. That is a security investigation in one line, and this idea never stops being useful.',
        'Learn how software gets installed: apt on Debian and Ubuntu, dnf on Fedora, pacman on Arch. Learn how background services are managed with systemctl: start, stop, status, enable. Attackers install services to survive reboots, so knowing what should be running is how you spot what should not be.',
        'Logs live in /var/log. auth.log or secure records logins and sudo use. syslog records general system events. journalctl reads the systemd journal. When something happens on a Linux box, these files are the first place you look.',
        'Two habits will save you repeatedly: read the manual with "man command", and never run a command you found online without understanding what it does. Especially anything with rm, dd, or a pipe into a shell.',
      ],
      words: [
        { term: 'Shell', means: 'The program that reads your typed commands.' },
        { term: 'Pipe (|)', means: 'Sends one command’s output into the next command.' },
        { term: 'sudo', means: 'Run this one command with administrator power.' },
        { term: 'Daemon / service', means: 'A program running quietly in the background.' },
      ],
      why: 'Almost every server on the internet is Linux. Almost every security tool assumes you can drive a shell. This is the single highest-value practical skill in the early stages.',
      doThis: 'Play OverTheWire Bandit levels 0 to 10. It is free, legal, and teaches the shell through puzzles rather than lectures.',
      check: 'Write a one-line command that finds every line containing the word "error" in a log file and counts how many there are.',
    },
    {
      id: '01-5',
      title: 'Windows internals and PowerShell',
      mins: 9,
      oneLine: 'Most companies run Windows, so most real attacks happen on Windows, and it works very differently to Linux.',
      like: 'Driving in another country. Same skill, opposite side of the road, different signs, and confidence from home will get you into trouble.',
      body: [
        'The registry is a giant settings database. It matters to security because programs use it to start automatically at boot: the Run keys are one of the most common places malware hides its persistence. Knowing the usual autostart locations is basic defensive literacy.',
        'Windows security revolves around identity. Every user and group has a SID (a unique ID). When you log in, you receive an access token carrying your privileges, and that token is what gets checked. Attackers steal or duplicate tokens to become someone else without ever knowing a password.',
        'Active Directory is the central directory service that runs most corporate networks: users, computers, groups, and the policies applied to them. Kerberos handles the authentication. AD is so central that attacking it is practically its own profession, and stage 06 covers it properly.',
        'PowerShell is the command line, and its trick is that it passes objects rather than text. "Get-Process | Where-Object CPU -gt 100" filters on a real property, not on string matching. It is the best Windows administration tool and, for exactly that reason, also a favourite attacker tool, which is why PowerShell logging matters so much for defence.',
        'Windows logging is rich if you know the event IDs. 4624 is a successful logon, 4625 a failed one, 4688 a new process. Those three alone will carry you through your first hundred investigations.',
      ],
      words: [
        { term: 'Registry', means: 'Windows’ central settings database.' },
        { term: 'SID', means: 'A unique identifier for a user or group.' },
        { term: 'Access token', means: 'The badge Windows checks to decide what you can do.' },
        { term: 'Active Directory (AD)', means: 'The central system managing users and computers in a company network.' },
      ],
      why: 'If you only learn Linux, you are prepared for servers but not for the environments where most breaches actually begin: corporate Windows desktops and Active Directory.',
      doThis: 'On a Windows machine, run "Get-Process | Sort-Object CPU -Descending | Select-Object -First 5". Then open Event Viewer and find a 4624 logon event.',
      check: 'What is the practical difference between PowerShell passing objects and Bash passing text?',
    },
    {
      id: '01-6',
      title: 'Virtual machines and containers',
      mins: 7,
      oneLine: 'Both give you isolated environments: a VM fakes a whole computer, a container only fakes a private room in one.',
      like: 'A VM is a separate house. A container is a locked apartment in a shared building: cheaper and faster, but you share the foundations.',
      body: [
        'A virtual machine includes its own kernel and its own operating system. That makes it heavy: gigabytes, and tens of seconds to boot, but the isolation is strong, because the hypervisor sits between it and the hardware.',
        'A container shares the host’s kernel and isolates only the process view, filesystem and network. That makes it light: megabytes, and milliseconds to start, but the isolation is weaker. If you escape a container, the host kernel is right there.',
        'This trade-off is a security decision, not just a performance one. Running untrusted code? Use a VM. Running your own microservices at scale? Containers are fine, but treat the host kernel as the shared risk it is.',
        'Docker is the common container tool. An image is the frozen template; a container is a running copy. Images are built in layers from a Dockerfile, and: importantly: a secret you delete in a later layer is still sitting in the earlier one, which is a classic way credentials leak.',
        'The dangerous defaults are worth memorising now: running a container as root, mounting the Docker socket inside a container, and using --privileged. Each of those effectively hands over the host.',
      ],
      words: [
        { term: 'Hypervisor', means: 'Software that runs virtual machines.' },
        { term: 'Container', means: 'An isolated process bundle sharing the host kernel.' },
        { term: 'Image', means: 'The frozen template a container is created from.' },
        { term: 'Container escape', means: 'Breaking out of a container onto the host machine.' },
      ],
      why: 'Nearly all modern software ships in containers, so nearly all modern infrastructure security involves understanding what containers do and do not isolate.',
      doThis: 'Run "docker run -it --rm ubuntu bash". Look around inside. Note that you are root: inside the container. Then exit and think about what that root means on the host.',
      check: 'Why would you choose a VM over a container to analyse a suspicious file?',
    },
    {
      id: '01-7',
      title: 'From source code to running program',
      mins: 8,
      oneLine: 'Code you write is text; the machine needs numbers, and the journey between the two is where many bugs are born.',
      like: 'Translating a book. The compiler is the translator, and the translation decides how the story actually reads.',
      body: [
        'Compiled languages like C and Go turn source into machine code ahead of time. The compiler checks and converts, the linker joins your code to libraries, and the result is a binary the CPU runs directly. Fast, but you must manage memory yourself, and that is where whole categories of vulnerabilities come from.',
        'Interpreted languages like Python and JavaScript are read and executed at run time by another program. Slower, far more forgiving, and the security problems shift from memory to logic, injection and dependencies.',
        'A binary is not a black box. Tools like strings, file, objdump and a debugger let you read what is inside. This is the entry point to reverse engineering: you do not need the source code to understand a program’s behaviour, only patience.',
        'Debuggers let you pause a running program, step one instruction at a time, and inspect memory. gdb on Linux, x64dbg or WinDbg on Windows. Learning to sit inside a paused program is the moment computers stop feeling like magic.',
        'One habit worth forming early: symbols and debug information make analysis vastly easier, which is why real malware strips them, and why your own builds should not ship them to production either.',
      ],
      words: [
        { term: 'Compiler', means: 'Turns source code into machine code.' },
        { term: 'Binary', means: 'The compiled, runnable file.' },
        { term: 'Debugger', means: 'A tool that pauses and inspects a running program.' },
        { term: 'Reverse engineering', means: 'Working out how something behaves without its source code.' },
      ],
      why: 'Malware analysis, exploit development and firmware research all begin with being comfortable holding a compiled program and asking what it does.',
      doThis: 'Write a three-line C program, compile it, then run "strings" and "objdump -d" on the result. Find your own text inside the binary.',
      check: 'Why do memory-safety bugs appear in C but rarely in Python?',
    },
    {
      id: '01-8',
      title: 'Baselines, logs and hardening',
      mins: 8,
      oneLine: 'You cannot spot abnormal until you have written down what normal looks like.',
      like: 'A doctor takes your resting pulse first. Without it, a reading of 90 means nothing at all.',
      body: [
        'A baseline is a documented snapshot of a healthy system, which services run, which ports listen, which accounts exist, which programs start at boot, what the usual CPU and network load looks like. Take it while the machine is clean, and store it somewhere the machine itself cannot edit.',
        'Hardening means shrinking the attack surface. Remove software you do not use. Close ports nothing needs. Disable default accounts. Require multi-factor authentication. Apply updates. Each of these removes a door rather than adding another lock, which is nearly always the better trade.',
        'Least privilege is the rule underneath all of it: every account and every process gets exactly the access it needs to do its job and not one bit more. It is boring, it is unglamorous, and it stops more real attacks than any product you can buy.',
        'Logs are your memory. Configure them to capture logins, privilege use, process creation and network connections, and then ship them somewhere else, because the first thing a competent attacker does is edit or wipe the local ones.',
        'Benchmarks exist so you do not have to invent all of this: CIS Benchmarks and vendor hardening guides give you tested, specific settings per platform. Use them as a starting point, then adjust for what the system actually does.',
      ],
      words: [
        { term: 'Baseline', means: 'A record of what a healthy system looks like.' },
        { term: 'Hardening', means: 'Reducing the number of ways in.' },
        { term: 'Least privilege', means: 'Give the minimum access required, nothing more.' },
        { term: 'Log forwarding', means: 'Sending logs off the machine so they survive an attacker.' },
      ],
      why: 'Every detection you will ever write is really a statement about the difference between this and normal. Without a baseline you are guessing.',
      doThis: 'Baseline your Linux VM: list listening ports, running services, user accounts and startup items. Save it. Install something, then diff the new state against it.',
      check: 'Why is a locally stored log less trustworthy after a compromise than a forwarded one?',
    },
  ],
};
