import type { Stage } from './types';

export const s02: Stage = {
  number: '02',
  title: 'How the internet moves data',
  subtitle: 'Packets, addresses, DNS, TLS — following a message from your finger to a server',
  level: 'EASY',
  tags: ['FOUNDATIONS', 'DEFENSE', 'OFFENSE'],
  weeks: 5,
  hours: 65,
  hue: 185,
  plain: 'Every attack and every defence eventually travels over a network. This stage teaches you to read that traffic like a sentence.',
  outcome: 'Given a connection that is failing or a flow that looks suspicious, you can say which layer is responsible and prove it with a packet capture.',
  project: 'Design a segmented home lab network, then capture and annotate real traffic for DNS, TCP, HTTP and TLS, explaining every field you highlight.',
  checkpoint: 'You can narrate exactly what happens between typing a web address and the page appearing, in order, without hand-waving.',
  resources: [
    { label: 'Wireshark User Guide', href: 'https://www.wireshark.org/docs/wsug_html_chunked/' },
    { label: 'Cloudflare Learning Center', href: 'https://www.cloudflare.com/learning/' },
    { label: 'Let’s Encrypt: how certificates work', href: 'https://letsencrypt.org/how-it-works/' },
  ],
  lessons: [
    {
      id: '02-1',
      title: 'Layers: the postal system model',
      mins: 7,
      oneLine: 'Networking is built in layers, where each layer does one job and hands the result to the next without caring how it works.',
      like: 'Posting a letter. You write the words, put them in an envelope, add an address, hand it to the post office, and never think about the trucks.',
      body: [
        'The practical model has four layers. Link moves data between two machines on the same local network. Internet moves it between networks using IP addresses. Transport handles the conversation between two programs, with TCP or UDP. Application is the actual thing you wanted — HTTP, DNS, email.',
        'The academic model, OSI, has seven layers and you will hear people say "that is a layer 7 problem". Just know the mapping: layer 3 is IP, layer 4 is TCP/UDP, layer 7 is the application. Those three numbers cover most conversations.',
        'Each layer wraps the one above it in a header, like envelopes inside envelopes. This is called encapsulation. When you open a packet in Wireshark you are unwrapping those envelopes one at a time, which is exactly why the tool looks the way it does.',
        'The security value of layers is that it tells you where to look. Cannot reach a host at all? Layer 3. Connection opens then dies? Layer 4. Page loads but shows the wrong data? Layer 7. This single habit will make you look experienced very quickly.',
      ],
      words: [
        { term: 'Packet', means: 'One chunk of data travelling across a network.' },
        { term: 'Header', means: 'The label at the front of a packet saying where it is going and how to handle it.' },
        { term: 'Encapsulation', means: 'Wrapping data in another layer’s envelope.' },
        { term: 'Protocol', means: 'An agreed set of rules for how two machines talk.' },
      ],
      why: 'Layered thinking turns "the internet is broken" into a specific, testable question — which is the difference between panicking and troubleshooting.',
      doThis: 'Install Wireshark, capture ten seconds of traffic, and click one packet. Expand each layer in turn and name what job it is doing.',
      check: 'A site loads over IP but the name will not resolve. Which layer and which protocol should you suspect?',
    },
    {
      id: '02-2',
      title: 'Local networks, MAC addresses and ARP',
      mins: 7,
      oneLine: 'Inside your own network, machines find each other by hardware address, and the system that does it politely trusts everyone.',
      like: 'Shouting "who owns the red car?" across a car park and believing whoever answers first.',
      body: [
        'Every network interface has a MAC address, a hardware identifier burned in at manufacture. Switches learn which MAC lives on which physical port and forward frames accordingly, which is why a switch is smarter than an old hub that shouted everything everywhere.',
        'ARP is how a machine translates an IP address into a MAC address on the local network. It broadcasts "who has 192.168.1.10?" and waits for an answer. There is no authentication. Any machine can answer, and the asker will believe it.',
        'That design flaw is ARP spoofing: an attacker on the same network answers first, claiming to be the router, and traffic starts flowing through them. This is the classic on-path attack, and it is why "we are on the same Wi-Fi" is a meaningful risk statement.',
        'VLANs split one physical switch into several logical networks that cannot talk directly. This is the cheapest, most effective piece of network security available: keep the printers, the guests, the servers and the lab on separate segments so a compromise in one does not reach the others.',
      ],
      words: [
        { term: 'MAC address', means: 'The hardware address of a network card.' },
        { term: 'ARP', means: 'The protocol that maps an IP address to a MAC address locally.' },
        { term: 'On-path attack', means: 'Sitting between two parties and reading or changing their traffic.' },
        { term: 'VLAN', means: 'A logical network separation inside one physical switch.' },
      ],
      why: 'Segmentation is the control that limits how far an intruder can move, and ARP is the reason a flat network is a single shared risk.',
      doThis: 'Run "arp -a" on your machine. Identify the entry for your router. Consider what would happen if that MAC quietly changed.',
      check: 'Why does putting IoT devices on their own VLAN meaningfully reduce risk?',
    },
    {
      id: '02-3',
      title: 'IP addresses, subnets and NAT',
      mins: 8,
      oneLine: 'An IP address is where a machine lives; a subnet mask says which part of that address is the street and which is the house.',
      like: 'A postal address. The postcode gets the letter to the right area; the house number finishes the job.',
      body: [
        'IPv4 addresses look like 192.168.1.10 — four numbers, each 0 to 255. The subnet mask, often written as /24, marks how many leading bits identify the network. In a /24, the first three numbers are the network and the last is the host, giving 254 usable addresses.',
        'Some ranges are private and never routed on the internet: 10.x.x.x, 172.16-31.x.x, and 192.168.x.x. Your home network uses one of these. Recognising them instantly tells you whether an address you are looking at is internal or external, which matters constantly in investigations.',
        'NAT is the trick that lets many private addresses share one public one. Your router rewrites outgoing packets to look like they came from itself and remembers who asked. This is why incoming connections do not just reach your laptop, and it is an accidental firewall that has protected home users for decades.',
        'IPv6 exists because IPv4 ran out of addresses. It is longer, hexadecimal, and every device can have a genuinely public address — which removes NAT’s accidental protection. Many networks run both, and defenders forget to filter the IPv6 side. Attackers do not forget.',
      ],
      words: [
        { term: 'IP address', means: 'The address of a machine on a network.' },
        { term: 'Subnet mask / CIDR', means: 'Which portion of an address identifies the network.' },
        { term: 'NAT', means: 'Sharing one public address among many private ones.' },
        { term: 'Private address range', means: 'Addresses only valid inside a local network.' },
      ],
      why: 'Reading an address and immediately knowing internal versus external, routable versus private, is a reflex you will use in every single investigation.',
      doThis: 'Find your own IP and subnet mask. Work out the network range by hand. Then check your answer with a subnet calculator.',
      check: 'Why can a firewall rule set that only filters IPv4 leave a network fully exposed?',
    },
    {
      id: '02-4',
      title: 'Routing, firewalls and ports',
      mins: 8,
      oneLine: 'Routers decide where a packet goes next; firewalls decide whether it should be allowed to go there at all.',
      like: 'Road junctions and border checkpoints. One picks the direction, the other checks the paperwork.',
      body: [
        'A router looks at a packet’s destination, consults its routing table, and forwards it one hop closer. No single router knows the whole path — the internet works because each one only needs to know the next step. Your machine has a routing table too; "the default gateway" is simply where it sends anything it does not recognise.',
        'A port is a number identifying which program on a machine should receive the data. 80 is web, 443 is secure web, 22 is SSH, 53 is DNS, 3389 is Windows remote desktop. Learning about fifteen common ports is worth doing; they come up constantly.',
        'A firewall filters traffic on rules. A stateless one judges each packet alone. A stateful one remembers conversations, so it can allow replies to something you started while blocking unsolicited arrivals. Nearly everything modern is stateful.',
        'Two defaults matter enormously. Default-deny means everything is blocked unless explicitly allowed, and it is the correct choice. Default-allow means everything passes unless specifically blocked, and it will eventually let something through that you never thought to name.',
        'Egress filtering — controlling what leaves — is the one most organisations skip. Attackers rely on that: their stolen data and their remote control channel both flow outward, usually over ports nobody thought to restrict.',
      ],
      words: [
        { term: 'Port', means: 'A number identifying which service on a machine should get the traffic.' },
        { term: 'Default gateway', means: 'Where your machine sends traffic it does not know how to reach.' },
        { term: 'Stateful firewall', means: 'One that remembers ongoing conversations.' },
        { term: 'Egress filtering', means: 'Restricting outbound traffic, not just inbound.' },
      ],
      why: 'Most of network defence is deciding what is allowed to talk to what. Get that right and entire classes of attack simply cannot complete.',
      doThis: 'Run "netstat -tuln" or "ss -tuln" on your machine. Every listening port is a door. Ask yourself, for each one, whether it needs to be open.',
      check: 'Why does blocking outbound traffic frustrate an attacker who has already got inside?',
    },
    {
      id: '02-5',
      title: 'DNS: the internet’s phone book',
      mins: 8,
      oneLine: 'DNS turns names people can remember into addresses machines can use — and almost everything trusts it completely.',
      like: 'Asking directory enquiries for a phone number. Convenient, until someone impersonates the operator.',
      body: [
        'When you type a web address, your machine asks a resolver, which asks the root servers, then the top-level domain servers, then the domain’s own name servers, until it gets an answer. That answer is cached at every step for a set time, called TTL.',
        'Record types you will meet constantly: A maps a name to an IPv4 address, AAAA to IPv6, CNAME is an alias, MX points to mail servers, TXT holds arbitrary text — and TXT is where SPF, DKIM and DMARC live, the three records that decide whether someone can convincingly forge your email domain.',
        'DNS is a defender’s goldmine because every connection usually starts with a lookup. DNS logs reveal malware calling home, data being smuggled out inside subdomains, and users visiting newly registered domains. If you can only collect one log source, many professionals would choose this one.',
        'It is also an attacker’s tool. Cache poisoning inserts false answers. Typosquatting registers lookalike names. Fast-flux rotates addresses to dodge blocking. DNS tunnelling hides an entire command channel inside lookups that most firewalls happily allow.',
        'Encrypted DNS — DoH and DoT — protects users from eavesdropping and simultaneously blinds defenders who relied on watching plain DNS. This is a genuinely unresolved tension, and a good example of how privacy and visibility can pull against each other.',
      ],
      words: [
        { term: 'DNS', means: 'The system that turns names into IP addresses.' },
        { term: 'Resolver', means: 'The server that does the lookup work on your behalf.' },
        { term: 'TTL', means: 'How long an answer may be cached before asking again.' },
        { term: 'DNS tunnelling', means: 'Hiding other data inside DNS queries to sneak past filters.' },
      ],
      why: 'DNS sits in front of nearly every attack chain, which makes it one of the highest-value places to both watch and defend.',
      doThis: 'Run "dig example.com" and then "dig example.com MX" and "dig example.com TXT". Read the answers. Find a domain’s SPF record and work out what it permits.',
      check: 'Why is a burst of DNS queries to long random subdomains of one domain suspicious?',
    },
    {
      id: '02-6',
      title: 'TCP, UDP and the handshake',
      mins: 7,
      oneLine: 'TCP is a careful phone call that confirms every word; UDP is shouting a postcard and hoping.',
      like: 'Registered post with signatures versus dropping a flyer through the door. One guarantees arrival, one is fast and cheap.',
      body: [
        'TCP sets up a connection with a three-way handshake: SYN, SYN-ACK, ACK. After that it numbers every byte, acknowledges what arrived, retransmits what did not, and closes politely with FIN. This reliability is why web pages and file transfers use it.',
        'UDP does none of that. It fires a packet and forgets. That makes it perfect for DNS, video calls and games, where a late packet is worse than a missing one — and it makes it easy to spoof, because there is no handshake to complete.',
        'That spoofability is why UDP powers amplification attacks. Send a small forged request to a service that replies with something much larger, put the victim’s address as the sender, and repeat. DNS and NTP have both been abused this way at enormous scale.',
        'The handshake also explains scanning. A full connect scan completes all three steps and is noisy. A SYN scan sends the first packet and never finishes, which is faster and quieter. The response tells you the state: SYN-ACK means open, RST means closed, silence usually means filtered.',
      ],
      words: [
        { term: 'TCP', means: 'Reliable, ordered, connection-based transport.' },
        { term: 'UDP', means: 'Fast, connectionless transport with no delivery guarantee.' },
        { term: 'Three-way handshake', means: 'SYN, SYN-ACK, ACK — how a TCP connection opens.' },
        { term: 'Amplification attack', means: 'Using a service that replies large to small forged requests, aimed at a victim.' },
      ],
      why: 'Reading connection states is how you tell a port scan from normal traffic, and a failing service from a blocked one.',
      doThis: 'In Wireshark, filter on "tcp.flags.syn == 1 && tcp.flags.ack == 0" and watch connections being opened. Then find the matching SYN-ACK.',
      check: 'Why can a SYN scan detect an open port without completing a connection?',
    },
    {
      id: '02-7',
      title: 'HTTP, TLS and certificates',
      mins: 9,
      oneLine: 'HTTP is how browsers ask for things; TLS is the envelope that stops anyone else reading or changing the request.',
      like: 'Sending a postcard versus a sealed, tamper-evident envelope from a courier who checks the recipient’s ID.',
      body: [
        'An HTTP request has a method (GET, POST, PUT, DELETE), a path, headers, and sometimes a body. The response has a status code — 200 fine, 301 moved, 401 not authenticated, 403 not allowed, 404 missing, 500 server broke. Those six codes explain most of what you will see.',
        'HTTP is stateless: each request stands alone. Cookies exist to fix that, carrying a session identifier so the server remembers you. That makes cookies extremely valuable to steal, and the reason flags like HttpOnly, Secure and SameSite exist.',
        'TLS wraps HTTP to give three things: encryption so nobody can read it, integrity so nobody can change it, and authentication so you know you reached the right server. The handshake agrees a shared secret using asymmetric cryptography, then switches to faster symmetric encryption for the actual data.',
        'Certificates are how the authentication part works. A certificate authority signs a statement that a public key belongs to a domain. Your browser trusts a list of authorities, so it trusts the chain. When you see a certificate warning, that chain of trust failed — and clicking through it is exactly what an on-path attacker needs you to do.',
        'HTTP/2 and HTTP/3 changed the transport underneath — HTTP/3 runs on QUIC over UDP — but the request and response ideas stayed the same. Know that it changes what your network tools can see, because more of the connection is encrypted earlier.',
      ],
      words: [
        { term: 'HTTP method', means: 'The verb of a request: GET, POST and friends.' },
        { term: 'Cookie', means: 'A small stored value the browser sends back on each request, usually to keep you logged in.' },
        { term: 'TLS', means: 'The encryption layer that turns HTTP into HTTPS.' },
        { term: 'Certificate authority', means: 'An organisation browsers trust to vouch for who owns a domain.' },
      ],
      why: 'The web is where most applications and most attacks live. Reading raw HTTP fluently is a prerequisite for all of stage 05.',
      doThis: 'Open your browser’s developer tools, go to the Network tab, and load any site. Read one request fully: method, headers, cookies, status code.',
      check: 'What exactly are you trusting when a browser shows a padlock, and what is it not promising you?',
    },
    {
      id: '02-8',
      title: 'Wi-Fi, VPNs and reading captures',
      mins: 8,
      oneLine: 'Wireless and VPNs change who can see your traffic, and packet capture is how you check what is really happening.',
      like: 'Wi-Fi is a conversation in a crowded room. A VPN is a soundproof tube to somewhere else — the room changes, the conversation does not.',
      body: [
        'Wi-Fi security has generations. WEP is broken and must never be used. WPA2 is common and vulnerable to offline password guessing if the passphrase is weak. WPA3 improves this substantially with a handshake resistant to offline cracking. Open networks encrypt nothing at all between you and the access point.',
        'The realistic wireless risks are simple: rogue access points imitating a real network name, deauthentication attacks kicking clients off so they reconnect somewhere hostile, and captured handshakes cracked offline. All of them assume physical proximity, which is exactly why cafes and hotels matter.',
        'A VPN encrypts your traffic to a server and sends it out from there. That protects you from the local network and hides your address from destinations. It does not make you anonymous, does not stop malware, and moves your trust to the VPN provider rather than removing the need for trust.',
        'Packet capture is the ground truth. Wireshark shows every field; tcpdump does the same from a command line and is what you will find installed on a server. Learn a handful of display filters — "http", "dns", "ip.addr == x", "tcp.port == 443" — and you can answer most questions quickly.',
        'One habit: capture first, then filter. Filtering while capturing throws away the context you did not know you needed, and you rarely get the same five minutes back.',
      ],
      words: [
        { term: 'WPA2 / WPA3', means: 'Wi-Fi encryption standards; WPA3 is the current, stronger one.' },
        { term: 'Rogue access point', means: 'A fake Wi-Fi network pretending to be a legitimate one.' },
        { term: 'VPN', means: 'An encrypted tunnel to another network.' },
        { term: 'pcap', means: 'A saved file of captured network traffic.' },
      ],
      why: 'When logs disagree or a tool reports something impossible, packet capture is the evidence that settles it.',
      doThis: 'Capture traffic while visiting a plain HTTP site and an HTTPS site. Compare what you can read in each. The difference is the whole argument for TLS.',
      check: 'A colleague says a VPN makes them anonymous. Give two specific reasons that is not accurate.',
    },
  ],
};
