import type { Stage } from './types';

export const s03: Stage = {
  number: '03',
  title: 'Code enough to be dangerous',
  subtitle: 'Python, Bash, PowerShell, SQL and a little C: automate the boring, understand the rest',
  level: 'EASY',
  tags: ['BUILD', 'FOUNDATIONS'],
  weeks: 5,
  hours: 65,
  hue: 265,
  plain: 'You do not need to be a software engineer. You need to read code without fear and write small programs that do your repetitive work for you.',
  outcome: 'You can write scripts that parse logs, call APIs, test inputs and produce reports, and read unfamiliar code well enough to spot its assumptions.',
  project: 'Build a command-line tool that reads security logs, pulls out indicators, enriches them, and exports a clean report with tests.',
  checkpoint: 'Given a script you did not write, you can explain what it does, what could go wrong, and what it trusts that it should not.',
  resources: [
    { label: 'Official Python tutorial', href: 'https://docs.python.org/3/tutorial/' },
    { label: 'Automate the Boring Stuff (free online)', href: 'https://automatetheboringstuff.com/' },
    { label: 'SQL practice: SQLBolt', href: 'https://sqlbolt.com/' },
  ],
  lessons: [
    {
      id: '03-1',
      title: 'Python: your everyday tool',
      mins: 9,
      oneLine: 'Python is the language most security work is written in, because it is readable and gets out of your way.',
      like: 'A Swiss Army knife. Not the best tool for any single job, but the one you actually carry.',
      body: [
        'You need surprisingly little: variables, strings, lists, dictionaries, loops, conditions, functions, and reading a file. That is perhaps two weeks of evenings and it covers the overwhelming majority of scripts you will ever write in this field.',
        'Dictionaries deserve special attention. Almost every security data format: JSON from an API, a parsed log line, a configuration file: arrives as nested dictionaries and lists. Getting comfortable walking those structures is most of the practical skill.',
        'Three libraries carry you a long way. "requests" talks to web APIs. "json" reads and writes the format everything speaks. "argparse" turns your script into a real command-line tool with proper options instead of hard-coded values.',
        'Write functions early. A script that is one long block cannot be tested, reused, or debugged when it breaks at 2am. Small named functions that each do one thing is not academic advice; it is what makes tools survive contact with reality.',
        'Handle errors on purpose. Network calls fail, files are missing, data is malformed. A tool that crashes on the first bad line of a million-line log is a tool you will not trust. Decide what should stop everything and what should be logged and skipped.',
      ],
      words: [
        { term: 'Dictionary', means: 'A lookup table of keys and values: the shape most data arrives in.' },
        { term: 'Library / module', means: 'Someone else’s code you import instead of writing.' },
        { term: 'JSON', means: 'A common text format for structured data.' },
        { term: 'Virtual environment', means: 'A per-project sandbox for Python packages, so projects do not break each other.' },
      ],
      why: 'Automation is the difference between checking ten machines and checking ten thousand. It is also the difference between an analyst and a senior analyst.',
      doThis: 'Write a Python script that opens a log file, counts how many times each IP address appears, and prints the top five. About fifteen lines.',
      check: 'Why should a log-parsing tool keep going when it meets one malformed line?',
    },
    {
      id: '03-2',
      title: 'Bash: gluing tools together',
      mins: 7,
      oneLine: 'Bash is not for building software; it is for chaining existing tools into an answer in one line.',
      like: 'A conveyor belt in a kitchen. Each station does one small thing and passes the plate along.',
      body: [
        'The philosophy is small sharp tools. grep filters lines, cut and awk pull out fields, sort orders them, uniq counts duplicates, sed edits text, jq handles JSON. Chained with pipes, these answer questions faster than any script you could write.',
        'A worked example: "cat access.log | awk \'{print $1}\' | sort | uniq -c | sort -rn | head" gives you the top talking IP addresses in a web log. Learning to build that chain step by step, checking the output at each stage, is a core investigative skill.',
        'Bash has genuinely dangerous edges. Unquoted variables split on spaces and can turn one filename into several arguments. Filenames with unusual characters break naive loops. Always quote your variables, and prefer looping over "find -print0" style output when names might be strange.',
        'The biggest security risk in shell scripting is putting untrusted input into a command string. If a variable ends up inside something the shell evaluates, whoever controls that variable controls your machine. This is command injection, and it is the same bug you will exploit in stage 05.',
        'Use "set -euo pipefail" at the top of any script that matters. It makes the script stop on errors instead of ploughing on with wrong assumptions, which is almost always what you actually wanted.',
      ],
      words: [
        { term: 'awk', means: 'A tool for pulling out and processing columns of text.' },
        { term: 'jq', means: 'A tool for querying JSON on the command line.' },
        { term: 'Command injection', means: 'Untrusted input becoming part of a command the system runs.' },
        { term: 'Exit code', means: 'A number a command returns; 0 means success.' },
      ],
      why: 'On a compromised server at 3am, you will have a shell and standard tools. Fluency here is what lets you answer questions with what is already installed.',
      doThis: 'Build a one-liner that finds the ten most common failed-login usernames in an auth log. Check the output after adding each stage of the pipe.',
      check: 'Why is an unquoted shell variable a security problem and not just a bug?',
    },
    {
      id: '03-3',
      title: 'PowerShell and Windows automation',
      mins: 8,
      oneLine: 'PowerShell is how you ask thousands of Windows machines a question and get a structured answer back.',
      like: 'A spreadsheet you can query, rather than a printout you have to read.',
      body: [
        'Everything in PowerShell is an object with properties, not text. "Get-Process" returns process objects, so "Get-Process | Where-Object { $_.CPU -gt 100 }" filters on an actual number. No parsing, no regular expressions, no fragile string matching.',
        'Command names follow Verb-Noun, which makes them guessable: Get-Service, Stop-Process, New-Item, Set-ExecutionPolicy. When you do not know a command, "Get-Command *event*" and "Get-Help" will usually find it.',
        'For security work specifically, learn Get-WinEvent for reading event logs, Get-NetTCPConnection for live connections, Get-LocalUser and Get-ADUser for accounts, and Invoke-Command for running something across many machines at once.',
        'PowerShell is also the attacker’s favourite Windows tool, because it is present everywhere, signed, and can run code entirely in memory without touching disk. That is exactly why script block logging, module logging and transcription matter: they turn an invisible tool into a recorded one.',
        'Execution policy is not a security boundary and never was. It stops accidents, not attackers, since it can be bypassed by anyone who can run PowerShell at all. Treat it as a guardrail, not a wall.',
      ],
      words: [
        { term: 'Cmdlet', means: 'A PowerShell command, always shaped Verb-Noun.' },
        { term: 'Pipeline object', means: 'Structured data passed between commands, not plain text.' },
        { term: 'Script block logging', means: 'Recording the actual code PowerShell executed.' },
        { term: 'Living off the land', means: 'Attacking using tools already installed on the system.' },
      ],
      why: 'Most enterprise environments are Windows. Investigating or hardening them at scale without PowerShell means doing it by hand, machine by machine.',
      doThis: 'Run "Get-WinEvent -FilterHashtable @{LogName=\'Security\'; ID=4625} -MaxEvents 20" and read the failed logon attempts on your own machine.',
      check: 'Why is PowerShell logging one of the highest-value settings to turn on in a Windows environment?',
    },
    {
      id: '03-4',
      title: 'JavaScript and how browsers run code',
      mins: 8,
      oneLine: 'JavaScript runs inside every visitor’s browser, which makes it both the web’s engine and its biggest security surface.',
      like: 'A shop that lets every customer bring their own robot assistant inside. Very useful, occasionally catastrophic.',
      body: [
        'A page is a tree of elements called the DOM. JavaScript can read and rewrite any part of it, react to clicks, and make network requests in the background. That is what makes modern web applications feel like applications.',
        'The rule keeping this safe is the same-origin policy: code from one site cannot read data from another. Origin means scheme, host and port together, all three matching. Nearly every browser security feature is either enforcing this rule or carefully making an exception to it.',
        'CORS is the official exception mechanism. A server can say "this other origin may read my responses". Misconfigured CORS: especially reflecting any origin while allowing credentials: hands attackers exactly the cross-site read the policy was designed to prevent.',
        'Cross-site scripting is what happens when attacker-controlled text is treated as code by the page. Their script then runs with your site’s origin and your user’s session, which means it can do anything the user could. Understanding the DOM is what makes this bug make sense rather than feel like magic.',
        'You do not need to be a front-end developer. You need to read JavaScript, follow where user input travels, and recognise dangerous sinks like innerHTML, eval and document.write.',
      ],
      words: [
        { term: 'DOM', means: 'The live tree structure of a web page that code can change.' },
        { term: 'Same-origin policy', means: 'Code from one site cannot read another site’s data.' },
        { term: 'CORS', means: 'The controlled way a server permits cross-origin reads.' },
        { term: 'Sink', means: 'A place in code where data becomes dangerous, like being executed or rendered as HTML.' },
      ],
      why: 'Stage 05 is mostly web security, and it is impossible to test what you cannot read. This is the prerequisite.',
      doThis: 'Open any page’s console and use JavaScript to change some text on it. Then find where that page reads a value from the URL.',
      check: 'Why does the same-origin policy exist, and what would the web look like without it?',
    },
    {
      id: '03-5',
      title: 'SQL and how databases get broken',
      mins: 8,
      oneLine: 'SQL is the language for asking databases questions, and mixing it with user input is one of the oldest disasters in computing.',
      like: 'Letting a customer write part of the instruction you hand to the warehouse. Usually fine. Occasionally they write "and also send me everything".',
      body: [
        'The core is small: SELECT columns FROM table WHERE condition, plus JOIN to combine tables, ORDER BY, GROUP BY and LIMIT. Add INSERT, UPDATE and DELETE and you can do most of what an application needs.',
        'For security work, being able to write a query matters because evidence lives in databases. Log platforms, asset inventories and case management systems all answer SQL or something very close to it.',
        'SQL injection happens when input is concatenated into a query string. If the application builds "SELECT * FROM users WHERE name = \'" plus whatever you typed, then typing a quote lets you finish their sentence and add your own. From there you can read other tables, bypass logins, and sometimes reach the operating system.',
        'The fix is not filtering quotes. The fix is parameterised queries, where the database receives the query structure and the values separately and never confuses one for the other. This is a total fix, not a mitigation, which is rare and worth appreciating.',
        'NoSQL databases are not immune. Passing raw user input into a MongoDB query object lets an attacker inject operators like a "not equal" condition that always matches. Different syntax, identical root cause: data becoming instruction.',
      ],
      words: [
        { term: 'Query', means: 'A question you ask a database.' },
        { term: 'SQL injection', means: 'Attacker input changing the meaning of a database query.' },
        { term: 'Parameterised query', means: 'Sending structure and values separately so input can never become code.' },
        { term: 'ORM', means: 'A library that writes SQL for you from normal code.' },
      ],
      why: 'Injection is still in the OWASP Top 10 after twenty years. Understanding it properly once means recognising the whole family of "data became instruction" bugs.',
      doThis: 'Install SQLite, create a small table, and write five queries. Then write the same lookup twice, once with string concatenation, once parameterised, and compare.',
      check: 'Why does escaping quotes fail as a defence where parameterisation succeeds?',
    },
    {
      id: '03-6',
      title: 'A little C, and why memory bugs exist',
      mins: 8,
      oneLine: 'C gives you direct control of memory, which is why it is fast, and why forgetting a boundary check becomes a security hole.',
      like: 'Writing on a shared whiteboard with no edges marked. Write past your section and you overwrite someone else’s notes.',
      body: [
        'In C, you manage memory yourself. You ask for a block, you use it, you free it. There is no automatic checking that you stayed inside what you asked for, because that checking costs time the language refuses to spend.',
        'A buffer overflow happens when a program writes more data into a space than it can hold. The extra spills into whatever sits next in memory: other variables, or the record of where the function should return to. Control that return address and you control what the CPU does next.',
        'Related bugs come from the same freedom: use-after-free (using memory you already released), double-free, integer overflow (a number wrapping around and defeating a size check), and off-by-one errors at the boundary of an array.',
        'Modern systems fight back with defences you should know by name: stack canaries detect overwritten return addresses, DEP or NX makes data areas non-executable, and ASLR randomises where things live so the attacker cannot predict addresses. Exploitation today is mostly the art of defeating these one at a time.',
        'You do not need to write C professionally. You need to read it, recognise the dangerous functions like strcpy, gets and sprintf, and understand why memory-safe languages such as Rust and Go remove this entire category of bug by design.',
      ],
      words: [
        { term: 'Buffer overflow', means: 'Writing past the end of an allocated space.' },
        { term: 'Use-after-free', means: 'Using memory that has already been released.' },
        { term: 'ASLR', means: 'Randomising memory layout so attackers cannot guess addresses.' },
        { term: 'Memory-safe language', means: 'One that prevents these bugs automatically.' },
      ],
      why: 'The most severe vulnerabilities: the ones that give full remote control: still overwhelmingly come from memory bugs in C and C++.',
      doThis: 'Write a tiny C program with a fixed 16-byte buffer and copy a longer string into it. Watch it crash. That crash is the entire idea.',
      check: 'Why does an attacker care specifically about overwriting a function’s return address?',
    },
    {
      id: '03-7',
      title: 'Regex, parsing and encoding traps',
      mins: 7,
      oneLine: 'Regular expressions find patterns in text, and the mistakes people make with them cause both missed detections and outages.',
      like: 'A fishing net. Holes too big and things slip through; too small and you catch everything including the seaweed.',
      body: [
        'Learn a working subset: character classes, quantifiers, anchors, groups, and alternation. That covers nearly all practical use. Anchoring matters more than beginners expect: a pattern without a start and end anchor can match in the middle of something else entirely.',
        'Regex is excellent for extracting known shapes: IP addresses, hashes, timestamps, domain names. It is bad for parsing structured formats. Do not parse HTML, JSON or CSV with regex; use a real parser that understands nesting and quoting, because the edge cases will find you.',
        'There is a security bug specific to regex: catastrophic backtracking, where a badly written pattern takes exponential time on a crafted input. Sending one short string can pin a CPU at 100% and take a service down. This is ReDoS, and it hides in innocuous-looking validation code.',
        'Encoding is where detections quietly fail. The same payload can appear as plain text, URL-encoded, double-encoded, Base64, HTML entities, or unicode-escaped. If your rule matches only one form, an attacker will send another. Normalise first, then match.',
        'Same lesson from the other side: when validating input, decode fully before you check it. Checking a value and then decoding it is how filters get bypassed, and it is a genuinely common mistake in production code.',
      ],
      words: [
        { term: 'Regex', means: 'A pattern language for matching text.' },
        { term: 'Anchor', means: 'A marker forcing a match at the start or end of a string.' },
        { term: 'ReDoS', means: 'A denial of service caused by a slow regular expression.' },
        { term: 'Canonicalisation', means: 'Reducing input to one standard form before checking it.' },
      ],
      why: 'Detection rules, log parsing and input validation are all pattern matching. Doing it badly creates blind spots that look like coverage.',
      doThis: 'Write a regex to extract IPv4 addresses from a log. Then deliberately try to sneak one past it using an unusual but valid representation.',
      check: 'Why should you decode input before validating it rather than after?',
    },
    {
      id: '03-8',
      title: 'APIs, Git and not shipping secrets',
      mins: 8,
      oneLine: 'Tools talk to each other over APIs, your work lives in Git, and both are places credentials leak constantly.',
      like: 'A shared workshop with a logbook. Everything you do is recorded: including the day you left your keys on the bench.',
      body: [
        'A REST API is just HTTP with structure: a URL identifies a thing, a method says what to do with it, JSON carries the data, and a token proves who you are. Once you can read HTTP, you can use almost any security product’s API to automate the boring parts.',
        'Rate limits and pagination are the two practical realities. Ask too fast and you get blocked; assume one response contains everything and you will silently miss results. Both bite beginners writing their first enrichment script.',
        'Git tracks every change forever, which is exactly the problem. Committing an API key and deleting it in the next commit does not remove it: it is still in history, and automated scanners find leaked keys on public repositories within minutes. Rotate the secret, do not just delete the line.',
        'Keep secrets out of code entirely: environment variables, a secrets manager, or an ignored local file. Add a pre-commit scanner such as gitleaks so the mistake is caught before it becomes permanent. This one habit prevents a genuinely common cause of breaches.',
        'Finally, write tests for anything you will rely on. Not a full suite: one test that fails if the parsing breaks. Security tooling that silently stops working is worse than no tooling, because you believe you are covered.',
      ],
      words: [
        { term: 'REST API', means: 'A web interface programs use to talk to a service.' },
        { term: 'API token', means: 'A credential proving your program is allowed to call an API.' },
        { term: 'Commit history', means: 'Git’s permanent record of every change ever made.' },
        { term: 'Secret scanning', means: 'Automatically detecting credentials in code.' },
      ],
      why: 'Leaked credentials in code repositories are one of the most reliable ways attackers get an initial foothold, and one of the easiest to prevent.',
      doThis: 'Install gitleaks and run it on a repository you own. Then move any hard-coded value into an environment variable.',
      check: 'You accidentally pushed an API key and immediately deleted it. What must you actually do, and why is deleting insufficient?',
    },
  ],
};
