import type { Stage } from './types';

export const s04: Stage = {
  number: '04',
  title: 'Security thinking',
  subtitle: 'Risk, identity, cryptography, zero trust and threat modelling',
  level: 'MEDIUM',
  tags: ['FOUNDATIONS', 'BUILD', 'LEADERSHIP'],
  weeks: 4,
  hours: 55,
  hue: 230,
  plain: 'This is where you stop collecting facts and start making decisions: what to protect, how much, and how you would know it worked.',
  outcome: 'You can turn a principle into a layered set of controls that fits real risk, instead of copying a checklist you found online.',
  project: 'Threat-model a small online product end to end, then propose a risk-ranked security design with a test for every control you recommend.',
  checkpoint: 'You can justify any control by naming its threat, its cost, its evidence, and the risk you are choosing to accept anyway.',
  resources: [
    { label: 'NIST CSF 2.0', href: 'https://www.nist.gov/cyberframework' },
    { label: 'OWASP Threat Modeling Cheat Sheet', href: 'https://cheatsheetseries.owasp.org/cheatsheets/Threat_Modeling_Cheat_Sheet.html' },
    { label: 'CVSS v4.0 specification', href: 'https://www.first.org/cvss/v4.0/' },
  ],
  lessons: [
    {
      id: '04-1',
      title: 'Risk: the measure that guides priorities',
      mins: 8,
      oneLine: 'Risk is how likely something bad is, multiplied by how bad it would be, and it is the only sane way to decide what to fix first.',
      like: 'Insurance. You do not insure everything equally; you insure what would hurt most, at a price that makes sense.',
      body: [
        'Every organisation has more vulnerabilities than time. Risk is the tool that turns an infinite list into a ranked one. Without it you fix whatever is loudest, newest, or most recently featured on the news, which is how genuinely dangerous things go untouched for years.',
        'Likelihood is not a guess pulled from air. It comes from evidence: is this exploitable remotely, is exploit code public, is it being used in the wild right now, and do we actually run the vulnerable configuration? A critical score on a system nobody can reach is less urgent than a medium on your front door.',
        'Impact means consequence in the real world: money, safety, legal exposure, reputation, operational downtime. If you cannot express impact in terms a non-technical decision-maker recognises, you will lose the argument for funding, and the risk will remain.',
        'You have exactly four options for any risk: reduce it with controls, transfer it (insurance, contracts), avoid it by not doing the risky thing, or accept it deliberately and write that down. Accepting risk is legitimate and professional. Ignoring risk is neither, and the difference is documentation.',
        'Residual risk is what remains after your controls. It is never zero. Being able to state it clearly is what separates a security professional from someone who promises safety they cannot deliver.',
      ],
      words: [
        { term: 'Likelihood', means: 'How probable it is that something happens.' },
        { term: 'Impact', means: 'How much damage it would cause.' },
        { term: 'Risk appetite', means: 'How much risk an organisation is deliberately willing to carry.' },
        { term: 'Residual risk', means: 'What is left after your controls are in place.' },
      ],
      why: 'Every budget conversation, every prioritisation meeting, and every serious interview question is fundamentally about risk.',
      doThis: 'List five risks to your own digital life. Score each 1 to 5 for likelihood and impact, multiply, and sort. Now look at whether your actual habits match that order.',
      check: 'Give an example of a risk that is correctly accepted rather than fixed, and say what makes that acceptance defensible.',
    },
    {
      id: '04-2',
      title: 'Identity: who are you, and what may you do',
      mins: 9,
      oneLine: 'Authentication proves who you are; authorisation decides what you are allowed to touch, and confusing them causes breaches.',
      like: 'A passport gets you into the country. It does not get you into the cockpit.',
      body: [
        'Authentication factors come in three kinds, something you know (password), something you have (a phone, a hardware key), something you are (fingerprint, face). Multi-factor means genuinely different kinds. A password plus a security question is still one kind, and it is not MFA.',
        'Not all MFA is equal. SMS codes can be intercepted or stolen through SIM swapping. App-generated codes are better but still phishable, because a convincing fake site can ask for the code and use it immediately. Hardware security keys using FIDO2 and passkeys resist phishing structurally, because the key checks the real domain before it responds.',
        'Passwords should be long rather than complicated, unique per site, and stored in a password manager. Forced ninety-day rotation is now considered harmful: it pushes people towards predictable patterns. Current guidance favours length, breach-checking against known leaked passwords, and MFA everywhere that matters.',
        'Single sign-on centralises login. SAML and OpenID Connect are the protocols that carry it; OAuth 2.0 handles delegated authorisation, letting one app act on your behalf in another without receiving your password. The main distinction: OAuth is about permission, OIDC adds identity on top. People mix these up constantly.',
        'Authorisation models scale differently. RBAC assigns permissions to roles and roles to people. ABAC decides from attributes such as department, device health or location. Whichever you use, the rule is the same: least privilege, and review it regularly, because permissions accumulate and nobody ever asks to have access removed.',
      ],
      words: [
        { term: 'Authentication', means: 'Proving who you are.' },
        { term: 'Authorisation', means: 'Deciding what you may do.' },
        { term: 'MFA', means: 'Requiring two or more different kinds of proof.' },
        { term: 'Passkey', means: 'A phishing-resistant login bound to the real website, replacing passwords.' },
      ],
      why: 'Identity is the new perimeter. Stolen or misused credentials are involved in a large share of real breaches, far more than exotic exploits.',
      doThis: 'Audit your own accounts. Turn on MFA everywhere it exists, upgrade SMS to an app or key where possible, and check your addresses on a breach notification service.',
      check: 'Why is a hardware security key phishing-resistant when an authenticator app code is not?',
    },
    {
      id: '04-3',
      title: 'Cryptography without the maths',
      mins: 10,
      oneLine: 'Cryptography gives you four powers: hide data, prove it was not changed, prove who sent it, and agree a secret over an open line.',
      like: 'A lockable box, a tamper-evident seal, a signature, and a way for two strangers to agree on a key while shouting across a room.',
      body: [
        'Symmetric encryption uses one shared key for both locking and unlocking. AES is the standard, and it is fast. The hard part is not the algorithm; it is getting the key to the other side safely and keeping it safe afterwards. Key management is where real systems fail, not the maths.',
        'Asymmetric encryption uses a pair: a public key anyone may have, and a private key you never share. Anyone can encrypt to your public key; only your private key opens it. Reverse the operation and you get signatures: you sign with the private key, and anyone can verify with the public one.',
        'Hashing is one-way. It turns any input into a fixed-length fingerprint. Use SHA-256 for integrity checks. Do not use MD5 or SHA-1 for anything security-relevant; both are broken for collision resistance. And never store passwords with a plain fast hash: use a deliberately slow password hash like Argon2, bcrypt or scrypt, with a unique salt per user.',
        'The right way to encrypt data in transit or at rest is authenticated encryption, such as AES-GCM or ChaCha20-Poly1305, which gives confidentiality and integrity together. Encryption alone lets an attacker flip bits without detection, and that has caused real vulnerabilities.',
        'The rule that matters most: never write your own cryptography. Use vetted libraries at a high level. Almost every catastrophic crypto failure in production came from someone assembling primitives themselves: reusing a nonce, choosing ECB mode, comparing secrets with a non-constant-time comparison.',
        'Post-quantum matters now, not later. NIST finalised ML-KEM (FIPS 203) for key exchange and ML-DSA (FIPS 204) plus SLH-DSA (FIPS 205) for signatures in August 2024. Guidance points at deprecating today’s algorithms around 2030, and hybrid key exchange is already carrying a large share of real web traffic. The urgency comes from harvest-now-decrypt-later: data stolen today can be decrypted when the machines arrive.',
      ],
      words: [
        { term: 'Symmetric encryption', means: 'One shared key locks and unlocks. Fast.' },
        { term: 'Asymmetric encryption', means: 'A public and private key pair. Enables signatures and key exchange.' },
        { term: 'Hash', means: 'A one-way fingerprint of data.' },
        { term: 'Salt', means: 'Random data added per user so identical passwords hash differently.' },
        { term: 'ML-KEM', means: 'The NIST post-quantum key exchange standard, FIPS 203.' },
      ],
      why: 'Crypto underpins TLS, signing, passwords, backups and blockchains. Using it correctly is a job requirement; inventing it is a career-ending habit.',
      doThis: 'Hash the same word with MD5 and SHA-256 and compare. Then hash it twice with bcrypt and notice the outputs differ: that is the salt doing its job.',
      check: 'Why is a fast hash the wrong choice for storing passwords, when it is the right choice for verifying a downloaded file?',
    },
    {
      id: '04-4',
      title: 'Defence in depth and zero trust',
      mins: 8,
      oneLine: 'Assume every single control will fail, and design so that failure is survivable.',
      like: 'A castle has a moat, walls, gates and guards, not because any one is weak, but because the attacker has to beat all of them.',
      body: [
        'Defence in depth means layering independent controls so no single failure is fatal. A phishing email gets through, but MFA stops the login. MFA is bypassed, but the account has minimal privileges. Privileges are escalated, but segmentation limits movement. Each layer buys time and generates evidence.',
        'The old model was a hard perimeter with a soft interior: get past the firewall and you were trusted. Remote work, cloud services and mobile devices destroyed that idea. There is no inside any more.',
        'Zero trust replaces location-based trust with continuous verification. Every request is authenticated and authorised, regardless of where it comes from. Trust decisions consider identity, device health, and context, and they are re-evaluated rather than granted once at the door.',
        'The practical building blocks are unglamorous: strong identity with MFA everywhere, device posture checks, micro-segmentation so systems only reach what they need, least privilege with just-in-time elevation, and logging everything so decisions can be reviewed.',
        'Beware the word as a product. Zero trust is an architecture and a discipline, not something you buy. Vendors will tell you otherwise. In practice, it is a multi-year programme of removing implicit trust wherever you find it.',
      ],
      words: [
        { term: 'Defence in depth', means: 'Multiple independent layers, so one failure is not fatal.' },
        { term: 'Zero trust', means: 'Never trust based on network location; verify every request.' },
        { term: 'Micro-segmentation', means: 'Fine-grained network separation between workloads.' },
        { term: 'Lateral movement', means: 'An attacker spreading from one system to others.' },
      ],
      why: 'Breaches become disasters when one compromised laptop can reach everything. Segmentation and verification are what turn an incident into a contained event.',
      doThis: 'Map your home network. Which devices can talk to which? Put your smart devices on a guest network and observe what genuinely breaks.',
      check: 'Name three independent layers that would have to fail before a phishing email became a full breach.',
    },
    {
      id: '04-5',
      title: 'Threat modelling: thinking like the attacker, on paper',
      mins: 9,
      oneLine: 'Threat modelling is asking four questions about a design before you build it, and it is the cheapest security you will ever do.',
      like: 'Walking around a house you are about to buy, imagining how you would break in: before you move your things inside.',
      body: [
        'The four questions, from Adam Shostack, are: What are we building? What can go wrong? What are we going to do about it? Did we do a good job? Everything else in threat modelling is a technique for answering one of those.',
        'Start with a data flow diagram. Draw the components, the data moving between them, and: most importantly: the trust boundaries where data crosses from a less trusted zone into a more trusted one. Nearly every interesting vulnerability lives on a trust boundary.',
        'STRIDE gives you a prompt list for what can go wrong: Spoofing (pretending to be someone), Tampering (changing data), Repudiation (denying an action), Information disclosure (leaking), Denial of service (breaking availability), Elevation of privilege (gaining power). Walk each element of the diagram against those six.',
        'Attack trees are the other useful shape: put the attacker’s goal at the top and branch downwards into ways of achieving it. This exposes the cheap paths, which are the ones attackers actually take. Real adversaries are lazy and economical, not theatrical.',
        'Do it early and do it roughly. A whiteboard model in an hour before code is written finds design flaws that no scanner will ever catch, because scanners find implementation bugs and this finds bad ideas. Redo it whenever the design changes meaningfully.',
      ],
      words: [
        { term: 'Threat model', means: 'A structured look at what could go wrong with a design.' },
        { term: 'Trust boundary', means: 'Where data moves between zones of different trust.' },
        { term: 'STRIDE', means: 'Six prompts for finding threats: spoofing, tampering, repudiation, disclosure, denial, elevation.' },
        { term: 'Abuse case', means: 'A user story written from the attacker’s point of view.' },
      ],
      why: 'Design flaws are far more expensive to fix than code bugs, and they are invisible to every automated tool. This is the skill that finds them.',
      doThis: 'Draw a data flow diagram for a login page: browser, server, database, email service. Mark the trust boundaries. Apply STRIDE to just one arrow.',
      check: 'Why can a scanner find a missing security header but never find a flawed permission design?',
    },
    {
      id: '04-6',
      title: 'Vulnerability management: CVE, CVSS and reality',
      mins: 8,
      oneLine: 'Knowing about a vulnerability is easy; deciding which of the ten thousand you found actually matters is the job.',
      like: 'A hospital triage desk. Everyone is unwell, but you treat the person who is bleeding before the person with a cough.',
      body: [
        'A CVE is a unique identifier for one publicly known vulnerability: CVE-2021-44228 is Log4Shell, for example. It names the problem so everyone can talk about the same thing. It does not tell you how bad it is for you.',
        'CVSS scores severity from 0 to 10. Version 4.0 improved the ability to describe real-world context. But a base score is a generic measurement made by someone who does not know your environment. Treating it as a work queue is the most common vulnerability management mistake.',
        'Two data sources fix that. EPSS estimates the probability a vulnerability will actually be exploited in the next thirty days. The CISA Known Exploited Vulnerabilities catalogue lists what is being exploited right now. A medium-severity flaw on the KEV list outranks a critical nobody has ever weaponised.',
        'Then add your own context: is the asset internet-facing, does it hold sensitive data, is it business-critical, is there a compensating control already in place? Severity times exposure times value is a far better queue than severity alone.',
        'The process, not the scan, is what matters: discover assets, assess them, prioritise, remediate, verify the fix, and report. Most organisations do the first two well and the last two badly, which is why the same findings appear in report after report.',
      ],
      words: [
        { term: 'CVE', means: 'A unique ID for one known vulnerability.' },
        { term: 'CVSS', means: 'A 0-10 severity score.' },
        { term: 'EPSS', means: 'A probability estimate that a vulnerability will be exploited soon.' },
        { term: 'KEV', means: 'CISA’s catalogue of vulnerabilities known to be exploited in the wild.' },
      ],
      why: 'Patching everything is impossible. Patching the right things quickly is achievable, and it is what actually reduces breach likelihood.',
      doThis: 'Pick any recent critical CVE. Find its CVSS score, its EPSS probability, and whether it is on the KEV list. Notice how differently those three read.',
      check: 'Why might a CVSS 6.5 deserve attention before a CVSS 9.8 in a specific organisation?',
    },
    {
      id: '04-7',
      title: 'Resilience: backups, patching and recovery',
      mins: 8,
      oneLine: 'Since prevention eventually fails, the ability to recover quickly is itself a security control: often the most valuable one.',
      like: 'Smoke alarms and a fire escape do not stop fires. They decide whether a fire is an incident or a tragedy.',
      body: [
        'The 3-2-1 rule is the durable advice: three copies of your data, on two different media, with one kept off-site. Ransomware sharpened it into 3-2-1-1-0: add one copy that is offline or immutable, and zero errors when you test the restore.',
        'A backup you have never restored is a hypothesis, not a backup. Test restores on a schedule. Organisations discover the hard way that their backups were incomplete, encrypted by the same attacker, or take three weeks to restore: always during the incident, never before.',
        'Two numbers drive design. RPO is how much data you can afford to lose, measured in time. RTO is how long you can afford to be down. These are business decisions, not technical ones, and they determine what you build and what it costs.',
        'Patching is the least exciting and most effective control there is. Most successful attacks use known vulnerabilities with available fixes. The barrier is rarely technical; it is change control, uptime fear, and unowned systems. Automate what you can, and maintain an emergency path for the genuinely urgent.',
        'Configuration drift undoes all of this quietly. Systems that started hardened wander over time as people make exceptions. Infrastructure as code and regular compliance checking are how you notice, because nobody remembers the temporary rule they added eight months ago.',
      ],
      words: [
        { term: 'RPO', means: 'How much data loss is acceptable, measured in time.' },
        { term: 'RTO', means: 'How quickly you must be back up and running.' },
        { term: 'Immutable backup', means: 'A copy that cannot be altered or deleted, even by an administrator.' },
        { term: 'Configuration drift', means: 'Systems slowly moving away from their intended secure state.' },
      ],
      why: 'When ransomware lands, the quality of your backups is the entire difference between an expensive week and an extinction event.',
      doThis: 'Back up something you care about using the 3-2-1 rule. Then actually restore it to a different machine and time how long it takes.',
      check: 'Why is an immutable or offline copy specifically necessary against ransomware, when three online copies are not enough?',
    },
    {
      id: '04-8',
      title: 'Governance, privacy and the law',
      mins: 8,
      oneLine: 'Policies, standards and regulations are how security scales beyond the people who care about it personally.',
      like: 'Traffic laws. You could rely on everyone driving sensibly, or you could write the rules down and make them enforceable.',
      body: [
        'Understand the hierarchy. A policy states what must happen and why. A standard sets specific mandatory requirements. A procedure gives step-by-step instructions. A guideline suggests. Most confusion in security programmes comes from mixing these up, usually by writing a forty-page policy nobody can follow.',
        'Privacy law shapes real engineering. GDPR gives people rights over their data and requires a lawful basis for processing it, with meaningful penalties. Similar laws exist across many regions. The practical consequences are data minimisation, retention limits, breach notification deadlines, and the ability to actually find and delete one person’s data.',
        'Compliance frameworks describe what good looks like. ISO 27001 is a management system for security. SOC 2 reports on controls for service providers. PCI DSS governs card data. HIPAA covers health information in the US. They overlap heavily, so map controls once and report many times.',
        'The trap is treating compliance as security. A compliant organisation can still be breached badly; compliance is a floor written by committee and always lags the threat. The reverse is also true: a secure organisation can fail an audit for lacking evidence. You need both, and you must name which one you are measuring.',
        'Security awareness closes the loop with people. It works when it is specific, frequent, short, and blame-free. It fails when it is an annual video and a punitive phishing test. The goal is a culture where reporting a mistake quickly is rewarded, because early reporting is worth more than any amount of quiz completion.',
      ],
      words: [
        { term: 'Policy', means: 'A high-level statement of what must be done.' },
        { term: 'GDPR', means: 'European data protection law giving people rights over their personal data.' },
        { term: 'ISO 27001', means: 'An international standard for a security management system.' },
        { term: 'Audit evidence', means: 'Proof that a control actually operates, not just that it exists.' },
      ],
      why: 'Governance is how a security programme survives the departure of the person who was holding it together, and how it gets funded at all.',
      doThis: 'Read one organisation’s public privacy policy. Identify what data they collect, why, and how long they keep it. Note anything you find vague.',
      check: 'Give a concrete example of an organisation that is compliant but not secure, and explain how that happens.',
    },
  ],
};
