import type { Stage } from './types';

export const s05: Stage = {
  number: '05',
  title: 'Breaking and fixing web apps',
  subtitle: 'The OWASP Top 10 (2025), APIs, and finding the root cause instead of the symptom',
  level: 'MEDIUM',
  tags: ['BUILD', 'OFFENSE', 'RESEARCH'],
  weeks: 5,
  hours: 55,
  hue: 25,
  plain: 'Most of the world runs on web applications, so most real vulnerabilities are web vulnerabilities. This stage teaches you to find them and fix them properly.',
  outcome: 'You can trace trust boundaries through a web or API stack, reproduce a flaw safely in a lab, and design a fix that closes the whole class of abuse.',
  project: 'Work through a curated set of legal web labs, then write a developer-ready report with evidence, root cause, and a test that proves the fix holds.',
  checkpoint: 'You can tell the difference between a symptom and a root cause, and prove that your fix actually closes the path.',
  resources: [
    { label: 'PortSwigger Web Security Academy (free)', href: 'https://portswigger.net/web-security' },
    { label: 'OWASP Top 10: 2025', href: 'https://owasp.org/Top10/' },
    { label: 'OWASP Cheat Sheet Series', href: 'https://cheatsheetseries.owasp.org/' },
  ],
  lessons: [
    {
      id: '05-1',
      title: 'The OWASP Top 10, 2025 edition',
      mins: 9,
      oneLine: 'A ranked awareness list of the ten risk categories that break web applications most often, refreshed for 2025.',
      like: 'The list of things a building inspector checks first, because that is where problems usually are.',
      body: [
        'The 2025 list, finalised in January 2026, reads: A01 Broken Access Control, A02 Security Misconfiguration, A03 Software Supply Chain Failures, A04 Cryptographic Failures, A05 Injection, A06 Insecure Design, A07 Authentication Failures, A08 Software and Data Integrity Failures, A09 Security Logging and Alerting Failures, A10 Mishandling of Exceptional Conditions.',
        'Two entries are new and both are significant. Software Supply Chain Failures entered at number three, replacing the narrower "vulnerable components" category — a recognition that attacks moved to build systems, dependencies and the tools everyone trusts. Mishandling of Exceptional Conditions is genuinely novel: it covers what happens when code meets a state its author did not expect, including failing open.',
        'Broken Access Control staying at number one is the important, boring truth. The most common serious web vulnerability is not clever. It is a page that forgets to check whether this particular user is allowed to see this particular thing.',
        'Security Misconfiguration rising to second reflects modern reality: applications are assembled from cloud services, containers and frameworks, each with defaults, and the defaults are rarely the safe choice.',
        'Use the list as a checklist for coverage, not as a syllabus of everything. It is deliberately a top ten, which means the eleventh risk is not safe — it just did not make the cut.',
      ],
      words: [
        { term: 'OWASP', means: 'A nonprofit producing free application security guidance.' },
        { term: 'CWE', means: 'A catalogue of weakness types that Top 10 categories are built from.' },
        { term: 'Awareness document', means: 'A prioritisation aid, not a complete standard.' },
        { term: 'ASVS', means: 'OWASP’s detailed verification standard — the thing to use when you need completeness.' },
      ],
      why: 'It is the shared vocabulary of application security. Reports, job interviews and developer conversations all assume you know it.',
      doThis: 'Read the OWASP Top 10 2025 introduction and one full category page. Note which of the ten you could not currently explain to a developer.',
      check: 'Why did Software Supply Chain Failures deserve its own category rather than staying inside "vulnerable components"?',
    },
    {
      id: '05-2',
      title: 'Broken access control',
      mins: 9,
      oneLine: 'The application knows who you are but forgets to check whether you should be allowed to do this particular thing.',
      like: 'A hotel that checks your ID at reception and then gives every guest a key that opens every room.',
      body: [
        'The classic form is IDOR — insecure direct object reference. A URL contains /invoice/1043, you change it to 1042, and you see someone else’s invoice. The application authenticated you but never asked whether this record is yours. This single bug has leaked enormous amounts of real data.',
        'Vertical escalation is reaching functions above your level: a normal user calling an admin endpoint that was only hidden from the menu, not actually protected. If security depends on the user not knowing a URL exists, there is no security.',
        'Force browsing and method tampering are variations. Try the endpoint directly. Change GET to POST or PUT. Remove a parameter. Add an unexpected one. Many frameworks route differently based on method, and only one of those paths got the check.',
        'The root cause is nearly always that authorisation is scattered across individual handlers rather than enforced centrally. Every new endpoint is another chance to forget. The fix is deny by default, a single enforcement layer that every request passes through, and ownership checks based on the session rather than on anything the client sent.',
        'Test it by having two accounts. Do something as user A, capture the request, replay it with user B’s session. If it works, you have found the most common serious web vulnerability there is.',
      ],
      words: [
        { term: 'IDOR', means: 'Changing an identifier in a request to reach someone else’s data.' },
        { term: 'Privilege escalation', means: 'Gaining rights you should not have.' },
        { term: 'Force browsing', means: 'Requesting URLs directly that the interface never showed you.' },
        { term: 'Deny by default', means: 'Everything is refused unless a rule explicitly permits it.' },
      ],
      why: 'It is number one on the Top 10 for good reason: it is easy to introduce, easy to exploit, and often leaks everything at once.',
      doThis: 'Complete the PortSwigger access control labs. They are free, legal, and go from obvious to genuinely subtle.',
      check: 'Why is hiding an admin link from the menu not access control?',
    },
    {
      id: '05-3',
      title: 'Injection: when data becomes instruction',
      mins: 9,
      oneLine: 'Injection happens whenever untrusted input is glued into something that gets interpreted — SQL, a shell, a template, an LDAP query.',
      like: 'Dictating a letter to someone who writes down everything you say, including "and now ignore the rest of this letter".',
      body: [
        'SQL injection is the archetype. Input concatenated into a query lets the attacker end the intended statement and add their own. Blind variants extract data one bit at a time using true/false differences or timing, without ever seeing an error message. Automated tools like sqlmap exploit this ruthlessly once a single injectable parameter exists.',
        'Command injection puts input into something the operating system runs. A filename field that ends up in a shell command means whoever controls the filename controls the server. This is why passing user input to system() or a shell is one of the most dangerous patterns in programming.',
        'Server-side template injection abuses template engines. If user input becomes part of the template rather than data passed to it, the engine will happily evaluate expressions — and many template engines can reach the runtime, turning a text field into remote code execution.',
        'The universal fix is separation: never mix instruction and data in the same string. Parameterised queries for SQL. Argument arrays instead of shell strings for commands. Templates that treat input strictly as values. Where separation is impossible, use a strict allow-list of known-good values, never a deny-list of bad ones.',
        'Deny-lists fail because encoding and context are endless. You cannot enumerate every dangerous input, but you can enumerate every acceptable one. That asymmetry is the whole design lesson.',
      ],
      words: [
        { term: 'Injection', means: 'Untrusted input changing the meaning of a command or query.' },
        { term: 'Blind injection', means: 'Extracting data through timing or true/false differences instead of visible output.' },
        { term: 'Allow-list', means: 'Permitting only known-good values.' },
        { term: 'RCE', means: 'Remote code execution — running your own code on someone else’s server.' },
      ],
      why: 'Injection has been on the Top 10 since it existed. The pattern recurs in every new technology, including AI prompts.',
      doThis: 'Work through the SQL injection labs on Web Security Academy, including a blind one. Then write the parameterised version of the vulnerable query.',
      check: 'What single design principle prevents SQL injection, command injection and template injection simultaneously?',
    },
    {
      id: '05-4',
      title: 'XSS, CSRF and browser trust',
      mins: 9,
      oneLine: 'Cross-site scripting runs the attacker’s code in your user’s browser; cross-site request forgery makes the browser act on its own credentials.',
      like: 'XSS is a stranger speaking with your voice inside your own house. CSRF is someone forging your signature on a form you never saw.',
      body: [
        'XSS comes in three shapes. Reflected: the payload is in the request and echoed straight back. Stored: it is saved on the server and served to every later visitor, which is by far the worst. DOM-based: the server never sees it, because client-side JavaScript takes something from the URL and writes it into the page unsafely.',
        'Because the injected script runs in the site’s origin, it can read the DOM, steal session tokens not protected by HttpOnly, make authenticated requests, and rewrite what the user sees. "It only pops an alert box" is a demonstration, not a limit.',
        'The defence is context-aware output encoding: escape data differently depending on whether it lands in HTML, an attribute, JavaScript, a URL or CSS. Modern frameworks do this by default, which is why the remaining bugs cluster around the places developers deliberately bypass it — innerHTML, dangerouslySetInnerHTML, v-html. A strong Content Security Policy is a valuable second layer.',
        'CSRF works differently. The browser automatically attaches cookies to requests, so a hostile page can trigger a request to your bank and the browser will authenticate it for them. The classic fix is an anti-CSRF token the attacker cannot read. The modern structural fix is SameSite cookies, which stop the browser sending the cookie cross-site in the first place.',
        'Note that these two defend against opposite things, and one can undo the other: if you have XSS, CSRF tokens are worthless, because the attacker’s script can simply read the token. Fix XSS first.',
      ],
      words: [
        { term: 'XSS', means: 'Getting your JavaScript to run in another user’s browser session.' },
        { term: 'Stored XSS', means: 'The payload is saved server-side and served to many victims.' },
        { term: 'CSRF', means: 'Tricking a browser into making an authenticated request the user did not intend.' },
        { term: 'CSP', means: 'Content Security Policy — a header restricting what scripts a page may run.' },
      ],
      why: 'These are the two oldest web attacks and they still work, because the browser trust model they abuse has not fundamentally changed.',
      doThis: 'Complete the reflected, stored and DOM-based XSS labs. Then add a CSP header to a test page and watch which payloads stop working.',
      check: 'Why does having an XSS vulnerability make your CSRF protection irrelevant?',
    },
    {
      id: '05-5',
      title: 'SSRF, XXE, deserialisation and file handling',
      mins: 9,
      oneLine: 'Four ways to make a server fetch, parse or reconstruct something it should never have touched.',
      like: 'Persuading a trusted employee to open the internal safe and read the contents out to you, because you asked politely and from the right desk.',
      body: [
        'SSRF — server-side request forgery — is when you control a URL the server fetches. Because the request comes from inside, it can reach internal services, admin panels and, in cloud environments, the instance metadata endpoint that hands out credentials. SSRF is how several very large cloud breaches actually happened.',
        'Defending SSRF properly means an allow-list of permitted destinations, resolving and validating the address after DNS resolution to defeat rebinding, blocking internal ranges, disabling redirects, and — in cloud — enforcing IMDSv2 so metadata cannot be read with a simple GET.',
        'XXE — XML external entity — abuses XML parsers that follow external references. A crafted document can read local files, or make the server issue requests. The fix is one line in most languages: disable external entity resolution. It is almost always on by default for historical reasons.',
        'Insecure deserialisation is turning attacker-controlled bytes back into live objects. During reconstruction, code can run before any of your validation happens. Java, PHP, Python pickle and .NET have all had catastrophic versions of this. Never deserialise untrusted data with a format that can carry code; use plain JSON with an explicit schema.',
        'File upload combines several of these. Validate type by content rather than extension, generate your own filename, store outside the web root, never let uploads be executed, and scan them. "Path traversal" — a filename containing ../ — is the oldest trick here and still finds new victims every year.',
      ],
      words: [
        { term: 'SSRF', means: 'Making the server fetch a URL you choose.' },
        { term: 'IMDS', means: 'Cloud instance metadata service, which can hand out credentials.' },
        { term: 'Deserialisation', means: 'Rebuilding objects from stored bytes.' },
        { term: 'Path traversal', means: 'Using ../ to escape an intended directory.' },
      ],
      why: 'These bugs tend to be critical rather than moderate: they often lead directly to credentials, internal access, or code execution.',
      doThis: 'Do the SSRF labs on Web Security Academy, including the one reaching an internal admin interface. Then read your cloud provider’s metadata hardening guidance.',
      check: 'Why is SSRF far more dangerous in a cloud environment than on a standalone server?',
    },
    {
      id: '05-6',
      title: 'API security: REST, GraphQL and the new perimeter',
      mins: 9,
      oneLine: 'APIs expose business logic directly, without a user interface to hide behind, and they are now the majority of web traffic.',
      like: 'A restaurant that lets customers call the kitchen directly. Faster, but now every cook needs to check who is asking.',
      body: [
        'The OWASP API Security Top 10 exists because APIs fail differently. The top two are Broken Object Level Authorisation — the API version of IDOR, at scale and automatable — and Broken Authentication. Both are authorisation problems, not exotic ones.',
        'Broken Object Property Level Authorisation covers two habits: returning more fields than the client needs and letting the client set fields it should not. Mass assignment — sending "role": "admin" in a JSON body and having the framework helpfully bind it — is the classic version.',
        'GraphQL adds its own surface. Introspection can reveal the entire schema. Deeply nested queries can be used for denial of service. Batching can defeat rate limiting on login endpoints. Field-level authorisation is essential because a single query can traverse many objects across many resolvers.',
        'Common API mistakes worth checking every time: missing rate limits, verbose errors that leak stack traces or internal identifiers, old unversioned endpoints still running, undocumented "shadow" APIs, and authentication enforced at the gateway but not at the service behind it.',
        'Test APIs directly rather than through the interface. Read the OpenAPI or GraphQL schema, enumerate endpoints, and try each one with a low-privilege token. The user interface is not a security control and never was.',
      ],
      words: [
        { term: 'BOLA', means: 'Broken Object Level Authorisation — the API version of IDOR.' },
        { term: 'Mass assignment', means: 'The client setting fields it should not be allowed to set.' },
        { term: 'Introspection', means: 'A GraphQL feature that reveals the whole schema.' },
        { term: 'Shadow API', means: 'An undocumented endpoint nobody is monitoring.' },
      ],
      why: 'Most modern applications are an API with a thin interface on top. Testing only the interface leaves most of the attack surface untouched.',
      doThis: 'Find a public API with documentation, read its OpenAPI spec, and map which endpoints change data versus read it. Note which ones would be dangerous without authorisation.',
      check: 'Why does testing through the web interface miss most API vulnerabilities?',
    },
    {
      id: '05-7',
      title: 'Supply chain and integrity failures',
      mins: 9,
      oneLine: 'Your application is mostly other people’s code, and attacking the code you trust is easier than attacking the code you wrote.',
      like: 'Poisoning the flour supplier rather than breaking into every bakery.',
      body: [
        'A typical application has hundreds of transitive dependencies. Each one is code you run with full trust and rarely read. Software Supply Chain Failures entered the 2025 Top 10 at number three because attackers noticed this asymmetry and industrialised it.',
        'Attack shapes to recognise: typosquatting a popular package name, taking over an abandoned package, compromising a maintainer account, poisoning the build system so the artefact differs from the source, and dependency confusion where a public package shadows a private internal name.',
        'Software and Data Integrity Failures — A08 — is the related category: accepting updates, plugins or data without verifying who produced them. Auto-updating from an unverified source, or deserialising signed-looking data you never actually checked, both belong here.',
        'The defences are concrete. Pin exact versions and use lockfiles. Generate an SBOM so you know what you actually ship. Verify signatures with Sigstore or similar. Use SLSA levels as a maturity target for build integrity. Isolate your build environment, because a compromised CI runner can rewrite anything.',
        'Log4Shell is the case study worth understanding fully: a logging library used almost everywhere, a feature nobody knew was there, and a one-line payload giving remote code execution. The lesson was not "patch faster" — it was "you cannot patch what you cannot inventory".',
      ],
      words: [
        { term: 'Transitive dependency', means: 'A library pulled in by another library you chose.' },
        { term: 'SBOM', means: 'Software Bill of Materials — a list of everything in your software.' },
        { term: 'Dependency confusion', means: 'A public package impersonating a private internal one.' },
        { term: 'SLSA', means: 'A framework of levels for build and supply chain integrity.' },
      ],
      why: 'You can write flawless code and still be compromised through a dependency. This is now one of the most active attack paths in the industry.',
      doThis: 'Run "npm audit" or "pip-audit" on any project. Then generate an SBOM with Syft and count how many packages you did not know you depended on.',
      check: 'Why does pinning versions help, and what does it fail to protect against on its own?',
    },
    {
      id: '05-8',
      title: 'Secure design, testing and shipping the fix',
      mins: 9,
      oneLine: 'Finding a bug is a quarter of the work; the rest is fixing the cause, proving the fix, and stopping it coming back.',
      like: 'A leak in a ceiling. Mopping the floor is not the repair, and the repair is not finished until it rains again and stays dry.',
      body: [
        'Insecure Design — A06 — is the category for flaws you cannot patch, because the idea itself was wrong. A password reset that relies on a guessable question, a checkout that trusts a client-supplied price. No amount of input validation fixes those; the design must change. This is what threat modelling in stage 04 is for.',
        'Know what each kind of testing can and cannot see. SAST reads source and finds patterns but produces false positives. DAST attacks a running application and finds real behaviour but misses what it cannot reach. SCA checks dependencies. IAST instruments the running app. Manual testing finds logic flaws that none of the tools can, because tools do not understand business rules.',
        'Mishandling of Exceptional Conditions — the new A10 — deserves attention because it is genuinely under-examined. What happens when the database is down, the token service times out, or a value is null? Failing open is the dangerous pattern: an authorisation check that errors and returns "allow" is worse than no check at all, because it looks correct.',
        'Logging and Alerting Failures — A09 — is the difference between an incident and an unnoticed breach. Log authentication events, access control failures, and input validation failures with enough context to investigate, without logging the secrets themselves. Then confirm someone actually receives the alert.',
        'When you report a finding, developers need four things: how to reproduce it, what the impact really is, the root cause, and a concrete fix. Then verify the fix by retesting, and add a regression test so the next release cannot quietly reintroduce it.',
      ],
      words: [
        { term: 'SAST / DAST', means: 'Static analysis of code / dynamic testing of a running app.' },
        { term: 'Fail open / fail closed', means: 'On error, allow access / deny access. Prefer closed.' },
        { term: 'Regression test', means: 'A test that fails if an old bug returns.' },
        { term: 'Root cause', means: 'The underlying reason, not the visible symptom.' },
      ],
      why: 'Reports that get fixed share the same qualities, and reports that get ignored share the opposite ones. This is a writing skill as much as a technical one.',
      doThis: 'Take any lab vulnerability you solved and write a one-page report: reproduction, impact, root cause, fix, and a test that would catch it returning.',
      check: 'Why is an authorisation check that fails open more dangerous than having no check at all?',
    },
  ],
};
