import type { Stage } from './types';

export const s06: Stage = {
  number: '06',
  title: 'Attacking, with permission',
  subtitle: 'Penetration testing from scope to report — recon, exploitation, Active Directory, cleanup',
  level: 'HARD',
  tags: ['OFFENSE', 'RESEARCH'],
  weeks: 6,
  hours: 80,
  hue: 350,
  plain: 'Testing like an attacker, inside legal boundaries, so defenders find out what is broken before a criminal does.',
  outcome: 'You can run a controlled assessment from rules of engagement to an evidence-backed report, without breaking what you were hired to protect.',
  project: 'Assess an intentionally vulnerable lab environment, chain at least two weaknesses into real impact, clean up after yourself, and deliver both an executive and a technical report.',
  checkpoint: 'You can state scope, prove impact safely, preserve evidence, stop at boundaries, and recommend fixes a developer can act on.',
  resources: [
    { label: 'PTES technical guidelines', href: 'http://www.pentest-standard.org/' },
    { label: 'HackTricks methodology notes', href: 'https://book.hacktricks.wiki/' },
    { label: 'Hack The Box Academy', href: 'https://academy.hackthebox.com/' },
  ],
  lessons: [
    {
      id: '06-1',
      title: 'Scope, method and not causing harm',
      mins: 8,
      oneLine: 'A professional test is defined by its paperwork before it is defined by its tools.',
      like: 'A demolition crew does not start swinging until the permits, the plans and the exclusion zone are agreed.',
      body: [
        'Rules of engagement fix the boundaries: exactly which systems and addresses are in scope, which techniques are permitted, which are forbidden, when testing may run, who to contact immediately if something breaks, and how findings will be handled. Get it signed by someone with actual authority over those systems.',
        'Some things are almost always excluded and you should raise them explicitly: denial of service, social engineering against staff, physical entry, and anything touching production data or safety systems. Ambiguity here is how testers end up in genuine legal trouble.',
        'Follow a methodology so your coverage is defensible rather than lucky. PTES, the OWASP Testing Guide, and the OSSTMM all give you a repeatable structure: reconnaissance, enumeration, vulnerability analysis, exploitation, post-exploitation, reporting. Ad-hoc testing finds what you happened to think of.',
        'Take notes continuously — every command, every timestamp, every finding. When a client asks "did you cause this outage at 14:20?", your log is the only answer that helps. Tools like a simple timestamped terminal log are enough; discipline matters more than tooling.',
        'Minimise impact deliberately. Prove a vulnerability exists without exhausting it: read one record, not the table. Take a screenshot, not a copy of the database. The goal is evidence sufficient to convince, and nothing beyond it.',
      ],
      words: [
        { term: 'Rules of engagement', means: 'The signed agreement defining what you may do.' },
        { term: 'Scope creep', means: 'Testing drifting into systems that were never authorised.' },
        { term: 'PTES', means: 'Penetration Testing Execution Standard — a common methodology.' },
        { term: 'Proof of concept', means: 'The minimum demonstration that a flaw is real.' },
      ],
      why: 'The difference between a respected professional and a liability is almost never skill. It is discipline about boundaries and evidence.',
      doThis: 'Write a full rules-of-engagement document for a fictional client, including out-of-scope systems, emergency contacts, and testing hours.',
      check: 'You find a vulnerability on a system that was not in scope. What do you do, and what must you not do?',
    },
    {
      id: '06-2',
      title: 'Reconnaissance and OSINT',
      mins: 8,
      oneLine: 'Before touching anything, you learn everything about the target that is already public.',
      like: 'A film crew scouting a location for weeks before a single camera arrives.',
      body: [
        'Passive reconnaissance never touches the target. Certificate transparency logs reveal subdomains, because every issued certificate is published. DNS records, WHOIS data, public code repositories, job adverts describing internal technology, LinkedIn profiles listing tools — all of it is free intelligence.',
        'Attack surface mapping is the practical output: every domain, subdomain, IP range, cloud bucket, exposed service and third-party integration that belongs to the target. Organisations are consistently surprised by this list, because nobody owns the inventory.',
        'Shodan and Censys index internet-facing devices continuously. Searching for an organisation’s name or address range often reveals forgotten servers, exposed admin panels and industrial equipment that was never meant to be reachable.',
        'Breach data matters. Credentials leaked from unrelated services get reused, and a single valid password in an exposed corporate account can be worth more than every technical vulnerability you might find. Handle this material carefully and only within scope.',
        'Active reconnaissance touches the target directly and generates logs. It is louder, so it comes after passive work, and only once you are certain you are inside scope. Confusing the two is how testers accidentally scan someone else’s network.',
      ],
      words: [
        { term: 'OSINT', means: 'Open source intelligence — information gathered from public sources.' },
        { term: 'Certificate transparency', means: 'Public logs of issued certificates, useful for finding subdomains.' },
        { term: 'Attack surface', means: 'Everything belonging to the target that can be reached.' },
        { term: 'Passive vs active', means: 'Not touching the target versus interacting with it.' },
      ],
      why: 'Real attackers spend most of their effort here. The forgotten server nobody remembers owning is a far more likely entry point than a novel exploit.',
      doThis: 'Pick a company that runs a public bug bounty programme. Using only passive sources, map their subdomains with crt.sh. Do not scan anything.',
      check: 'Why can certificate transparency logs reveal internal-sounding hostnames the organisation never intended to publish?',
    },
    {
      id: '06-3',
      title: 'Scanning and enumeration',
      mins: 9,
      oneLine: 'Find what is listening, work out exactly what it is, and turn a list of ports into a list of possibilities.',
      like: 'Walking the perimeter of a building noting every door, window and vent — then checking what each one is made of.',
      body: [
        'Nmap is the standard tool. A basic sweep finds live hosts; a SYN scan finds open ports quickly; service detection identifies what is running and often the exact version. Full port scans matter because interesting things hide on unusual ports precisely to avoid casual scanning.',
        'Enumeration is the step beginners rush and professionals dwell on. An open port is a starting point, not a finding. What version? What configuration? What default credentials? What does it expose without authentication? Ninety percent of successful tests come from thorough enumeration, not clever exploitation.',
        'Learn the high-value services and what to ask each one. SMB shares and null sessions. LDAP for directory information. SNMP with default community strings, which still leak entire device configurations. NFS exports. Web servers with directory listings, admin panels, and forgotten backup files.',
        'Web enumeration deserves its own attention: directory and file discovery, virtual host discovery, parameter discovery, and reading JavaScript files for hidden endpoints. Front-end code frequently references API paths the developers assumed nobody would look at.',
        'Scanning is noisy and it can break fragile things. Industrial and medical devices have been knocked offline by ordinary scans. Know your target, control your rate, and never assume a scan is harmless.',
      ],
      words: [
        { term: 'Port scan', means: 'Checking which network ports are open on a host.' },
        { term: 'Service enumeration', means: 'Identifying exactly what software and version is listening.' },
        { term: 'Banner grabbing', means: 'Reading the identifying text a service announces.' },
        { term: 'Null session', means: 'Connecting to a service without credentials to extract information.' },
      ],
      why: 'The quality of your enumeration determines the quality of your test. Everything downstream depends on knowing precisely what you are facing.',
      doThis: 'In your lab, run nmap against your vulnerable VM with service and version detection. For every open port, write one sentence about what it is and what you would check next.',
      check: 'Why is a service version number often more valuable than the fact that the port is open?',
    },
    {
      id: '06-4',
      title: 'Exploitation and validating impact',
      mins: 9,
      oneLine: 'Exploitation is proving a weakness is real; the discipline is proving it without causing damage.',
      like: 'A structural engineer demonstrating that a beam is unsafe, without dropping the building to make the point.',
      body: [
        'Start by matching what you found to known vulnerabilities: version numbers to CVEs, default credentials to services, misconfigurations to known abuse paths. Public exploit code exists for much of it, and reading that code before running it is not optional — plenty of "exploits" online are backdoored.',
        'Metasploit is a framework of modules for exploitation and post-exploitation. It is efficient, and it teaches bad habits if it is all you know. Understand what the module actually does, because in a real test you will meet things no module covers.',
        'Password attacks are frequently the shortest path. Credential stuffing with breach data, password spraying one common password across many accounts to avoid lockouts, and cracking captured hashes offline with Hashcat. Spraying in particular defeats naive lockout policies and is a favourite in real intrusions.',
        'Impact must be validated, not assumed. "Port 445 is open" is not a finding. "Using these credentials I obtained domain administrator and could read this file" is. Business impact is what makes a report actionable, and it is what the client is actually paying for.',
        'Stop at the point of proof. Do not pivot beyond scope. Do not exfiltrate real data. Do not disable security tooling. Every one of those has ended engagements badly, and none of them were necessary to demonstrate the risk.',
      ],
      words: [
        { term: 'Exploit', means: 'Code or a technique that takes advantage of a vulnerability.' },
        { term: 'Payload', means: 'What runs after successful exploitation.' },
        { term: 'Password spraying', means: 'Trying one common password across many accounts to avoid lockout.' },
        { term: 'Proof of exploitation', means: 'Evidence the flaw is genuinely usable, gathered with minimum impact.' },
      ],
      why: 'Findings that are not validated get dismissed as scanner noise. Findings that cause outages get you fired. The narrow path between is the profession.',
      doThis: 'In your lab, exploit one known-vulnerable service. Write down what you did, what proof you captured, and what you deliberately chose not to do.',
      check: 'Why is password spraying more effective against a lockout policy than brute forcing one account?',
    },
    {
      id: '06-5',
      title: 'Privilege escalation on Linux',
      mins: 9,
      oneLine: 'You landed as a low-privilege user; now you look for the one misconfiguration that makes you root.',
      like: 'Being let into the lobby and finding the cleaner’s master key taped under a desk.',
      body: [
        'Enumerate first, always. What user are you? What groups? What can you run with sudo? What is scheduled in cron? What SetUID binaries exist? What is listening only on localhost? Tools like LinPEAS automate this, but understanding the categories is what lets you spot the unusual case.',
        'Sudo misconfiguration is the most common quick win. A user allowed to run a specific program as root often escalates trivially, because many programs can spawn a shell or read arbitrary files. GTFOBins catalogues exactly which binaries can be abused and how.',
        'Weak file permissions come next: a world-writable script that root executes on a schedule, a configuration file containing credentials, a service binary you can replace. Also check PATH manipulation, where a script calls a command without a full path and you control an earlier directory in PATH.',
        'Credentials are everywhere once you look: shell history files, configuration files, environment variables, backup files, and the .git directory of a deployed application. This is usually faster than any kernel exploit.',
        'Kernel exploits are the last resort. They are version-specific, often unstable, and can crash the machine — which in a real engagement means an outage you caused. Prefer configuration paths, and if you must use a kernel exploit, get explicit agreement first.',
      ],
      words: [
        { term: 'Privilege escalation', means: 'Moving from limited access to full control.' },
        { term: 'GTFOBins', means: 'A catalogue of standard binaries that can be abused to escalate.' },
        { term: 'Cron job', means: 'A scheduled task, often running as root.' },
        { term: 'PATH hijacking', means: 'Getting your own program run instead of the intended one.' },
      ],
      why: 'Initial access is rarely privileged. The value of a test usually depends on demonstrating what an attacker could reach afterwards.',
      doThis: 'Run LinPEAS in your lab VM and read the whole output once, slowly. Look up anything highlighted that you do not recognise.',
      check: 'Why is a writable cron script owned by root a critical finding rather than a minor one?',
    },
    {
      id: '06-6',
      title: 'Windows and Active Directory',
      mins: 10,
      oneLine: 'Corporate networks run on Active Directory, and attacking identity relationships beats attacking machines.',
      like: 'A company where everyone’s keycard permissions were set up over fifteen years and nobody kept the map. Somewhere, an intern can open the vault.',
      body: [
        'AD stores users, computers, groups and policies, and Kerberos authenticates them with tickets. The security problem is not usually a single vulnerability — it is the accumulated graph of who can control what, which nobody has ever fully reviewed.',
        'Kerberoasting is the signature technique: any authenticated user can request a service ticket for an account that has a service principal name, then crack it offline. Service accounts frequently have weak, never-rotated passwords and excessive privileges, which makes this remarkably reliable.',
        'AS-REP roasting targets accounts with pre-authentication disabled, yielding crackable material without any credentials at all. Both techniques are quiet, both are old, and both still work in a large share of real environments.',
        'Credential theft drives lateral movement. Tools can extract hashes and tickets from memory on a compromised machine. Pass-the-hash and pass-the-ticket let you authenticate as that user without ever knowing the password — which is why the password policy is not the control you thought it was.',
        'BloodHound is the tool that changed this discipline. It maps the relationships and computes attack paths — "this ordinary user can reset that password, whose owner can write to that group, which administers the domain controller". Defenders should run it too, and most of the findings are permissions granted years ago for a reason nobody remembers.',
        'The defensive counterparts are worth learning at the same time: tiered administration, dedicated admin workstations, group Managed Service Accounts with automatic long passwords, LAPS for unique local administrator passwords, and removing the standing privileges that make these paths exist.',
      ],
      words: [
        { term: 'Kerberos ticket', means: 'The token Windows uses to prove identity to a service.' },
        { term: 'Kerberoasting', means: 'Requesting service tickets and cracking them offline.' },
        { term: 'Pass-the-hash', means: 'Authenticating with a stolen password hash instead of the password.' },
        { term: 'BloodHound', means: 'A tool that maps Active Directory attack paths as a graph.' },
      ],
      why: 'Active Directory is the crown jewel of most corporate networks. Compromising it usually means compromising everything at once.',
      doThis: 'Build a small AD lab with a domain controller and two clients, or use a prepared range. Run BloodHound and follow one shortest path to domain admin.',
      check: 'Why does pass-the-hash mean a strong password policy alone does not protect an account?',
    },
    {
      id: '06-7',
      title: 'Pivoting and chaining weaknesses',
      mins: 9,
      oneLine: 'Real impact usually comes from several medium problems connected together, not from one critical bug.',
      like: 'A chain of small favours: each one reasonable on its own, and together they let a stranger walk out with the safe.',
      body: [
        'Pivoting means using a compromised machine as a route into networks you cannot otherwise reach. SSH tunnels, SOCKS proxies and tools like Chisel or Ligolo forward traffic through your foothold, making internal-only systems reachable from your own machine.',
        'Chaining is the analytical skill. An information disclosure gives you a username format. A password spray gives you one weak account. That account can read a share containing a configuration file. The file contains a service credential. The service is privileged. None of those alone would rate as critical.',
        'This is why severity ratings on individual findings can mislead. A good report shows the chain and rates the chain, because that is what an attacker will actually do. Clients frequently deprioritise "medium" findings that were three steps from catastrophe.',
        'Persistence is what an attacker sets up to survive reboots and password changes: scheduled tasks, services, registry autoruns, SSH keys, additional accounts. In an authorised test you must document every single one and remove them all. This is a professional obligation, not a courtesy.',
        'Detection is part of the exercise too. Note what you did that generated alerts and what did not. A test that reveals the defenders never noticed the domain compromise is often more valuable than the compromise itself.',
      ],
      words: [
        { term: 'Pivot', means: 'Using one compromised host to reach further into a network.' },
        { term: 'Attack chain', means: 'A sequence of weaknesses combined into real impact.' },
        { term: 'Persistence', means: 'Ensuring access survives reboots and password changes.' },
        { term: 'Detection gap', means: 'Something an attacker did that nobody noticed.' },
      ],
      why: 'Thinking in chains is the difference between a scanner report and a security assessment.',
      doThis: 'In your lab, deliberately chain three low-severity issues into one meaningful outcome. Write the chain as a numbered narrative.',
      check: 'Why can three medium-severity findings justify a critical rating when combined?',
    },
    {
      id: '06-8',
      title: 'Cleanup, reporting and purple teaming',
      mins: 9,
      oneLine: 'The report is the product; everything before it was research.',
      like: 'A surgeon who operates brilliantly and writes no notes has helped one patient once, and taught nobody anything.',
      body: [
        'Clean up completely and verifiably. Remove every account, tool, shell, scheduled task and configuration change you made. Keep a checklist as you go, because you will not remember at the end of a two-week engagement, and leftover access is a genuine liability for both sides.',
        'The report has two audiences. Executives need the business risk, what it would cost, and what to do first — one page, no jargon. Technical staff need reproduction steps, evidence, affected systems, root cause and specific remediation. Writing one document for both audiences serves neither.',
        'Each finding should carry: a clear title, severity with reasoning, affected assets, reproduction steps someone else can follow, evidence such as screenshots or output, actual impact, and a fix that is specific enough to implement. "Improve input validation" is not a fix.',
        'Retesting closes the loop. A finding is not resolved because a ticket was closed; it is resolved when you verify the fix and confirm it did not simply move the problem elsewhere.',
        'Purple teaming is where the field is heading. Rather than an adversarial exercise with a report at the end, attackers and defenders work together: run a technique, check whether it was detected, tune the detection, run it again. It produces measurable defensive improvement instead of an annual document that gets filed.',
      ],
      words: [
        { term: 'Executive summary', means: 'The business-level explanation, written without jargon.' },
        { term: 'Reproduction steps', means: 'Instructions precise enough for someone else to repeat the finding.' },
        { term: 'Retest', means: 'Verifying that a fix genuinely closed the issue.' },
        { term: 'Purple team', means: 'Attackers and defenders working together to improve detection.' },
      ],
      why: 'Clients remember the report. It is the artefact that persists, gets forwarded, and determines whether anything actually improves.',
      doThis: 'Write a complete two-page report for one lab finding: executive summary, technical detail, evidence, remediation, retest plan.',
      check: 'Why is a purple team exercise often more valuable to a mature organisation than a traditional penetration test?',
    },
  ],
};
