import type { Stage } from './types';

export const s07: Stage = {
  number: '07',
  title: 'Defending and detecting',
  subtitle: 'Logs, SIEM, MITRE ATT&CK, detection engineering and SOC triage',
  level: 'HARD',
  tags: ['DEFENSE', 'BUILD'],
  weeks: 6,
  hours: 75,
  hue: 155,
  plain: 'Attacks will get through. This stage is about seeing them happen, deciding fast whether it is real, and stopping it spreading.',
  outcome: 'You can turn endpoint, identity, network and cloud telemetry into detections that fire on real behaviour instead of on noise.',
  project: 'Build a small detection lab with normalised logs, write five detections mapped to ATT&CK techniques, and document your triage and tuning decisions.',
  checkpoint: 'For any alert you write, you can state the hypothesis, the data source, the blind spots, the triage path and the response.',
  resources: [
    { label: 'MITRE ATT&CK', href: 'https://attack.mitre.org/' },
    { label: 'Sigma detection rules', href: 'https://github.com/SigmaHQ/sigma' },
    { label: 'Atomic Red Team (safe technique tests)', href: 'https://atomicredteam.io/' },
  ],
  lessons: [
    {
      id: '07-1',
      title: 'Telemetry: you can only detect what you collect',
      mins: 8,
      oneLine: 'Detection begins with a decision about what to record, and most detection failures are really collection failures.',
      like: 'Security cameras. The clever software does not matter if the camera was never pointed at the door.',
      body: [
        'The highest-value sources, roughly in order: endpoint process creation with command lines, authentication and identity events, DNS queries, network flows, cloud control-plane audit logs, and application logs. If you only had process creation and identity, you could still catch a surprising share of real intrusions.',
        'On Windows, native logging is not enough by default. Sysmon adds process creation with hashes and parent lineage, network connections per process, and file and registry changes. Turning on PowerShell script block logging and command line auditing costs nothing and transforms visibility.',
        'On Linux, auditd or eBPF-based tooling gives similar coverage. In cloud, the control plane audit log — CloudTrail, Azure Activity, GCP Audit Logs — is the single most important source, because that is where identity abuse and privilege changes appear.',
        'Data quality decides whether any of it is usable. Timestamps must be synchronised and stored in a single timezone, or your timeline will be fiction. Fields must be normalised so a username means the same thing across sources. Missing context — no hostname, no user, no parent process — turns an alert into an unanswerable question.',
        'Retention is a real constraint. Intrusions are often discovered months after they began, so thirty days of logs means you cannot investigate your own breach. Balance cost against the practical minimum, and keep the highest-value sources longest.',
      ],
      words: [
        { term: 'Telemetry', means: 'The signals and logs you collect from systems.' },
        { term: 'Sysmon', means: 'A Windows tool that adds detailed process and network logging.' },
        { term: 'Normalisation', means: 'Making fields from different sources mean the same thing.' },
        { term: 'Retention', means: 'How long logs are kept before deletion.' },
      ],
      why: 'Every detection is a query against data. No data, no detection — and you will not find out until you are investigating something that matters.',
      doThis: 'Install Sysmon with a good public configuration on a Windows VM. Run a few normal programs and read the resulting events, especially the parent-child relationships.',
      check: 'Why does a thirty-day retention policy create a serious investigation problem?',
    },
    {
      id: '07-2',
      title: 'SIEM: making a million logs answer a question',
      mins: 8,
      oneLine: 'A SIEM collects logs centrally, normalises them, and lets you search and correlate across everything at once.',
      like: 'A newspaper archive with a good index. The value is not the paper, it is being able to ask a question and get an answer.',
      body: [
        'The pipeline is always the same: collect, parse, normalise, enrich, store, search, alert. Products differ in query language and price, not in concept. Splunk, Microsoft Sentinel, Elastic and open-source stacks like Wazuh all do this shape of work.',
        'Correlation is the point. One failed login is noise. Fifty failed logins across fifty accounts from one address, followed by one success and then a new administrative group membership, is a story. Correlation rules exist to assemble stories from events that are individually meaningless.',
        'Enrichment turns raw fields into decisions. Add asset criticality, owner, geolocation, threat intelligence matches and user department. An analyst who has to open four other tools to understand an alert will triage far fewer alerts per hour, and quality drops with fatigue.',
        'Learn one query language properly. KQL for Sentinel, SPL for Splunk, Lucene or ES|QL for Elastic. The concepts transfer — filter, aggregate, join, time-window — so depth in one gives you competence in all of them.',
        'The dominant failure mode is alert fatigue. A SIEM producing thousands of daily alerts trains analysts to close them without reading. Fewer, better alerts genuinely beat more coverage on paper, and tuning is not a sign of weakness.',
      ],
      words: [
        { term: 'SIEM', means: 'Security Information and Event Management — central log search and alerting.' },
        { term: 'Correlation rule', means: 'Logic linking multiple events into one meaningful alert.' },
        { term: 'Enrichment', means: 'Adding context to raw log data.' },
        { term: 'Alert fatigue', means: 'So many alerts that real ones get ignored.' },
      ],
      why: 'The SIEM is the SOC’s workbench. Fluency in querying it is the core day-to-day skill of a defender.',
      doThis: 'Set up a free Elastic or Wazuh instance, ship your VM logs into it, and write three queries: failed logins by user, new processes by parent, outbound connections by destination.',
      check: 'Why can reducing the number of alerts improve security rather than weaken it?',
    },
    {
      id: '07-3',
      title: 'MITRE ATT&CK as a working tool',
      mins: 8,
      oneLine: 'A catalogue of what attackers actually do, which lets you measure your detection coverage instead of guessing at it.',
      like: 'A list of every move a burglar is known to use, so you can check which ones your cameras would catch.',
      body: [
        'The structure is tactics and techniques. A tactic is the goal — initial access, persistence, credential access, lateral movement, exfiltration. A technique is the method used to achieve it, with sub-techniques for specific variants. Everything is observed in real incidents, not invented.',
        'Version 18, released in October 2025, restructured detection guidance significantly: it introduced Detection Strategies describing the high-level approach for a technique, and Analytics giving platform-specific logic. It also fully deprecated the old data source objects, so older mappings need revisiting.',
        'The main defensive use is coverage mapping. For each technique relevant to your environment, ask: do we collect the data needed? Do we have a detection? Has it been tested? Colour the matrix honestly and the gaps become a work plan rather than an anxiety.',
        'Prioritise rather than chasing the whole matrix. Use threat intelligence about groups that actually target your sector, and focus on techniques that are hard for attackers to avoid — credential dumping, persistence mechanisms, and abuse of remote services all appear in a large share of real intrusions.',
        'Beware coverage theatre. A rule that exists but has never been tested against a real technique execution is not coverage. This is exactly why Atomic Red Team exists: run the technique safely and check whether the alert fires.',
      ],
      words: [
        { term: 'Tactic', means: 'The attacker’s goal at a stage of the intrusion.' },
        { term: 'Technique', means: 'The specific method used to achieve that goal.' },
        { term: 'Coverage map', means: 'An honest picture of which techniques you can detect.' },
        { term: 'Atomic test', means: 'A small safe script that simulates one technique.' },
      ],
      why: 'ATT&CK converts "are we secure?" — which is unanswerable — into "which of these specific behaviours would we catch?", which is measurable.',
      doThis: 'Pick five techniques relevant to Windows endpoints. For each, check whether your lab collects the required data and whether anything would alert.',
      check: 'Why is an untested detection rule not the same as detection coverage?',
    },
    {
      id: '07-4',
      title: 'Writing detections that survive contact',
      mins: 9,
      oneLine: 'Good detections describe attacker behaviour, not one specific tool — because tools change and behaviour is harder to avoid.',
      like: 'Recognising a burglar by how they move, not by the brand of their crowbar.',
      body: [
        'David Bianco’s Pyramid of Pain ranks indicator types by how much they cost an attacker to change. Hashes are trivial to alter, addresses and domains are cheap, tools take effort, and tactics and behaviours are genuinely painful. Detections aimed at the top of the pyramid last longer.',
        'A concrete example: alerting on a specific malicious hash is defeated by recompiling. Alerting on "a Microsoft Office process spawning a scripting engine which then makes an outbound connection" catches an entire family of phishing chains, regardless of the specific payload.',
        'Every rule needs a testable hypothesis stated in words first: "when an attacker dumps credentials from LSASS, another process opens a handle to it with specific access rights". Write that sentence before writing the query, and the query almost writes itself.',
        'Sigma is the portable format for sharing detections. Write once in YAML, convert to the query language of whichever platform you use. It also gives you access to a large community rule set, which is an excellent way to learn what good detection logic looks like.',
        'Tuning is continuous. Every rule needs known-good exceptions, and every exception needs a documented reason — because in a year, nobody will remember why that path was excluded, and attackers eventually learn to live in whatever your exclusions permit.',
      ],
      words: [
        { term: 'Pyramid of Pain', means: 'A model ranking indicators by how costly they are for attackers to change.' },
        { term: 'Sigma', means: 'A portable YAML format for detection rules.' },
        { term: 'False positive', means: 'An alert on benign activity.' },
        { term: 'Detection as code', means: 'Managing rules in version control with testing, like software.' },
      ],
      why: 'Indicator-based detection expires within days. Behaviour-based detection keeps working across campaigns and tools.',
      doThis: 'Write one Sigma rule for a technique you understand well. Run the matching Atomic Red Team test in your lab and confirm it fires.',
      check: 'Why does a detection based on a file hash provide much weaker long-term value than one based on process lineage?',
    },
    {
      id: '07-5',
      title: 'Endpoint and identity signals',
      mins: 8,
      oneLine: 'Most attacks touch an endpoint and almost all of them touch identity, which makes these the two richest places to watch.',
      like: 'Watching the doors and the staff badges, rather than trying to watch every corridor.',
      body: [
        'EDR tools record process trees, file and registry changes, network connections and memory activity, then apply behavioural detection and allow remote response. The response capability matters as much as detection: isolating a host in seconds is often what limits an incident.',
        'Process lineage is the single most useful endpoint concept. Word spawning PowerShell spawning a network connection is not normal. Neither is a browser spawning a shell, or a scheduled task spawning an encoded command. Parent-child relationships expose intent that a single event never shows.',
        'Attackers deliberately use tools already present — PowerShell, WMI, certutil, rundll32, regsvr32, mshta. This is "living off the land", and it defeats detections that look for unknown binaries. The answer is to look at how legitimate tools are being used, not whether they are present.',
        'Identity telemetry is where modern intrusions become visible. Impossible travel, sign-ins from unusual devices, MFA fatigue prompts, new OAuth application consent, changes to mail forwarding rules, and additions to privileged groups. Business email compromise is often visible only here — there is no malware to find.',
        'Cloud identity deserves its own attention. A new access key, an assumed role from an unfamiliar location, or a policy change granting broad permissions can be the entire attack. In cloud, the control plane is the endpoint.',
      ],
      words: [
        { term: 'EDR', means: 'Endpoint Detection and Response — deep endpoint visibility plus response actions.' },
        { term: 'Process lineage', means: 'The chain of which process started which.' },
        { term: 'LOLBin', means: 'A legitimate built-in binary abused by attackers.' },
        { term: 'Impossible travel', means: 'Logins from distant locations too close together in time.' },
      ],
      why: 'Endpoint and identity together cover the overwhelming majority of the intrusion lifecycle, from first foothold to final theft.',
      doThis: 'Using Sysmon data, build a query that lists every process whose parent is an Office application. Look at what normal actually produces first.',
      check: 'Why is business email compromise often invisible to endpoint tooling?',
    },
    {
      id: '07-6',
      title: 'Network monitoring and its blind spots',
      mins: 8,
      oneLine: 'Network data shows you what talked to what, which endpoint tooling cannot tell you when the endpoint is not covered.',
      like: 'Phone records. You may not hear the conversation, but who called whom, when, and for how long tells you a great deal.',
      body: [
        'Flow data — NetFlow or Zeek connection logs — records the metadata of every conversation. This scales far better than full packet capture and answers most investigative questions: who connected to this address, for how long, how much data moved.',
        'Encryption removes content but not patterns. Beaconing is the classic example: malware calling home at regular intervals with small consistent payloads. That rhythm is visible even inside TLS, and JA3 or JA4 fingerprints can identify the client software from the handshake alone.',
        'Zeek is the tool worth learning. It produces structured logs per protocol — connections, DNS, HTTP, TLS, files — which are far more useful for hunting than raw packets. Suricata complements it with signature-based alerting on known malicious patterns.',
        'The blind spots matter as much as the coverage. Encrypted traffic hides content. Cloud-to-cloud traffic never crosses your network. Remote workers connecting directly to software as a service bypass your sensors entirely. Do not claim coverage you do not have.',
        'Network detection remains valuable precisely because it is hard for an attacker to avoid entirely. Data has to leave somehow, and command and control has to reach back somehow. Watching egress is a small effort with a large return.',
      ],
      words: [
        { term: 'NetFlow', means: 'Metadata records of network conversations.' },
        { term: 'Beaconing', means: 'Regular, repeated check-ins from malware to its controller.' },
        { term: 'Zeek', means: 'A network monitor that produces rich structured protocol logs.' },
        { term: 'JA3 / JA4', means: 'A fingerprint of a TLS client, usable even without decryption.' },
      ],
      why: 'When an endpoint agent is missing, disabled, or on a device you do not manage, network data may be your only evidence.',
      doThis: 'Run Zeek over a saved packet capture and read conn.log and dns.log. Find the longest connection and the most frequently queried domain.',
      check: 'How can you detect malware command and control inside encrypted traffic without decrypting it?',
    },
    {
      id: '07-7',
      title: 'Threat intelligence, used properly',
      mins: 8,
      oneLine: 'Intelligence is knowing which threats actually apply to you, so you can prepare for those rather than for everything.',
      like: 'A weather forecast for your town, not a list of every storm on earth.',
      body: [
        'There are three levels. Strategic intelligence informs leadership about trends and risk. Operational intelligence describes campaigns and adversary behaviour. Tactical intelligence is the indicators — addresses, domains, hashes — that feed tooling directly.',
        'Indicators expire quickly, which beginners underestimate. A malicious address may be reused for days and then abandoned. Feeding enormous indicator lists into a SIEM produces noise and a false sense of coverage. Behavioural intelligence outlasts it substantially.',
        'The intelligence cycle keeps this useful: define what you actually need to know, collect, process, analyse, disseminate to people who can act, and take feedback. Intelligence that does not change a decision is trivia, however interesting it is.',
        'Structured formats let this scale. STIX describes threat information consistently, TAXII moves it between organisations, and MISP is a widely used open platform for sharing within trust communities. Sector-specific sharing groups are frequently the highest-quality source available.',
        'Judge every claim by evidence and confidence. Attribution in particular is difficult, politically loaded, and frequently wrong in early reporting. Separate what was observed from what was inferred, and label your own confidence honestly.',
      ],
      words: [
        { term: 'IOC', means: 'Indicator of compromise — an observable sign of an attack.' },
        { term: 'TTP', means: 'Tactics, techniques and procedures — how an adversary operates.' },
        { term: 'STIX / TAXII', means: 'Standard formats for describing and sharing threat intelligence.' },
        { term: 'Attribution', means: 'Determining who was responsible. Harder and less certain than it sounds.' },
      ],
      why: 'Intelligence lets a small team spend its limited attention on threats that are actually relevant to its sector and systems.',
      doThis: 'Read one detailed threat report end to end. Extract the ATT&CK techniques used, then check whether your lab would detect any of them.',
      check: 'Why do behavioural TTPs stay useful far longer than indicator lists?',
    },
    {
      id: '07-8',
      title: 'Triage, hunting and closing the loop',
      mins: 9,
      oneLine: 'Triage decides fast whether an alert is real; hunting looks for what never alerted at all.',
      like: 'Triage is the emergency department. Hunting is the doctor who checks on the patients nobody flagged.',
      body: [
        'Triage is a repeatable process, not intuition. What fired and why? What is the affected asset and how critical is it? Who is the user and is this normal for them? What happened immediately before and after? Is there a benign explanation that fits all the evidence?',
        'The discipline is to look for disconfirming evidence, not just supporting evidence. Analysts under time pressure find the story that fits and stop. Deliberately asking "what would I expect to see if this were benign?" catches both false positives and, more importantly, real attacks that were nearly dismissed.',
        'Document as you go, in the ticket, in plain language. The next analyst — often you, at 3am, in six weeks — needs to know what you checked and what you concluded, including the things you ruled out.',
        'Threat hunting starts from a hypothesis rather than an alert: "if an attacker were using scheduled tasks for persistence, I would see tasks created outside change windows". Then you go and look. Hunting finds the intrusions your detections were never written for, and every hunt should end with either a finding or a new detection rule.',
        'Close the loop every time. Every false positive should produce a tuning change. Every true positive should produce a detection improvement and a lesson. Every hunt should produce a new rule or a documented gap. A SOC that does not do this handles the same alert forever.',
      ],
      words: [
        { term: 'Triage', means: 'Quickly assessing whether an alert is real and how urgent it is.' },
        { term: 'Threat hunting', means: 'Proactively searching for undetected intrusions.' },
        { term: 'Hypothesis-driven', means: 'Starting from a specific idea of what an attacker would do.' },
        { term: 'Feedback loop', means: 'Turning every investigation into an improvement.' },
      ],
      why: 'This is the actual daily work of defence, and the habit of closing the loop is what separates a maturing SOC from a treadmill.',
      doThis: 'Write a triage checklist for one alert type. Then run a hunt in your lab: pick a persistence technique, form a hypothesis, and search for it.',
      check: 'Why should every threat hunt end with either a finding or a new detection rule?',
    },
  ],
};
