import type { Stage } from './types';

export const s08: Stage = {
  number: '08',
  title: 'When it goes wrong',
  subtitle: 'Incident response, digital forensics, memory analysis and malware triage',
  level: 'HARD',
  tags: ['DEFENSE', 'RESEARCH'],
  weeks: 6,
  hours: 70,
  hue: 275,
  plain: 'Something bad happened. Now you work out exactly what, stop it spreading, prove it with evidence, and make sure it cannot happen the same way twice.',
  outcome: 'You can preserve evidence properly, build a defensible timeline, analyse malicious behaviour safely, contain an incident and improve the system afterwards.',
  project: 'Investigate a simulated compromise end to end and produce a timeline, a scope statement, a containment plan and a lessons-learned brief.',
  checkpoint: 'Another analyst can reproduce your findings from your notes, and can tell your confirmed facts from your hypotheses.',
  resources: [
    { label: 'NIST SP 800-61r3 incident response', href: 'https://csrc.nist.gov/pubs/sp/800/61/r3/final' },
    { label: 'Volatility Foundation', href: 'https://volatilityfoundation.org/' },
    { label: 'DFIR training and free labs', href: 'https://www.13cubed.com/' },
  ],
  lessons: [
    {
      id: '08-1',
      title: 'The incident response lifecycle',
      mins: 8,
      oneLine: 'Response follows a repeatable cycle — prepare, detect and analyse, contain, eradicate, recover, learn — and preparation does most of the work.',
      like: 'A fire drill. The reason evacuations go smoothly is entirely the practice that happened when nothing was burning.',
      body: [
        'NIST SP 800-61 revision 3, published in 2025, realigned incident response with the CSF 2.0 functions, which places Govern around everything and treats response as continuous improvement rather than a linear checklist. The practical phases remain familiar.',
        'Preparation is the phase that determines the outcome: a written plan, defined roles, an out-of-band communication channel, contact lists, retained forensic tooling, legal and PR contacts agreed in advance, and logging already turned on. You cannot add any of these during an incident.',
        'Detection and analysis is where you establish what actually happened, how far it reached, and what is confirmed versus suspected. The most common failure here is declaring scope too early — announcing containment while the attacker still holds access somewhere you have not looked.',
        'Containment has short-term and long-term forms. Isolating a host stops immediate damage; rebuilding trust in the environment takes longer. Beware of alerting the attacker before you understand the full scope, because a rushed partial containment often triggers destructive behaviour.',
        'Eradication removes the attacker and their persistence. Recovery restores service and monitors closely for return. Then the lessons-learned review — held blamelessly, within two weeks, with concrete owned actions — is the only part that reduces the chance of a repeat.',
      ],
      words: [
        { term: 'Incident', means: 'An event that actually harms or threatens security, not merely a suspicious log line.' },
        { term: 'Containment', means: 'Stopping the damage spreading further.' },
        { term: 'Eradication', means: 'Removing the attacker and their footholds completely.' },
        { term: 'Post-incident review', means: 'A blameless analysis producing concrete improvements.' },
      ],
      why: 'The quality of the first hour usually decides the total cost of the incident, and the first hour is decided by preparation.',
      doThis: 'Write a one-page incident response plan for a small organisation: who decides, who communicates, who investigates, and what happens in the first thirty minutes.',
      check: 'Why can containing an incident too early make the overall outcome worse?',
    },
    {
      id: '08-2',
      title: 'Evidence: order of volatility and chain of custody',
      mins: 8,
      oneLine: 'Evidence disappears in a predictable order, so you collect the most fragile things first and prove nothing changed afterwards.',
      like: 'A crime scene. Footprints in the rain get photographed before the fingerprints indoors, and everything is bagged, labelled and signed for.',
      body: [
        'The order of volatility, most fragile first: CPU registers and cache, memory, network connections and running processes, temporary files, disk, remote logs, then archived backups. Pulling the power cord destroys everything above disk, which is why the old advice to immediately unplug is usually wrong now.',
        'Chain of custody records who handled evidence, when, and why, from collection to conclusion. Break the chain and the evidence may be inadmissible in court and unreliable in an internal disciplinary process. Even when law is not involved, it keeps your own analysis honest.',
        'Work from copies, never originals. Take a bit-for-bit image, hash it, and verify the hash before and after. Matching hashes prove the copy is identical and that nothing changed while you worked. Use a write blocker for physical media.',
        'Live acquisition is often unavoidable in cloud and in always-on systems, and it inevitably changes the system slightly. That is acceptable if you document exactly what you ran and when. Undocumented changes are what destroy credibility, not the fact of interacting.',
        'In cloud environments, evidence means snapshots of volumes, memory captures where available, and — critically — the control plane audit logs, which are frequently the only record of what an attacker actually did with stolen credentials.',
      ],
      words: [
        { term: 'Order of volatility', means: 'The sequence in which evidence is lost, most fragile first.' },
        { term: 'Chain of custody', means: 'The documented record of who handled evidence and when.' },
        { term: 'Forensic image', means: 'An exact bit-for-bit copy of storage.' },
        { term: 'Write blocker', means: 'Hardware preventing any change to the original media.' },
      ],
      why: 'Evidence collected badly is worthless later, and you rarely get a second chance at a system that has since been rebuilt.',
      doThis: 'Image a small USB drive with dd or FTK Imager, hash the source and the image, and confirm they match. Document every step as if it were real.',
      check: 'Why is immediately powering off a suspected compromised machine often the wrong first move?',
    },
    {
      id: '08-3',
      title: 'Disk forensics and the artefacts that talk',
      mins: 9,
      oneLine: 'Operating systems record far more about user and program activity than users realise, and most of it survives deletion.',
      like: 'A house where every visitor leaves fingerprints, receipts and footprints — even the ones who tidied up on the way out.',
      body: [
        'Deleting a file usually removes the pointer, not the data. Until the space is reused, carving tools can recover content by recognising file headers. This is why secure deletion and full disk encryption matter, and why "I deleted it" means very little forensically.',
        'Filesystem timestamps are the backbone of a timeline. NTFS keeps two sets — the standard information and the file name attribute — and attackers who alter timestamps often change only one, which is itself a detectable anomaly known as timestomping.',
        'Windows is unusually rich in execution evidence. Prefetch records what ran and how often. Shimcache and Amcache record program presence. ShellBags record folder browsing. Jump lists and LNK files record opened documents, including from removable drives that are no longer present.',
        'The registry holds user activity, USB device history, network profiles the machine has joined, and — importantly for intrusions — the persistence mechanisms in the Run keys, services and scheduled tasks. Browser history, cache and downloads round out the picture of user behaviour.',
        'Build a super timeline that merges all of these into one chronological view, then narrate it. The story you can defend is the one where each claim points at a specific artefact and each gap is stated as a gap.',
      ],
      words: [
        { term: 'File carving', means: 'Recovering deleted files by recognising their structure.' },
        { term: 'Prefetch', means: 'A Windows artefact recording program execution.' },
        { term: 'Timestomping', means: 'Altering timestamps to hide activity.' },
        { term: 'Super timeline', means: 'A merged chronological view of all artefacts.' },
      ],
      why: 'The timeline is the deliverable in most investigations. It answers what happened, in what order, and therefore how far it reached.',
      doThis: 'Download a free forensic image from a public training set and use Autopsy to build a timeline. Find one program execution and one deleted file.',
      check: 'Why does a mismatch between two sets of NTFS timestamps suggest tampering?',
    },
    {
      id: '08-4',
      title: 'Memory forensics',
      mins: 9,
      oneLine: 'Memory holds what disk never sees — running processes, injected code, keys, passwords and network connections in flight.',
      like: 'Reading the notes on a person’s desk while they are still working, rather than searching the filing cabinet afterwards.',
      body: [
        'Modern intrusions often run entirely in memory to avoid leaving files behind. Fileless malware, reflectively loaded modules, and in-memory command and control frameworks are all invisible to a disk-only investigation, which is why memory capture became standard practice.',
        'Capture with a documented tool — WinPmem, DumpIt, LiME on Linux — as early as possible, because every minute of runtime overwrites more of what you wanted. Then analyse the image offline with Volatility 3 or a similar framework.',
        'The high-value questions memory answers: what processes were running and what were their parents, what network connections existed, what command lines were used, what modules were loaded, and which regions of memory are executable but do not correspond to any file on disk.',
        'That last one is the strongest signal for code injection. A memory region marked executable with no backing file is difficult for an attacker to avoid entirely, and it is why memory analysis frequently finds what everything else missed.',
        'Memory also holds secrets: cached credentials, cryptographic keys, decrypted content and pasted passwords. This is a capability for investigators and a warning for defenders about what a compromised host actually exposes.',
      ],
      words: [
        { term: 'Memory image', means: 'A captured copy of a system’s RAM.' },
        { term: 'Volatility', means: 'The standard open-source memory analysis framework.' },
        { term: 'Fileless malware', means: 'Malicious code that runs without writing files to disk.' },
        { term: 'Process injection', means: 'Running malicious code inside another legitimate process.' },
      ],
      why: 'Skipping memory capture means an entire category of modern attack simply does not appear in your investigation.',
      doThis: 'Capture memory from your own lab VM and run Volatility’s process list and network connection plugins. Compare the results with what the machine reported about itself.',
      check: 'Why is an executable memory region with no corresponding file on disk suspicious?',
    },
    {
      id: '08-5',
      title: 'Email, identity and cloud investigations',
      mins: 8,
      oneLine: 'Many modern incidents involve no malware at all — just a stolen identity used through legitimate services.',
      like: 'A thief who never breaks a window because they simply took a copy of the key and walked in during business hours.',
      body: [
        'Business email compromise is the archetype. An attacker phishes credentials, defeats or bypasses MFA, logs in, creates a mail rule to hide replies, monitors conversations, and eventually redirects a payment. There is nothing on the endpoint to find, because nothing was ever installed.',
        'Email headers are evidence. Received headers trace the path, and SPF, DKIM and DMARC results show whether the sender was authorised for that domain. Learning to read a full header set is a fast, high-value skill for triaging reported phishing.',
        'For identity investigations, the audit log is the crime scene: sign-in records with location and device, MFA challenge results, consent grants to OAuth applications, mailbox rule creation, delegation changes, and privileged role assignments. Malicious OAuth consent in particular grants durable access that surviving a password reset.',
        'In cloud, the control plane audit log answers the central question: what did those credentials do? Look for new access keys, role assumptions from unusual sources, changes to logging configuration, snapshots being shared externally, and permissions being broadened.',
        'A specific pattern to remember: attackers frequently disable or reconfigure logging early. A gap in the audit trail is not the absence of evidence — it is evidence.',
      ],
      words: [
        { term: 'BEC', means: 'Business Email Compromise — fraud carried out through a hijacked mailbox.' },
        { term: 'Mail rule abuse', means: 'Creating hidden rules to conceal an intruder’s activity.' },
        { term: 'OAuth consent phishing', means: 'Tricking a user into granting a malicious app durable access.' },
        { term: 'Control plane log', means: 'The record of management actions in a cloud environment.' },
      ],
      why: 'Identity-based intrusions are now among the most common and most costly, and they are invisible to malware-focused investigation.',
      doThis: 'Take a phishing email from your own spam folder. Read the full headers, check the SPF and DKIM results, and trace the actual sending path.',
      check: 'Why does resetting a password fail to remove access granted through a malicious OAuth application?',
    },
    {
      id: '08-6',
      title: 'Malware triage, safely',
      mins: 9,
      oneLine: 'Work out what a hostile file does — first without running it, then by running it somewhere it cannot escape.',
      like: 'Examining a suspicious package with an X-ray before deciding whether to open it, and opening it inside a blast box.',
      body: [
        'Safety first, and this is not optional. Analyse in an isolated virtual machine with no network or a simulated one, with snapshots, on a host that holds nothing you value. Modern malware detects analysis environments and can attempt to escape them.',
        'Static analysis examines the file without executing it: hashes to check against known samples, file type, strings, imported functions, packing indicators, and for Windows binaries the PE structure and its sections. Suspicious imports alone often reveal intent — process injection, keylogging, or persistence APIs.',
        'Dynamic analysis runs it in a sandbox and observes behaviour: files created, registry changes, processes spawned, network destinations contacted, and persistence established. Sandboxes such as Cuckoo, or online services for non-sensitive samples, automate much of this.',
        'Be careful about what you upload. Submitting a sample from a real incident to a public service can alert the attacker that they have been discovered, and may expose confidential data embedded in the file. This has genuinely compromised investigations.',
        'The output that matters is behavioural: indicators to hunt for across the estate, ATT&CK techniques observed, persistence to remove, and network destinations to block. Deep reverse engineering is a specialisation; triage is a skill every responder needs.',
      ],
      words: [
        { term: 'Static analysis', means: 'Examining a file without running it.' },
        { term: 'Dynamic analysis', means: 'Running a file in a controlled environment and watching what it does.' },
        { term: 'Packer', means: 'Software that compresses or obfuscates a binary to resist analysis.' },
        { term: 'Sandbox evasion', means: 'Malware detecting analysis and behaving harmlessly.' },
      ],
      why: 'During an incident you need to know quickly what a sample does, what it touched, and what to hunt for. That is triage, not research.',
      doThis: 'Take a harmless program, run strings and a PE viewer on it, then execute it in a sandboxed VM with monitoring and compare what static analysis predicted.',
      check: 'Why can uploading a sample to a public sandbox damage an active investigation?',
    },
    {
      id: '08-7',
      title: 'Reverse engineering: reading what the machine reads',
      mins: 9,
      oneLine: 'When you need to know exactly what code does and you have no source, you read the assembly.',
      like: 'Working out a machine’s function by watching every gear turn, because nobody kept the manual.',
      body: [
        'Assembly is the human-readable form of machine code. You need surprisingly little to start: registers, the stack, moving data, arithmetic, comparisons, jumps, and how function calls pass arguments and return values. x86-64 and ARM64 cover almost everything you will meet.',
        'Ghidra, from the NSA, is free and includes a decompiler that produces approximate C from a binary. IDA Pro is the long-standing commercial standard, and Binary Ninja sits between them. The decompiler is a huge accelerator, but it is an approximation — when something looks impossible, check the assembly.',
        'Combine static reading with a debugger. Set a breakpoint, run to it, inspect memory and registers, step forward. Watching a decryption routine run and seeing the plaintext appear teaches more in five minutes than an hour of static reading.',
        'Expect obfuscation. Packing, anti-debugging checks, encrypted strings decoded only at runtime, and control flow flattening all exist specifically to waste your time. Often the practical move is to let the program unpack itself and then capture memory.',
        'Set a goal before you start, because reverse engineering expands to fill infinite time. "What is the command and control protocol?" or "how does it decide to encrypt?" are answerable questions. "Understand this binary" is not.',
      ],
      words: [
        { term: 'Assembly', means: 'Low-level instructions the CPU executes.' },
        { term: 'Decompiler', means: 'A tool producing approximate high-level code from a binary.' },
        { term: 'Breakpoint', means: 'A marker that pauses execution so you can inspect state.' },
        { term: 'Obfuscation', means: 'Deliberately making code hard to understand.' },
      ],
      why: 'It is the foundation of malware analysis, vulnerability research and firmware work — the skill that removes the last black box.',
      doThis: 'Write a small C program with a password check, compile it, open it in Ghidra, and find the comparison. Then patch it to always succeed.',
      check: 'Why is running a packed sample and dumping memory often more efficient than statically unpacking it?',
    },
    {
      id: '08-8',
      title: 'Ransomware, recovery and learning',
      mins: 9,
      oneLine: 'Ransomware is a business, the encryption is the last step, and recovery is decided long before the ransom note appears.',
      like: 'A burglary where they photograph everything, take copies, change the locks, and only then leave a note demanding payment.',
      body: [
        'The modern pattern is double extortion: the attacker gains access, moves laterally for days or weeks, steals data, deliberately destroys or encrypts backups, then encrypts systems. Paying may return your files but cannot un-steal the data, which is why "we have backups" is only half an answer.',
        'The initial access is rarely exotic — phishing, exposed remote access, unpatched internet-facing services, or purchased stolen credentials. The controls that prevent it are the boring ones from stage 04: MFA, patching, least privilege and segmentation.',
        'During the incident, prioritise in order: contain the spread, preserve evidence, confirm the scope, verify your backups are intact and offline, and involve legal, insurance and law enforcement early. Payment decisions are business and legal decisions, not technical ones, and may carry sanctions implications.',
        'Recovery must be rebuild-first. Restoring a compromised system restores the compromise. Rebuild from known-good images, restore data after scanning, rotate every credential in the environment, and monitor intensively afterwards, because return visits are common.',
        'Tabletop exercises are the highest-value preparation available. Walk through the scenario with the real decision-makers before it happens: who declares an incident, who talks to press, who can authorise shutting down production. The awkward discoveries in a two-hour exercise are the ones you do not want to make live.',
      ],
      words: [
        { term: 'Double extortion', means: 'Stealing data as well as encrypting it, to force payment.' },
        { term: 'Immutable backup', means: 'A copy that cannot be modified or deleted, even by an administrator.' },
        { term: 'Tabletop exercise', means: 'A discussion-based rehearsal of an incident.' },
        { term: 'Blameless review', means: 'Analysing failure to fix systems rather than to punish people.' },
      ],
      why: 'Ransomware is the most likely severe incident most organisations will face, and preparation determines whether it is expensive or existential.',
      doThis: 'Run a tabletop with friends or colleagues. Give them a ransomware scenario and make them decide, out loud, in the first thirty minutes.',
      check: 'Why is restoring an encrypted system from backup insufficient without also rebuilding and rotating credentials?',
    },
  ],
};
