import type { Stage } from './types';

export const s09: Stage = {
  number: '09',
  title: 'Cloud and DevSecOps',
  subtitle: 'Shared responsibility, cloud identity, containers, Kubernetes and securing the pipeline',
  level: 'HARD',
  tags: ['CLOUD', 'BUILD', 'DEFENSE'],
  weeks: 5,
  hours: 65,
  hue: 200,
  plain: 'Almost everything now runs in the cloud and ships through an automated pipeline. Both are new places to be attacked, and both are securable.',
  outcome: 'You can secure identity, data, workloads, deployment pipelines and software provenance across cloud-native systems.',
  project: 'Ship a hardened containerised service through a scanned CI pipeline with least privilege, signed artefacts, an SBOM and working alerts.',
  checkpoint: 'You can say exactly who owns which control in your cloud provider’s model, and prove security from commit through to runtime.',
  resources: [
    { label: 'Kubernetes security checklist', href: 'https://kubernetes.io/docs/concepts/security/security-checklist/' },
    { label: 'NIST Secure Software Development Framework', href: 'https://csrc.nist.gov/pubs/sp/800/218/final' },
    { label: 'CIS Benchmarks', href: 'https://www.cisecurity.org/cis-benchmarks' },
  ],
  lessons: [
    {
      id: '09-1',
      title: 'Shared responsibility, and who owns what',
      mins: 8,
      oneLine: 'The cloud provider secures the platform; you secure what you put on it — and the boundary moves depending on the service.',
      like: 'Renting a flat. The landlord maintains the building and the front door. You are still responsible for locking your own.',
      body: [
        'With infrastructure as a service you get a virtual machine, and you own the operating system, patching, configuration, application and data. With platform as a service the provider handles more of the stack. With software as a service you mostly own only identity, configuration and data. The line moves, and assuming it has not is a common cause of breaches.',
        'One rule never moves: the customer always owns identity, access management and data classification. No provider will stop you from giving an intern administrative rights or making a storage bucket public.',
        'Public storage misconfiguration remains one of the most reliable sources of large data exposure. It is not a sophisticated attack; it is a checkbox, and it happens because defaults, convenience and speed all pull the same way.',
        'Cloud changes the shape of an attack. Instead of exploiting a server, an attacker steals a credential or a token and uses the provider’s own API to do everything — enumerate resources, snapshot a database, share it externally. There is no malware and no unusual binary, only API calls that look administrative.',
        'That is why the control plane audit log is your primary evidence source, and why alerting on identity and permission changes matters more in cloud than almost anything else.',
      ],
      words: [
        { term: 'IaaS / PaaS / SaaS', means: 'Increasing levels of provider-managed stack.' },
        { term: 'Shared responsibility model', means: 'The published split of who secures what.' },
        { term: 'Control plane', means: 'The management API that creates and changes cloud resources.' },
        { term: 'Data plane', means: 'The actual running workloads and data.' },
      ],
      why: 'Most cloud breaches are customer-side misconfiguration, not provider failure. Knowing your half of the model is the whole job.',
      doThis: 'Read your cloud provider’s shared responsibility page for one specific service. Write down three things you assumed they handled that they do not.',
      check: 'Why is a stolen cloud credential often more dangerous than a compromised virtual machine?',
    },
    {
      id: '09-2',
      title: 'Cloud identity and least privilege',
      mins: 9,
      oneLine: 'In cloud, identity is the perimeter, and over-permissive roles are the most common serious weakness.',
      like: 'A building where most staff were quietly given master keys because it was easier than issuing the right ones.',
      body: [
        'Learn the core objects: users, groups, roles and policies. A role is a set of permissions something can assume temporarily; a policy is the document that says what is allowed. Prefer roles with short-lived credentials over long-lived access keys, which get committed to repositories and never expire.',
        'Least privilege is genuinely hard here because permissions are numerous and granular. The practical approach is to start restrictive and widen based on evidence: use the provider’s access analyser tooling to see what was actually used, then trim what was not.',
        'Watch for privilege escalation paths inside the permission model itself. The ability to create a role, attach a policy, pass a role to a service, or update a function’s code can each be equivalent to administrative access even when the account looks limited. These are non-obvious and are exactly what an attacker enumerates first.',
        'Federate identity rather than creating separate cloud accounts. Single sign-on with your central identity provider means joiners, movers and leavers are handled once, and it removes the orphaned accounts that survive people leaving.',
        'For machines, use workload identity — the instance, function or pod gets a short-lived credential automatically — rather than embedding keys. And enforce IMDSv2 so a server-side request forgery bug cannot simply read the instance credentials.',
      ],
      words: [
        { term: 'Role', means: 'A set of permissions that can be assumed temporarily.' },
        { term: 'Policy', means: 'The document defining what actions are allowed on what resources.' },
        { term: 'Workload identity', means: 'Automatic short-lived credentials for a machine or service.' },
        { term: 'Privilege escalation path', means: 'A permission that indirectly grants far more than it appears to.' },
      ],
      why: 'Cloud intrusions are overwhelmingly identity intrusions. Getting permissions right prevents more damage than any detection tool.',
      doThis: 'In a free-tier cloud account, create a role with a deliberately broad policy, then narrow it using access analyser findings until only what is used remains.',
      check: 'Why can the permission to pass a role to a service be equivalent to administrator access?',
    },
    {
      id: '09-3',
      title: 'Cloud networking, data and keys',
      mins: 8,
      oneLine: 'Same networking principles as before, different names — plus a key management service you should let do the hard part.',
      like: 'A new city with familiar road rules. The signs look different, the physics of traffic do not.',
      body: [
        'Virtual private clouds, subnets, security groups and network access control lists are the cloud versions of segmentation and firewalls. Default-deny still wins. Private subnets with no direct internet route, and endpoints that keep traffic on the provider’s network rather than the public internet, are the standard secure shape.',
        'Encryption at rest is usually a single setting and should always be on. The interesting decision is key ownership: provider-managed keys are simplest, customer-managed keys give you control over rotation and revocation, and customer-supplied keys give maximum control and maximum responsibility for losing them.',
        'A key management service does the part people get wrong: generating, storing, rotating and auditing keys, and never exposing the raw key material to your application. Use envelope encryption — a data key encrypts the data, the KMS key encrypts the data key — because it scales without shipping master keys around.',
        'Secrets need somewhere real to live. A dedicated secrets manager with automatic rotation and audited access beats environment variables, which beat configuration files, which enormously beat source code. Every step up removes a class of leak.',
        'Data classification is what makes all of this coherent. If you do not know which storage holds regulated or sensitive data, you cannot apply proportionate controls, and you will end up either over-securing everything or protecting the wrong thing.',
      ],
      words: [
        { term: 'VPC', means: 'Your isolated virtual network inside a cloud provider.' },
        { term: 'Security group', means: 'A stateful firewall attached to a resource.' },
        { term: 'KMS', means: 'Key Management Service — manages cryptographic keys for you.' },
        { term: 'Envelope encryption', means: 'Encrypting data with a data key, and the data key with a master key.' },
      ],
      why: 'Cloud gives you strong cryptographic tooling almost free. The failures come from key handling and from data nobody knew existed.',
      doThis: 'Create an encrypted storage bucket with a customer-managed key. Then try to read an object after revoking access to the key and observe what happens.',
      check: 'Why does envelope encryption scale better than encrypting every object directly with a master key?',
    },
    {
      id: '09-4',
      title: 'Cloud posture, monitoring and response',
      mins: 8,
      oneLine: 'Cloud environments change constantly, so security has to be checked continuously rather than reviewed annually.',
      like: 'A building that adds and removes rooms every day. An annual inspection tells you almost nothing.',
      body: [
        'Cloud security posture management tools continuously check configuration against benchmarks: public storage, unencrypted volumes, over-permissive roles, disabled logging, exposed databases. This class of tooling exists because misconfiguration is the dominant cloud risk and it reappears constantly.',
        'Turn on the audit log in every region and every account, and send it somewhere the account itself cannot delete. Attackers disable logging early; a separate logging account with restricted access is the standard defence.',
        'Threat detection services — GuardDuty, Defender for Cloud, Security Command Center — analyse provider telemetry for known-bad patterns such as credential use from anomalous locations, cryptomining behaviour, and reconnaissance API calls. They are cheap relative to their value and are usually the first alert you will get.',
        'Cloud incident response differs meaningfully. You can snapshot a volume instantly, isolate a resource by changing its security group, and revoke a session by invalidating credentials — all through the API. Preparation means having these runbooks written and the permissions to run them, before the incident.',
        'A specific cloud-native risk worth naming: resource hijacking for cryptomining. It is common, it is fast, and it is often the first sign that a credential leaked. An unexplained spend increase is a security alert.',
      ],
      words: [
        { term: 'CSPM', means: 'Cloud Security Posture Management — continuous configuration checking.' },
        { term: 'Audit log', means: 'The record of every management action taken in the account.' },
        { term: 'Guardrail', means: 'A policy that prevents unsafe configuration being created at all.' },
        { term: 'Cryptojacking', means: 'Stealing compute resources to mine cryptocurrency.' },
      ],
      why: 'Continuous change means continuous drift. Point-in-time assessment is structurally unable to keep up.',
      doThis: 'Enable your provider’s free security scoring or posture tool on a test account, then deliberately create a public bucket and see how quickly it is flagged.',
      check: 'Why should audit logs be written to a separate account rather than the one being monitored?',
    },
    {
      id: '09-5',
      title: 'Container security in practice',
      mins: 8,
      oneLine: 'Containers are convenient and their defaults are not secure — most of the risk comes from the image and the permissions.',
      like: 'Prefabricated rooms delivered to site. Fast and consistent, but you inherit whatever the factory put inside.',
      body: [
        'Start from a minimal base image. Distroless or Alpine images contain fewer packages, which means fewer vulnerabilities and fewer tools for an attacker to use after they land. A full operating system image ships hundreds of packages your application never calls.',
        'Never run as root inside the container. Add a user in the Dockerfile and use it. Combine that with a read-only root filesystem and dropped Linux capabilities, and a container escape becomes substantially harder.',
        'Build with multi-stage Dockerfiles so build tools and source do not ship to production. Remember that image layers are permanent: a secret added in one layer and deleted in a later one is still recoverable from the image, which is a very common way credentials leak.',
        'Scan images for known vulnerabilities in CI with Trivy or Grype, and generate an SBOM so you know what you actually shipped. Rebuild regularly — an image built six months ago is six months behind on every patch, even if your code has not changed.',
        'The three configurations that effectively hand over the host, and which you should be able to spot instantly: running privileged, mounting the Docker socket into a container, and mounting the host filesystem. Each of these turns container access into host access.',
      ],
      words: [
        { term: 'Base image', means: 'The starting layer your container is built from.' },
        { term: 'Distroless', means: 'An image containing only your app and its runtime, no shell or package manager.' },
        { term: 'Capabilities', means: 'Fine-grained Linux privileges that can be dropped individually.' },
        { term: 'Image scanning', means: 'Checking image contents for known vulnerable packages.' },
      ],
      why: 'Containers are how software ships now. Insecure defaults multiplied across hundreds of services becomes a very large attack surface.',
      doThis: 'Take any Dockerfile you have. Add a non-root user, switch to a minimal base, and scan before and after with Trivy. Compare the vulnerability counts.',
      check: 'Why is mounting the Docker socket into a container equivalent to giving it root on the host?',
    },
    {
      id: '09-6',
      title: 'Kubernetes: the parts that bite',
      mins: 9,
      oneLine: 'Kubernetes is powerful, complicated, and insecure by default in ways that are not obvious until you look.',
      like: 'An enormous automated warehouse. Extremely capable, and one wrong configuration file sends everything to the wrong address.',
      body: [
        'The API server is the centre of everything, and access to it is access to the cluster. Anonymous access must be off, RBAC must be enabled and actually restrictive, and the audit log must be on. A cluster with a permissive default role is a cluster with no security model.',
        'RBAC deserves genuine care. Avoid cluster-admin bindings. Watch for permissions that are administrative in disguise: creating pods, reading secrets, or the ability to create a pod that mounts a privileged service account are all escalation paths.',
        'Pod security matters because a pod is a process on a node. Enforce Pod Security Standards or an admission controller policy: no privileged containers, no host network or host path mounts, run as non-root, drop capabilities. Admission control is where you prevent unsafe workloads existing at all, rather than detecting them later.',
        'Network policies are default-allow until you create them, which surprises people. Without policies, every pod can reach every other pod. Start with a default-deny policy per namespace and permit only what is needed — this is the single highest-value Kubernetes control.',
        'Secrets in Kubernetes are Base64-encoded, not encrypted, unless you enable encryption at rest or use an external secrets store. Anyone who can read secrets in a namespace can read them in plain text, which is why that RBAC permission is more sensitive than it looks.',
      ],
      words: [
        { term: 'API server', means: 'The Kubernetes control plane component everything talks to.' },
        { term: 'RBAC', means: 'Role-based access control governing who can do what in the cluster.' },
        { term: 'Admission controller', means: 'A gate that validates or rejects resources before they are created.' },
        { term: 'Network policy', means: 'Rules controlling which pods may talk to which.' },
      ],
      why: 'Kubernetes runs a huge share of modern production workloads, and its default posture assumes a trusted environment that does not exist.',
      doThis: 'Run a local cluster with kind or minikube. Apply a default-deny network policy, then watch which of your test workloads break and why.',
      check: 'Why is the ability to read secrets in a namespace effectively a privileged permission?',
    },
    {
      id: '09-7',
      title: 'Securing the pipeline itself',
      mins: 9,
      oneLine: 'Your CI/CD system can deploy anything to production, which makes it one of the most powerful and least protected systems you own.',
      like: 'The keys to every door in the building, kept in an unlocked drawer because everyone needs them.',
      body: [
        'Treat CI as production. It holds deployment credentials, cloud roles, signing keys and source code. Compromising it means compromising everything downstream without touching production directly — which is precisely why attackers target it.',
        'Specific hardening that matters: require review before merge, restrict who can modify pipeline definitions, pin third-party actions and plugins to a commit hash rather than a moving tag, use ephemeral runners so nothing persists between jobs, and use short-lived OIDC federation to the cloud instead of stored long-lived keys.',
        'Pull request triggers from forks are a classic weakness. A workflow that runs untrusted code from a fork with access to repository secrets is a straightforward path to credential theft. Understand which trigger types expose secrets and which do not.',
        'Infrastructure as code brings the same discipline to infrastructure: reviewable, testable, repeatable. Scan Terraform or CloudFormation with Checkov or tfsec before apply, and remember that the state file contains secrets and must be protected accordingly.',
        'Secret scanning belongs at multiple layers — pre-commit hooks, repository scanning, and CI. And when a secret does leak, the response is rotation. Removing the commit is cosmetic; the credential is already collected.',
      ],
      words: [
        { term: 'CI/CD', means: 'Automated build, test and deployment pipelines.' },
        { term: 'Ephemeral runner', means: 'A build machine destroyed after each job.' },
        { term: 'OIDC federation', means: 'Short-lived cloud credentials issued to a pipeline instead of stored keys.' },
        { term: 'Infrastructure as code', means: 'Defining infrastructure in version-controlled files.' },
      ],
      why: 'A compromised pipeline is a compromise of everything it deploys, and it usually bypasses the controls protecting production.',
      doThis: 'Audit one repository’s CI configuration. Check trigger types, secret exposure, and whether third-party actions are pinned to a hash.',
      check: 'Why is pinning a GitHub Action to a version tag weaker than pinning it to a commit hash?',
    },
    {
      id: '09-8',
      title: 'Provenance: proving what you shipped',
      mins: 8,
      oneLine: 'Supply chain security ends with being able to prove that what is running is what you built, from source you reviewed.',
      like: 'A tamper-evident seal plus a receipt showing which factory made it, on which day, from which ingredients.',
      body: [
        'An SBOM lists every component in your software. SPDX and CycloneDX are the standard formats, and tools like Syft generate them automatically. Its real value arrives on the day a new critical vulnerability is announced and you need to answer "are we affected?" in minutes rather than weeks.',
        'Signing proves origin. Sigstore with cosign makes this genuinely easy, using short-lived keys tied to an identity, with a public transparency log so signatures cannot be issued secretly. Signing artefacts and verifying signatures at deployment closes the gap between build and run.',
        'SLSA is the maturity framework for build integrity, with levels describing increasingly strong guarantees — from basic provenance through to fully hardened, non-falsifiable builds. Use it as a roadmap rather than a badge.',
        'Admission-time verification is what makes any of this real. A cluster policy that refuses to run an unsigned image, or one whose provenance does not match the expected builder, converts a signature from documentation into an enforced control.',
        'NIST’s Secure Software Development Framework, SP 800-218, ties the whole stage together: prepare the organisation, protect the software, produce well-secured software, and respond to vulnerabilities. It is a useful checklist for whether your pipeline covers what it should.',
      ],
      words: [
        { term: 'SBOM', means: 'A machine-readable list of everything in your software.' },
        { term: 'Sigstore / cosign', means: 'Tooling for easy artefact signing with a public transparency log.' },
        { term: 'Provenance', means: 'Verifiable evidence of how and from what an artefact was built.' },
        { term: 'SLSA', means: 'A tiered framework for supply chain integrity.' },
      ],
      why: 'Software Supply Chain Failures entered the OWASP Top 10 at number three in 2025. Provenance is the structural answer to it.',
      doThis: 'Generate an SBOM for a container image with Syft, then sign the image with cosign and verify the signature. Note how long the whole thing took.',
      check: 'Why does signing an artefact only become a security control once something verifies the signature at deployment?',
    },
  ],
};
