import type { Stage } from './types';

export const s10: Stage = {
  number: '10',
  title: 'The deep end',
  subtitle: 'Exploit development, mobile, wireless, hardware, OT, cryptography and AI security',
  level: 'EXPERT',
  tags: ['RESEARCH', 'OFFENSE', 'DEFENSE'],
  weeks: 5,
  hours: 55,
  hue: 300,
  plain: 'Eight frontier fields at introductory depth. Pick one to study further. Nobody masters all of them.',
  outcome: 'You can sample advanced specialities, judge which suits you, and go genuinely deep in one rather than superficially wide across all.',
  project: 'Complete one specialisation capstone with a reproducible lab, original analysis, and a write-up safe to publish.',
  checkpoint: 'You can read primary technical material, reproduce someone else’s result, question its assumptions, and say clearly what remains unknown.',
  resources: [
    { label: 'pwn.college (free systems security curriculum)', href: 'https://pwn.college/' },
    { label: 'MITRE ATLAS: adversarial AI', href: 'https://atlas.mitre.org/' },
    { label: 'OWASP GenAI Security Project', href: 'https://genai.owasp.org/' },
  ],
  lessons: [
    {
      id: '10-1',
      title: 'Exploit development and modern mitigations',
      mins: 10,
      oneLine: 'Turning a crash into reliable control of a program, against defences specifically designed to stop you.',
      like: 'Lock picking against a lock that shuffles its own pins, checks for tampering, and reports break-in attempts.',
      body: [
        'The path is always the same: find a memory-safety bug, understand what you can control, and convert that control into execution. A stack buffer overflow overwriting a return address is the teaching example, and almost nothing in production is that simple any more.',
        'The mitigations arrived in layers and you must defeat them in order. Stack canaries detect overwritten return addresses, so you need a leak or an alternative target. DEP or NX makes the stack non-executable, which is why return-oriented programming exists: chain fragments of existing legitimate code instead of injecting your own.',
        'ASLR randomises where everything lives, so exploits now typically need an information leak first: a separate bug that reveals an address, turning a two-step problem into the normal shape of modern exploitation. Control Flow Integrity and hardware features like CET and pointer authentication raise the bar further.',
        'Heap exploitation is its own discipline. Allocators have structure, and manipulating allocation and free patterns to arrange memory the way you need: heap grooming: is often the hardest and most craft-like part of the work.',
        'Learn this legally and thoroughly. pwn.college is a free, structured university curriculum. Capture the flag competitions provide endless legal targets. And know that exploit development is the clearest demonstration of why memory-safe languages matter: they remove the entire category rather than mitigating it.',
      ],
      words: [
        { term: 'ROP', means: 'Return-oriented programming: chaining existing code fragments to run your logic.' },
        { term: 'Info leak', means: 'A bug revealing memory addresses, used to defeat randomisation.' },
        { term: 'Heap grooming', means: 'Arranging heap memory deliberately to make an exploit reliable.' },
        { term: 'CFI', means: 'Control Flow Integrity: enforcing that execution follows expected paths.' },
      ],
      why: 'It is the deepest test of systems understanding, and it explains precisely why the industry is moving to memory-safe languages.',
      doThis: 'Work through the pwn.college memory-corruption modules in order. Do not skip the ones that look basic; the mitigations build on them.',
      check: 'Why does ASLR mean most modern exploits require two vulnerabilities rather than one?',
    },
    {
      id: '10-2',
      title: 'Mobile application security',
      mins: 9,
      oneLine: 'Phones hold everything, run apps from thousands of publishers, and put a copy of the client in the attacker’s hands.',
      like: 'Handing every customer the shop’s till and trusting them not to open it.',
      body: [
        'Both platforms sandbox apps and encrypt storage, and both are strong by default. Nearly all real mobile findings are the developer’s: secrets hard-coded in the app, sensitive data written to unprotected storage or logs, weak certificate validation, and exported components that other apps can invoke.',
        'The structural point is that client-side controls are advisory. The app runs on a device the attacker controls, so any check inside it can be removed. Root or jailbreak detection, certificate pinning and obfuscation raise cost; they do not create a boundary. The server must enforce everything that matters.',
        'Static analysis means unpacking the app: an APK is a zip, decompile the DEX to readable Java; an IPA can be inspected and its binary examined, then searching for keys, endpoints, and logic that should have been server-side. This alone finds a large share of real issues.',
        'Dynamic analysis uses an intercepting proxy for traffic and Frida for runtime instrumentation, hooking functions to observe or bypass behaviour. Bypassing certificate pinning to see the actual API traffic is usually the first practical step, because the API is where the real vulnerabilities are.',
        'Use the OWASP Mobile Application Security Testing Guide and MASVS for structure. And remember the finding that repeats endlessly: the mobile app is a client, and the backend API is what actually needs testing.',
      ],
      words: [
        { term: 'Sandbox', means: 'Platform isolation preventing apps from reaching each other’s data.' },
        { term: 'Certificate pinning', means: 'An app accepting only a specific certificate, resisting interception.' },
        { term: 'Frida', means: 'A toolkit for hooking and modifying app behaviour at runtime.' },
        { term: 'Exported component', means: 'An app component other apps are allowed to invoke.' },
      ],
      why: 'Mobile is the primary computing device for most people on earth, and mobile apps front the same APIs everything else uses.',
      doThis: 'Take an app you wrote or a deliberately vulnerable one, decompile it, and search for hard-coded URLs and keys. Then intercept its traffic.',
      check: 'Why is root detection a cost-raising measure rather than a security boundary?',
    },
    {
      id: '10-3',
      title: 'Wireless and radio',
      mins: 9,
      oneLine: 'Anything transmitting through the air can be received by anyone nearby, which changes the threat model completely.',
      like: 'A conversation in a public square. Encryption is speaking in code; it does not stop people hearing that you spoke.',
      body: [
        'Wi-Fi attacks are the familiar ones: capturing a handshake and cracking a weak passphrase offline, deauthentication to force reconnection, evil twin access points impersonating a trusted network, and captive portal phishing. WPA3 substantially improves resistance to offline cracking, but adoption is uneven and downgrade paths exist.',
        'Enterprise Wi-Fi with 802.1X is stronger but has its own failure: if clients do not validate the server certificate, an attacker can stand up a fake authentication server and harvest credentials. This is a configuration problem on thousands of managed devices, which is why it persists.',
        'Bluetooth and BLE are widely deployed and often weakly secured. Pairing weaknesses, unauthenticated characteristics on BLE devices, and long-lived static identifiers enabling tracking are all common in consumer products.',
        'Software-defined radio opens everything else. With inexpensive hardware and tools like GNU Radio you can receive and analyse a huge range of signals: key fobs, tyre sensors, industrial telemetry, aircraft transponders. Many use fixed codes or no authentication because the designers assumed nobody would listen.',
        'Transmitting is legally restricted almost everywhere, and this genuinely matters. Receiving is usually permitted; transmitting on licensed bands is not, and interfering with aviation, emergency or medical systems carries serious consequences. Research in a shielded environment or on permitted bands.',
      ],
      words: [
        { term: 'Handshake capture', means: 'Recording the authentication exchange to attack offline.' },
        { term: 'Evil twin', means: 'A fake access point impersonating a legitimate network.' },
        { term: 'SDR', means: 'Software-defined radio: receiving and processing radio in software.' },
        { term: 'Replay attack', means: 'Recording a valid transmission and sending it again.' },
      ],
      why: 'Wireless removes physical access as a barrier, and a great deal of deployed radio equipment was designed with no security at all.',
      doThis: 'Capture a WPA2 handshake on your own network and attempt to crack it with a wordlist that includes your passphrase. Then change to a long random one and try again.',
      check: 'Why does a client failing to validate the RADIUS server certificate undermine enterprise Wi-Fi entirely?',
    },
    {
      id: '10-4',
      title: 'Hardware, firmware and IoT',
      mins: 9,
      oneLine: 'Physical access changes everything, and most connected devices were built to a price rather than to a threat model.',
      like: 'A safe with a strong door and a thin back panel, because nobody expected anyone to walk behind it.',
      body: [
        'The usual entry point is a debug interface left enabled: UART giving a serial console, often with a root shell and no password; JTAG or SWD giving full processor control. Manufacturers leave them for production testing and rarely disable them afterwards.',
        'Firmware extraction is the next step: reading the flash chip directly with a programmer, or downloading an update file. Binwalk unpacks the image, and what falls out is frequently a full filesystem containing hard-coded credentials, private keys, and services with known vulnerabilities.',
        'Secure boot is the control that should prevent modified firmware running: each stage verifies the signature of the next before executing it. It only works if the root of trust is genuinely immutable and the verification cannot be bypassed, and implementations get this wrong regularly.',
        'Side-channel attacks extract secrets from physical behaviour rather than from logic. Power analysis can recover cryptographic keys by measuring consumption during operations; timing attacks exploit operations that take different durations for different inputs. This is why constant-time cryptographic implementations exist.',
        'The IoT reality is harsh: default credentials, no update mechanism, hard-coded keys shared across an entire product line, and a lifespan far exceeding the manufacturer’s support. Mirai demonstrated what happens when millions of such devices are recruited at once, and little has structurally changed.',
      ],
      words: [
        { term: 'UART', means: 'A serial interface often exposing a console on embedded devices.' },
        { term: 'JTAG', means: 'A debug interface giving deep control of a processor.' },
        { term: 'Secure boot', means: 'Verifying each stage of startup code before running it.' },
        { term: 'Side-channel', means: 'Extracting secrets from physical behaviour like power or timing.' },
      ],
      why: 'Embedded devices are everywhere, rarely patched, and increasingly connected to networks that matter.',
      doThis: 'Download a router firmware image from a manufacturer’s site and run binwalk on it. Look for the filesystem, then search it for credentials and keys.',
      check: 'Why does a hard-coded key shared across a product line create a fundamentally different risk than one unique per device?',
    },
    {
      id: '10-5',
      title: 'Operational technology and industrial control',
      mins: 9,
      oneLine: 'In OT, the priorities invert: availability and safety come first, and a wrong action can hurt people.',
      like: 'A hospital ventilator. You do not reboot it to install an update because a patch was released this morning.',
      body: [
        'OT runs physical processes: power, water, manufacturing, transport. The Purdue model describes the layered separation between enterprise IT and control systems, and understanding that hierarchy is the foundation of every OT security conversation.',
        'Priorities reverse. In IT, confidentiality usually leads. In OT, safety and availability lead absolutely: a controller taken offline can stop a production line or endanger people. This is why scanning is dangerous, patching is slow, and change windows may be annual.',
        'Legacy protocols like Modbus and DNP3 were designed for isolated, trusted networks and have no authentication or encryption. Anyone who can reach the network can often issue commands. Retrofitting security means segmentation and monitoring, because the protocols themselves cannot be fixed.',
        'The case studies are essential reading. Stuxnet showed physical damage caused by manipulated controllers while operators saw normal readings. The Ukrainian grid attacks showed coordinated remote operation of breakers. Triton targeted a safety instrumented system directly: the layer whose entire purpose is preventing harm.',
        'Practical OT defence is mostly architectural: strong segmentation between IT and OT, tightly controlled and monitored remote access, passive network monitoring rather than active scanning, and incident plans that account for physical consequences and manual fallback.',
      ],
      words: [
        { term: 'PLC', means: 'Programmable Logic Controller: the computer directly controlling equipment.' },
        { term: 'SCADA', means: 'The system supervising and controlling industrial processes.' },
        { term: 'Purdue model', means: 'The layered reference architecture separating IT from control systems.' },
        { term: 'Safety instrumented system', means: 'The independent system that prevents dangerous conditions.' },
      ],
      why: 'These systems run the physical world, and consequences here are measured in safety and continuity rather than in records disclosed.',
      doThis: 'Read a public analysis of the Triton or Ukraine grid incidents. Map the attack against the Purdue model layers it crossed.',
      check: 'Why is an active vulnerability scan that is routine in IT potentially unacceptable in an OT environment?',
    },
    {
      id: '10-6',
      title: 'Cryptographic engineering and post-quantum',
      mins: 9,
      oneLine: 'Real cryptographic failures come from implementation and key management, not from broken mathematics.',
      like: 'An excellent lock installed in a hollow door, with the key under the mat.',
      body: [
        'The recurring implementation failures are worth memorising: nonce reuse, which can destroy the security of otherwise sound modes; ECB mode leaking patterns visibly; non-constant-time comparison of secrets creating timing oracles; padding oracles allowing decryption without the key; and weak randomness, which silently undermines everything above it.',
        'Protocol design is where subtle failures live. Downgrade attacks force a weaker algorithm. Key confirmation missing from a handshake allows impersonation. Formal verification tools now exist precisely because human review repeatedly missed these.',
        'Post-quantum cryptography is the live migration. NIST finalised FIPS 203 (ML-KEM) for key establishment, FIPS 204 (ML-DSA) and FIPS 205 (SLH-DSA) for signatures in August 2024, and selected HQC in 2025 as a backup key encapsulation mechanism built on different mathematics. FN-DSA is still being finalised.',
        'The timeline is not distant. Guidance points at deprecating current public-key algorithms around 2030, with federal deadlines for high-value systems around 2030 and 2031, and CNSA 2.0 requiring PQC for new national security systems from 2027. More than half of human web traffic already uses hybrid post-quantum key exchange.',
        'Harvest-now-decrypt-later is why this is urgent rather than theoretical. Encrypted traffic captured today can be stored and decrypted once capable machines exist. Anything requiring secrecy for a decade should already be moving to hybrid key exchange, and every organisation needs a cryptographic inventory before it can migrate anything.',
      ],
      words: [
        { term: 'Nonce', means: 'A number used once; reusing one often breaks the encryption entirely.' },
        { term: 'ML-KEM', means: 'The NIST post-quantum key encapsulation standard, FIPS 203.' },
        { term: 'Hybrid key exchange', means: 'Combining classical and post-quantum algorithms so both must break.' },
        { term: 'Crypto agility', means: 'Being able to change algorithms without redesigning the system.' },
      ],
      why: 'Every organisation faces a multi-year cryptographic migration, and almost none currently know where all their cryptography lives.',
      doThis: 'Check whether your browser negotiated a hybrid post-quantum key exchange on a major site. Then list every place your own projects use cryptography.',
      check: 'Why does harvest-now-decrypt-later make post-quantum migration urgent even before quantum computers exist?',
    },
    {
      id: '10-7',
      title: 'AI and LLM security',
      mins: 10,
      oneLine: 'AI systems fail in ways traditional software does not, because their instructions and their data arrive through the same channel.',
      like: 'An assistant who reads every document you hand them and follows any instruction written inside, including the ones you did not write.',
      body: [
        'Prompt injection is the defining vulnerability and it holds the top spot in the OWASP Top 10 for LLM Applications. Because a model has no structural boundary between instruction and data, hostile text in a retrieved document, a web page or an email can redirect its behaviour. Indirect prompt injection, where the payload arrives through content the model reads, is the dangerous form.',
        'There is no complete fix today. Mitigation is architectural: treat all model output as untrusted, keep the model’s permissions minimal, require human confirmation for consequential actions, isolate tool access, and validate output before it reaches anything that executes.',
        'Excessive agency is the related design failure. The damage from prompt injection is bounded by what the model is permitted to do. An agent with broad credentials and no confirmation step converts a text vulnerability into a real-world one: this is exactly why least privilege matters more, not less, for AI systems.',
        'Other risks from the 2025 list are worth knowing by name: sensitive information disclosure, supply chain risk in models and datasets, data and model poisoning, improper output handling, system prompt leakage, and vector and embedding weaknesses in retrieval systems where one tenant’s data can surface for another.',
        'MITRE ATLAS is the ATT&CK equivalent for AI systems, cataloguing real adversarial techniques. Use it the same way: map what applies to your architecture, and use evidence to check whether you would detect it.',
        'And the reverse direction matters too: attackers use AI to scale phishing, generate malware variants and automate reconnaissance, while defenders use it for triage and detection. The tooling changes speed on both sides; the fundamentals in stages 00 to 09 do not change at all.',
      ],
      words: [
        { term: 'Prompt injection', means: 'Hostile instructions in content the model reads, changing its behaviour.' },
        { term: 'Indirect prompt injection', means: 'The payload arrives through retrieved data rather than user input.' },
        { term: 'Excessive agency', means: 'Giving an AI system more permission or autonomy than the risk justifies.' },
        { term: 'MITRE ATLAS', means: 'A knowledge base of adversarial techniques against AI systems.' },
      ],
      why: 'AI systems are being deployed with real permissions faster than the security patterns for them are being agreed, which is the definition of a growing risk.',
      doThis: 'Build a tiny retrieval application, then put an instruction inside a document it retrieves and watch what the model does with it.',
      check: 'Why does limiting an AI agent’s permissions matter more than trying to filter malicious prompts?',
    },
    {
      id: '10-8',
      title: 'Choosing your depth',
      mins: 7,
      oneLine: 'Sampling is over; now pick one field and go deeper than is comfortable, because depth is what makes you valuable.',
      like: 'Studying medicine broadly, then choosing a specialty. You keep the general knowledge, but you become genuinely useful in one place.',
      body: [
        'Choose on evidence, not aspiration. Which of these seven lessons made you lose track of time? Which one did you read twice? Which one made you open a terminal? That reaction is better career advice than any salary chart.',
        'Depth means being able to contribute something new rather than apply what others published. Reproduce known results first, then push slightly past them. The gap between "I understand this" and "I found something" is smaller than beginners assume and larger than experts remember.',
        'Read primary sources. Conference papers, original advisories, source code and specifications, not summaries of summaries. Every field here has a small set of foundational papers, and reading five of them properly puts you ahead of most practitioners.',
        'Build a lab specific to your choice and keep it. Exploit development needs a debugging environment; OT needs simulators; hardware needs physical kit. The lab is where depth actually accumulates.',
        'And keep the breadth alive. Specialists who lose sight of the fundamentals produce technically impressive work that solves the wrong problem. The T-shape is a shape, not a spike.',
      ],
      words: [
        { term: 'Primary source', means: 'The original paper, advisory or specification rather than a summary.' },
        { term: 'Reproduction', means: 'Independently recreating someone else’s published result.' },
        { term: 'Specialisation', means: 'Deliberately going deep in one area.' },
        { term: 'Capstone', means: 'A substantial project demonstrating real capability.' },
      ],
      why: 'Broad knowledge gets you hired; depth in one area is what makes you difficult to replace.',
      doThis: 'Pick one field from this stage. Find three primary sources, read them properly, and write a plan for a capstone project you could finish in a month.',
      check: 'Which topic in this stage did you want to keep reading about, and what does that tell you?',
    },
  ],
};
