import type { Stage } from './types';

export const s11: Stage = {
  number: '11',
  title: 'Becoming a professional',
  subtitle: 'Research, disclosure, writing, portfolio, influence and the long game',
  level: 'EXPERT',
  tags: ['RESEARCH', 'LEADERSHIP'],
  weeks: 4,
  hours: 40,
  hue: 45,
  plain: 'The final stage is about becoming someone the field trusts: doing original work, disclosing it responsibly, explaining it clearly, and helping others.',
  outcome: 'You can turn curiosity into reproducible research, disclose it responsibly, write about it convincingly, and be trusted with judgement calls.',
  project: 'Publish a sanitised capstone portfolio: the problem, your method, your evidence, its limitations, the fix, a talk, and a clear retrospective.',
  checkpoint: 'Your work survives peer review, helps a real audience, and clearly labels what is evidence, what is inference, and what is still unknown.',
  resources: [
    { label: 'CVE Program', href: 'https://www.cve.org/' },
    { label: 'NICE Framework work roles', href: 'https://niccs.cisa.gov/workforce-development/nice-framework' },
    { label: 'disclose.io: disclosure policy templates', href: 'https://disclose.io/' },
  ],
  lessons: [
    {
      id: '11-1',
      title: 'Doing research that holds up',
      mins: 8,
      oneLine: 'Research is a question narrow enough to answer, a method someone else could repeat, and a clear account of what you did not prove.',
      like: 'A recipe rather than a review. Anyone following your steps should get your result, or find out precisely where they diverged.',
      body: [
        'Start with a specific question. "Is this protocol secure?" is unanswerable. "Does this implementation validate the certificate chain when the hostname does not match?" can be tested this afternoon. Narrow questions produce real answers; broad questions produce essays.',
        'Read what already exists before you start. Most promising ideas have been examined, and knowing the prior work tells you where the genuine gaps are. It also prevents the common and embarrassing outcome of rediscovering something published in 2014.',
        'Design so results are reproducible: fixed versions, documented environment, scripted setup, recorded configuration. If you cannot rerun it in three months, neither can a reviewer, and unreproducible security research is only an anecdote.',
        'Distinguish rigorously between what you observed, what you inferred, and what you assumed. This single discipline is what separates credible researchers from confident ones, and reviewers notice it immediately.',
        'Report negative results too. "This attack does not work against this configuration, and here is why" saves other people weeks. The field under-publishes these because they feel like failures, which is precisely why they are valuable.',
      ],
      words: [
        { term: 'Reproducible', means: 'Someone else can repeat your method and get your result.' },
        { term: 'Prior work', means: 'What has already been published on the question.' },
        { term: 'Threat to validity', means: 'A reason your conclusion might be wrong.' },
        { term: 'Negative result', means: 'A finding that something does not work as expected.' },
      ],
      why: 'Research is how the field advances, and reproducibility is the only thing separating research from assertion.',
      doThis: 'Pick a narrow claim from a blog post and try to reproduce it exactly. Document where your environment differed and what happened.',
      check: 'Why is a negative result worth publishing, and why does the field see so few of them?',
    },
    {
      id: '11-2',
      title: 'Fuzzing and finding new bugs',
      mins: 9,
      oneLine: 'Fuzzing throws enormous quantities of malformed input at software and watches for the crashes that reveal real bugs.',
      like: 'Testing a bridge by driving every possible vehicle across it, including several nobody expected to exist.',
      body: [
        'Coverage-guided fuzzing changed the field. AFL++ and libFuzzer instrument the target, observe which code paths each input reaches, and mutate inputs that discover new paths. This turns blind random testing into a guided search, and it finds bugs humans consistently miss.',
        'A good harness matters more than the fuzzer. You want a small, fast entry point that takes a byte buffer and exercises the interesting logic without unnecessary setup. Fuzzing a whole application through its user interface is thousands of times slower than fuzzing the parser directly.',
        'Sanitizers make crashes visible. AddressSanitizer catches memory errors at the moment they occur rather than whenever they eventually corrupt something. Without them, most memory bugs do not crash, and your fuzzer reports nothing while quietly finding plenty.',
        'Triage is the real work. Thousands of crashes usually collapse into a handful of unique bugs. Deduplicate by stack trace, minimise each input to the smallest reproducer, and state what the evidence proves about exploitability. Many crashes are real bugs that are not usefully exploitable.',
        'Variant analysis is the highest-return habit. When you find a bug, look for the same mistake elsewhere in the codebase and in similar projects. Developers repeat patterns, and one finding frequently becomes five.',
      ],
      words: [
        { term: 'Fuzzing', means: 'Automatically feeding malformed input to find crashes.' },
        { term: 'Harness', means: 'The small wrapper that feeds fuzzer input to the target code.' },
        { term: 'Sanitizer', means: 'Instrumentation that makes memory errors crash immediately and visibly.' },
        { term: 'Variant analysis', means: 'Looking for the same bug pattern elsewhere.' },
      ],
      why: 'It is the most productive known method for finding memory-safety bugs at scale, and it is how most modern CVEs in parsers are discovered.',
      doThis: 'Write a small C program that parses a format, fuzz it with AFL++ and AddressSanitizer, and minimise the first crashing input you get.',
      check: 'Why does coverage guidance make fuzzing dramatically more effective than random input generation?',
    },
    {
      id: '11-3',
      title: 'Coordinated disclosure',
      mins: 8,
      oneLine: 'You found a real flaw in someone else’s software; now you have an ethical obligation and a process to follow.',
      like: 'Noticing a structural crack in a public building. You tell the owner and the authorities, you do not post the address online.',
      body: [
        'Report privately first. Look for a security.txt file, a security contact page, or a bug bounty programme. If none exists, try the standard security address, then a national CERT, which can often make contact where you cannot.',
        'Give a reasonable timeline. Ninety days is the widely accepted norm, with flexibility for genuinely complex fixes and urgency for actively exploited issues. Agree it explicitly, and hold to it: deadlines exist because indefinite silence protects nobody except the vendor’s reputation.',
        'Write the report the way you would want to receive it: clear summary, affected versions, reproduction steps, impact, and a suggested fix. Vendors respond far better to reports that reduce their work, and a hostile tone reliably slows everything down.',
        'Request a CVE so the issue has a stable public identifier that defenders can track. Many vendors are CNAs and can assign one directly; otherwise MITRE can. Publish an advisory once the fix ships, and make sure it explains impact in terms defenders can act on.',
        'Never demand payment for silence. Bug bounties are a legitimate framework with rules agreed in advance; asking for money outside one to withhold disclosure is extortion, regardless of how it is phrased. Stay inside the programme’s scope, and expect that going outside it removes your legal protection.',
      ],
      words: [
        { term: 'Coordinated disclosure', means: 'Working with the vendor on a timeline before going public.' },
        { term: 'security.txt', means: 'A standard file listing an organisation’s security contact.' },
        { term: 'CNA', means: 'CVE Numbering Authority: an organisation that can assign CVE IDs.' },
        { term: 'Embargo', means: 'An agreed period before details are made public.' },
      ],
      why: 'How you disclose determines whether you are seen as a professional or a liability, and it determines whether users actually get protected.',
      doThis: 'Read three companies’ vulnerability disclosure policies and compare their scope, timelines and safe harbour language. Note which you would trust.',
      check: 'Why do disclosure deadlines exist, and what goes wrong without them?',
    },
    {
      id: '11-4',
      title: 'Writing that people act on',
      mins: 8,
      oneLine: 'Technical work that nobody understands changes nothing, so writing clearly is a security skill, not a soft one.',
      like: 'A brilliant diagnosis delivered in a language the patient does not speak.',
      body: [
        'Lead with the conclusion. Executives read the first paragraph and may read no further, so it must contain what happened, what it means, and what you want them to do. Building suspense is for fiction.',
        'Write for one audience per document. An executive summary states business impact in plain language with no jargon. A technical report gives reproduction, evidence and root cause. Trying to serve both in one document produces something that satisfies neither.',
        'Impact must be concrete. "SQL injection in the login form" is a fact. "An unauthenticated attacker can read all customer records, including payment details, in under a minute" is a decision. The second one gets funded.',
        'Diagrams carry weight text cannot. A simple attack chain diagram: five boxes and four arrows: communicates more than three paragraphs. Keep them minimal; a diagram people have to decode is worse than none.',
        'Edit ruthlessly. Cut hedging, cut jargon that adds nothing, cut sentences that only demonstrate effort. And be explicit about uncertainty where it exists: "we assess with moderate confidence" is more credible, and more useful, than false precision.',
      ],
      words: [
        { term: 'Executive summary', means: 'The business-level explanation, first and jargon-free.' },
        { term: 'BLUF', means: 'Bottom Line Up Front: state the conclusion immediately.' },
        { term: 'Confidence level', means: 'A stated estimate of how sure you are.' },
        { term: 'Actionable', means: 'The reader knows exactly what to do next.' },
      ],
      why: 'Every finding, incident and recommendation reaches decision-makers as writing. It is one of the most useful skills in the course.',
      doThis: 'Take any technical finding you have written and rewrite it twice: one paragraph for a chief executive, one page for a developer. Show both to someone outside the field.',
      check: 'Why does stating impact in business terms change the outcome of a report?',
    },
    {
      id: '11-5',
      title: 'Portfolio, interviews and proof',
      mins: 8,
      oneLine: 'Nobody can see what you know, so you have to build things that show it.',
      like: 'An architect’s portfolio. Nobody hires from a list of buildings you have read about.',
      body: [
        'A strong portfolio has a small number of substantial pieces rather than many trivial ones: a detection lab with rules you wrote and tested, a tool that solves a real problem, a documented investigation, a research write-up, a disclosed vulnerability. Depth signals capability; volume signals activity.',
        'Write up everything, including failures. A post explaining what you tried, why it did not work, and what you learned is more convincing than a polished success, because it shows how you think, which is what interviewers are actually assessing.',
        'Contribute where it is visible: open-source security tools, Sigma rule repositories, documentation, or a well-written answer to a hard question. Contributions carry an implicit reference from the maintainers who accepted them.',
        'Interviews test reasoning more than recall. Expect "walk me through what happens when you type a URL", "how would you investigate this alert", and "explain a time you were wrong". Say what you do not know, then say how you would find out: that answer beats a confident guess every time.',
        'Certifications validate; they do not educate. Security+ demonstrates fundamentals, OSCP demonstrates hands-on offensive capability, CISSP demonstrates breadth and management context, and cloud certifications map to real platform work. Choose them because a job you want requires one, not as a substitute for building things.',
      ],
      words: [
        { term: 'Portfolio', means: 'Evidence of what you can actually do.' },
        { term: 'Write-up', means: 'A documented account of work, including reasoning.' },
        { term: 'Home lab', means: 'Your own environment for practice, and portfolio evidence in itself.' },
        { term: 'Behavioural interview', means: 'Questions about how you have actually handled situations.' },
      ],
      why: 'This field hires on demonstrated ability far more than on credentials, and demonstrated ability has to be visible to count.',
      doThis: 'Publish one detailed write-up of something you built or investigated in this course. Include what went wrong, not only the result.',
      check: 'Why does a write-up about a failed investigation impress an interviewer?',
    },
    {
      id: '11-6',
      title: 'Risk communication and influence',
      mins: 8,
      oneLine: 'Being right is not enough; security only happens when other people, who do not report to you, choose to act.',
      like: 'A doctor who explains the risk well enough that the patient actually changes their diet.',
      body: [
        'Understand what your audience is measured on. Engineering leaders care about delivery and reliability. Finance cares about cost and exposure. Legal cares about obligation. Frame the same risk in the terms each of them already uses, and you go from obstacle to ally.',
        'Quantify where you can. Comparing potential loss against the cost of a control turns an argument about fear into a business decision. Even rough ranges beat adjectives, and executives are entirely comfortable with ranges and confidence levels.',
        'Do not overstate. Calling everything critical destroys your credibility permanently, and the loss is asymmetric: you spend it once and never get it back. Reserve your strongest language for the situations that genuinely warrant it, and people will believe you when it counts.',
        'Offer options rather than ultimatums. "We can fix it properly in six weeks, mitigate it this week with this trade-off, or accept it with these conditions" respects that the decision is theirs. It also documents the choice, which protects everyone including you.',
        'Say no well when you must. Explain the risk, propose the safest achievable alternative, document the decision if you are overruled, and move on. Security professionals who cannot do this become the department everyone routes around.',
      ],
      words: [
        { term: 'Risk appetite', means: 'How much risk the organisation is willing to accept.' },
        { term: 'Compensating control', means: 'An alternative measure when the ideal fix is not possible.' },
        { term: 'Risk acceptance', means: 'A documented decision to live with a risk.' },
        { term: 'Credibility', means: 'Your most valuable professional asset, and easily spent.' },
      ],
      why: 'Most security failures are organisational, not technical. Influence is what converts knowledge into actual change.',
      doThis: 'Take a real risk you care about and write three versions of the same argument: for an engineer, for a finance director, and for a lawyer.',
      check: 'Why does labelling too many findings as critical make an organisation less safe?',
    },
    {
      id: '11-7',
      title: 'Staying current without burning out',
      mins: 8,
      oneLine: 'The field changes constantly, and the goal is a sustainable system for keeping up rather than heroic attention.',
      like: 'Fitness. Consistency beats intensity, and the people who train every day at seventy percent outlast the ones who sprint and stop.',
      body: [
        'Build a small, deliberate information diet. A handful of high-quality sources you actually read beats a hundred you skim: your national CERT advisories, the CISA KEV catalogue, a few vendor research blogs, and one or two well-run community spaces. Prune anything that produces anxiety rather than knowledge.',
        'Filter by relevance, not by novelty. Most published research will never touch your systems. Ask "does this affect what I am responsible for?" and let the rest go without guilt. The compulsion to read everything is the beginning of burnout.',
        'Learn in projects rather than in feeds. A weekend building something with a new technology teaches more than three months of reading about it, and it produces evidence you can show.',
        'Burnout in security is common and has specific causes: constant alerting, on-call, adversarial work, the sense that you can never be finished, and the belief that a breach would be your personal failure. Take the leave, keep the boundaries, and treat rest as operational capacity rather than weakness.',
        'And keep perspective. You cannot prevent every incident, and a mature organisation does not expect you to. Your job is to reduce likelihood, limit impact, and respond well, not to guarantee an outcome nobody can guarantee.',
      ],
      words: [
        { term: 'Information diet', means: 'The deliberate set of sources you follow.' },
        { term: 'Alert fatigue', means: 'Desensitisation from too many alerts, causing real ones to be missed.' },
        { term: 'On-call', means: 'Being available outside working hours to respond to incidents.' },
        { term: 'Sustainable pace', means: 'A workload you could maintain for years.' },
      ],
      why: 'The people who have long, effective careers in this field are the ones who built a system instead of relying on enthusiasm.',
      doThis: 'Write down every security source you currently follow. Cut it to five. Notice over a fortnight whether you actually missed anything important.',
      check: 'How would you tell the difference between learning something because it matters and reading it because you feel behind?',
    },
    {
      id: '11-8',
      title: 'Teaching, mentoring and what comes next',
      mins: 8,
      oneLine: 'Explaining what you know makes you better at it, and it is how the field replaces itself.',
      like: 'A craft passed down through apprenticeships. Every master was somebody’s beginner, and the craft survives only because they taught.',
      body: [
        'Teaching exposes the gaps in your own understanding immediately and mercilessly. The moment you try to explain something clearly, you discover which parts you had only memorised. This is the fastest known way to convert familiarity into genuine knowledge.',
        'Start where you are. You do not need to be an expert to help someone one step behind you: in fact you are better placed than an expert, because you still remember what was confusing and why.',
        'Contribute concretely: write documentation, answer questions properly, create a lab exercise, give an internal talk, mentor one person consistently. Small consistent contributions compound into a reputation far more reliably than occasional grand gestures.',
        'Be the kind of colleague this field needs. Investigate without blame, give credit, help beginners, and admit your own mistakes. Security has a gatekeeping problem. Refusing to join in makes the field better.',
        'Finally: you will never finish this course, and that is the correct outcome. Cybersecurity is a practice, not a body of knowledge to complete. Keep a lab, keep a notebook, keep asking how things actually work, and keep teaching what you learn. That is the whole job, for the rest of your career.',
      ],
      words: [
        { term: 'Mentoring', means: 'Consistently helping one person develop over time.' },
        { term: 'Blameless culture', means: 'Analysing failure to fix systems, not to punish people.' },
        { term: 'Gatekeeping', means: 'Making a field artificially hard to enter.' },
        { term: 'Community contribution', means: 'Work that helps people beyond your own organisation.' },
      ],
      why: 'The field grows faster than it can train people, and the shortage is a training problem before it is a talent problem.',
      doThis: 'Teach one lesson from this course to someone who does not work in security. Note every question they asked that you could not answer well.',
      check: 'What is the one topic in this entire course you could teach confidently right now, and what would you need to learn to teach the next one?',
    },
  ],
};
