import type { Stage } from './types';

export const s12: Stage = {
  number: '12',
  title: 'Internship ready',
  subtitle: 'The tools and the audit work real junior adverts ask for — Burp, ZAP, Nmap, VAPT, control testing',
  level: 'MEDIUM',
  tags: ['CAREER', 'OFFENSE', 'DEFENSE', 'LEADERSHIP'],
  weeks: 3,
  hours: 55,
  hue: 95,
  plain: 'Everything else teaches you how security works. This stage teaches you to do the specific tasks junior job adverts list, so the requirements stop looking like a foreign language.',
  outcome: 'You can drive Burp Suite, ZAP and Nmap on a legal target, write a finding a developer will act on, and take part in a security audit and a risk assessment.',
  project: 'Run a full mini-assessment of a deliberately vulnerable app: scope it, scan it, verify by hand, and deliver a findings report plus a small control-testing worksheet.',
  checkpoint: 'You can read a junior job advert line by line and say, honestly, which parts you have actually done and where the evidence is.',
  resources: [
    { label: 'PortSwigger Web Security Academy (free, includes Burp)', href: 'https://portswigger.net/web-security' },
    { label: 'OWASP ZAP', href: 'https://www.zaproxy.org/' },
    { label: 'Nmap reference guide', href: 'https://nmap.org/book/man.html' },
    { label: 'ISO/IEC 27001 Annex A control overview', href: 'https://www.iso.org/standard/27001' },
  ],
  lessons: [
    {
      id: '12-1',
      title: 'VAPT: the job those adverts describe',
      mins: 8,
      oneLine: 'VAPT means finding weaknesses with tools and then proving by hand which of them are actually real.',
      like: 'A building survey. The scanner walks round with a clipboard listing everything that might be wrong; the surveyor then goes and pushes on each one to see which actually gives way.',
      body: [
        'VAPT stands for Vulnerability Assessment and Penetration Testing, and it is two jobs joined by a hyphen. The assessment half is broad and mostly automated: scan everything, list what looks wrong, rank it. The testing half is narrow and manual: take the promising items and prove whether they can really be exploited.',
        'Most junior work is weighted heavily towards the first half, and that is good news, because the first half is learnable in weeks. You run the scanner, you remove the false positives, you verify the real ones carefully, and you write them up. The senior tester takes the interesting chains further.',
        'The single skill that separates a useful junior from a noisy one is false-positive triage. Scanners flag things that are not exploitable in context all the time — a "vulnerable" library version that is never called, a missing header on a page with no session, a self-signed certificate on an internal test box. Handing a client the raw scanner output is not a report; it is homework you did not do.',
        'The workflow is the same every time: agree scope in writing, discover what is actually there, scan, verify by hand, assess real impact, write it up, and retest after the fix. When an advert says "perform VAPT on web, API and infrastructure", it means run that loop across three kinds of target.',
        'Infrastructure means hosts, ports and services — stage 02 and stage 06 territory. Web and API mean applications — stage 05. Nothing in that advert is outside what this course covers; the only missing pieces were the tools, which is what the next three lessons are for.',
      ],
      words: [
        { term: 'VAPT', means: 'Vulnerability Assessment and Penetration Testing — scan broadly, then verify by hand.' },
        { term: 'False positive', means: 'A tool reporting a problem that is not actually exploitable here.' },
        { term: 'Verification', means: 'Proving by hand that a reported weakness is real.' },
        { term: 'Retest', means: 'Checking after the fix that the issue is genuinely closed.' },
      ],
      why: 'It is the phrase at the top of most junior security adverts in South Asia and the Middle East, and it describes about eighty percent of what you would actually be asked to do.',
      doThis: 'Take the Navitsa-style advert line "Perform VAPT on web, API and infrastructure systems" and write, under each of the three, which stage of this course covers it and which lab you would practise it in.',
      check: 'A scanner reports a critical flaw in a library. What do you check before it goes anywhere near a report?',
    },
    {
      id: '12-2',
      title: 'Burp Suite, properly',
      mins: 10,
      oneLine: 'Burp sits between your browser and the site so you can read, change and replay every request.',
      like: 'A post office where you get to open every letter, read it, edit it, and send it on — in both directions.',
      body: [
        'The Community Edition is free and is what you should learn on. The paid Professional edition adds an automated scanner and a few conveniences, but every manual technique that matters works identically in Community, and interviewers know this.',
        'Set it up once: start Burp, set your browser proxy to 127.0.0.1 on port 8080, then install Burp\'s CA certificate in the browser so HTTPS traffic can be read. Burp also ships an embedded browser with this already done, which removes the most common beginner blocker.',
        'Learn the tabs in this order. **Proxy** intercepts traffic and holds requests so you can edit them before they go. **HTTP history** is the log of everything that passed through, and it is where most of your actual investigation happens. **Repeater** takes one request and lets you send it again, tweaked, as many times as you want — this is where you confirm an injection or an access control flaw. **Intruder** automates a request with a list of payloads, for things like testing a parameter or spraying an endpoint. **Decoder** and **Comparer** handle encoding and spotting the difference between two responses.',
        'The workflow that finds real bugs is unglamorous: browse the whole application normally with Burp recording, so history fills with every endpoint. Then read that history. Look for identifiers you could change, parameters that end up in a page or a query, endpoints that never asked who you were. Send the interesting ones to Repeater and start poking.',
        'Two habits from day one. Set your scope in the Target tab so Burp only records what you are allowed to touch, which stops you accidentally logging traffic to your bank in the same session. And save your project file, because "I found something and then closed Burp" is a story every tester tells exactly once.',
      ],
      words: [
        { term: 'Intercepting proxy', means: 'A tool that sits between browser and server so requests can be read and changed.' },
        { term: 'Repeater', means: 'Burp\'s tool for re-sending one request with modifications.' },
        { term: 'Intruder', means: 'Burp\'s tool for sending many variations of a request automatically.' },
        { term: 'Scope', means: 'The targets Burp is allowed to record and act on.' },
      ],
      why: 'Burp is named in a large share of junior security adverts, and "familiarity with Burp Suite" means being able to do the Repeater loop without being shown.',
      doThis: 'Install Burp Community, proxy the PortSwigger Web Security Academy labs through it, and solve one access control lab entirely from Repeater. That is the exact skill the advert is asking for.',
      check: 'You change a numeric ID in a request and get another user\'s record back. Which Burp tool did you use, and what do you capture as evidence?',
    },
    {
      id: '12-3',
      title: 'OWASP ZAP and automated scanning',
      mins: 8,
      oneLine: 'ZAP is the free, scriptable scanner you reach for when you need coverage rather than precision.',
      like: 'A metal detector swept across a field. Fast and thorough at finding candidates, useless at telling you which are treasure and which are bottle caps.',
      body: [
        'ZAP is fully open source and includes an active scanner, which makes it the natural free counterpart to Burp Professional. Many organisations run both: ZAP or Burp Pro for automated coverage, and manual Burp work for anything that needs judgement.',
        'Know the difference between its two scan types, because getting this wrong causes incidents. A **passive scan** only observes traffic that already happened and is safe against anything. An **active scan** sends attack payloads at the target — it can create records, trigger emails, lock accounts, and in badly built applications delete data. Never point an active scan at anything you do not have explicit written permission to attack.',
        'The spider crawls links to build a site map; the AJAX spider drives a real browser to reach content that only appears after JavaScript runs. Modern applications need the second one, and forgetting it is why beginners report "the scanner found nothing" on a single-page app.',
        'Authentication is the part everyone gets wrong. A scan run without a logged-in session tests only the public surface, which is usually the least interesting part. Configuring a context, a user, and a logged-in indicator so ZAP stays authenticated is the difference between a useful scan and a wasted one.',
        'ZAP is also automatable, which is where it earns its place in a pipeline: its baseline scan runs in CI against every build and fails on new findings. That is a genuinely useful thing for an intern to set up, and it is the sort of initiative that gets noticed.',
      ],
      words: [
        { term: 'Passive scan', means: 'Analysing traffic that already happened. Safe.' },
        { term: 'Active scan', means: 'Sending attack payloads at the target. Requires permission.' },
        { term: 'Spider / crawler', means: 'Automatically discovering the pages and endpoints of a site.' },
        { term: 'Baseline scan', means: 'A quick automated check suitable for running on every build.' },
      ],
      why: 'It is the second tool named in the advert, it is free forever, and knowing when *not* to run an active scan is a maturity signal.',
      doThis: 'Run ZAP against a local deliberately vulnerable app such as OWASP Juice Shop. Do a passive scan first, then an authenticated active scan, and compare how many findings each produced.',
      check: 'Why can an active scan be dangerous, and what must exist before you run one?',
    },
    {
      id: '12-4',
      title: 'Nmap for real work',
      mins: 9,
      oneLine: 'Nmap answers one question thoroughly: what is listening on these machines, and what exactly is it.',
      like: 'Walking the perimeter of a building at night, noting which windows have lights on, then getting close enough to read the name on each door.',
      body: [
        'Six invocations cover most real work. A host discovery sweep with `-sn` finds what is alive. A default TCP scan finds the common ports. `-p-` scans all 65,535 ports, which is slow but finds the things hidden high up deliberately. `-sV` identifies the service and version. `-O` guesses the operating system. `-sC` runs the default script set, which does a surprising amount of enumeration for you.',
        'The one to remember is `nmap -sV -sC -p- -oA scanname target` — all ports, versions, default scripts, and output saved in all three formats. The `-oA` matters more than it looks: an unsaved scan is work you will have to repeat, and the file is evidence of what you found and when.',
        'Timing is a real control, not a detail. `-T4` is a reasonable default on a robust network; `-T1` or `-T2` are for fragile targets or when you are trying not to trip alarms. Industrial and medical equipment has genuinely been knocked offline by default-speed scans, which is why the OT lesson in stage 10 says what it does.',
        'Understand what the results mean. **Open** means something accepted the connection. **Closed** means the host answered but nothing is listening. **Filtered** means you got no answer at all, which usually means a firewall — and that is information too. UDP scanning with `-sU` is slow and unreliable by nature, because silence is ambiguous.',
        'The Nmap Scripting Engine is where the depth is. Scripts exist for enumerating SMB shares, pulling SSL certificate details, checking for specific known vulnerabilities, and grabbing service banners. `--script vuln` is a common starting point, though it is noisy and its findings still need manual verification like any other scanner output.',
      ],
      words: [
        { term: 'Host discovery', means: 'Finding which addresses have a live machine on them.' },
        { term: 'Service and version detection', means: 'Identifying exactly what software is listening, not just that something is.' },
        { term: 'Filtered port', means: 'No response — usually a firewall dropping the packet.' },
        { term: 'NSE', means: 'Nmap Scripting Engine — scripts that automate enumeration and checks.' },
      ],
      why: 'Every infrastructure assessment starts here, and "familiarity with Nmap" in an advert means being able to explain your flags and read the output.',
      doThis: 'Scan your own lab VM with `-sV -sC -p-`. For every open port, write one line saying what the service is and what you would check next. That written list is the actual deliverable.',
      check: 'What is the practical difference between a closed port and a filtered port, and what does each tell you about the target?',
    },
    {
      id: '12-5',
      title: 'Writing a finding somebody fixes',
      mins: 9,
      oneLine: 'A finding is a small persuasive document: here is the problem, here is the proof, here is what it costs, here is the fix.',
      like: 'A doctor\'s note. Symptom, test result, diagnosis, prescription. Nobody wants the differential diagnosis you considered and discarded.',
      body: [
        'Every finding needs six parts, and juniors usually miss the last two. A clear title that names the flaw and the location. A severity with reasoning. Reproduction steps precise enough that someone else gets the same result. Evidence — a screenshot, a request and response, a log line. The actual business impact. And a specific remediation.',
        'Severity should be argued, not asserted. CVSS gives you a vector and a number, but the sentence that follows matters more: "critical because this is internet-facing, needs no authentication, and exposes every customer record". If you cannot write that sentence, the severity is probably wrong.',
        'Evidence has rules. Redact real personal data — a screenshot proving you read customer records should show one record with the sensitive fields blurred, not a database dump. Include the full request and response, because developers reproduce from those, not from prose. Timestamp everything.',
        'Remediation must be specific enough to implement. "Use parameterised queries in the getUserById function in orders.js" is a fix. "Improve input validation" is a way of telling the developer you did not understand the bug. If you genuinely do not know the fix, say so and describe the property the fix must have.',
        'Write the impact for the person who signs off the work, not for yourself. "SQL injection in the login form" is a fact. "An attacker with no account can retrieve every customer record, including payment details, in under a minute" is a decision. The second one gets scheduled this sprint.',
        'And keep a personal template. Every finding you write against the same skeleton gets faster and more consistent, and consistency is most of what makes a junior look experienced.',
      ],
      words: [
        { term: 'Reproduction steps', means: 'Instructions precise enough for someone else to see the same result.' },
        { term: 'Proof of concept', means: 'The minimum demonstration that the flaw is genuinely exploitable.' },
        { term: 'Remediation', means: 'The specific change that closes the issue.' },
        { term: 'Redaction', means: 'Removing real personal or sensitive data from evidence.' },
      ],
      why: 'The advert says "document vulnerabilities, risks and remediation recommendations" — this lesson is that bullet point, and the report is the only part of your work most people ever see.',
      doThis: 'Take any lab you have solved and write the finding against the six-part skeleton. Give it to someone non-technical and ask them to tell you back what the risk is.',
      check: 'Rewrite "XSS found on the search page — fix input validation" into a finding somebody would actually action.',
    },
    {
      id: '12-6',
      title: 'How a security audit actually runs',
      mins: 9,
      oneLine: 'An audit checks whether the controls a company claims to have are real, working, and evidenced.',
      like: 'A restaurant hygiene inspection. It is not about whether the chef says the fridge is cold — it is about the temperature log, signed, for the last six months.',
      body: [
        'This is the whole job behind the words "control assurance". A control is something the organisation does to reduce risk — quarterly access reviews, mandatory MFA, encrypted backups. The audit asks three questions of each one: does it exist on paper, is it actually operating, and can you prove it?',
        'Two words you will hear constantly. **Design effectiveness** asks whether the control, as written, would actually address the risk — a password policy that permits eight characters is badly designed no matter how well it runs. **Operating effectiveness** asks whether it really happens — a beautifully designed quarterly review that was last performed fourteen months ago is not operating.',
        'Testing follows a ladder of strength. **Inquiry** is asking someone, and it proves almost nothing on its own. **Observation** is watching it happen. **Inspection** is examining the records. **Re-performance** is doing it yourself and getting the same result, and it is the strongest evidence there is. Auditors combine them; juniors are usually given inspection work, which means sampling.',
        'Sampling is the mechanical part of the job. If access reviews should happen quarterly across forty systems, you do not check all one hundred and sixty; you pick a defined sample, test those, and record how you chose them. An exception is any sampled item that fails, and exceptions are what the report is built from.',
        'Evidence is everything, and this is where an intern adds real value. A screenshot with a visible date, an exported ticket, a signed approval, a system-generated report. "The team confirmed they do this" is not evidence, it is inquiry, and it will be rejected by whoever reviews your work.',
        'Frameworks give you the control list so you are not inventing one. ISO 27001 Annex A, the NIST CSF categories from stage 00, and SOC 2 trust criteria all describe similar controls in different words. Most companies map their controls to one and report against several.',
      ],
      words: [
        { term: 'Control', means: 'Something an organisation does to reduce a risk.' },
        { term: 'Design vs operating effectiveness', means: 'Would it work as written, and is it actually happening.' },
        { term: 'Sampling', means: 'Testing a defined subset rather than every instance.' },
        { term: 'Exception', means: 'A tested item that failed — the raw material of the audit report.' },
      ],
      why: 'This is the entire Control Assurance advert. Nothing in it requires hacking skill, and it is one of the most reliable ways into the industry.',
      doThis: 'Pick one control in your own life — "my important accounts have MFA". Write the test steps, gather evidence for a sample of three accounts, and record any exceptions. That is an audit working paper.',
      check: 'A manager tells you the quarterly access review is always done. What would you need before you could record that control as operating effectively?',
    },
    {
      id: '12-7',
      title: 'Risk assessment and the risk register',
      mins: 8,
      oneLine: 'A risk assessment turns vague worry into a ranked, owned, tracked list that somebody has to decide about.',
      like: 'A to-do list where every item has a cost of ignoring it, a name next to it, and a date.',
      body: [
        'The process is the same everywhere. Identify what could go wrong. Analyse how likely it is and how bad it would be. Evaluate it against the organisation\'s appetite. Then treat it — reduce, transfer, avoid or accept, the same four options from stage 04.',
        'Inherent risk is the risk before controls; residual risk is what remains after them. Both belong in the assessment, because the gap between them is exactly what your controls are buying, and it is the number that justifies their cost.',
        'A risk register is the living document. Each row: an identifier, a plain-language description, the affected asset, likelihood, impact, the resulting score, existing controls, the treatment decision, an owner, and a review date. The two fields juniors leave blank are owner and review date, and those two are the entire reason the register exists — a risk with no name against it is a risk nobody is handling.',
        'Write risks as cause and consequence, not as one-word topics. "Phishing" is a topic. "An employee enters credentials on a phishing page, allowing an attacker to access the finance mailbox and redirect a supplier payment" is a risk you can score, control and test.',
        'Scoring is usually a five-by-five matrix, and it is more subjective than the neat colours suggest. That is acceptable as long as the criteria are written down and applied consistently — the value is in the ranking and the conversation, not in the arithmetic. Anyone who presents a risk score as precise is overselling it.',
      ],
      words: [
        { term: 'Inherent risk', means: 'The risk before any controls are applied.' },
        { term: 'Residual risk', means: 'What remains after controls.' },
        { term: 'Risk register', means: 'The living list of identified risks, owners and decisions.' },
        { term: 'Risk owner', means: 'The named person accountable for the decision about it.' },
      ],
      why: 'Both adverts name risk assessment explicitly, and the register is the artefact most GRC work revolves around.',
      doThis: 'Build a five-row risk register for a small imagined company. Force yourself to fill in owner and review date on every row.',
      check: 'Rewrite "ransomware" as a proper risk statement with a cause and a consequence.',
    },
    {
      id: '12-8',
      title: 'Applying when you have no experience',
      mins: 9,
      oneLine: 'Junior adverts describe an ideal candidate who does not exist; what they actually screen for is evidence that you can do the work.',
      like: 'A recipe listing twelve ingredients when the dish genuinely needs six. The cook knows which six.',
      body: [
        'Read a requirements list as a wish list, not a gate. "Familiarity with Burp Suite, OWASP ZAP, Nmap or similar" contains the word "or similar" for a reason. Applying at roughly sixty percent of the listed requirements is normal and expected; waiting until you meet all of them means applying a year late, alongside people who applied a year early.',
        'What actually differentiates an application is evidence. Not certificates, not a claim of familiarity — a link. A write-up of a lab you solved with your reasoning shown. A findings report you wrote against a deliberately vulnerable app. A GitHub repository with a small tool that parses logs. A short blog post explaining SSRF in plain language. Three of those beat any wording you could put on a CV.',
        'For the roles in front of you, the mapping is direct. VAPT on web and API is Web Security Academy plus a written report. Infrastructure is an Nmap scan of your own lab with your notes. Endpoint monitoring is the Sysmon lab in stage 07. Audits and control assurance is the working paper from lesson 12-6. Cloud is a free-tier account with the posture tool switched on.',
        'In the interview, expect reasoning questions rather than trivia: walk me through what happens when you type a URL, how would you investigate this alert, tell me about something you got wrong. Saying "I do not know, but here is how I would find out" is a strong answer. Bluffing is the only reliably fatal one, because the person opposite has done the job.',
        'Also read the advert for what it tells you about them. A list this broad on an internship usually means a small team where you will touch everything, which is excellent for learning and demanding on your first month. Ask in the interview what an intern actually did last quarter — the answer is informative, and asking it makes you look like someone who thinks about the work.',
        'Finally, apply. One hundred and forty-three applicants sounds discouraging, but most will have no evidence attached at all. A single link to a report you wrote moves you past the majority before anyone has read your CV.',
      ],
      words: [
        { term: 'Evidence of skill', means: 'Something a stranger can look at that shows you did the work.' },
        { term: 'Write-up', means: 'A documented account of solving something, including the reasoning.' },
        { term: 'Transferable requirement', means: 'A listed tool that any equivalent tool satisfies.' },
        { term: 'Screening', means: 'The first filter, usually looking for reasons to shortlist rather than reject.' },
      ],
      why: 'The gap between people who get junior roles and people who do not is rarely knowledge. It is visible evidence and applying earlier than feels comfortable.',
      doThis: 'Take the advert in front of you. Write every requirement in one column, and in the next column either the evidence you already have or the smallest lab that would create it. Then build the top two.',
      check: 'Which requirement on the advert you want could you produce evidence for this weekend?',
    },
    {
      id: '12-9',
      title: 'The CV and the portfolio',
      mins: 9,
      oneLine: 'A CV gets you past the filter; the portfolio is what convinces the person who reads it.',
      like: 'A menu and the actual food. The menu decides whether anyone orders; the food decides whether they come back.',
      body: [
        'Assume your CV gets thirty seconds and possibly a keyword filter before it. That means one page, plain formatting, no photo, no skill bars — nobody can act on "Networking ▓▓▓▓░". Save it as a PDF named with your own name, because "cv_final_v3.pdf" arrives in a folder with four hundred others.',
        'Lead with evidence, not adjectives. Instead of a Skills section listing twenty tools you have opened once, write a Projects section where each entry is one line of what you built, one line of what it demonstrates, and a link. Three real projects beat any list. If a recruiter has to take your word for something, it is not evidence.',
        'Mirror the language of the advert, honestly. If it says "VAPT" and "OWASP Top 10", use those words where they are true of you — the filter and the human are both scanning for them. Never claim a tool you could not be asked about, though: the interviewer has done the job, and one bluff undoes everything else on the page.',
        'For each project, a good entry reads: what the problem was, what you built, what you found or learned, and what you would do differently. That last part is the one that marks you out — it shows judgement rather than completion, and it is the natural opening for a conversation in the interview.',
        'Keep a portfolio somewhere a stranger can reach in one click: a GitHub profile with a real README, or a simple site. Pin three repositories, write an actual README for each one explaining the decisions rather than just the commands, and include the failures. A write-up saying "this did not work, here is why" is worth more than a polished success, because anyone can copy a tutorial.',
        'Two more things people forget. Put your labs on it — a home lab with a written build log is legitimate experience, and adverts explicitly ask for it. And write about something you learned, in plain language, once a month; the ability to explain SSRF to a non-specialist is a demonstrable skill and it is rarer than knowing what SSRF is.',
      ],
      words: [
        { term: 'ATS', means: 'Applicant tracking system — software that filters CVs on keywords before a human sees them.' },
        { term: 'Portfolio', means: 'Work a stranger can look at without asking you for anything.' },
        { term: 'Write-up', means: 'A documented account of solving something, including the reasoning and the dead ends.' },
        { term: 'Pinned repository', means: 'The projects you choose to show first on a GitHub profile.' },
      ],
      why: 'This field hires on demonstrated ability, and demonstrated ability has to be visible before an interview to get you one. The gap between people who get junior roles and people who do not is rarely knowledge.',
      doThis: 'Cut your CV to one page. Replace the skills list with three projects, each with a link. Then write a README for the best one explaining why you built it that way.',
      check: 'Take one line from your CV. Could a stranger verify it in under a minute? If not, what link would make it verifiable?',
    },
    {
      id: '12-10',
      title: 'The interview',
      mins: 9,
      oneLine: 'Interviews test how you think, not what you memorised, and the honest answer beats the confident one every time.',
      like: 'A driving test. They are not checking whether you know the manual — they are watching how you handle a junction you did not expect.',
      body: [
        'Expect four kinds of question. Fundamentals, usually "walk me through what happens when you type a URL into a browser" — they are checking whether your knowledge is a chain or a pile. Scenario, usually "this alert just fired, what do you do" — they want your process, not the answer. Experience, "tell me about something you built" — this is where your portfolio earns its keep. And behavioural, "tell me about a time you were wrong".',
        'For scenario questions, narrate your reasoning out loud and ask clarifying questions first. What is the asset, who is the user, is it internet-facing, what does normal look like here? A candidate who asks two good questions before answering is demonstrating exactly the habit the job requires. Jumping straight to a tool name is the weaker answer even when the tool is right.',
        'When you do not know, say so and then say how you would find out. "I have not worked with Sentinel, but it is a SIEM, so I would expect to start from the identity logs and pivot on the account — is that roughly how it works there?" That answer is strong. Bluffing is the only reliably fatal move, because the person opposite has done the job and will notice.',
        'Prepare three stories in advance and know them cold: something you built, something that went wrong and what you changed, and something you had to explain to a non-technical person. Structure each as situation, task, action, result. Most behavioural questions are one of those three wearing a different hat.',
        'Do fifteen minutes of homework on the company. What do they actually sell, what would an attacker want from them, what is in the news about their sector? Then have two real questions ready. "What did your last intern actually work on?" and "what does the first month look like?" are better than anything about culture, because the answers tell you something and asking them signals you are thinking about the work.',
        'Finally, the boring mechanics that decide more outcomes than people admit: test the video call setup beforehand, have your portfolio open in a tab, keep water nearby, and send a short thank-you afterwards mentioning one specific thing from the conversation. And ask what the next step is before you hang up.',
      ],
      words: [
        { term: 'Scenario question', means: 'A hypothetical incident used to see your process rather than your recall.' },
        { term: 'STAR', means: 'Situation, task, action, result — a structure for answering behavioural questions.' },
        { term: 'Clarifying question', means: 'Asking for missing context before answering. A signal of competence, not doubt.' },
        { term: 'Technical screen', means: 'An early filtering interview, often with a recruiter or a short practical exercise.' },
      ],
      why: 'You can be the strongest candidate on paper and lose to someone who explained their reasoning better. Interviewing is a separate skill from the job, and unlike the job, it is one you can rehearse.',
      doThis: 'Record yourself answering "walk me through what happens when you type a URL" for three minutes. Play it back. Most people discover they skipped DNS entirely.',
      check: 'You are asked about a tool you have never used. What exactly do you say?',
    },
  ],
};
