/**
 * Writes the service worker after `next build`, with a precache list taken from
 * what was actually built.
 *
 * Doing it here rather than hand-maintaining a list matters because Next hashes
 * its chunk filenames: a hard-coded list goes stale on the very next build and
 * fails silently, which is the worst way for a cache to be wrong. The cache
 * name is derived from those filenames, so a new build is automatically a new
 * cache and the old one is cleaned up on activate.
 */

import { createHash } from 'node:crypto';
import { readdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'out');
const BASE = process.env.PAGES_BASE_PATH ? `/${process.env.PAGES_BASE_PATH}` : '';

/** Files worth having before the network is gone. */
const PRECACHE_EXT = new Set(['.html', '.css', '.js', '.png', '.svg', '.webmanifest', '.woff2']);
/* Audio is deliberately excluded: a full narration library is tens of
   megabytes, and forcing that down on first visit would be hostile. It caches
   as you listen instead. */
const SKIP_DIRS = new Set(['audio']);
/* The worker must never precache itself: a cached worker is how you ship an
   update that can never take effect. */
const SKIP_FILES = new Set(['sw.js']);

async function walk(dir, base = '') {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const rel = base ? `${base}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      out.push(...(await walk(path.join(dir, entry.name), rel)));
    } else if (PRECACHE_EXT.has(path.extname(entry.name)) && !SKIP_FILES.has(rel)) {
      out.push(rel);
    }
  }
  return out;
}

try {
  await stat(OUT);
} catch {
  console.error('No out/ directory — run the build first.');
  process.exit(1);
}

const files = (await walk(OUT)).sort();
const urls = [`${BASE}/`, ...files.map((f) => `${BASE}/${f}`)];
const version = createHash('sha256').update(urls.join('\n')).digest('hex').slice(0, 12);

const sw = `/* Generated by scripts/make-sw.mjs — do not edit. Build ${version}. */
const CACHE = 'cipher-school-${version}';
const START = ${JSON.stringify(`${BASE}/`)};
const PRECACHE = ${JSON.stringify(urls, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      // One failed asset must not fail the whole install, so they are added
      // individually rather than with addAll.
      .then((cache) => Promise.all(PRECACHE.map((url) => cache.add(url).catch(() => {}))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  if (event.data === 'skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Navigations: try the network so a new deploy is picked up, fall back to the
  // cached start page when offline. This is what makes the app open on a train.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(START, copy)).catch(() => {});
          return res;
        })
        .catch(() => caches.match(START).then((hit) => hit || caches.match(request))),
    );
    return;
  }

  // Everything else: cache first. Chunk filenames are content-hashed, so a
  // cached hit can never be stale — a changed file is a different URL.
  event.respondWith(
    caches.match(request).then((hit) => {
      if (hit) return hit;
      return fetch(request).then((res) => {
        if (res.ok && res.type === 'basic') {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(request, copy)).catch(() => {});
        }
        return res;
      });
    }),
  );
});
`;

await writeFile(path.join(OUT, 'sw.js'), sw);
console.log(`service worker: ${urls.length} files precached, build ${version}`);
