/**
 * Writes app/curriculum/light.ts — the part of the curriculum the app needs
 * before anyone has clicked anything.
 *
 * The roadmap needs a stage's metadata and, for each lesson, its title, its one
 * line and its length. It does not need the twenty-two thousand words of
 * explanation, the two hundred and twenty quiz questions or the four hundred
 * jargon definitions, and shipping those in the first bundle meant a third of
 * it was prose nobody had asked to read yet.
 *
 * The generated file has the same shape as the real thing minus the heavy
 * fields, which is what lets every piece of navigation, filtering and lookup in
 * the app keep working against it untouched.
 *
 * Regenerated by `npm run build` (prebuild) and checked by `npm test`, so it
 * cannot drift from the source it was derived from.
 *
 *   node scripts/make-index.mjs [--check]
 */

import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIR = path.join(ROOT, 'app', 'curriculum');
const OUT = path.join(DIR, 'light.ts');

/*
 * The stage files are imported one by one rather than through index.ts: Node
 * cannot resolve TypeScript's extensionless "./s00" specifiers, but each stage
 * file only imports its types, and type-only imports are erased.
 */
async function load(name) {
  const mod = await import(pathToFileURL(path.join(DIR, `${name}.ts`)).href);
  return mod[name];
}

const stageFiles = (await readdir(DIR)).filter((f) => /^s\d\d\.ts$/.test(f)).sort();
const stages = [];
for (const file of stageFiles) stages.push(await load(file.slice(0, -3)));

const quizFiles = (await readdir(DIR)).filter((f) => /^quiz-[a-z]\.ts$/.test(f)).sort();
const questions = [];
for (const file of quizFiles) {
  const mod = await import(pathToFileURL(path.join(DIR, file)).href);
  questions.push(...Object.values(mod)[0]);
}

/* Deduplicated the same way the glossary is, so a term belongs to one lesson. */
const seen = new Set();
const termsByLesson = new Map();
for (const stage of stages) {
  for (const lesson of stage.lessons) {
    for (const w of lesson.words) {
      const key = w.term.toLowerCase();
      if (seen.has(key)) continue;
      seen.add(key);
      const list = termsByLesson.get(lesson.id) ?? [];
      list.push(w.term);
      termsByLesson.set(lesson.id, list);
    }
  }
}

const questionIdsByLesson = new Map();
for (const q of questions) {
  const list = questionIdsByLesson.get(q.lesson) ?? [];
  list.push(q.id);
  questionIdsByLesson.set(q.lesson, list);
}

/*
 * Review card ids per lesson. The ids are what the app needs to know which
 * cards a finished lesson unlocks; the questions and definitions behind them
 * are only needed once a review actually starts.
 */
const cardIds = {};
for (const stage of stages) {
  for (const lesson of stage.lessons) {
    cardIds[lesson.id] = [
      ...(questionIdsByLesson.get(lesson.id) ?? []).map((id) => `q:${id}`),
      ...(termsByLesson.get(lesson.id) ?? []).map((t) => `w:${t}`),
    ];
  }
}

const light = stages.map((s) => ({
  number: s.number,
  title: s.title,
  subtitle: s.subtitle,
  level: s.level,
  tags: s.tags,
  weeks: s.weeks,
  hours: s.hours,
  hue: s.hue,
  plain: s.plain,
  outcome: s.outcome,
  project: s.project,
  checkpoint: s.checkpoint,
  resources: s.resources,
  lessons: s.lessons.map((l) => ({ id: l.id, title: l.title, oneLine: l.oneLine, mins: l.mins })),
}));

const body = `/*
 * GENERATED by scripts/make-index.mjs — do not edit.
 *
 * The roadmap, without the reading. Everything here is needed to draw the
 * course before anyone has opened a lesson; the prose, the questions and the
 * definitions load on demand from ./full.
 */
import type { Level } from './types';

export type LightLesson = { id: string; title: string; oneLine: string; mins: number };

export type LightStage = {
  number: string;
  title: string;
  subtitle: string;
  level: Level;
  tags: string[];
  weeks: number;
  hours: number;
  hue: number;
  plain: string;
  outcome: string;
  project: string;
  checkpoint: string;
  resources: { label: string; href: string }[];
  lessons: LightLesson[];
};

export const stages: LightStage[] = ${JSON.stringify(light, null, 2)};

/** Review card ids per lesson, so unlocking does not need the cards themselves. */
export const cardIdsByLesson: Record<string, string[]> = ${JSON.stringify(cardIds, null, 2)};

export const glossaryCount = ${seen.size};
export const totalQuestions = ${questions.length};
`;

if (process.argv.includes('--check')) {
  const current = await readFile(OUT, 'utf8').catch(() => '');
  if (current !== body) {
    console.error('light.ts is stale — run `node scripts/make-index.mjs`.');
    process.exit(1);
  }
  console.log('curriculum index: up to date');
} else {
  await writeFile(OUT, body);
  const kb = (Buffer.byteLength(body) / 1024).toFixed(0);
  console.log(`curriculum index: ${light.length} stages, ${light.reduce((n, s) => n + s.lessons.length, 0)} lessons, ${kb}kB`);
}
