/**
 * Writes the service worker after `next build`, with a precache list taken from
 * what was actually built.
 *
 * Doing it here rather than hand-maintaining a list matters because Next hashes
 * its chunk filenames: a hard-coded list goes stale on the very next build and
 * fails silently, which is the worst way for a cache to be wrong. The cache
 * name is derived from the files and their contents, so every changed build is
 * a new cache even when the bundler keeps a stable chunk name.
 */

import { createHash } from 'node:crypto';
import { readFile, readdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'out');
const BASE = process.env.PAGES_BASE_PATH ? `/${process.env.PAGES_BASE_PATH}` : '';

/** Files worth having before the network is gone. */
const PRECACHE_EXT = new Set(['.html', '.css', '.js', '.png', '.svg', '.webmanifest', '.woff2']);
/* Audio is deliberately excluded: a full narration library is tens of
   megabytes, and forcing that down on first visit would be hostile. It caches
   as you listen instead. */
const SKIP_DIRS = new Set(['audio']);
/* The worker must never precache itself: a cached worker is how you ship an
   update that can never take effect. */
const SKIP_FILES = new Set(['sw.js']);

async function walk(dir, base = '') {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const rel = base ? `${base}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      out.push(...(await walk(path.join(dir, entry.name), rel)));
    } else if (PRECACHE_EXT.has(path.extname(entry.name)) && !SKIP_FILES.has(rel)) {
      out.push(rel);
    }
  }
  return out;
}

try {
  await stat(OUT);
} catch {
  console.error('No out/ directory — run the build first.');
  process.exit(1);
}

const files = (await walk(OUT)).sort();
const urls = [`${BASE}/`, ...files.map((f) => `${BASE}/${f}`)];
const fingerprint = createHash('sha256');
for (const file of files) {
  fingerprint.update(file);
  fingerprint.update('\0');
  fingerprint.update(await readFile(path.join(OUT, file)));
  fingerprint.update('\0');
}
const version = fingerprint.digest('hex').slice(0, 12);

const sw = `/* Generated by scripts/make-sw.mjs — do not edit. Build ${version}. */
const CACHE = 'cipher-school-${version}';
const START = ${JSON.stringify(`${BASE}/`)};
const PRECACHE = ${JSON.stringify(urls, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    // Install the app shell as one complete version. If even one required
    // asset is unavailable, the install fails and the previous complete
    // worker stays in control instead of activating a half-filled cache.
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then(async (keys) => {
        const upgrading = keys.some((key) => key.startsWith('cipher-school-') && key !== CACHE);
        await Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key)));
        await self.clients.claim();

        /* An older page can miss controllerchange because its listener was
           attached after it requested activation. Once this complete cache is
           active, refresh safe pages from the worker side so those clients do
           not remain stranded on old HTML and JavaScript. Leave an open lesson
           alone; its page code offers the update without interrupting reading. */
        if (!upgrading) return;
        const windows = await self.clients.matchAll({ type: 'window' });
        await Promise.all(
          windows.map((client) => {
            if (new URL(client.url).hash.startsWith('#/lesson/')) return undefined;
            return client.navigate(client.url).catch(() => undefined);
          }),
        );
      }),
  );
});

self.addEventListener('message', (event) => {
  if (event.data === 'skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Navigations: answer from the cache immediately. Never overwrite this
  // worker's cached HTML with a document from a newer deployment: that document
  // can point at newer hashed chunks which this cache does not contain, leaving
  // the next offline launch with HTML but no app. The new worker installs the
  // new HTML and all of its chunks together, then takes over as one unit.
  if (request.mode === 'navigate') {
    event.respondWith(
      caches.match(START).then((hit) => {
        return hit || fetch(request).catch(() => caches.match(request));
      }),
    );
    return;
  }

  // Everything else: cache first. Chunk filenames are content-hashed, so a
  // cached hit can never be stale — a changed file is a different URL.
  event.respondWith(
    caches.match(request).then((hit) => {
      if (hit) return hit;
      return fetch(request).then((res) => {
        if (res.ok && res.type === 'basic') {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(request, copy)).catch(() => {});
        }
        return res;
      });
    }),
  );
});
`;

await writeFile(path.join(OUT, 'sw.js'), sw);
console.log(`service worker: ${urls.length} files precached, build ${version}`);
